/* Skenario sektor EBT: dimuat setelah js/data.js dan menambahkan diri ke SCENARIOS. */
/* =====================================================================
   EBT: PLT Biogas Limbah Cair Pabrik Kelapa Sawit (POME)
   ===================================================================== */
const SCN_BIOGAS = {
  id: 'biogas',
  title: 'PLT Biogas Limbah Cair Sawit (POME)',
  subtitle: 'Kolam digester tertutup, blower, bio-scrubber H2S, gas engine, flare',
  level: 'Menengah',
  sector: 'ebt',
  area: 'Bioenergi (PLTBg)',
  color: '#3d7a5c',
  kits: ['biogas'],
  op: 'Operasi PLT Biogas',
  overview: [
    'Unit ini memanfaatkan limbah cair pabrik kelapa sawit (POME) sebagai bahan baku pembangkit listrik tenaga biogas. POME sekitar 60 m³/jam dialirkan ke kolam digester tertutup DG-701 yang ditutup membran HDPE. Bakteri anaerob menguraikan bahan organik dan menghasilkan sekitar 1.000 Nm³/jam biogas yang terkumpul di bawah cover pada tekanan hanya sekitar 2 mbar.',
    'Biogas mengandung metana 55 hingga 65 persen, karbon dioksida, uap air, dan H2S dalam orde ribuan ppm. Blower B-701 menyedot biogas melalui knock-out KO-701 yang memisahkan kondensat, lalu mengalirkannya ke bio-scrubber SC-701. Di scrubber, bakteri mengoksidasi H2S dengan bantuan sedikit udara yang diinjeksikan melalui FCV-702.',
    'Biogas bersih dibakar di gas engine GE-701 berdaya 1 MW yang menyalurkan listrik ke jaringan PLN. Saat engine berhenti, operator membuka katup manual XV-701 untuk mengalirkan biogas ke flare FL-701. Bahaya utama unit ini adalah gas beracun H2S, kebakaran dan ledakan metana, serta robeknya cover digester.',
  ],
  production: { label: 'Energi listrik dibangkitkan', unit: 'kWh', var: 'MW7', k: 1 / 60 },
  fluidNames: { gas: 'Biogas (CH4, CO2, H2S)', mix: 'POME dan efluen', air: 'Udara injeksi scrubber', power: 'Kabel daya' },
  equipment: [
    { id: 'PO-700', type: 'sink', x: 150, y: 410, dir: 'left', name: 'POME dari Kolam Pendingin',
      desc: 'Limbah cair pabrik kelapa sawit yang telah didinginkan hingga sekitar 40 °C.' },
    { id: 'DG-701', type: 'lagoon', x: 200, y: 240, w: 300, h: 220, name: 'Kolam Digester Tertutup DG-701',
      desc: 'Kolam anaerob berkapasitas sekitar 30.000 m³ yang ditutup membran HDPE. Membran diangkurkan di parit tepi kolam dan dirancang untuk tekanan biogas hanya beberapa milibar.', vars: ['PC'] },
    { id: 'XV-701', type: 'valve', sub: 'manual', x: 250, y: 175, name: 'XV-701 (Katup Manual ke Flare)',
      desc: 'Katup manual yang dibuka operator untuk mengalirkan biogas ke flare saat engine berhenti atau tekanan digester naik.' },
    { id: 'FL-701', type: 'flare', x: 95, y: 250, name: 'Flare FL-701', flameVar: 'TF',
      desc: 'Membakar biogas berlebih. Pilot dinyalakan secara manual dan nyala dipantau secara visual oleh operator.', vars: ['TF'] },
    { id: 'KO-701', type: 'vessel', x: 436, y: 80, w: 44, h: 84, name: 'Knock-out Kondensat KO-701', level: 'LCT',
      desc: 'Memisahkan air yang mengembun dari biogas jenuh sebelum masuk ke blower. Kondensat dibuang melalui saluran drain gravitasi yang mudah tersumbat lumpur.', vars: ['LCT'] },
    { id: 'B-701', type: 'fan', x: 540, y: 120, name: 'Blower Biogas B-701',
      desc: 'Menyedot biogas dari bawah cover dan menaikkan tekanannya untuk scrubber dan engine. Blower tidak toleran terhadap air.', vars: ['FBG'] },
    { id: 'SC-701', type: 'column', x: 610, y: 70, w: 60, h: 170, name: 'Bio-Scrubber H2S SC-701',
      desc: 'Kolom berisi media tempat bakteri mengoksidasi H2S menjadi sulfur. Proses ini membutuhkan sedikit oksigen dari injeksi udara; kadar O2 normal dalam biogas kurang dari 1 persen.', vars: ['CH4', 'H2S', 'O2'] },
    { id: 'FCV-702', type: 'valve', sub: 'control', x: 675, y: 300, tag: 'FIC', name: 'FCV-702 (Injeksi Udara Scrubber)',
      desc: 'Mengatur laju udara ke scrubber sekitar 4 persen dari aliran biogas. Bila gagal terbuka penuh, oksigen dalam biogas menjadi berlebih.' },
    { id: 'AIR-701', type: 'sink', x: 720, y: 300, dir: 'right', name: 'Udara dari Kompresor',
      desc: 'Suplai udara bertekanan untuk injeksi bio-scrubber.' },
    { id: 'GE-701', type: 'generator', x: 760, y: 110, w: 130, h: 60, name: 'Gas Engine GE-701 1 MW',
      desc: 'Mesin gas yang menggerakkan generator 1 MW. Biogas harus bersih dari H2S dan air agar mesin tidak cepat rusak.', vars: ['MW7'] },
    { id: 'GRID-701', type: 'sink', x: 848, y: 230, dir: 'right', name: 'Ke Jaringan PLN 20 kV',
      desc: 'Listrik disalurkan melalui trafo step-up ke jaringan distribusi PLN.' },
    { id: 'EF-701', type: 'sink', x: 848, y: 420, dir: 'right', name: 'Efluen ke Kolam Aerobik',
      desc: 'Efluen digester dialirkan ke kolam aerobik untuk pengolahan lanjut.' },
    { id: 'CR-700', type: 'building', x: 640, y: 505, name: 'Ruang Kendali',
      desc: 'Operator memantau tekanan digester, kualitas biogas, dan gas engine.' },
    { id: 'MP-700', type: 'muster', x: 930, y: 505, name: 'Titik Kumpul',
      desc: 'Area berkumpul pada arah angin yang aman dari digester dan flare.' },
  ],
  pipes: [
    { id: 'po', fluid: 'mix', w: 7, pts: [[150, 410], [222, 410]], arrow: true },
    { id: 'ef', fluid: 'mix', w: 7, pts: [[478, 420], [848, 420]], arrow: true },
    { id: 'g1', fluid: 'gas', w: 7, pts: [[350, 238], [350, 120], [436, 120]] },
    { id: 'fl', fluid: 'gas', w: 5, pts: [[350, 175], [150, 175], [150, 246], [103, 246]], arrow: true },
    { id: 'g2', fluid: 'gas', w: 7, pts: [[480, 120], [518, 120]] },
    { id: 'g3', fluid: 'gas', w: 6, pts: [[574, 104], [610, 104]] },
    { id: 'air', fluid: 'air', w: 4, pts: [[720, 300], [640, 300], [640, 240]], arrow: true },
    { id: 'g4', fluid: 'gas', w: 6, pts: [[640, 70], [640, 44], [825, 44], [825, 110]], arrow: true },
    { id: 'pw', fluid: 'power', w: 5, pts: [[825, 170], [825, 230], [848, 230]], arrow: true },
  ],
  labels: [
    { x: 300, y: 165, text: 'Ke flare', size: 10 },
  ],
  vars: {
    PC:  { label: 'Tekanan Bawah Cover Digester', unit: 'mbar', normal: 2.0, min: -2, max: 10, lo: 0.5, lolo: 0, hi: 4, hihi: 6, node: 'DG-701', x: 262, y: 224, tau: 4, noise: 0.03, dec: 1 },
    FBG: { label: 'Aliran Biogas', unit: 'Nm³/j', normal: 1000, min: 0, max: 2000, lo: 500, hi: 1600, node: 'B-701', x: 520, y: 62, tau: 2, noise: 6, dec: 0 },
    CH4: { label: 'Kadar Metana', unit: '%', normal: 60, min: 0, max: 80, lo: 50, node: 'SC-701', x: 725, y: 80, tau: 3, noise: 0.15, dec: 1 },
    H2S: { label: 'H2S Keluar Scrubber', unit: 'ppm', normal: 150, min: 0, max: 3000, hi: 300, hihi: 500, node: 'SC-701', x: 720, y: 200, tau: 4, noise: 2, dec: 0 },
    O2:  { label: 'Kadar O2 dalam Biogas', unit: '%', normal: 0.5, min: 0, max: 21, hi: 2, hihi: 4, node: 'SC-701', x: 720, y: 228, tau: 2, noise: 0.02, dec: 1 },
    TF:  { label: 'Suhu Nyala Flare', unit: '°C', normal: 750, min: 0, max: 1000, lo: 400, lolo: 200, node: 'FL-701', x: 95, y: 118, tau: 1.5, noise: 3, dec: 0 },
    LCT: { label: 'Level Kondensat KO-701', unit: '%', normal: 25, min: 0, max: 100, hi: 60, hihi: 80, node: 'KO-701', x: 458, y: 186, tau: 4, noise: 0.3, dec: 0 },
    MW7: { label: 'Daya Gas Engine', unit: 'kW', normal: 1000, min: 0, max: 1300, lo: 400, node: 'GE-701', x: 935, y: 140, tau: 2, noise: 4, dec: 0 },
  },
  trendVars: ['PC', 'O2', 'TF', 'LCT'],
  controls: [
    { id: 'pome', label: 'Laju umpan POME', unit: 'm³/j', min: 30, max: 90, def: 60, step: 5,
      effects: [{ var: 'FBG', gain: 16 }, { var: 'PC', gain: 0.015 }] },
    { id: 'airdose', label: 'Injeksi udara scrubber (FIC-702)', unit: '%', min: 2, max: 8, def: 4, step: 0.5,
      effects: [{ var: 'O2', gain: 0.12 }, { var: 'H2S', gain: -25 }] },
    { id: 'engine', label: 'Beban gas engine', unit: 'kW', min: 500, max: 1200, def: 1000, step: 50,
      effects: [{ var: 'MW7', gain: 1 }, { var: 'TF', gain: -0.5 }, { var: 'PC', gain: -0.002 }] },
  ],
  quiz: [
    { q: 'Apa komponen utama biogas dari POME?', opts: ['Hidrogen dan nitrogen', 'Metana sekitar 55 hingga 65 persen, karbon dioksida, serta H2S dalam orde ribuan ppm', 'Oksigen murni', 'Uap air dan amonia saja'], ans: 1,
      why: 'Metana membuat biogas bernilai sebagai bahan bakar sekaligus mudah terbakar. H2S membuatnya sangat beracun dan korosif sehingga perlu dihilangkan sebelum masuk engine.' },
    { q: 'Mengapa tekanan di bawah cover membran harus dijaga sangat rendah?', opts: ['Agar POME mengalir lebih cepat', 'Karena cover membran hanya dirancang untuk tekanan beberapa milibar dan mudah robek di parit angkur bila tekanan berlebih', 'Agar gas engine lebih hemat', 'Karena metana tidak dapat ditekan'], ans: 1,
      why: 'Cover HDPE adalah struktur ringan. Tekanan berlebih membuat membran menggembung dan robek di tepi, melepaskan biogas pada ketinggian rendah di dekat pekerja.' },
    { q: 'Mengapa injeksi udara ke bio-scrubber harus dibatasi?', opts: ['Agar bakteri tidak kedinginan', 'Karena udara berlebih membentuk campuran biogas dan udara yang mudah meledak di dalam sistem', 'Agar kadar H2S naik', 'Agar blower bekerja lebih ringan'], ans: 1,
      why: 'Bakteri pengoksidasi H2S membutuhkan sedikit oksigen, tetapi kelebihan udara menurunkan kadar metana ke rentang mudah meledak di dalam pipa dan scrubber.' },
    { q: 'Apa fungsi flare pada PLT biogas?', opts: ['Memanaskan digester', 'Membakar biogas berlebih atau saat engine berhenti sehingga metana dan H2S tidak lepas tanpa dibakar', 'Menambah daya listrik', 'Mengeringkan biogas'], ans: 1,
      why: 'Flare adalah sarana pembuangan aman. Flare yang padam justru melepaskan biogas mentah yang beracun dan mudah terbakar.' },
    { q: 'Mengapa H2S sangat berbahaya bagi pekerja di sekitar digester?', opts: ['Karena baunya selalu tercium pada konsentrasi berapa pun', 'Karena pada konsentrasi tinggi H2S melumpuhkan indra penciuman dan dapat menyebabkan pingsan hingga kematian dalam waktu singkat', 'Karena H2S lebih ringan dari udara sehingga cepat hilang', 'Karena H2S hanya berbahaya bila tertelan'], ans: 1,
      why: 'Pada sekitar 100 ppm ke atas penciuman lumpuh sehingga bau tidak lagi menjadi peringatan. H2S juga lebih berat dari udara dan dapat terkumpul di cekungan dan ruang tertutup.' },
  ],
  events: [
    { id: 'e1', effects: [{ var: 'FBG', to: 0, delay: 1, dur: 3 }, { var: 'MW7', to: 0, delay: 2, dur: 4 }, { var: 'PC', to: 9.5, delay: 2, dur: 22 }],
      warnings: [
        { t: 12, type: 'vibration', sev: 'warn', at: 'DG-701', text: 'Cover membran digester menggembung tinggi dan berderit keras tertiup angin.' },
        { t: 18, type: 'toxic', sev: 'crit', at: 'DG-701', pos: [215, 330], text: 'GAS BERACUN: membran robek di parit angkur tepi kolam; biogas mengandung H2S keluar. Detektor gas personal pekerja berbunyi.' },
        { t: 26, type: 'fire', sev: 'final', at: 'DG-701', pos: [232, 320], text: 'Biogas yang lepas tersulut percikan dari kendaraan di dekat kolam; terjadi KEBAKARAN di tepi digester.' },
      ],
      answer: { node: ['DG-701', 'B-701'], param: ['P', 'F'], guide: ['high', 'none'] },
      hint: 'Biogas terus terbentuk, tetapi tidak ada yang menyedotnya keluar dari bawah cover.',
      causes: ['Blower B-701 trip dan flare tidak dinyalakan tepat waktu sehingga biogas menumpuk di bawah cover', 'Laju POME turun', 'Injeksi udara scrubber terlalu kecil', 'Level kondensat rendah'], causeAns: 0,
      cons: ['Tekanan di bawah cover melampaui batas, membran robek, dan biogas beracun serta mudah terbakar lepas ke area kerja', 'Daya gas engine naik', 'Kadar metana naik tanpa dampak', 'Efluen menjadi lebih jernih'], consAns: 0,
      explain: 'Aliran biogas berhenti, lalu tekanan di bawah cover naik terus. Cover membran dirancang untuk tekanan hanya beberapa milibar. Proteksi yang tepat adalah katup pengaman tekanan-vakum pada cover, alarm tekanan, dan flare yang menyala otomatis saat tekanan tinggi atau engine berhenti.' },
    { id: 'e2', effects: [{ var: 'O2', to: 11, delay: 1, dur: 14 }, { var: 'CH4', to: 42, delay: 2, dur: 14 }],
      warnings: [
        { t: 8, type: 'vibration', sev: 'warn', at: 'GE-701', text: 'Gas engine GE-701 tersendat dan terjadi letupan balik (backfire) di saluran masuk.' },
        { t: 14, type: 'heat', sev: 'crit', at: 'SC-701', text: 'Dinding scrubber SC-701 memanas; terdengar dentuman kecil di pipa biogas.' },
        { t: 21, type: 'explosion', sev: 'final', at: 'SC-701', pos: [640, 150], text: 'LEDAKAN di scrubber SC-701: campuran biogas dan udara tersulut, nyala api merambat balik di pipa biogas.' },
      ],
      answer: { node: ['SC-701', 'FCV-702'], param: ['C'], guide: ['high', 'other'] },
      hint: 'Kadar oksigen dalam biogas naik terus. Udara masuk jauh lebih banyak dari seharusnya.',
      causes: ['FCV-702 injeksi udara scrubber gagal terbuka penuh sehingga oksigen dalam biogas berlebih', 'Blower trip', 'Laju POME naik', 'Flare padam'], causeAns: 0,
      cons: ['Terbentuk campuran biogas dan udara yang mudah meledak di dalam scrubber dan pipa, lalu tersulut dan meledak', 'Kadar H2S naik', 'Daya engine naik', 'Level kondensat naik'], consAns: 0,
      explain: 'Kadar oksigen naik dari kurang dari satu persen menuju belasan persen sementara metana turun. Bio-scrubber memang membutuhkan sedikit udara, tetapi kelebihan udara membentuk campuran mudah meledak. Proteksi yang tepat adalah analyzer O2 yang menghentikan injeksi udara dan blower, serta flame arrester agar nyala tidak merambat ke digester.' },
    { id: 'e3', effects: [{ var: 'MW7', to: 0, delay: 1, dur: 3 }, { var: 'TF', to: 40, delay: 2, dur: 5 }],
      warnings: [
        { t: 7, type: 'leak', sev: 'warn', at: 'FL-701', pos: [95, 152], text: 'Nyala flare FL-701 padam; biogas tidak terbakar keluar dari ujung flare.' },
        { t: 13, type: 'toxic', sev: 'crit', at: 'FL-701', pos: [125, 170], big: true, text: 'GAS BERACUN: H2S terbawa angin ke area kerja; bau telur busuk sangat menyengat.' },
        { t: 20, type: 'toxic', sev: 'final', at: 'FL-701', pos: [170, 300], big: true, text: 'Pekerja di area penerimaan pingsan akibat paparan H2S. Evakuasi dan penyelamatan darurat diperlukan.' },
      ],
      answer: { node: ['FL-701', 'XV-701'], param: ['T', 'C'], guide: ['low', 'none'] },
      hint: 'Suhu nyala flare turun drastis. Biogas tetap mengalir ke flare, tetapi tidak lagi dibakar.',
      causes: ['Nyala flare padam karena angin kencang atau pilot gagal, sementara biogas terus dialirkan ke flare', 'Kadar O2 naik', 'Level kondensat tinggi', 'Laju POME turun'], causeAns: 0,
      cons: ['Biogas yang tidak terbakar membawa H2S ke area kerja dan permukiman sehingga terjadi keracunan', 'Daya engine naik', 'Tekanan cover turun tanpa dampak', 'Efluen tercemar minyak'], consAns: 0,
      explain: 'Daya engine hilang sehingga biogas dialihkan ke flare, lalu suhu nyala flare anjlok. Biogas sawit mengandung H2S ribuan ppm, sedangkan nilai ambang batas H2S di tempat kerja di Indonesia hanya 1 ppm. Flare harus dilengkapi pilot, penyalaan otomatis, dan pemantauan nyala yang menutup aliran bila nyala tidak terdeteksi.' },
    { id: 'e4', effects: [{ var: 'LCT', to: 99, delay: 2, dur: 16 }, { var: 'FBG', to: 700, delay: 12, dur: 6 }],
      warnings: [
        { t: 15, type: 'vibration', sev: 'warn', at: 'B-701', text: 'Blower B-701 bergetar keras; terdengar benturan air di rumah blower.' },
        { t: 21, type: 'toxic', sev: 'crit', at: 'B-701', pos: [545, 152], text: 'Seal blower rusak; biogas dan H2S bocor di rumah blower.' },
        { t: 28, type: 'fire', sev: 'final', at: 'B-701', pos: [540, 122], text: 'Biogas yang bocor tersulut motor blower; terjadi KEBAKARAN di rumah blower.' },
      ],
      answer: { node: ['KO-701', 'B-701'], param: ['L'], guide: ['high'] },
      hint: 'Air kondensat terus terkumpul di knock-out, tetapi tidak dibuang. Pikirkan akibatnya bagi blower di hilir.',
      causes: ['Saluran pembuangan kondensat KO-701 tersumbat lumpur sehingga air terbawa ke blower', 'Injeksi udara terlalu besar', 'Flare padam', 'Laju POME turun'], causeAns: 0,
      cons: ['Air terbawa ke blower, blower rusak dan seal bocor, lalu biogas beracun dan mudah terbakar lepas dan terbakar', 'Kadar metana naik', 'Tekanan cover turun tanpa dampak', 'Daya engine naik'], consAns: 0,
      explain: 'Level kondensat naik terus tanpa perubahan lain, lalu blower bergetar. Biogas dari digester yang hangat jenuh uap air sehingga air terus mengembun di pipa. Proteksi yang tepat adalah alarm level dan trip level tinggi-tinggi yang menghentikan blower, serta pemeriksaan rutin saluran kondensat.' },
  ],
  hotspots: [
    /* Tahap 3: pencegahan */
    { id: 'h31', stage: 3, x: 440, y: 270, label: 'Cover digester (katup pengaman tekanan-vakum)', accept: ['PVRV'],
      why: 'Katup tekanan-vakum melepas biogas melalui titik tinggi yang terarah sebelum membran robek di tepi kolam, serta mencegah membran tersedot saat vakum.' },
    { id: 'h32', stage: 3, x: 290, y: 262, label: 'Cover digester (transmitter tekanan)', accept: ['PT'],
      why: 'Alarm tekanan di bawah cover memberi peringatan dini agar operator menyalakan flare atau memulihkan blower.' },
    { id: 'h33', stage: 3, x: 150, y: 212, label: 'Jalur flare (start dan penyalaan otomatis)', accept: ['FIG'],
      why: 'Flare otomatis membuka jalur dan menyalakan pilot saat tekanan tinggi atau engine berhenti, serta menyalakan ulang bila nyala padam.' },
    { id: 'h34', stage: 3, x: 720, y: 44, label: 'Biogas keluar scrubber (analyzer oksigen)', accept: ['O2T'],
      why: 'Analyzer O2 menghentikan injeksi udara dan blower sebelum campuran biogas dan udara mencapai rentang mudah meledak.' },
    { id: 'h35', stage: 3, x: 500, y: 120, label: 'Pipa biogas sebelum blower (flame arrester)', accept: ['FARR'],
      why: 'Flame arrester mencegah nyala dari engine, flare, atau ledakan di hilir merambat balik ke digester.' },
    { id: 'h36', stage: 3, x: 458, y: 180, label: 'Knock-out KO-701 (level kondensat)', accept: ['LSHH', 'LT'],
      why: 'Trip level tinggi-tinggi menghentikan blower sebelum air terbawa. Alarm level diterima sebagai lapisan respons operator.' },
    { id: 'h37', stage: 3, x: 186, y: 410, label: 'Saluran masuk POME', accept: [],
      why: 'Aliran POME masuk tidak terkait langsung dengan skenario yang teridentifikasi. Perangkat di sini tidak memutus rantai kejadian utama.' },
    { id: 'h38', stage: 3, x: 905, y: 194, label: 'Gas engine GE-701 (sisi listrik)', accept: [],
      why: 'Proteksi listrik generator penting, tetapi tidak menangani ancaman biogas pada digester, scrubber, dan flare.' },
    { id: 'h39', stage: 3, x: 592, y: 104, label: 'Discharge blower B-701', accept: ['NRV'],
      why: 'Check valve mencegah biogas bertekanan dari header engine mengalir balik ke blower yang berhenti.' },
    /* Tahap 4: mitigasi */
    { id: 'h41', stage: 4, x: 205, y: 322, label: 'Tepi digester (detektor H2S dan metana)', accept: ['GD'],
      why: 'Detektor gas di tepi kolam mendeteksi kebocoran membran pada ketinggian rendah tempat H2S terkumpul.' },
    { id: 'h42', stage: 4, x: 585, y: 152, label: 'Rumah blower (detektor gas)', accept: ['GD'],
      why: 'Seal blower adalah titik bocor umum di area tertutup. Detektor gas memicu alarm, ventilasi, dan penghentian blower.' },
    { id: 'h43', stage: 4, x: 790, y: 44, label: 'Jalur biogas ke gas engine (isolasi jarak jauh)', accept: ['EIV'],
      why: 'Katup isolasi jarak jauh menghentikan pasokan biogas ke area kebocoran atau kebakaran dari lokasi aman.' },
    { id: 'h44', stage: 4, x: 690, y: 478, label: 'Ruang kendali (ESD)', accept: ['ESD'],
      why: 'ESD menghentikan blower, engine, dan injeksi udara secara serentak.' },
    { id: 'h45', stage: 4, x: 862, y: 505, label: 'Pos operator (SCBA dan detektor personal)', accept: ['SCBA'],
      why: 'Alat bantu napas dan detektor personal memungkinkan evakuasi serta penyelamatan pekerja di area H2S.' },
    { id: 'h46', stage: 4, x: 500, y: 186, label: 'Rumah blower (hidran)', accept: ['FW'],
      why: 'Hidran dan monitor air dipakai untuk memadamkan kebakaran dan mendinginkan peralatan di sekitar rumah blower.' },
    { id: 'h47', stage: 4, x: 976, y: 505, label: 'Titik kumpul (arah angin) dan alarm umum', accept: ['ALARM'],
      why: 'Evakuasi harus mengikuti arah angin karena awan H2S dapat menyebar ke area kerja dan permukiman.' },
    { id: 'h48', stage: 4, x: 350, y: 256, label: 'Permukaan digester (sistem busa)', accept: [],
      why: 'Busa dipakai untuk kebakaran cairan mudah terbakar. Pelepasan biogas dari membran tidak dimitigasi dengan busa.' },
    { id: 'h49', stage: 4, x: 905, y: 194, label: 'Gas engine (pemadam api ringan)', accept: ['APAR'],
      why: 'APAR kelas B dan C memungkinkan operator memadamkan api tahap awal di sekitar engine.' },
  ],
  inspect: [
    { id: 'B-701', itpm: 'ROT', why: 'Pemantauan getaran blower mendeteksi kerusakan bantalan dan seal, serta tanda awal air terbawa.' },
    { id: 'GE-701', itpm: 'ROT', why: 'Perawatan prediktif gas engine mengurangi trip mendadak yang memaksa biogas dialihkan ke flare.' },
    { id: 'SC-701', itpm: 'VESSEL', why: 'H2S dan sulfur membuat scrubber sangat korosif. Pemeriksaan ketebalan dinding mencegah kebocoran biogas beracun.' },
  ],
  budget: { 3: 27, 4: 26 },
  bowtie: {
    top: 'Pelepasan biogas (metana dan H2S) atau campuran mudah meledak di sistem PLT biogas',
    threats: ['Blower trip, tekanan cover naik', 'Udara berlebih masuk ke biogas', 'Flare padam saat engine berhenti', 'Kondensat terbawa ke blower'],
    cons: ['Robek membran dan kebakaran tepi kolam', 'Ledakan scrubber dan pipa', 'Keracunan H2S pekerja dan warga', 'Kebakaran rumah blower'],
  },
};
SCENARIOS.push(SCN_BIOGAS);
