/* Skenario sektor EBT: dimuat setelah js/data.js dan menambahkan diri ke SCENARIOS. */
/* =====================================================================
   EBT: PLTS dengan Sistem Penyimpanan Energi Baterai (BESS)
   ===================================================================== */
const SCN_BESS = {
  id: 'bess',
  title: 'PLTS dengan Penyimpanan Baterai (BESS)',
  subtitle: 'Larik surya, inverter, kontainer baterai litium, HVAC, trafo step-up',
  level: 'Lanjutan',
  sector: 'ebt',
  area: 'Energi Surya (PLTS + BESS)',
  color: '#2f7f9c',
  kits: ['bess'],
  op: 'Operasi PLTS dan BESS',
  overview: [
    'Unit ini adalah PLTS berkapasitas 5 MWp yang dilengkapi sistem penyimpanan energi baterai (BESS). Larik surya PV-801 menghasilkan listrik arus searah yang dikumpulkan di kotak combiner CB-801, lalu diubah menjadi arus bolak-balik oleh inverter INV-801 dan dinaikkan tegangannya oleh trafo TR-801 ke jaringan 20 kV.',
    'Pada siang hari, sebagian energi disimpan di kontainer baterai litium BT-801 dan BT-802 berkapasitas total sekitar 8 MWh melalui power conversion system PCS-802, lalu dilepas pada malam hari. Setiap kontainer berisi ribuan sel yang tersusun dalam modul dan rak.',
    'Sel litium bekerja aman hanya pada rentang tegangan dan suhu tertentu. Unit HVAC HV-801 menjaga suhu kontainer sekitar 24 °C. Bahaya utama BESS adalah thermal runaway, yaitu pemanasan sel yang tak terkendali, yang melepaskan gas mudah terbakar dan dapat berakhir dengan ledakan atau kebakaran yang sulit dipadamkan.',
  ],
  production: { label: 'Energi PV tersalurkan', unit: 'MWh', var: 'PPV', k: 1 / 60, dec: 2 },
  fluidNames: { power: 'Kabel daya DC dan AC', air: 'Udara pendingin kontainer' },
  zones: [
    { x: 95, y: 290, w: 400, h: 250, label: 'Area BESS', labelPos: 'bottom' },
  ],
  equipment: [
    { id: 'PV-801', type: 'solar', x: 40, y: 60, w: 240, h: 70, n: 4, name: 'Larik Surya PV-801 5 MWp',
      desc: 'Ribuan modul surya yang dirangkai seri dan paralel menghasilkan arus searah hingga sekitar 1.500 V DC. Kabel DC dan konektor terpapar panas, hujan, dan hewan pengerat.', vars: ['RISO'] },
    { id: 'CB-801', type: 'panel', x: 310, y: 72, w: 50, h: 46, name: 'Kotak Combiner DC CB-801',
      desc: 'Menggabungkan arus dari banyak string modul surya dan dilengkapi sekering string. Sambungan yang longgar menjadi titik panas dan busur listrik.' },
    { id: 'INV-801', type: 'panel', sub: 'DC/AC', x: 410, y: 64, w: 80, h: 60, name: 'Inverter PV INV-801',
      desc: 'Mengubah arus searah dari larik surya menjadi arus bolak-balik 0,8 kV dan memantau tahanan isolasi sisi DC.', vars: ['PPV'] },
    { id: 'TR-801', type: 'transformer', x: 620, y: 90, w: 90, h: 70, name: 'Trafo Step-up TR-801',
      desc: 'Menaikkan tegangan dari 0,8 kV menjadi 20 kV untuk disalurkan ke jaringan PLN.' },
    { id: 'GRID-801', type: 'sink', x: 848, y: 125, dir: 'right', name: 'Ke Jaringan PLN 20 kV',
      desc: 'Titik sambung ke jaringan distribusi 20 kV.' },
    { id: 'PCS-802', type: 'panel', sub: 'PCS', x: 520, y: 330, w: 80, h: 60, name: 'Power Conversion System PCS-802',
      desc: 'Pengubah dua arah yang mengisi baterai saat siang dan melepas energi saat malam. Arus pengisian diatur sesuai perintah BMS dan SCADA.', vars: ['PB'] },
    { id: 'BT-801', type: 'battery', x: 200, y: 320, w: 270, h: 90, name: 'Kontainer Baterai BT-801',
      desc: 'Kontainer 40 kaki berisi rak baterai litium besi fosfat (LFP) sekitar 4 MWh. Rentang aman sel sekitar 2,5 hingga 3,65 V dengan suhu operasi 15 hingga 35 °C.', vars: ['SOC', 'TC', 'VC', 'VMIN'] },
    { id: 'BT-802', type: 'battery', x: 200, y: 450, w: 270, h: 70, name: 'Kontainer Baterai BT-802',
      desc: 'Kontainer kedua dengan konfigurasi yang sama, berjarak sekitar 3 meter dari BT-801.' },
    { id: 'HV-801', type: 'cooler', x: 110, y: 330, w: 70, h: 50, fans: 1, name: 'Unit HVAC Kontainer HV-801',
      desc: 'Unit pendingin udara tunggal yang menjaga suhu kontainer BT-801 sekitar 24 °C. Saat ini tidak tersedia unit cadangan.', vars: ['TK'] },
    { id: 'CR-800', type: 'building', x: 760, y: 470, name: 'Ruang Kontrol & SCADA',
      desc: 'Operator memantau BMS, PCS, dan inverter melalui SCADA, serta mengoordinasikan tanggap darurat.' },
    { id: 'MP-800', type: 'muster', x: 920, y: 480, name: 'Titik Kumpul',
      desc: 'Area berkumpul evakuasi yang jauh dari kontainer baterai.' },
  ],
  pipes: [
    { id: 'dc1', fluid: 'power', w: 4, pts: [[280, 95], [310, 95]] },
    { id: 'dc2', fluid: 'power', w: 4, pts: [[360, 95], [410, 95]] },
    { id: 'ac1', fluid: 'power', w: 5, pts: [[490, 94], [560, 94], [560, 250], [665, 250], [665, 160]] },
    { id: 'grid', fluid: 'power', w: 5, pts: [[728, 125], [848, 125]], arrow: true },
    { id: 'pcs', fluid: 'power', w: 5, pts: [[560, 330], [560, 250]] },
    { id: 'bt1', fluid: 'power', w: 4, pts: [[470, 365], [520, 365]] },
    { id: 'bt2', fluid: 'power', w: 4, pts: [[470, 485], [590, 485], [590, 390]] },
    { id: 'air', fluid: 'air', w: 5, pts: [[180, 355], [200, 355]], arrow: true },
  ],
  labels: [
    { x: 612, y: 240, text: 'Bus AC 0,8 kV', size: 10 },
  ],
  vars: {
    SOC:  { label: 'State of Charge BESS', unit: '%', normal: 60, min: 0, max: 100, lo: 10, hi: 92, hihi: 98, node: 'BT-801', x: 300, y: 302, tau: 3, noise: 0.05, dec: 0 },
    TC:   { label: 'Suhu Sel Maksimum', unit: '°C', normal: 31, min: 15, max: 200, hi: 45, hihi: 55, node: 'BT-801', x: 400, y: 302, tau: 4, noise: 0.08, dec: 1 },
    VC:   { label: 'Tegangan Sel Maksimum', unit: 'V', normal: 3.38, min: 2, max: 5, hi: 3.55, hihi: 3.65, node: 'BT-801', x: 500, y: 302, tau: 2, noise: 0.003, dec: 2 },
    VMIN: { label: 'Tegangan Sel Minimum', unit: 'V', normal: 3.30, min: 1.5, max: 4, lo: 3.0, lolo: 2.8, node: 'BT-801', x: 540, y: 420, tau: 2, noise: 0.003, dec: 2 },
    TK:   { label: 'Suhu Udara Kontainer', unit: '°C', normal: 24, min: 10, max: 80, hi: 32, hihi: 38, node: 'HV-801', x: 145, y: 300, tau: 4, noise: 0.08, dec: 1 },
    PPV:  { label: 'Daya Keluaran PV', unit: 'MW', normal: 4.0, min: 0, max: 6, lo: 1, node: 'INV-801', x: 450, y: 166, tau: 2, noise: 0.03, dec: 2 },
    RISO: { label: 'Tahanan Isolasi DC Larik PV', unit: 'kΩ', normal: 1500, min: 0, max: 3000, lo: 500, lolo: 100, node: 'PV-801', x: 160, y: 160, tau: 2, noise: 6, dec: 0 },
    PB:   { label: 'Daya Pengisian BESS', unit: 'MW', normal: 2.0, min: -4, max: 4, node: 'PCS-802', x: 650, y: 360, tau: 1.5, noise: 0.01, dec: 2 },
  },
  trendVars: ['TC', 'TK', 'VC', 'VMIN'],
  controls: [
    { id: 'irr', label: 'Iradiasi matahari', unit: 'W/m²', min: 200, max: 1000, def: 800, step: 50,
      effects: [{ var: 'PPV', gain: 0.005 }, { var: 'TK', gain: 0.004 }] },
    { id: 'pbess', label: 'Daya pengisian BESS', unit: 'MW', min: 0, max: 3, def: 2, step: 0.25,
      effects: [{ var: 'PB', gain: 1 }, { var: 'TC', gain: 2 }, { var: 'VC', gain: 0.04 }, { var: 'TK', gain: 0.5 }] },
    { id: 'hvac', label: 'Set point HVAC kontainer', unit: '°C', min: 20, max: 28, def: 24, step: 1,
      effects: [{ var: 'TK', gain: 1 }, { var: 'TC', gain: 0.8 }] },
  ],
  quiz: [
    { q: 'Apa yang dimaksud thermal runaway pada baterai litium?', opts: ['Sel menghasilkan panas lebih cepat daripada yang dapat dibuang, sehingga suhu naik tak terkendali dan gas mudah terbakar keluar', 'Penurunan kapasitas sel secara cepat akibat suhu operasi tinggi dalam waktu lama', 'Kondisi saat BMS menghentikan pengisian karena suhu sel melampaui batas aman yang ditetapkan pabrikan', 'Lonjakan arus pengisian karena inverter gagal membatasi daya yang masuk dari larik surya ke rak baterai'], ans: 0,
      why: 'Thermal runaway dapat dipicu penyalahgunaan termal (panas), listrik (overcharge atau hubung singkat), mekanis, atau cacat internal sel. Panas dari satu sel dapat merambat ke sel lain.' },
    { q: 'Mengapa gas yang keluar dari sel saat thermal runaway berbahaya di dalam kontainer?', opts: ['Gas tersebut mudah terbakar dan dapat terakumulasi di dalam kontainer hingga meledak bila tersulut', 'Gas tersebut menggantikan oksigen sehingga bahaya utamanya hanya sesak napas bagi petugas', 'Gas tersebut bersifat korosif dan merusak kabel, tetapi tidak dapat terbakar di dalam kontainer', 'Gas tersebut sangat panas sehingga langsung menyalakan sel lain tanpa perlu menumpuk'], ans: 0,
      why: 'Off-gas sel litium mengandung hidrogen, karbon monoksida, dan hidrokarbon. Di ruang tertutup, campuran ini dapat mencapai batas mudah terbakar sehingga NFPA 855 mensyaratkan pengendalian ledakan.' },
    { q: 'Apa fungsi utama BMS (Battery Management System)?', opts: ['Memantau tegangan dan suhu setiap sel serta menghentikan pengisian atau memutus rak saat keluar batas', 'Mengubah arus searah dari baterai menjadi arus bolak-balik untuk disalurkan ke jaringan PLN', 'Mengatur suhu kontainer dengan menyalakan HVAC saat suhu sel naik', 'Memadamkan kebakaran sel dengan memutus aliran udara ke dalam modul dan menyuntikkan gas inert'], ans: 0,
      why: 'BMS adalah barier pencegahan utama terhadap overcharge, overdischarge, dan suhu berlebih pada tingkat sel.' },
    { q: 'Mengapa busur listrik DC pada larik surya lebih sulit padam dibanding busur AC?', opts: ['Arus DC tidak pernah melewati titik nol seperti arus AC sehingga busur dapat bertahan lama', 'Tegangan DC larik surya selalu lebih tinggi dari tegangan AC sehingga busur yang terbentuk lebih panjang', 'Kabel DC tidak memiliki pentanahan sehingga arus bocor terus mengalir', 'Panel surya menyimpan muatan seperti baterai sehingga busur tetap disuplai setelah pemutus terbuka'], ans: 0,
      why: 'Arus AC melewati nol seratus kali per detik pada 50 Hz sehingga busur cenderung padam sendiri. Busur DC tidak memiliki kesempatan itu dan mudah menyulut isolasi serta vegetasi.' },
    { q: 'Media pemadam mana yang paling dianjurkan untuk kebakaran kontainer baterai litium skala besar?', opts: ['Air dalam jumlah besar untuk mendinginkan modul dan mencegah penjalaran thermal runaway', 'Gas pemadam bersih saja, karena air dapat menghantarkan listrik di dalam kontainer baterai', 'Busa, karena elektrolit baterai termasuk cairan mudah terbakar kelas B', 'Serbuk kimia kering yang disemprotkan langsung ke modul yang terbakar melalui pintu kontainer'], ans: 0,
      why: 'Gas pemadam dapat memadamkan nyala, tetapi tidak mendinginkan sel sehingga thermal runaway dapat berlanjut dan menyala kembali. Pengujian dan NFPA 855 mengarahkan pada sistem berbasis air.' },
  ],
  events: [
    { id: 'e1', threat: 0, effects: [{ var: 'TK', to: 52, delay: 1, dur: 18 }, { var: 'TC', to: 95, delay: 4, dur: 22 }],
      warnings: [
        { t: 12, type: 'heat', sev: 'warn', at: 'HV-801', text: 'Unit HVAC HV-801 berhenti; udara di dalam kontainer baterai terasa sangat panas.' },
        { t: 19, type: 'smoke', sev: 'crit', at: 'BT-801', pos: [335, 330], text: 'ASAP putih keluar dari celah pintu kontainer: sel mulai melepas uap elektrolit (off-gas).' },
        { t: 27, type: 'explosion', sev: 'final', at: 'BT-801', pos: [335, 362], text: 'LEDAKAN KONTAINER BATERAI: off-gas yang mudah terbakar terakumulasi lalu tersulut, pintu kontainer terlempar dan api menyala.' },
      ],
      answer: { node: ['HV-801', 'BT-801'], param: ['T'], guide: ['high'] },
      hint: 'Panas di dalam kontainer tidak lagi dibuang. Periksa sistem pendingin udara kontainer.',
      causes: ['Kompresor HVAC HV-801 trip tanpa unit cadangan, sementara baterai terus diisi pada siang hari', 'Iradiasi matahari turun', 'Tahanan isolasi PV turun', 'Trafo step-up kelebihan beban'], causeAns: 0,
      cons: ['Suhu sel naik hingga thermal runaway, off-gas terakumulasi dan meledak, lalu kebakaran baterai', 'SOC turun tanpa dampak', 'Daya PV naik', 'Tegangan jaringan naik sedikit'], consAns: 0,
      explain: 'Suhu udara kontainer naik lebih dulu, lalu suhu sel mengikuti. Baterai litium yang terlalu panas menua cepat dan dapat memasuki thermal runaway. Proteksi yang tepat adalah HVAC cadangan dengan pergantian otomatis, alarm suhu kontainer, dan BMS yang menghentikan pengisian saat suhu sel melewati batas.' },
    { id: 'e2', threat: 1, effects: [{ var: 'SOC', to: 100, delay: 1, dur: 10 }, { var: 'VC', to: 4.4, delay: 2, dur: 14 }, { var: 'TC', to: 110, delay: 8, dur: 18 }],
      warnings: [
        { t: 12, type: 'heat', sev: 'warn', at: 'BT-801', pos: [300, 365], text: 'Rak baterai nomor 3 memanas; kipas rak berputar maksimum.' },
        { t: 18, type: 'smoke', sev: 'crit', at: 'BT-801', pos: [300, 330], text: 'Asap putih berbau manis elektrolit keluar dari ventilasi kontainer.' },
        { t: 26, type: 'fire', sev: 'final', at: 'BT-801', pos: [335, 352], text: 'KEBAKARAN BATERAI: thermal runaway merambat dari modul ke modul di dalam kontainer.' },
      ],
      answer: { node: ['BT-801', 'PCS-802'], param: ['E', 'L'], guide: ['high'] },
      hint: 'Pengisian tidak berhenti walaupun baterai sudah penuh.',
      causes: ['BMS gagal menghentikan pengisian sehingga PCS terus mengisi baterai yang sudah penuh (overcharge)', 'Iradiasi matahari turun', 'HVAC terlalu dingin', 'Tahanan isolasi PV turun'], causeAns: 0,
      cons: ['Tegangan sel melampaui batas, sel memanas dan memasuki thermal runaway yang merambat menjadi kebakaran kontainer', 'Daya PV turun', 'Suhu kontainer turun', 'Tegangan jaringan turun'], consAns: 0,
      explain: 'SOC mencapai 100 persen, tegangan sel terus naik melewati batas pengisian, lalu suhu sel naik. Overcharge adalah penyalahgunaan listrik yang merusak struktur elektroda dan memicu thermal runaway. Barier utamanya adalah BMS dengan proteksi tegangan dan suhu yang membuka kontaktor rak secara independen dari sistem kendali PCS. Dalam HAZOP, deviasi ini dibaca sebagai tegangan atau tingkat pengisian lebih tinggi.' },
    { id: 'e3', threat: 2, effects: [{ var: 'RISO', to: 10, delay: 1, dur: 9 }, { var: 'PPV', to: 2.6, delay: 5, dur: 5 }],
      warnings: [
        { t: 10, type: 'arc', sev: 'warn', at: 'CB-801', pos: [335, 92], text: 'Inverter berulang kali memberi peringatan gangguan isolasi; tercium bau plastik terbakar di kotak combiner CB-801.' },
        { t: 15, type: 'arc', sev: 'crit', at: 'CB-801', pos: [335, 88], text: 'BUSUR LISTRIK DC di kotak combiner disertai desis dan kilatan; kabel mulai meleleh.' },
        { t: 21, type: 'fire', sev: 'final', at: 'PV-801', pos: [250, 118], text: 'KEBAKARAN di kotak combiner dan kabel DC, merambat ke rumput kering di bawah larik surya.' },
      ],
      answer: { node: ['CB-801', 'PV-801'], param: ['E'], guide: ['low', 'other'] },
      hint: 'Tahanan isolasi kabel DC turun drastis. Arus mencari jalan lain melalui isolasi yang rusak.',
      causes: ['Isolasi kabel DC rusak karena digigit hewan, terkelupas, atau konektor longgar sehingga terjadi gangguan isolasi dan busur listrik', 'HVAC kontainer mati', 'SOC terlalu tinggi', 'Trafo step-up kepanasan'], causeAns: 0,
      cons: ['Busur listrik DC yang sulit padam menyulut kotak combiner, kabel, dan vegetasi di bawah larik', 'Suhu sel baterai turun', 'SOC naik', 'Tegangan jaringan naik'], consAns: 0,
      explain: 'Tahanan isolasi turun dari ribuan menjadi puluhan kilo-ohm, lalu daya PV turun. Busur listrik DC tidak memiliki titik nol arus seperti AC sehingga lebih sulit padam dan mudah menyulut material di sekitarnya. Proteksi yang tepat adalah deteksi busur listrik yang memutus sirkuit, pentanahan dan bonding rangka, serta inspeksi kabel berkala.' },
    { id: 'e4', threat: 3, effects: [{ var: 'VMIN', to: 2.0, delay: 1, dur: 10 }, { var: 'TC', to: 120, delay: 4, dur: 20 }],
      warnings: [
        { t: 12, type: 'heat', sev: 'warn', at: 'BT-801', pos: [380, 365], text: 'Satu modul di rak 5 memanas lokal, sementara modul lain masih normal.' },
        { t: 19, type: 'smoke', sev: 'crit', at: 'BT-801', pos: [372, 330], text: 'Off-gas putih keluar dari modul yang memanas dan mulai mengisi kontainer.' },
        { t: 27, type: 'fire', sev: 'final', at: 'BT-801', pos: [360, 360], big: true, text: 'KEBAKARAN BATERAI merambat ke seluruh rak dan mengancam kontainer BT-802 di sebelahnya.' },
      ],
      answer: { node: ['BT-801'], param: ['E', 'T'], guide: ['low', 'high'] },
      hint: 'Tegangan satu sel turun tajam tanpa perubahan pengisian. Ada hubung singkat di dalam sel itu sendiri.', hintVar: 'VMIN',
      causes: ['Cacat internal sel, misalnya kontaminasi atau dendrit litium, menyebabkan hubung singkat di dalam sel', 'Iradiasi matahari naik', 'Kabel DC PV rusak', 'Trafo step-up kelebihan beban'], causeAns: 0,
      cons: ['Sel memanas dan memasuki thermal runaway yang merambat ke modul lain dan kontainer di sebelahnya', 'Daya PV naik', 'Suhu kontainer turun', 'SOC naik tanpa dampak'], consAns: 0,
      explain: 'Tegangan sel minimum anjlok lalu suhu sel naik tanpa pemicu dari luar. Hubung singkat internal sulit dicegah saat operasi, sehingga deteksi dini dan mitigasi menjadi penting: deteksi off-gas, ventilasi exhaust, venting ledakan, pemadam berbasis air, dan dinding tahan api antarkontainer. Insiden BESS McMicken di Arizona tahun 2019 berawal dari kegagalan internal sel dan berakhir dengan ledakan gas yang terakumulasi di dalam kontainer.' },
    { id: 'e5', start: 12,
      hf: { type: 'violation', team: 'mtc', threat: 1, title: 'Proteksi BMS dimatikan karena alarm mengganggu', factor: 'Proteksi tegangan sel BMS dinonaktifkan tanpa izin',
        lesson: 'Ini violation rutin yang lahir dari kelelahan alarm: proteksi dimatikan demi kenyamanan dan dianggap wajar karena hanya sementara. Teknisi memakai password vendor sehingga mengubah parameter yang bukan kewenangannya, dan supervisor ikut mendorong. Kontrolnya adalah pengelolaan bypass proteksi dengan otorisasi tertulis, batas waktu, dan pemantauan pengganti, serta penyelidikan akar masalah alarm, bukan penonaktifan proteksi.',
        controls: ['Parameter proteksi BMS hanya diubah vendor atau personel berwenang melalui MOC', 'Bypass proteksi memerlukan otorisasi, batas waktu, dan pemantauan pengganti', 'Alarm berulang diselidiki penyebabnya, bukan dimatikan'] },
      chat: [
        { t: 1, who: 'hendra', at: 'CR-800', text: 'Alarm tegangan sel di rak BT-801 bunyi terus dari kemarin. Operator jadi tidak fokus.' },
        { t: 4, who: 'wawan', at: 'BT-801', mood: 'ragu', text: 'Kemungkinan sensor tegangannya bermasalah. Vendor baru bisa datang minggu depan.' },
        { t: 7, who: 'hendra', at: 'CR-800', mood: 'santai', text: 'Bisa dimatikan dulu proteksinya? Biar tidak mengganggu.' },
        { t: 10, who: 'wawan', at: 'PCS-802', mood: 'santai', text: 'Bisa, aku masih simpan password vendor. Proteksi tegangan sel kunonaktifkan sementara.' },
        { t: 13, who: 'raka', at: 'CR-800', text: 'Siang ini daya PLTS penuh, SOC naik cepat. Kupantau ya.' },
        { t: 26, who: 'raka', at: 'CR-800', mood: 'ragu', text: 'SOC sudah lewat 95 persen tapi pengisian tidak berhenti. Tegangan sel terus naik.' },
        { t: 30, who: 'raka', at: 'CR-800', mood: 'panik', text: 'Suhu sel di BT-801 naik cepat! Wawan, aktifkan lagi proteksinya!' },
      ],
      effects: [{ var: 'SOC', to: 100, delay: 1, dur: 10 }, { var: 'VC', to: 4.4, delay: 2, dur: 14 }, { var: 'TC', to: 110, delay: 8, dur: 18 }],
      warnings: [
        { t: 12, type: 'heat', sev: 'warn', at: 'BT-801', pos: [300, 365], text: 'Rak baterai nomor 3 memanas; kipas rak berputar maksimum.' },
        { t: 18, type: 'smoke', sev: 'crit', at: 'BT-801', pos: [300, 330], text: 'Asap putih berbau manis elektrolit keluar dari ventilasi kontainer.' },
        { t: 26, type: 'fire', sev: 'final', at: 'BT-801', pos: [335, 352], text: 'KEBAKARAN BATERAI: thermal runaway merambat dari modul ke modul di dalam kontainer.' },
      ],
      answer: { node: ['BT-801', 'PCS-802'], param: ['E', 'L'], guide: ['high'] },
      hint: 'Pengisian tidak berhenti walaupun SOC dan tegangan sel melewati batas. Fungsi yang seharusnya memutus pengisian sedang tidak aktif. Baca kembali obrolan tentang alarm yang mengganggu.',
      causes: ['Proteksi tegangan sel di BMS dinonaktifkan teknisi memakai password vendor untuk menghentikan alarm', 'Sensor tegangan sel rusak sehingga BMS membaca tegangan terlalu rendah', 'PCS gagal menerima perintah henti dari BMS karena kabel komunikasi putus', 'Iradiasi matahari terlalu tinggi sehingga daya PLTS melebihi kapasitas rak'], causeAns: 0,
      cons: ['Sel kelebihan muatan sehingga terjadi thermal runaway, gas mudah terbakar terakumulasi, dan kontainer dapat meledak', 'Kapasitas baterai bertambah karena terisi melebihi 100 persen', 'Inverter PV berhenti otomatis tanpa dampak', 'Pendingin HVAC bekerja lebih berat tetapi suhu tetap aman'], consAns: 0,
      explain: 'SOC dan tegangan sel naik melewati batas tanpa ada pemutusan, lalu suhu sel naik. BMS adalah barier utama terhadap kelebihan muatan, dan menonaktifkannya membuat pengisian tidak terkendali. Alarm yang sering muncul adalah gejala yang harus diselidiki, bukan dimatikan.' },
    { id: 'e6', threat: 0, effects: [{ var: 'VMIN', to: 2.4, delay: 4, dur: 8 }, { var: 'TC', to: 85, delay: 6, dur: 18 }],
      warnings: [
        { t: 11, type: 'leak', sev: 'warn', at: 'HV-801', pos: [215, 340], text: 'Air menetes dari saluran kondensat HVAC yang tersumbat ke atas rak baterai nomor 2 di BT-801.' },
        { t: 18, type: 'arc', sev: 'crit', at: 'BT-801', pos: [260, 365], text: 'Kilatan dan desis dari busbar rak nomor 2 yang basah. Asap putih mulai keluar dari modul.' },
        { t: 26, type: 'fire', sev: 'final', at: 'BT-801', pos: [300, 360], text: 'Busur listrik di busbar yang basah menyulut modul baterai. Thermal runaway merambat ke rak di sebelahnya.' },
      ],
      answer: { node: ['BT-801', 'HV-801'], param: ['C', 'E'], guide: ['aswell', 'low'] },
      hint: 'Tegangan sel minimum turun lalu suhu sel naik, padahal pengisian dan suhu udara kontainer normal. Perhatikan laporan lapangan tentang air di dalam kontainer.', hintVar: 'VMIN',
      causes: ['Saluran kondensat HVAC tersumbat sehingga air menetes ke rak baterai dan membasahi busbar, lalu terjadi hubung singkat dan busur listrik', 'BMS gagal menghentikan pengisian sehingga sel kelebihan muatan', 'Kompresor HVAC trip sehingga udara kontainer kepanasan', 'Isolasi kabel DC larik surya rusak digigit hewan'], causeAns: 0,
      cons: ['Busur listrik di busbar yang basah memanaskan modul hingga thermal runaway, lalu kebakaran merambat antar-rak', 'Air mendinginkan modul sehingga suhu sel turun dan aman', 'SOC naik karena tegangan sel turun', 'Daya PV naik karena inverter bekerja lebih ringan'], consAns: 0,
      explain: 'Tegangan sel minimum turun dan suhu sel naik, sementara pengisian dan suhu udara kontainer tetap normal. Air dari saluran kondensat HVAC yang tersumbat menetes ke rak dan membasahi busbar sehingga terjadi hubung singkat antarterminal. Ini deviasi Serta (As well as): kontainer tetap sejuk, tetapi disertai air yang tidak dikehendaki di dekat bagian bertegangan. Investigasi kebakaran ESS di Korea Selatan tahun 2019 menyebut lingkungan operasi yang lembap dan berdebu sebagai salah satu faktor penyebab. Pemeriksaan saluran kondensat, pengendalian kelembapan, dan deteksi gangguan isolasi pada sisi baterai memutus rantai ini.' },
    { id: 'e7', start: 12,
      hf: { type: 'mistake', team: 'ktr', threat: 2, title: 'Konektor PV beda merek dipasangkan karena dikira kompatibel', factor: 'Konektor PV beda merek dipasang berpasangan',
        roles: { bayu: 'Kontraktor O&M PLTS', hendra: 'Supervisor PLTS', raka: 'Operator SCADA', wawan: 'Teknisi Listrik' },
        lesson: 'Bayu yakin konektor merek lain yang bentuknya sama pasti cocok, sehingga ia memasangkannya dengan konektor bawaan modul. Tindakannya sesuai niat, tetapi keputusannya keliru karena kurang pengetahuan, sehingga tergolong mistake. Konektor DC dari pabrikan berbeda dapat memiliki toleransi dan bahan kontak yang tidak serasi, sehingga tahanan kontak naik, sambungan memanas, dan isolasinya meleleh. IEC 62852 mensyaratkan konektor yang dipasangkan berasal dari tipe dan pabrikan yang sama. Pencegahnya adalah daftar suku cadang yang disetujui, pelatihan teknisi kontraktor, dan termografi setelah perbaikan.',
        controls: ['Daftar suku cadang yang disetujui, konektor pasangan dari tipe dan pabrikan yang sama (IEC 62852)', 'Pelatihan dan verifikasi kompetensi teknisi kontraktor PLTS', 'Termografi dan uji tahanan isolasi setelah perbaikan string'] },
      chat: [
        { t: 1, who: 'hendra', at: 'CR-800', text: 'Bayu, konektor string 12 yang rusak digigit tikus sudah diganti?' },
        { t: 4, who: 'bayu', at: 'CB-801', text: 'Sudah, Pak. Stok konektor merek pabrikan habis, jadi kupakai merek lain dari toko. Bentuknya sama persis, pasti cocok.' },
        { t: 7, who: 'hendra', at: 'CR-800', mood: 'santai', text: 'Bagus, string 12 langsung dioperasikan lagi ya. Siang ini iradiasi tinggi.' },
        { t: 10, who: 'raka', at: 'CR-800', text: 'String 12 sudah masuk, arusnya normal.' },
        { t: 21, who: 'raka', at: 'CR-800', mood: 'ragu', text: 'Inverter memberi alarm tahanan isolasi rendah dan daya PV ikut turun.' },
        { t: 25, who: 'wawan', at: 'PV-801', mood: 'panik', text: 'Ada asap dari konektor string 12 yang baru diganti!' },
        { t: 29, who: 'hendra', at: 'CR-800', mood: 'panik', text: 'Putuskan string dan inverter dari SCADA sekarang, siapkan APAR!' },
      ],
      effects: [{ var: 'RISO', to: 10, delay: 1, dur: 9 }, { var: 'PPV', to: 2.6, delay: 5, dur: 5 }],
      warnings: [
        { t: 10, type: 'arc', sev: 'warn', at: 'CB-801', pos: [300, 100], text: 'Konektor string 12 di dekat kotak combiner menghitam dan tercium bau plastik terbakar.' },
        { t: 15, type: 'arc', sev: 'crit', at: 'CB-801', pos: [335, 88], text: 'Busur listrik DC di konektor string 12 disertai desis dan kilatan. Kabel di sekitarnya mulai meleleh.' },
        { t: 21, type: 'fire', sev: 'final', at: 'PV-801', pos: [250, 118], text: 'Busur listrik menyulut kabel DC dan rumput kering di bawah larik surya. Api merambat di antara meja modul.' },
      ],
      answer: { node: ['CB-801', 'PV-801'], param: ['E'], guide: ['low', 'other'] },
      hint: 'Tahanan isolasi DC turun drastis tak lama setelah string diperbaiki. Baca kembali obrolan tentang konektor pengganti yang dipakai.',
      causes: ['Konektor pengganti dari merek lain dipasangkan dengan konektor bawaan modul sehingga tahanan kontak tinggi, sambungan memanas, dan isolasinya meleleh', 'Kabel DC digigit tikus lagi di lokasi lain pada larik surya', 'Inverter salah membaca tahanan isolasi karena sensornya rusak', 'Kompresor HVAC kontainer trip sehingga kabel kepanasan'], causeAns: 0,
      cons: ['Busur listrik DC yang sulit padam menyulut kabel, kotak combiner, dan vegetasi di bawah larik', 'Daya PV naik karena tahanan kontak turun', 'Baterai terisi lebih cepat tanpa dampak', 'Tegangan jaringan 20 kV turun sesaat lalu normal kembali'], consAns: 0,
      explain: 'Tahanan isolasi turun drastis dan daya PV turun, polanya sama dengan gangguan isolasi kabel DC. Penyebabnya adalah pasangan konektor dari dua pabrikan berbeda yang tidak serasi, sehingga tahanan kontak tinggi dan sambungan memanas sampai isolasinya rusak. Deteksi busur listrik yang memutus sirkuit, pentanahan rangka, dan inspeksi termografi tetap diperlukan sebagai lapisan pengaman.' },
    { id: 'e8', start: 12,
      hf: { type: 'lapse', team: 'mtc', threat: 3, title: 'Baut busbar modul pengganti belum dikencangkan dengan kunci torsi', factor: 'Baut busbar rak lupa dikencangkan dengan kunci torsi',
        roles: { wawan: 'Teknisi Baterai', raka: 'Operator SCADA', hendra: 'Supervisor PLTS' },
        lesson: 'Wawan berniat mengencangkan baut busbar dengan kunci torsi setelah mengambilnya dari gudang, tetapi lupa karena dipanggil ke pekerjaan lain. Langkah yang tertunda lalu terlupa tergolong lapse. Sambungan yang hanya dikencangkan dengan tangan memiliki tahanan kontak tinggi sehingga memanas saat arus pengisian besar. Pencegahnya adalah menyelesaikan langkah kritis sebelum berpindah tugas, penandaan baut yang sudah ditorsi dan verifikasi orang kedua, serta termografi sebelum rak kembali beroperasi penuh.',
        controls: ['Langkah kritis diselesaikan sebelum berpindah tugas, atau peralatan diberi label belum selesai', 'Penandaan torsi dan verifikasi orang kedua pada sambungan busbar', 'Termografi rak sebelum kembali ke daya pengisian penuh'] },
      chat: [
        { t: 1, who: 'raka', at: 'CR-800', text: 'Wawan, modul pengganti di rak 4 BT-801 sudah terpasang? Siang ini pengisian mau penuh 2 MW.' },
        { t: 4, who: 'wawan', at: 'BT-801', text: 'Sudah terpasang. Baut busbar baru kukencangkan dengan tangan, kunci torsinya masih di gudang.' },
        { t: 7, who: 'hendra', at: 'CR-800', text: 'Wawan, ke inverter sebentar, ada panel yang perlu dicek sekarang.' },
        { t: 10, who: 'wawan', at: 'INV-801', mood: 'santai', text: 'Siap, Pak, aku ke sana. BT-801 sudah bisa dioperasikan.' },
        { t: 22, who: 'raka', at: 'CR-800', mood: 'ragu', text: 'Suhu sel maksimum BT-801 naik terus, padahal suhu udara kontainer normal.' },
        { t: 27, who: 'raka', at: 'CR-800', mood: 'panik', text: 'Wawan, baut busbar rak 4 tadi sudah dikencangkan dengan kunci torsi?' },
        { t: 31, who: 'wawan', at: 'INV-801', mood: 'panik', text: 'Belum! Aku lupa kembali ke BT-801 setelah dari inverter.' },
      ],
      effects: [{ var: 'TC', to: 98, delay: 2, dur: 18 }],
      warnings: [
        { t: 13, type: 'heat', sev: 'warn', at: 'BT-801', pos: [420, 365], text: 'Kamera termal menunjukkan sambungan busbar rak 4 di BT-801 sangat panas, sementara rak lain normal.' },
        { t: 19, type: 'smoke', sev: 'crit', at: 'BT-801', pos: [410, 330], text: 'Bau isolasi terbakar dan asap tipis keluar dari rak 4. Pelindung plastik busbar mulai meleleh.' },
        { t: 27, type: 'fire', sev: 'final', at: 'BT-801', pos: [400, 360], text: 'Busur listrik di sambungan busbar yang longgar menyulut modul. Thermal runaway merambat ke rak di sebelahnya.' },
      ],
      answer: { node: ['BT-801'], param: ['T'], guide: ['high'] },
      hint: 'Suhu sel maksimum naik terus padahal suhu udara kontainer, SOC, dan tegangan sel normal. Baca kembali obrolan tentang pemasangan modul pengganti.',
      causes: ['Baut busbar modul pengganti hanya dikencangkan dengan tangan dan lupa ditorsi, sehingga sambungan memanas saat arus pengisian besar', 'Kompresor HVAC trip sehingga udara kontainer kepanasan', 'BMS gagal menghentikan pengisian sehingga sel kelebihan muatan', 'Sel mengalami hubung singkat internal karena cacat produksi'], causeAns: 0,
      cons: ['Sambungan yang memanas memicu busur listrik dan thermal runaway yang merambat ke rak lain', 'Suhu sel turun sendiri setelah pengisian selesai tanpa kerusakan', 'SOC naik lebih cepat karena tahanan sambungan bertambah', 'Daya PV naik karena inverter bekerja lebih ringan'], consAns: 0,
      explain: 'Suhu sel maksimum naik terus, sementara suhu udara kontainer, SOC, dan tegangan sel normal. Panas berasal dari satu titik, yaitu sambungan busbar yang belum dikencangkan dengan torsi yang benar. Pada sambungan longgar, tahanan kontak tinggi mengubah arus pengisian menjadi panas. Deviasinya suhu lebih tinggi pada rak baterai. Termografi berkala, BMS yang menghentikan pengisian saat suhu melewati batas, dan deteksi off-gas tetap diperlukan sebagai lapisan pengaman.' },
  ],
  variants: [
    ['e2', 'e6', 'e7', 'e1', 'e8'],
    ['e1', 'e3', 'e7', 'e4', 'e5'],
    ['e4', 'e3', 'e8', 'e6', 'e5'],
    ['e6', 'e1', 'e5', 'e2', 'e7'],
    ['e3', 'e4', 'e5', 'e2', 'e8'],
  ],
  hotspots: [
    /* Tahap 3: pencegahan, diurutkan menurut posisi baca pada P&ID (kiri ke kanan, atas ke bawah) */
    { id: 'h38', stage: 3, on: 'PV-801', tap: [200, 59], x: 178, y: 37, label: 'Permukaan panel surya', accept: [],
      why: 'Perangkat di permukaan panel tidak menangani ancaman yang teridentifikasi. Kebersihan panel adalah urusan kinerja, bukan barier keselamatan proses.' },
    { id: 'h36', stage: 3, on: 'PV-801', tap: [68, 128], x: 95, y: 144, label: 'Rangka larik surya (pentanahan dan bonding)', accept: ['GRND'],
      why: 'Pentanahan dan bonding rangka mencegah tegangan sentuh dan mengarahkan arus gangguan, sehingga gangguan isolasi terdeteksi dan diputus.' },
    { id: 'h34', stage: 3, on: 'CB-801', tap: [312, 119], x: 282, y: 127, label: 'Kotak combiner DC (proteksi busur listrik)', accept: ['ARC'],
      why: 'Deteksi busur listrik DC memutus string dalam hitungan milidetik sebelum busur menyulut kabel dan vegetasi.' },
    { id: 'h37', stage: 3, on: 'grid', tap: [776, 125], x: 784, y: 155, label: 'Trafo step-up TR-801 (sisi 20 kV)', accept: [],
      why: 'Proteksi trafo dan jaringan penting, tetapi tidak memutus ancaman thermal runaway dan busur DC yang teridentifikasi.' },
    { id: 'h31', stage: 3, on: 'HV-801', tap: [144, 322], x: 144, y: 270, label: 'Unit HVAC (cadangan otomatis)', accept: ['HVR'],
      why: 'Unit HVAC cadangan dengan pergantian otomatis menghilangkan titik kegagalan tunggal pada pendinginan kontainer.' },
    { id: 'h32', stage: 3, on: 'BT-801', tap: [216, 319], x: 203, y: 269, label: 'Dalam kontainer (sensor suhu udara)', accept: ['TT'],
      why: 'Alarm suhu udara kontainer memberi peringatan dini kegagalan pendinginan sebelum suhu sel naik.' },
    { id: 'h33', stage: 3, on: 'BT-801', tap: [300, 319], x: 287, y: 269, label: 'Rak baterai (BMS dan kontaktor)', accept: ['BMSB'],
      why: 'BMS dengan proteksi tegangan dan suhu menghentikan pengisian dan membuka kontaktor rak saat sel keluar batas aman.' },
    { id: 'h35', stage: 3, on: 'bt1', tap: [494, 365], x: 513, y: 294, label: 'Kabel DC rak ke PCS (proteksi arus lebih)', accept: ['OCR'],
      why: 'Sekering atau pemutus DC memutus hubung singkat eksternal pada sisi baterai sebelum kabel dan busbar terbakar.' },
    /* Tahap 4: mitigasi, diurutkan menurut posisi baca pada P&ID (kiri ke kanan, atas ke bawah) */
    { id: 'h49', stage: 4, on: 'PV-801', tap: [148, 59], x: 126, y: 37, label: 'Larik surya (sprinkler)', accept: [],
      why: 'Larik surya di lapangan terbuka tidak memerlukan sprinkler. Risiko kebakaran rumput dikendalikan dengan pengelolaan vegetasi dan pemutusan busur listrik.' },
    { id: 'h41', stage: 4, on: 'BT-801', tap: [260, 319], x: 260, y: 267, label: 'Plafon kontainer (detektor off-gas)', accept: ['OGD'],
      why: 'Detektor off-gas mendeteksi gas sel sebelum asap terlihat, lalu memutus rak dan menyalakan ventilasi exhaust.' },
    { id: 'h44', stage: 4, on: 'BT-801', tap: [336, 319], x: 323, y: 269, label: 'Dalam kontainer (sistem pemadam)', accept: ['SPK'],
      why: 'Sistem berbasis air mendinginkan modul dan membatasi penjalaran thermal runaway. Pemadam gas bersih tidak mendinginkan sel sehingga api dapat menyala kembali.' },
    { id: 'h42', stage: 4, on: 'BT-801', tap: [416, 319], x: 416, y: 267, label: 'Atap kontainer (panel venting ledakan)', accept: ['DVENT'],
      why: 'Panel venting mengarahkan bola api ke atas bila gas tersulut, sehingga pintu dan dinding kontainer tidak terlempar ke arah petugas (NFPA 68).' },
    { id: 'h43', stage: 4, on: 'BT-801', tap: [470, 336], x: 514, y: 292, label: 'Ujung kontainer (ventilasi exhaust darurat)', accept: ['EXV'],
      why: 'Ventilasi exhaust menjaga konsentrasi off-gas di bawah batas mudah terbakar (NFPA 69).' },
    { id: 'h45', stage: 4, on: 'BT-801', tap: [199, 392], x: 177, y: 430, label: 'Dalam kontainer (detektor asap dan panas)', accept: ['SD'],
      why: 'Detektor asap dan panas memberi alarm kebakaran dan memicu sistem pemadam serta pemberitahuan ke regu pemadam.' },
    { id: 'h46', stage: 4, on: 'BT-801', tap: [464, 413], x: 496, y: 432, label: 'Antara BT-801 dan BT-802 (dinding tahan api)', accept: ['FWALL'],
      why: 'Dinding tahan api atau jarak pemisah mencegah kebakaran satu kontainer merambat ke kontainer lain (NFPA 855).' },
    { id: 'h47', stage: 4, on: 'CR-800', tap: [792, 452], x: 823, y: 452, label: 'Ruang kontrol (pemutus darurat BESS)', accept: ['ESD'],
      why: 'Pemutus darurat mengisolasi PCS dan rak dari sisi AC dan DC secara serentak dari lokasi aman.' },
    { id: 'h48', stage: 4, on: 'MP-800', tap: [940, 480], x: 971, y: 480, label: 'Titik kumpul dan alarm umum', accept: ['ALARM'],
      why: 'Petugas dan pemadam harus menjauh dari kontainer yang mengalami thermal runaway karena risiko ledakan gas.' },
  ],
  inspect: [
    { id: 'BT-801', itpm: 'ELEC', why: 'Termografi rak, pemeriksaan keseimbangan tegangan sel, dan uji kapasitas mendeteksi sel menyimpang sebelum memicu thermal runaway.' },
    { id: 'HV-801', itpm: 'ROT', why: 'Pemeliharaan prediktif kompresor dan kipas HVAC mengurangi kegagalan pendinginan pada siang hari saat beban panas tertinggi.' },
    { id: 'INV-801', itpm: 'ELEC', why: 'Termografi dan pemeriksaan pemantauan isolasi pada inverter dan sisi DC mendeteksi sambungan panas dan isolasi yang menurun.' },
  ],
  budget: { 3: 26, 4: 30 },
  bowtie: {
    top: 'Thermal runaway baterai atau busur listrik DC pada PLTS dan BESS',
    threats: ['Gangguan HVAC, kontainer panas atau lembap', 'Overcharge karena BMS gagal', 'Gangguan isolasi kabel DC PV', 'Hubung singkat sel atau sambungan rak panas'],
    cons: ['Ledakan off-gas di kontainer', 'Kebakaran baterai merambat antarmodul', 'Kebakaran combiner dan vegetasi', 'Kebakaran merambat ke kontainer lain'],
  },
};
SCENARIOS.push(SCN_BESS);
