/* Skenario sektor EBT: dimuat setelah js/data.js dan menambahkan diri ke SCENARIOS. */
/* =====================================================================
   EBT: PLT Biogas Limbah Cair Pabrik Kelapa Sawit (POME)
   ===================================================================== */
const SCN_BIOGAS = {
  id: 'biogas',
  title: 'PLT Biogas Limbah Cair Sawit (POME)',
  subtitle: 'Kolam digester tertutup, blower, bio-scrubber H2S, gas engine, dan flare',
  level: 'Menengah',
  sector: 'ebt',
  area: 'Bioenergi (PLTBg)',
  color: '#3d7a5c',
  kits: ['biogas'],
  op: 'Operasi PLT Biogas',
  overview: [
    'Unit ini memanfaatkan limbah cair pabrik kelapa sawit (POME) sebagai bahan baku pembangkit listrik tenaga biogas. POME sekitar 60 m³/jam dialirkan ke kolam digester tertutup DG-701 yang ditutup membran HDPE. Bakteri anaerob menguraikan bahan organik dan menghasilkan sekitar 1.000 Nm³/jam biogas yang terkumpul di bawah cover pada tekanan hanya sekitar 2 mbar.',
    'Biogas mengandung metana 55 hingga 65 persen, karbon dioksida, uap air, dan H2S dalam orde ribuan ppm. Blower B-701 menyedot biogas melalui knock-out KO-701 yang memisahkan kondensat, lalu mengalirkannya ke bio-scrubber SC-701. Di scrubber, bakteri mengoksidasi H2S dengan bantuan sedikit udara yang diinjeksikan melalui FCV-702.',
    'Biogas bersih dibakar di gas engine GE-701 berdaya 1 MW yang menyalurkan listrik ke jaringan PLN. Saat engine berhenti, operator membuka katup manual XV-701 untuk mengalirkan biogas ke flare FL-701. Bahaya utama unit ini adalah gas beracun H2S, kebakaran dan ledakan metana, serta robeknya cover digester.',
  ],
  production: { label: 'Energi listrik dibangkitkan', unit: 'kWh', var: 'MW7', k: 1 / 60 },
  fluidNames: { toxic: 'Biogas mengandung H2S (CH4, CO2, H2S)', water: 'POME dan efluen (air limbah)', air: 'Udara injeksi scrubber', power: 'Kabel daya' },
  equipment: [
    { id: 'PO-700', type: 'sink', x: 150, y: 410, dir: 'left', name: 'POME dari Kolam Pendingin',
      desc: 'Limbah cair pabrik kelapa sawit yang telah didinginkan hingga sekitar 40 °C.' },
    { id: 'DG-701', type: 'lagoon', x: 200, y: 240, w: 300, h: 220, name: 'Kolam Digester Tertutup DG-701',
      desc: 'Kolam anaerob berkapasitas sekitar 30.000 m³ yang ditutup membran HDPE. Membran diangkurkan di parit tepi kolam dan dirancang untuk tekanan biogas hanya beberapa milibar.', vars: ['PC'] },
    { id: 'XV-701', type: 'valve', sub: 'manual', x: 250, y: 175, name: 'XV-701 (Katup Manual ke Flare)',
      desc: 'Katup manual yang dibuka operator untuk mengalirkan biogas ke flare saat engine berhenti atau tekanan digester naik.' },
    { id: 'FL-701', type: 'flare', x: 95, y: 250, name: 'Flare FL-701', flameVar: 'TF',
      desc: 'Membakar biogas berlebih. Pilot dinyalakan secara manual dan nyala dipantau secara visual oleh operator.', vars: ['TF'] },
    { id: 'KO-701', type: 'vessel', x: 436, y: 80, w: 44, h: 84, name: 'Knock-out Kondensat KO-701', level: 'LCT',
      desc: 'Memisahkan air yang mengembun dari biogas jenuh sebelum masuk ke blower. Kondensat dibuang melalui saluran drain gravitasi yang mudah tersumbat lumpur.', vars: ['LCT'] },
    { id: 'B-701', type: 'fan', x: 540, y: 120, name: 'Blower Biogas B-701',
      desc: 'Menyedot biogas dari bawah cover dan menaikkan tekanannya untuk scrubber dan engine. Blower tidak toleran terhadap air.', vars: ['FBG'] },
    { id: 'SC-701', type: 'column', x: 610, y: 70, w: 60, h: 170, name: 'Bio-Scrubber H2S SC-701',
      desc: 'Kolom berisi media tempat bakteri mengoksidasi H2S menjadi sulfur. Proses ini membutuhkan sedikit oksigen dari injeksi udara. Kadar O2 normal dalam biogas kurang dari 1 persen.', vars: ['CH4', 'H2S', 'O2'] },
    { id: 'FCV-702', type: 'valve', sub: 'control', x: 675, y: 300, tag: 'FIC', name: 'FCV-702 (Injeksi Udara Scrubber)',
      desc: 'Mengatur laju udara ke scrubber sekitar 4 persen dari aliran biogas. Bila gagal terbuka penuh, oksigen dalam biogas menjadi berlebih.' },
    { id: 'AIR-701', type: 'sink', x: 720, y: 300, dir: 'right', name: 'Udara dari Kompresor',
      desc: 'Suplai udara bertekanan untuk injeksi bio-scrubber.' },
    { id: 'GE-701', type: 'generator', x: 760, y: 110, w: 130, h: 60, name: 'Gas Engine GE-701 1 MW',
      desc: 'Mesin gas yang menggerakkan generator 1 MW. Biogas harus bersih dari H2S dan air agar mesin tidak cepat rusak.', vars: ['MW7'] },
    { id: 'GRID-701', type: 'sink', x: 848, y: 230, dir: 'right', name: 'Ke Jaringan PLN 20 kV',
      desc: 'Listrik disalurkan melalui trafo step-up ke jaringan distribusi PLN.' },
    { id: 'EF-701', type: 'sink', x: 848, y: 420, dir: 'right', name: 'Efluen ke Kolam Aerobik',
      desc: 'Efluen digester dialirkan ke kolam aerobik untuk pengolahan lanjut.' },
    { id: 'CR-700', type: 'building', x: 640, y: 505, name: 'Ruang Kendali',
      desc: 'Operator memantau tekanan digester, kualitas biogas, dan gas engine.' },
    { id: 'MP-700', type: 'muster', x: 930, y: 505, name: 'Titik Kumpul',
      desc: 'Area berkumpul pada arah angin yang aman dari digester dan flare.' },
  ],
  pipes: [
    { id: 'po', fluid: 'water', w: 7, pts: [[150, 410], [222, 410]], arrow: true },
    { id: 'ef', fluid: 'water', w: 7, pts: [[478, 420], [848, 420]], arrow: true },
    { id: 'g1', fluid: 'toxic', w: 7, pts: [[350, 238], [350, 120], [436, 120]] },
    { id: 'fl', fluid: 'toxic', w: 5, pts: [[350, 175], [150, 175], [150, 246], [103, 246]], arrow: true },
    { id: 'g2', fluid: 'toxic', w: 7, pts: [[480, 120], [518, 120]] },
    { id: 'g3', fluid: 'toxic', w: 6, pts: [[574, 104], [610, 104]] },
    { id: 'air', fluid: 'air', w: 4, pts: [[720, 300], [640, 300], [640, 240]], arrow: true },
    { id: 'g4', fluid: 'toxic', w: 6, pts: [[640, 70], [640, 44], [825, 44], [825, 110]], arrow: true },
    { id: 'pw', fluid: 'power', w: 5, pts: [[825, 170], [825, 230], [848, 230]], arrow: true },
  ],
  labels: [
    { x: 300, y: 165, text: 'Ke flare', size: 10 },
  ],
  vars: {
    PC:  { label: 'Tekanan Bawah Cover Digester', unit: 'mbar', normal: 2.0, min: -2, max: 10, lo: 0.5, lolo: 0, hi: 4, hihi: 6, node: 'DG-701', x: 262, y: 224, tau: 4, noise: 0.03, dec: 1 },
    FBG: { label: 'Aliran Biogas', unit: 'Nm³/j', normal: 1000, min: 0, max: 2000, lo: 500, hi: 1600, node: 'B-701', x: 520, y: 62, tau: 2, noise: 6, dec: 0 },
    CH4: { label: 'Kadar Metana', unit: '%', normal: 60, min: 0, max: 80, lo: 50, node: 'SC-701', x: 725, y: 80, tau: 3, noise: 0.15, dec: 1 },
    H2S: { label: 'H2S Keluar Scrubber', unit: 'ppm', normal: 150, min: 0, max: 3000, hi: 300, hihi: 500, node: 'SC-701', x: 720, y: 200, tau: 4, noise: 2, dec: 0 },
    O2:  { label: 'Kadar O2 dalam Biogas', unit: '%', normal: 0.5, min: 0, max: 21, hi: 2, hihi: 4, node: 'SC-701', x: 720, y: 228, tau: 2, noise: 0.02, dec: 1 },
    TF:  { label: 'Suhu Nyala Flare', unit: '°C', normal: 750, min: 0, max: 1000, lo: 400, lolo: 200, node: 'FL-701', x: 95, y: 118, tau: 1.5, noise: 3, dec: 0 },
    LCT: { label: 'Level Kondensat KO-701', unit: '%', normal: 25, min: 0, max: 100, hi: 60, hihi: 80, node: 'KO-701', x: 458, y: 186, tau: 4, noise: 0.3, dec: 0 },
    MW7: { label: 'Daya Gas Engine', unit: 'kW', normal: 1000, min: 0, max: 1300, lo: 400, node: 'GE-701', x: 935, y: 140, tau: 2, noise: 4, dec: 0 },
  },
  trendVars: ['PC', 'O2', 'TF', 'LCT'],
  controls: [
    { id: 'pome', label: 'Laju umpan POME', unit: 'm³/j', min: 30, max: 90, def: 60, step: 5,
      effects: [{ var: 'FBG', gain: 16 }, { var: 'PC', gain: 0.015 }] },
    { id: 'airdose', label: 'Injeksi udara scrubber (FIC-702)', unit: '%', min: 2, max: 8, def: 4, step: 0.5,
      effects: [{ var: 'O2', gain: 0.12 }, { var: 'H2S', gain: -25 }] },
    { id: 'engine', label: 'Beban gas engine', unit: 'kW', min: 500, max: 1200, def: 1000, step: 50,
      effects: [{ var: 'MW7', gain: 1 }, { var: 'TF', gain: -0.5 }, { var: 'PC', gain: -0.002 }] },
  ],
  quiz: [
    { q: 'Apa komponen utama biogas dari POME?', opts: ['Metana sekitar 55 hingga 65 persen, karbon dioksida, serta H2S dalam orde ribuan ppm', 'Metana sekitar 90 persen dengan sedikit etana, mirip gas alam dari pipa transmisi', 'Karbon dioksida sekitar 60 persen, metana, serta H2S dalam orde puluhan ppm saja', 'Metana sekitar 55 hingga 65 persen, nitrogen, serta oksigen yang terlarut dari udara di permukaan kolam'], ans: 0,
      why: 'Metana membuat biogas bernilai sebagai bahan bakar sekaligus mudah terbakar. H2S membuatnya sangat beracun dan korosif sehingga perlu dihilangkan sebelum masuk engine.' },
    { q: 'Mengapa tekanan di bawah cover membran harus dijaga sangat rendah?', opts: ['Cover membran hanya dirancang untuk beberapa milibar dan mudah robek di parit angkur bila tekanan berlebih', 'Agar metana tetap terlarut di dalam POME dan tidak lepas ke ruang gas di bawah cover', 'Agar blower tidak perlu bekerja dan biogas mengalir sendiri ke gas engine', 'Karena tekanan yang lebih tinggi langsung menghentikan aktivitas bakteri metanogen di dalam kolam digester'], ans: 0,
      why: 'Cover HDPE adalah struktur ringan. Tekanan berlebih membuat membran menggembung dan robek di tepi, melepaskan biogas pada ketinggian rendah di dekat pekerja.' },
    { q: 'Mengapa injeksi udara ke bio-scrubber harus dibatasi?', opts: ['Udara berlebih membentuk campuran biogas dan udara yang mudah meledak di dalam sistem', 'Udara berlebih membunuh bakteri pengoksidasi H2S sehingga penyisihan H2S di bio-scrubber gagal', 'Udara berlebih menaikkan kadar H2S karena sulfur yang terbentuk teroksidasi kembali menjadi gas', 'Udara berlebih menaikkan tekanan di bawah cover sehingga membran menggelembung'], ans: 0,
      why: 'Bakteri pengoksidasi H2S membutuhkan sedikit oksigen, tetapi kelebihan udara menurunkan kadar metana ke rentang mudah meledak di dalam pipa dan scrubber.' },
    { q: 'Apa fungsi flare pada PLT biogas?', opts: ['Membakar biogas berlebih atau saat engine berhenti sehingga metana dan H2S tidak lepas tanpa dibakar', 'Menjaga tekanan cover tetap rendah dengan membakar sebagian biogas secara terus-menerus siang dan malam', 'Memanaskan biogas agar uap air terpisah sebelum masuk gas engine', 'Menjadi sumber nyala cadangan untuk menyalakan gas engine saat start pagi hari'], ans: 0,
      why: 'Flare adalah sarana pembuangan aman. Flare yang padam justru melepaskan biogas mentah yang beracun dan mudah terbakar.' },
    { q: 'Mengapa H2S sangat berbahaya bagi pekerja di sekitar digester?', opts: ['Pada konsentrasi tinggi, H2S melumpuhkan indra penciuman dan dapat menyebabkan pingsan hingga kematian', 'Bau telur busuknya selalu tercium sehingga pekerja memiliki cukup waktu untuk menyelamatkan diri', 'H2S lebih ringan daripada udara sehingga terkumpul di atas cover dan sulit dideteksi dari permukaan tanah', 'H2S baru berbahaya setelah terbakar karena menghasilkan gas SO2 yang beracun'], ans: 0,
      why: 'Pada konsentrasi sekitar 100 ppm ke atas, indra penciuman lumpuh sehingga bau tidak lagi menjadi peringatan. H2S juga lebih berat daripada udara dan dapat terkumpul di cekungan dan ruang tertutup.' },
  ],
  events: [
    { id: 'e1', threat: 0, effects: [{ var: 'FBG', to: 0, delay: 1, dur: 3 }, { var: 'MW7', to: 0, delay: 2, dur: 4 }, { var: 'PC', to: 9.5, delay: 2, dur: 22 }],
      warnings: [
        { t: 12, type: 'vibration', sev: 'warn', at: 'DG-701', text: 'Cover membran digester menggembung tinggi dan berderit keras tertiup angin.' },
        { t: 18, type: 'toxic', sev: 'crit', at: 'DG-701', pos: [215, 330], text: 'Membran robek di parit angkur tepi kolam. Biogas beracun yang mengandung H2S keluar dan detektor gas personal pekerja berbunyi.' },
        { t: 26, type: 'fire', sev: 'final', at: 'DG-701', pos: [232, 320], text: 'Biogas yang lepas tersulut percikan dari kendaraan di dekat kolam. Kebakaran terjadi di tepi digester.' },
      ],
      answer: { node: ['DG-701', 'B-701'], param: ['P', 'F'], guide: ['high', 'none'] },
      hint: 'Biogas terus terbentuk, tetapi tidak ada yang menyedotnya keluar dari bawah cover.',
      causes: ['Blower B-701 trip dan flare tidak dinyalakan tepat waktu sehingga biogas menumpuk di bawah cover', 'Laju POME turun', 'Injeksi udara scrubber terlalu kecil', 'Level kondensat rendah'], causeAns: 0,
      cons: ['Tekanan di bawah cover melampaui batas, membran robek, dan biogas beracun serta mudah terbakar lepas ke area kerja', 'Daya gas engine naik', 'Kadar metana naik tanpa dampak', 'Efluen menjadi lebih jernih'], consAns: 0,
      explain: 'Aliran biogas berhenti, lalu tekanan di bawah cover naik terus. Cover membran dirancang untuk tekanan hanya beberapa milibar. Proteksi yang tepat adalah katup pengaman tekanan-vakum pada cover, alarm tekanan, dan flare yang menyala otomatis saat tekanan tinggi atau engine berhenti.' },
    { id: 'e2', threat: 1, effects: [{ var: 'O2', to: 11, delay: 1, dur: 14 }, { var: 'CH4', to: 42, delay: 2, dur: 14 }],
      warnings: [
        { t: 8, type: 'vibration', sev: 'warn', at: 'GE-701', text: 'Gas engine GE-701 tersendat dan terjadi letupan balik (backfire) di saluran masuk.' },
        { t: 14, type: 'heat', sev: 'crit', at: 'SC-701', text: 'Dinding scrubber SC-701 memanas dan terdengar dentuman kecil di pipa biogas.' },
        { t: 21, type: 'explosion', sev: 'final', at: 'SC-701', pos: [640, 150], text: 'Ledakan terjadi di scrubber SC-701. Campuran biogas dan udara tersulut, lalu nyala api merambat balik di pipa biogas.' },
      ],
      answer: { node: ['SC-701', 'FCV-702'], param: ['C'], guide: ['aswell', 'high'] },
      hint: 'Kadar oksigen dalam biogas naik terus. Udara masuk jauh lebih banyak daripada seharusnya.',
      causes: ['FCV-702 injeksi udara scrubber gagal terbuka penuh sehingga oksigen dalam biogas berlebih', 'Blower trip', 'Laju POME naik', 'Flare padam'], causeAns: 0,
      cons: ['Terbentuk campuran biogas dan udara yang mudah meledak di dalam scrubber dan pipa, lalu tersulut dan meledak', 'Kadar H2S naik', 'Daya engine naik', 'Level kondensat naik'], consAns: 0,
      explain: 'Kadar oksigen naik dari kurang dari satu persen menuju belasan persen, sementara metana turun. Bio-scrubber memang membutuhkan sedikit udara, tetapi kelebihan udara membentuk campuran mudah meledak. Proteksi yang tepat adalah analyzer O2 yang menghentikan injeksi udara dan blower, serta flame arrester agar nyala tidak merambat ke digester.' },
    { id: 'e3', threat: 2, effects: [{ var: 'MW7', to: 0, delay: 1, dur: 3 }, { var: 'TF', to: 40, delay: 2, dur: 5 }],
      warnings: [
        { t: 7, type: 'leak', sev: 'warn', at: 'FL-701', pos: [95, 152], text: 'Nyala flare FL-701 padam dan biogas yang tidak terbakar keluar dari ujung flare.' },
        { t: 13, type: 'toxic', sev: 'crit', at: 'FL-701', pos: [125, 170], big: true, text: 'Gas beracun H2S terbawa angin ke area kerja. Bau telur busuk sangat menyengat.' },
        { t: 20, type: 'toxic', sev: 'final', at: 'FL-701', pos: [170, 300], big: true, text: 'Pekerja di area penerimaan pingsan akibat paparan H2S. Evakuasi dan penyelamatan darurat diperlukan.' },
      ],
      answer: { node: ['FL-701', 'XV-701'], param: ['T', 'C'], guide: ['low', 'none'] },
      hint: 'Suhu nyala flare turun drastis. Biogas tetap mengalir ke flare, tetapi tidak lagi dibakar.',
      causes: ['Nyala flare padam karena angin kencang atau pilot gagal, sementara biogas terus dialirkan ke flare', 'Kadar O2 naik', 'Level kondensat tinggi', 'Laju POME turun'], causeAns: 0,
      cons: ['Biogas yang tidak terbakar membawa H2S ke area kerja dan permukiman sehingga terjadi keracunan', 'Daya engine naik', 'Tekanan cover turun tanpa dampak', 'Efluen tercemar minyak'], consAns: 0,
      explain: 'Daya engine hilang sehingga biogas dialihkan ke flare, lalu suhu nyala flare anjlok. Biogas sawit mengandung H2S ribuan ppm, sedangkan nilai ambang batas H2S di tempat kerja di Indonesia hanya 1 ppm. Flare harus dilengkapi pilot, penyalaan otomatis, dan pemantauan nyala yang menutup aliran bila nyala tidak terdeteksi.' },
    { id: 'e4', threat: 3, effects: [{ var: 'LCT', to: 99, delay: 2, dur: 16 }, { var: 'FBG', to: 700, delay: 12, dur: 6 }],
      warnings: [
        { t: 15, type: 'vibration', sev: 'warn', at: 'B-701', text: 'Blower B-701 bergetar keras dan terdengar benturan air di rumah blower.' },
        { t: 21, type: 'toxic', sev: 'crit', at: 'B-701', pos: [545, 152], text: 'Seal blower rusak. Biogas dan H2S bocor di rumah blower.' },
        { t: 28, type: 'fire', sev: 'final', at: 'B-701', pos: [540, 122], text: 'Biogas yang bocor tersulut motor blower. Kebakaran terjadi di rumah blower.' },
      ],
      answer: { node: ['KO-701', 'B-701'], param: ['L'], guide: ['high'] },
      hint: 'Air kondensat terus terkumpul di knock-out, tetapi tidak dibuang. Pikirkan akibatnya bagi blower di hilir.',
      causes: ['Saluran pembuangan kondensat KO-701 tersumbat lumpur sehingga air terbawa ke blower', 'Injeksi udara terlalu besar', 'Flare padam', 'Laju POME turun'], causeAns: 0,
      cons: ['Air terbawa ke blower, blower rusak dan seal bocor, lalu biogas beracun dan mudah terbakar lepas dan terbakar', 'Kadar metana naik', 'Tekanan cover turun tanpa dampak', 'Daya engine naik'], consAns: 0,
      explain: 'Level kondensat naik terus tanpa perubahan lain, lalu blower bergetar. Biogas dari digester yang hangat jenuh uap air sehingga air terus mengembun di pipa. Proteksi yang tepat adalah alarm level dan trip level tinggi-tinggi yang menghentikan blower, serta pemeriksaan rutin saluran kondensat.' },
    { id: 'e5', start: 12,
      hf: { type: 'mistake', team: 'ops', threat: 1, title: 'Injeksi udara dibuka melebihi batas', factor: 'Bypass udara scrubber dibuka melampaui set point',
        lesson: 'Dimas melakukan mistake berbasis pengetahuan: niatnya menurunkan H2S, tetapi keyakinannya bahwa udara berlebih selalu lebih baik ternyata keliru. Ia juga bertindak di luar kewenangan karena membuka bypass untuk melewati batas yang dikunci insinyur proses. Kontrolnya adalah pelatihan bahaya campuran biogas dan udara, trip oksigen tinggi yang menghentikan injeksi udara, dan larangan memakai bypass untuk melewati batas operasi.',
        controls: ['Pelatihan rentang mudah meledak biogas dan prinsip kerja bio-scrubber', 'Trip oksigen tinggi yang menutup injeksi udara secara otomatis', 'Perubahan batas operasi hanya melalui MOC dan persetujuan insinyur proses'] },
      chat: [
        { t: 1, who: 'hendra', at: 'CR-700', text: 'H2S keluar scrubber naik lagi. Jika terus begini, gas engine dapat trip. Mohon segera diturunkan.' },
        { t: 4, who: 'dimas', at: 'SC-701', mood: 'santai', text: 'Udara ke bio-scrubber saya buka lebar saja, Pak. Makin banyak udara, makin cepat bakteri menguraikan H2S.' },
        { t: 7, who: 'raka', at: 'CR-700', mood: 'ragu', text: 'Dimas, set point FCV-702 dikunci insinyur proses pada 4 persen. Ada batasnya.' },
        { t: 10, who: 'dimas', at: 'FCV-702', mood: 'santai', text: 'Saya buka melalui bypass manual, set point tidak saya ubah. Hanya sebentar sampai H2S turun.' },
        { t: 13, who: 'raka', at: 'CR-700', text: 'Baik, saya pantau kadar H2S.' },
        { t: 19, who: 'raka', at: 'CR-700', mood: 'ragu', text: 'H2S memang turun, tetapi kadar oksigen naik cepat dan metana ikut turun.' },
        { t: 24, who: 'raka', at: 'CR-700', mood: 'panik', text: 'Kadar oksigen sudah melewati batas alarm! Dimas, tutup bypass udara sekarang!' },
      ],
      effects: [{ var: 'O2', to: 11, delay: 1, dur: 14 }, { var: 'CH4', to: 42, delay: 2, dur: 14 }, { var: 'H2S', to: 60, delay: 1, dur: 8 }],
      warnings: [
        { t: 9, type: 'vibration', sev: 'warn', at: 'GE-701', text: 'Gas engine GE-701 tersendat dan terjadi letupan balik (backfire) di saluran masuk.' },
        { t: 15, type: 'heat', sev: 'crit', at: 'SC-701', text: 'Dinding scrubber SC-701 memanas dan terdengar dentuman kecil di pipa biogas.' },
        { t: 22, type: 'explosion', sev: 'final', at: 'SC-701', pos: [640, 150], text: 'Ledakan terjadi di scrubber SC-701. Campuran biogas dan udara tersulut, lalu nyala api merambat balik di pipa biogas.' },
      ],
      answer: { node: ['SC-701', 'FCV-702'], param: ['C'], guide: ['aswell', 'high'] },
      hint: 'H2S turun, tetapi oksigen naik dan metana turun. Ada udara yang masuk jauh melampaui set point. Baca kembali obrolan tentang cara menurunkan H2S.',
      causes: ['Operator membuka bypass udara bio-scrubber melampaui set point karena mengira udara berlebih selalu lebih baik', 'Membran cover digester bocor sehingga udara terisap ke ruang gas', 'Blower B-701 mengisap udara dari sambungan pipa yang longgar', 'Analyzer oksigen terkalibrasi keliru sehingga kadar oksigen terbaca tinggi'], causeAns: 0,
      cons: ['Campuran biogas dan udara masuk rentang mudah meledak, lalu tersulut di blower, scrubber, atau gas engine', 'H2S turun sehingga umur gas engine lebih panjang tanpa dampak lain', 'Produksi listrik naik karena oksigen membantu pembakaran di engine', 'Bakteri scrubber mati sehingga H2S naik kembali'], consAns: 0,
      explain: 'Kadar oksigen naik melewati batas alarm dan metana turun, sementara H2S justru membaik. Udara berlebih membentuk campuran metana dan udara yang dapat masuk rentang mudah meledak, sekitar 5 sampai 15 persen metana di udara. Penurunan H2S yang tampak baik menyembunyikan bahaya yang lebih besar.' },
    { id: 'e6', threat: 2, effects: [{ var: 'H2S', to: 2600, delay: 1, dur: 14 }],
      warnings: [
        { t: 10, type: 'toxic', sev: 'warn', at: 'GE-701', text: 'Bau telur busuk tercium di sekitar rumah gas engine dan gas buang engine berbau belerang menyengat.' },
        { t: 17, type: 'toxic', sev: 'crit', at: 'GE-701', text: 'Detektor gas personal mekanik yang memeriksa gas train di rumah engine berbunyi keras.' },
        { t: 24, type: 'toxic', sev: 'final', at: 'GE-701', pos: [780, 205], big: true, text: 'Mekanik di rumah engine pingsan akibat H2S yang bocor dari flens gas train. Penyelamatan darurat diperlukan.' },
      ],
      answer: { node: ['SC-701'], param: ['C'], guide: ['partof', 'high'] },
      hint: 'Kadar H2S keluar scrubber naik terus, sementara oksigen, metana, dan aliran biogas tetap normal. Pikirkan bagian proses pembersihan H2S yang berhenti bekerja.',
      causes: ['Pompa sirkulasi larutan nutrisi bio-scrubber trip sehingga media mengering dan bakteri berhenti mengoksidasi H2S', 'Injeksi udara scrubber gagal terbuka penuh sehingga oksigen dalam biogas berlebih', 'Flare padam sehingga biogas keluar tanpa dibakar', 'Saluran kondensat KO-701 tersumbat sehingga air terbawa ke blower'], causeAns: 0,
      cons: ['Biogas ber-H2S tinggi sampai ke rumah gas engine, kebocoran kecil di gas train meracuni pekerja, dan engine cepat rusak', 'H2S terbakar habis di dalam engine sehingga tidak berdampak', 'Kadar metana naik sehingga daya engine bertambah', 'Tekanan bawah cover naik sehingga membran robek'], consAns: 0,
      explain: 'H2S keluar scrubber naik terus, sementara oksigen, metana, dan aliran biogas tetap normal. Bio-scrubber hanya bekerja bila bakteri mendapat larutan nutrisi yang disirkulasikan. Saat pompa sirkulasi berhenti, hanya sebagian tujuan desain yang tercapai: biogas tetap mengalir, tetapi H2S tidak lagi dibersihkan. Ini deviasi komposisi Sebagian (Part of) yang tampak sebagai H2S lebih tinggi. Alarm dan trip H2S tinggi yang mengalihkan biogas ke flare, detektor H2S di rumah engine, dan pemeriksaan rutin pompa sirkulasi memutus rantai ini.' },
    { id: 'e7', start: 12,
      hf: { type: 'lapse', team: 'ops', threat: 3, title: 'Pembuangan kondensat manual KO-701 terlupa karena operator dialihkan ke tugas lain', factor: 'Drain manual KO-701 terlupa saat dialihkan ke tugas lain',
        lesson: 'Dimas berniat membuang kondensat pada jam yang dijadwalkan, tetapi lupa karena dialihkan ke pompa POME yang macet. Lupa melakukan langkah yang sudah direncanakan tergolong lapse. Akar masalahnya adalah tindakan sementara yang bergantung pada ingatan satu orang karena drain otomatis yang tersumbat belum diperbaiki. Pencegahnya adalah perbaikan drain otomatis secepatnya, pengingat dan daftar periksa untuk tugas manual berkala, serta trip level tinggi-tinggi yang menghentikan blower sebelum air terbawa.',
        controls: ['Drain otomatis segera diperbaiki, tindakan manual hanya sementara dan diberi batas waktu', 'Pengingat dan daftar periksa untuk tugas manual berkala, termasuk saat serah terima', 'Trip level tinggi-tinggi KO-701 yang menghentikan blower'] },
      chat: [
        { t: 1, who: 'hendra', at: 'CR-700', text: 'Drain otomatis KO-701 masih tersumbat. Sampai diperbaiki, kondensat dibuang secara manual setiap dua jam.' },
        { t: 4, who: 'dimas', at: 'KO-701', text: 'Baik, Pak. Terakhir saya buang pukul dua. Pukul empat nanti saya buang lagi.' },
        { t: 7, who: 'raka', at: 'CR-700', text: 'Dimas, pompa umpan POME di kolam pendingin macet. Mohon diperiksa terlebih dahulu.' },
        { t: 10, who: 'dimas', at: 'PO-700', mood: 'santai', text: 'Baik, saya ke kolam pendingin. Pompanya tersumbat sampah tandan dan perbaikannya perlu waktu agak lama.' },
        { t: 22, who: 'raka', at: 'CR-700', mood: 'ragu', text: 'Level kondensat KO-701 naik terus di layar. Dimas, apakah drain manual sudah dibuka?' },
        { t: 27, who: 'dimas', at: 'PO-700', mood: 'panik', text: 'Maaf, saya lupa! Saya masih di kolam pendingin dan segera ke sana.' },
        { t: 31, who: 'raka', at: 'CR-700', mood: 'panik', text: 'Blower bergetar keras! Hentikan blower sebelum air masuk lebih banyak!' },
      ],
      effects: [{ var: 'LCT', to: 99, delay: 2, dur: 16 }, { var: 'FBG', to: 700, delay: 12, dur: 6 }],
      warnings: [
        { t: 15, type: 'vibration', sev: 'warn', at: 'B-701', text: 'Blower B-701 bergetar keras dan terdengar benturan air di rumah blower.' },
        { t: 21, type: 'toxic', sev: 'crit', at: 'B-701', pos: [545, 152], text: 'Seal blower rusak. Biogas dan H2S bocor di rumah blower.' },
        { t: 28, type: 'fire', sev: 'final', at: 'B-701', pos: [540, 122], text: 'Biogas yang bocor tersulut motor blower. Kebakaran terjadi di rumah blower.' },
      ],
      answer: { node: ['KO-701', 'B-701'], param: ['L'], guide: ['high'] },
      hint: 'Level kondensat naik terus padahal tidak ada perubahan proses lain. Baca kembali obrolan tentang jadwal pembuangan kondensat dan tugas lain yang muncul.',
      causes: ['Operator lupa membuang kondensat KO-701 secara manual karena dialihkan ke tugas lain, sementara drain otomatis masih tersumbat', 'Injeksi udara scrubber terlalu besar sehingga uap air dalam biogas bertambah', 'Blower B-701 trip sehingga kondensat tidak lagi terbawa', 'Transmitter level KO-701 menyimpang sehingga level terbaca tinggi palsu'], causeAns: 0,
      cons: ['Air terbawa ke blower, blower rusak dan seal bocor, lalu biogas beracun dan mudah terbakar lepas dan terbakar', 'Kondensat menguap kembali sehingga level turun sendiri tanpa dampak', 'Kadar metana naik karena air terpisah lebih banyak', 'Daya gas engine naik karena biogas lebih kering'], consAns: 0,
      explain: 'Level kondensat naik terus tanpa perubahan proses lain, lalu blower bergetar karena air terbawa. Polanya sama dengan saluran kondensat yang tersumbat karena drain otomatis memang tersumbat dan pembuangan manual yang menggantikannya terlupa. Tindakan sementara yang bergantung pada ingatan manusia harus diberi batas waktu, dan trip level tinggi-tinggi tetap diperlukan sebagai pengaman.' },
    { id: 'e8', start: 12,
      hf: { type: 'violation', team: 'mgmt', threat: 0, title: 'Biogas sengaja ditahan di bawah cover tanpa flare karena keluhan warga', factor: 'Flare sengaja tidak dipakai saat engine berhenti',
        lesson: 'Hendra tahu SOP mewajibkan biogas dialirkan ke flare saat engine berhenti, tetapi sengaja menahannya di bawah cover agar warga tidak mengeluh. Penyimpangan yang disengaja dari prosedur yang diketahui tergolong violation, dalam hal ini violation situasional akibat tekanan dari luar. Keluhan warga adalah masalah nyata yang perlu diselesaikan, misalnya dengan flare tertutup (enclosed flare) dan komunikasi dengan warga, bukan dengan menghapus jalur pelepasan yang aman. Pencegahnya adalah flare otomatis yang menyala saat tekanan tinggi, katup pengaman tekanan-vakum pada cover, dan kebijakan bahwa keselamatan proses tidak dikorbankan karena keluhan nonteknis.',
        controls: ['Flare otomatis yang menyala saat tekanan cover tinggi atau engine berhenti', 'Katup pengaman tekanan-vakum pada cover digester', 'Keluhan warga ditangani dengan solusi teknis seperti flare tertutup, bukan dengan menunda pelepasan aman'] },
      chat: [
        { t: 1, who: 'hendra', at: 'CR-700', text: 'Gas engine GE-701 menjalani overhaul mulai malam ini sampai besok siang. Warga desa memprotes nyala flare yang terlalu terang dan bising.' },
        { t: 4, who: 'raka', at: 'CR-700', mood: 'ragu', text: 'Sesuai SOP, jika engine berhenti, biogas harus dialirkan ke flare, Pak.' },
        { t: 7, who: 'hendra', at: 'CR-700', mood: 'santai', text: 'Matikan blower dan jangan nyalakan flare. Biogas ditahan di bawah cover saja sampai pagi, membrannya masih kuat.' },
        { t: 10, who: 'dimas', at: 'DG-701', mood: 'ragu', text: 'Cover dirancang hanya untuk beberapa milibar, Pak. Sampai pagi masih lama.' },
        { t: 22, who: 'raka', at: 'CR-700', mood: 'ragu', text: 'Tekanan bawah cover naik terus dan sudah mendekati batas alarm.' },
        { t: 26, who: 'dimas', at: 'DG-701', mood: 'panik', text: 'Tali pemberat cover tertarik kencang dan membran berderit di tepi kolam!' },
        { t: 30, who: 'raka', at: 'CR-700', mood: 'panik', text: 'Membran robek di tepi kolam! Semua personel menjauh dan nyalakan flare sekarang!' },
      ],
      effects: [{ var: 'FBG', to: 0, delay: 1, dur: 3 }, { var: 'MW7', to: 0, delay: 1, dur: 3 }, { var: 'PC', to: 9.5, delay: 2, dur: 20 }],
      warnings: [
        { t: 12, type: 'vibration', sev: 'warn', at: 'DG-701', text: 'Cover membran menggembung tinggi seperti balon dan tali pemberatnya tertarik kencang.' },
        { t: 18, type: 'toxic', sev: 'crit', at: 'DG-701', pos: [215, 330], text: 'Membran robek di parit angkur tepi kolam. Biogas mengandung H2S keluar ke arah permukiman.' },
        { t: 26, type: 'fire', sev: 'final', at: 'DG-701', pos: [232, 320], text: 'Biogas yang lepas tersulut lampu dan kendaraan di jalan desa. Kebakaran terjadi di tepi digester.' },
      ],
      answer: { node: ['DG-701', 'B-701'], param: ['P', 'F'], guide: ['high', 'none'] },
      hint: 'Aliran biogas berhenti dan tekanan bawah cover naik, padahal tidak ada kerusakan peralatan. Baca kembali obrolan tentang flare dan keluhan warga.',
      causes: ['Supervisor sengaja menahan biogas di bawah cover dan melarang flare dinyalakan saat engine berhenti karena keluhan warga', 'Blower B-701 trip karena bantalannya rusak', 'Saluran kondensat KO-701 tersumbat sehingga blower terendam air', 'Transmitter tekanan cover menyimpang sehingga tekanan terbaca tinggi palsu'], causeAns: 0,
      cons: ['Tekanan bawah cover melampaui batas, membran robek, dan biogas beracun serta mudah terbakar lepas ke arah permukiman', 'Biogas tersimpan aman sampai pagi dan engine dapat langsung beroperasi penuh', 'Kadar metana naik sehingga produksi listrik esok hari lebih besar', 'Kolam digester mendingin sehingga bakteri berhenti bekerja tanpa dampak lain'], consAns: 0,
      explain: 'Aliran biogas berhenti dan tekanan bawah cover naik terus, polanya sama dengan blower trip. Bedanya, tidak ada peralatan yang rusak: biogas sengaja tidak dialirkan ke flare. Cover membran dirancang untuk tekanan hanya beberapa milibar sehingga produksi biogas yang terus berlangsung cepat melampaui batas tersebut. Katup pengaman tekanan-vakum dan flare otomatis tetap diperlukan karena prosedur dapat dilanggar.' },
  ],
  variants: [
    ['e3', 'e6', 'e8', 'e2', 'e7'],
    ['e1', 'e3', 'e5', 'e6', 'e7'],
    ['e4', 'e6', 'e8', 'e3', 'e5'],
    ['e6', 'e4', 'e5', 'e1', 'e8'],
    ['e2', 'e3', 'e8', 'e4', 'e7'],
  ],
  hotspots: [
    /* Tahap 3: pencegahan, diurutkan menurut posisi baca pada P&ID (kiri ke kanan, atas ke bawah) */
    { id: 'h35', stage: 3, on: 'g2', tap: [501, 120], x: 501, y: 76, label: 'Pipa biogas sebelum blower (flame arrester)', accept: ['FARR'],
      why: 'Flame arrester mencegah nyala dari engine, flare, atau ledakan di hilir merambat balik ke digester.' },
    { id: 'h39', stage: 3, on: 'g3', tap: [592, 104], x: 582, y: 68, label: 'Sisi keluar blower B-701', accept: ['NRV'],
      why: 'Check valve mencegah biogas bertekanan dari header engine mengalir balik ke blower yang berhenti.' },
    { id: 'h34', stage: 3, on: 'g4', tap: [700, 44], x: 708, y: 74, label: 'Biogas keluar scrubber (analyzer oksigen)', accept: ['O2T'],
      why: 'Analyzer O2 menghentikan injeksi udara dan blower sebelum campuran biogas dan udara mencapai rentang mudah meledak.' },
    { id: 'h33', stage: 3, on: 'fl', tap: [150, 214], x: 181, y: 214, label: 'Jalur flare (pembukaan dan penyalaan otomatis)', accept: ['FIG'],
      why: 'Flare otomatis membuka jalur dan menyalakan pilot saat tekanan tinggi atau engine berhenti, serta menyalakan ulang bila nyala padam.' },
    { id: 'h32', stage: 3, on: 'DG-701', tap: [291, 263], x: 264, y: 248, label: 'Cover digester (transmitter tekanan)', accept: ['PT'],
      why: 'Alarm tekanan di bawah cover memberi peringatan dini agar operator menyalakan flare atau memulihkan blower.' },
    { id: 'h31', stage: 3, on: 'DG-701', tap: [416, 265], x: 394, y: 243, label: 'Cover digester (katup pengaman tekanan-vakum)', accept: ['PVRV'],
      why: 'Katup tekanan-vakum melepas biogas melalui titik tinggi yang terarah sebelum membran robek di tepi kolam, serta mencegah membran tersedot saat vakum.' },
    { id: 'h36', stage: 3, on: 'KO-701', tap: [456, 165], x: 464, y: 195, label: 'Knock-out KO-701 (level kondensat)', accept: ['LSHH', 'LT'],
      why: 'Trip level tinggi-tinggi menghentikan blower sebelum air terbawa. Alarm level diterima sebagai lapisan respons operator.' },
    { id: 'h38', stage: 3, on: 'GE-701', tap: [800, 171], x: 774, y: 197, label: 'Gas engine GE-701 (sisi listrik)', accept: [],
      why: 'Proteksi listrik generator penting, tetapi tidak menangani ancaman biogas pada digester, scrubber, dan flare.' },
    { id: 'h37', stage: 3, on: 'po', tap: [180, 410], x: 158, y: 448, label: 'Saluran masuk POME', accept: [],
      why: 'Aliran POME masuk tidak terkait langsung dengan skenario yang teridentifikasi. Perangkat di sini tidak memutus rantai kejadian utama.' },
    /* Tahap 4: mitigasi, diurutkan menurut posisi baca pada P&ID (kiri ke kanan, atas ke bawah) */
    { id: 'h46', stage: 4, on: 'B-701', tap: [540, 97], x: 513, y: 82, label: 'Rumah blower (hidran)', accept: ['FW'],
      why: 'Hidran dan monitor air dipakai untuk memadamkan kebakaran dan mendinginkan peralatan di sekitar rumah blower.' },
    { id: 'h43', stage: 4, on: 'g4', tap: [790, 44], x: 798, y: 74, label: 'Jalur biogas ke gas engine (isolasi jarak jauh)', accept: ['EIV'],
      why: 'Katup isolasi jarak jauh menghentikan pasokan biogas ke area kebocoran atau kebakaran dari lokasi aman.' },
    { id: 'h49', stage: 4, on: 'GE-701', tap: [890, 140], x: 921, y: 140, label: 'Gas engine (pemadam api ringan)', accept: ['APAR'],
      why: 'APAR kelas B dan C memungkinkan operator memadamkan api tahap awal di sekitar engine.' },
    { id: 'h42', stage: 4, on: 'B-701', tap: [556, 136], x: 582, y: 181, label: 'Rumah blower (detektor gas)', accept: ['GD'],
      why: 'Seal blower adalah titik bocor umum di area tertutup. Detektor gas memicu alarm, ventilasi, dan penghentian blower.' },
    { id: 'h48', stage: 4, on: 'DG-701', tap: [388, 260], x: 388, y: 229, label: 'Permukaan digester (sistem busa)', accept: [],
      why: 'Busa dipakai untuk kebakaran cairan mudah terbakar. Pelepasan biogas dari membran tidak dimitigasi dengan busa.' },
    { id: 'h41', stage: 4, on: 'DG-701', tap: [217, 300], x: 186, y: 300, label: 'Tepi digester (detektor H2S dan metana)', accept: ['GD'],
      why: 'Detektor gas di tepi kolam mendeteksi kebocoran membran pada ketinggian rendah tempat H2S terkumpul.' },
    { id: 'h44', stage: 4, on: 'CR-700', tap: [674, 488], x: 666, y: 458, label: 'Ruang kendali (ESD)', accept: ['ESD'],
      why: 'ESD menghentikan blower, engine, dan injeksi udara secara serentak.' },
    { id: 'h45', stage: 4, on: 'CR-700', tap: [670, 504], x: 701, y: 504, label: 'Ruang kendali (SCBA dan detektor personal)', accept: ['SCBA'],
      why: 'Alat bantu napas dan detektor personal memungkinkan evakuasi serta penyelamatan pekerja di area H2S.' },
    { id: 'h47', stage: 4, on: 'MP-700', tap: [950, 504], x: 958, y: 474, label: 'Titik kumpul (arah angin) dan alarm umum', accept: ['ALARM'],
      why: 'Evakuasi harus mengikuti arah angin karena awan H2S dapat menyebar ke area kerja dan permukiman.' },
  ],
  inspect: [
    { id: 'B-701', itpm: 'ROT', why: 'Pemantauan getaran blower mendeteksi kerusakan bantalan dan seal, serta tanda awal air terbawa.' },
    { id: 'GE-701', itpm: 'ROT', why: 'Perawatan prediktif gas engine mengurangi trip mendadak yang memaksa biogas dialihkan ke flare.' },
    { id: 'SC-701', itpm: 'VESSEL', why: 'H2S dan sulfur membuat scrubber sangat korosif. Pemeriksaan ketebalan dinding mencegah kebocoran biogas beracun.' },
  ],
  budget: { 3: 27, 4: 26 },
  bowtie: {
    top: 'Pelepasan biogas (metana dan H2S) atau campuran mudah meledak di sistem PLT biogas',
    threats: ['Blower trip, tekanan cover naik', 'Udara berlebih masuk ke biogas', 'Flare padam atau H2S lolos dari scrubber', 'Kondensat terbawa ke blower'],
    cons: ['Membran robek dan kebakaran di tepi kolam', 'Ledakan scrubber dan pipa', 'Keracunan H2S pekerja dan warga', 'Kebakaran rumah blower'],
  },
};
SCENARIOS.push(SCN_BIOGAS);
