/* Skenario sektor EBT: dimuat setelah js/data.js dan menambahkan diri ke SCENARIOS. */
/* =====================================================================
   EBT: PLTS dengan Sistem Penyimpanan Energi Baterai (BESS)
   ===================================================================== */
const SCN_BESS = {
  id: 'bess',
  title: 'PLTS dengan Penyimpanan Baterai (BESS)',
  subtitle: 'Larik surya, inverter, kontainer baterai litium, HVAC, trafo step-up',
  level: 'Lanjutan',
  sector: 'ebt',
  area: 'Energi Surya (PLTS + BESS)',
  color: '#2f7f9c',
  kits: ['bess'],
  op: 'Operasi PLTS dan BESS',
  overview: [
    'Unit ini adalah PLTS berkapasitas 5 MWp yang dilengkapi sistem penyimpanan energi baterai (BESS). Larik surya PV-801 menghasilkan listrik arus searah yang dikumpulkan di kotak combiner CB-801, lalu diubah menjadi arus bolak-balik oleh inverter INV-801 dan dinaikkan tegangannya oleh trafo TR-801 ke jaringan 20 kV.',
    'Pada siang hari, sebagian energi disimpan di kontainer baterai litium BT-801 dan BT-802 berkapasitas total sekitar 8 MWh melalui power conversion system PCS-802, lalu dilepas pada malam hari. Setiap kontainer berisi ribuan sel yang tersusun dalam modul dan rak.',
    'Sel litium bekerja aman hanya pada rentang tegangan dan suhu tertentu. Unit HVAC HV-801 menjaga suhu kontainer sekitar 24 °C. Bahaya utama BESS adalah thermal runaway, yaitu pemanasan sel yang tak terkendali, yang melepaskan gas mudah terbakar dan dapat berakhir dengan ledakan atau kebakaran yang sulit dipadamkan.',
  ],
  production: { label: 'Energi PV tersalurkan', unit: 'MWh', var: 'PPV', k: 1 / 60, dec: 2 },
  fluidNames: { power: 'Kabel daya DC dan AC', air: 'Udara pendingin kontainer' },
  zones: [
    { x: 95, y: 290, w: 400, h: 250, label: 'Area BESS', labelPos: 'bottom' },
  ],
  equipment: [
    { id: 'PV-801', type: 'solar', x: 40, y: 60, w: 240, h: 70, n: 4, name: 'Larik Surya PV-801 5 MWp',
      desc: 'Ribuan modul surya yang dirangkai seri dan paralel menghasilkan arus searah hingga sekitar 1.500 V DC. Kabel DC dan konektor terpapar panas, hujan, dan hewan pengerat.', vars: ['RISO'] },
    { id: 'CB-801', type: 'panel', x: 310, y: 72, w: 50, h: 46, name: 'Kotak Combiner DC CB-801',
      desc: 'Menggabungkan arus dari banyak string modul surya dan dilengkapi sekering string. Sambungan yang longgar menjadi titik panas dan busur listrik.' },
    { id: 'INV-801', type: 'panel', sub: 'DC/AC', x: 410, y: 64, w: 80, h: 60, name: 'Inverter PV INV-801',
      desc: 'Mengubah arus searah dari larik surya menjadi arus bolak-balik 0,8 kV dan memantau tahanan isolasi sisi DC.', vars: ['PPV'] },
    { id: 'TR-801', type: 'transformer', x: 620, y: 90, w: 90, h: 70, name: 'Trafo Step-up TR-801',
      desc: 'Menaikkan tegangan dari 0,8 kV menjadi 20 kV untuk disalurkan ke jaringan PLN.' },
    { id: 'GRID-801', type: 'sink', x: 848, y: 125, dir: 'right', name: 'Ke Jaringan PLN 20 kV',
      desc: 'Titik sambung ke jaringan distribusi 20 kV.' },
    { id: 'PCS-802', type: 'panel', sub: 'PCS', x: 520, y: 330, w: 80, h: 60, name: 'Power Conversion System PCS-802',
      desc: 'Pengubah dua arah yang mengisi baterai saat siang dan melepas energi saat malam. Arus pengisian diatur sesuai perintah BMS dan SCADA.', vars: ['PB'] },
    { id: 'BT-801', type: 'battery', x: 200, y: 320, w: 270, h: 90, name: 'Kontainer Baterai BT-801',
      desc: 'Kontainer 40 kaki berisi rak baterai litium besi fosfat (LFP) sekitar 4 MWh. Rentang aman sel sekitar 2,5 hingga 3,65 V dengan suhu operasi 15 hingga 35 °C.', vars: ['SOC', 'TC', 'VC', 'VMIN'] },
    { id: 'BT-802', type: 'battery', x: 200, y: 450, w: 270, h: 70, name: 'Kontainer Baterai BT-802',
      desc: 'Kontainer kedua dengan konfigurasi yang sama, berjarak sekitar 3 meter dari BT-801.' },
    { id: 'HV-801', type: 'cooler', x: 110, y: 330, w: 70, h: 50, fans: 1, name: 'Unit HVAC Kontainer HV-801',
      desc: 'Unit pendingin udara tunggal yang menjaga suhu kontainer BT-801 sekitar 24 °C. Saat ini tidak tersedia unit cadangan.', vars: ['TK'] },
    { id: 'CR-800', type: 'building', x: 760, y: 470, name: 'Ruang Kontrol & SCADA',
      desc: 'Operator memantau BMS, PCS, dan inverter melalui SCADA, serta mengoordinasikan tanggap darurat.' },
    { id: 'MP-800', type: 'muster', x: 920, y: 480, name: 'Titik Kumpul',
      desc: 'Area berkumpul evakuasi yang jauh dari kontainer baterai.' },
  ],
  pipes: [
    { id: 'dc1', fluid: 'power', w: 4, pts: [[280, 95], [310, 95]] },
    { id: 'dc2', fluid: 'power', w: 4, pts: [[360, 95], [410, 95]] },
    { id: 'ac1', fluid: 'power', w: 5, pts: [[490, 94], [560, 94], [560, 250], [665, 250], [665, 160]] },
    { id: 'grid', fluid: 'power', w: 5, pts: [[728, 125], [848, 125]], arrow: true },
    { id: 'pcs', fluid: 'power', w: 5, pts: [[560, 330], [560, 250]] },
    { id: 'bt1', fluid: 'power', w: 4, pts: [[470, 365], [520, 365]] },
    { id: 'bt2', fluid: 'power', w: 4, pts: [[470, 485], [590, 485], [590, 390]] },
    { id: 'air', fluid: 'air', w: 5, pts: [[180, 355], [200, 355]], arrow: true },
  ],
  labels: [
    { x: 612, y: 240, text: 'Bus AC 0,8 kV', size: 10 },
  ],
  vars: {
    SOC:  { label: 'State of Charge BESS', unit: '%', normal: 60, min: 0, max: 100, lo: 10, hi: 92, hihi: 98, node: 'BT-801', x: 300, y: 302, tau: 3, noise: 0.05, dec: 0 },
    TC:   { label: 'Suhu Sel Maksimum', unit: '°C', normal: 31, min: 15, max: 200, hi: 45, hihi: 55, node: 'BT-801', x: 400, y: 302, tau: 4, noise: 0.08, dec: 1 },
    VC:   { label: 'Tegangan Sel Maksimum', unit: 'V', normal: 3.38, min: 2, max: 5, hi: 3.55, hihi: 3.65, node: 'BT-801', x: 500, y: 302, tau: 2, noise: 0.003, dec: 2 },
    VMIN: { label: 'Tegangan Sel Minimum', unit: 'V', normal: 3.30, min: 1.5, max: 4, lo: 3.0, lolo: 2.8, node: 'BT-801', x: 540, y: 420, tau: 2, noise: 0.003, dec: 2 },
    TK:   { label: 'Suhu Udara Kontainer', unit: '°C', normal: 24, min: 10, max: 80, hi: 32, hihi: 38, node: 'HV-801', x: 145, y: 300, tau: 4, noise: 0.08, dec: 1 },
    PPV:  { label: 'Daya Keluaran PV', unit: 'MW', normal: 4.0, min: 0, max: 6, lo: 1, node: 'INV-801', x: 450, y: 166, tau: 2, noise: 0.03, dec: 2 },
    RISO: { label: 'Tahanan Isolasi DC Larik PV', unit: 'kΩ', normal: 1500, min: 0, max: 3000, lo: 500, lolo: 100, node: 'PV-801', x: 160, y: 160, tau: 2, noise: 6, dec: 0 },
    PB:   { label: 'Daya Pengisian BESS', unit: 'MW', normal: 2.0, min: -4, max: 4, node: 'PCS-802', x: 650, y: 360, tau: 1.5, noise: 0.01, dec: 2 },
  },
  trendVars: ['TC', 'TK', 'VC', 'VMIN'],
  controls: [
    { id: 'irr', label: 'Iradiasi matahari', unit: 'W/m²', min: 200, max: 1000, def: 800, step: 50,
      effects: [{ var: 'PPV', gain: 0.005 }, { var: 'TK', gain: 0.004 }] },
    { id: 'pbess', label: 'Daya pengisian BESS', unit: 'MW', min: 0, max: 3, def: 2, step: 0.25,
      effects: [{ var: 'PB', gain: 1 }, { var: 'TC', gain: 2 }, { var: 'VC', gain: 0.04 }, { var: 'TK', gain: 0.5 }] },
    { id: 'hvac', label: 'Set point HVAC kontainer', unit: '°C', min: 20, max: 28, def: 24, step: 1,
      effects: [{ var: 'TK', gain: 1 }, { var: 'TC', gain: 0.8 }] },
  ],
  quiz: [
    { q: 'Apa yang dimaksud thermal runaway pada baterai litium?', opts: ['Baterai berhenti mengisi saat penuh', 'Reaksi di dalam sel yang menghasilkan panas lebih cepat daripada yang dapat dibuang, sehingga suhu naik tak terkendali dan sel melepaskan gas mudah terbakar', 'Penurunan kapasitas baterai karena usia', 'Pendinginan berlebih oleh HVAC'], ans: 1,
      why: 'Thermal runaway dapat dipicu penyalahgunaan termal (panas), listrik (overcharge atau hubung singkat), mekanis, atau cacat internal sel. Panas dari satu sel dapat merambat ke sel lain.' },
    { q: 'Mengapa gas yang keluar dari sel saat thermal runaway berbahaya di dalam kontainer?', opts: ['Karena gas tersebut mendinginkan sel', 'Karena gas tersebut mudah terbakar dan dapat terakumulasi hingga meledak bila tersulut', 'Karena gas tersebut hanya berbau', 'Karena gas tersebut menaikkan SOC'], ans: 1,
      why: 'Off-gas sel litium mengandung hidrogen, karbon monoksida, dan hidrokarbon. Di ruang tertutup, campuran ini dapat mencapai batas mudah terbakar sehingga NFPA 855 mensyaratkan pengendalian ledakan.' },
    { q: 'Apa fungsi utama BMS (Battery Management System)?', opts: ['Mengatur iradiasi matahari', 'Memantau tegangan dan suhu setiap sel serta menghentikan pengisian atau memutus rak saat keluar batas aman', 'Mendinginkan kontainer', 'Mengubah arus searah menjadi bolak-balik'], ans: 1,
      why: 'BMS adalah barier pencegahan utama terhadap overcharge, overdischarge, dan suhu berlebih pada tingkat sel.' },
    { q: 'Mengapa busur listrik DC pada larik surya lebih sulit padam dibanding busur AC?', opts: ['Karena tegangannya lebih rendah', 'Karena arus DC tidak pernah melewati titik nol seperti arus AC sehingga busur dapat bertahan lama', 'Karena kabel DC lebih tebal', 'Karena panel surya mendinginkan busur'], ans: 1,
      why: 'Arus AC melewati nol seratus kali per detik pada 50 Hz sehingga busur cenderung padam sendiri. Busur DC tidak memiliki kesempatan itu dan mudah menyulut isolasi serta vegetasi.' },
    { q: 'Media pemadam mana yang paling dianjurkan untuk kebakaran kontainer baterai litium skala besar?', opts: ['Busa', 'Air dalam jumlah besar untuk mendinginkan modul dan mencegah penjalaran thermal runaway', 'Pasir', 'Gas pemadam bersih saja tanpa pendinginan'], ans: 1,
      why: 'Gas pemadam dapat memadamkan nyala, tetapi tidak mendinginkan sel sehingga thermal runaway dapat berlanjut dan menyala kembali. Pengujian dan NFPA 855 mengarahkan pada sistem berbasis air.' },
  ],
  events: [
    { id: 'e1', effects: [{ var: 'TK', to: 52, delay: 1, dur: 18 }, { var: 'TC', to: 95, delay: 4, dur: 22 }],
      warnings: [
        { t: 12, type: 'heat', sev: 'warn', at: 'HV-801', text: 'Unit HVAC HV-801 berhenti; udara di dalam kontainer baterai terasa sangat panas.' },
        { t: 19, type: 'smoke', sev: 'crit', at: 'BT-801', pos: [335, 330], text: 'ASAP putih keluar dari celah pintu kontainer: sel mulai melepas uap elektrolit (off-gas).' },
        { t: 27, type: 'explosion', sev: 'final', at: 'BT-801', pos: [335, 362], text: 'LEDAKAN KONTAINER BATERAI: off-gas yang mudah terbakar terakumulasi lalu tersulut, pintu kontainer terlempar dan api menyala.' },
      ],
      answer: { node: ['HV-801', 'BT-801'], param: ['T'], guide: ['high'] },
      hint: 'Panas di dalam kontainer tidak lagi dibuang. Periksa sistem pendingin udara kontainer.',
      causes: ['Kompresor HVAC HV-801 trip tanpa unit cadangan, sementara baterai terus diisi pada siang hari', 'Iradiasi matahari turun', 'Tahanan isolasi PV turun', 'Trafo step-up kelebihan beban'], causeAns: 0,
      cons: ['Suhu sel naik hingga thermal runaway, off-gas terakumulasi dan meledak, lalu kebakaran baterai', 'SOC turun tanpa dampak', 'Daya PV naik', 'Tegangan jaringan naik sedikit'], consAns: 0,
      explain: 'Suhu udara kontainer naik lebih dulu, lalu suhu sel mengikuti. Baterai litium yang terlalu panas menua cepat dan dapat memasuki thermal runaway. Proteksi yang tepat adalah HVAC cadangan dengan pergantian otomatis, alarm suhu kontainer, dan BMS yang menghentikan pengisian saat suhu sel melewati batas.' },
    { id: 'e2', effects: [{ var: 'SOC', to: 100, delay: 1, dur: 10 }, { var: 'VC', to: 4.4, delay: 2, dur: 14 }, { var: 'TC', to: 110, delay: 8, dur: 18 }],
      warnings: [
        { t: 12, type: 'heat', sev: 'warn', at: 'BT-801', pos: [300, 365], text: 'Rak baterai nomor 3 memanas; kipas rak berputar maksimum.' },
        { t: 18, type: 'smoke', sev: 'crit', at: 'BT-801', pos: [300, 330], text: 'Asap putih berbau manis elektrolit keluar dari ventilasi kontainer.' },
        { t: 26, type: 'fire', sev: 'final', at: 'BT-801', pos: [335, 352], text: 'KEBAKARAN BATERAI: thermal runaway merambat dari modul ke modul di dalam kontainer.' },
      ],
      answer: { node: ['BT-801', 'PCS-802'], param: ['E', 'L'], guide: ['high'] },
      hint: 'Pengisian tidak berhenti walaupun baterai sudah penuh.',
      causes: ['BMS gagal menghentikan pengisian sehingga PCS terus mengisi baterai yang sudah penuh (overcharge)', 'Iradiasi matahari turun', 'HVAC terlalu dingin', 'Tahanan isolasi PV turun'], causeAns: 0,
      cons: ['Tegangan sel melampaui batas, sel memanas dan memasuki thermal runaway yang merambat menjadi kebakaran kontainer', 'Daya PV turun', 'Suhu kontainer turun', 'Tegangan jaringan turun'], consAns: 0,
      explain: 'SOC mencapai 100 persen, tegangan sel terus naik melewati batas pengisian, lalu suhu sel naik. Overcharge adalah penyalahgunaan listrik yang merusak struktur elektroda dan memicu thermal runaway. Barier utamanya adalah BMS dengan proteksi tegangan dan suhu yang membuka kontaktor rak secara independen dari sistem kendali PCS. Dalam HAZOP, deviasi ini dibaca sebagai tegangan atau tingkat pengisian lebih tinggi.' },
    { id: 'e3', effects: [{ var: 'RISO', to: 10, delay: 1, dur: 12 }, { var: 'PPV', to: 2.6, delay: 5, dur: 5 }],
      warnings: [
        { t: 8, type: 'arc', sev: 'warn', at: 'CB-801', pos: [335, 92], text: 'Inverter berulang kali memberi peringatan gangguan isolasi; tercium bau plastik terbakar di kotak combiner CB-801.' },
        { t: 14, type: 'arc', sev: 'crit', at: 'CB-801', pos: [335, 88], text: 'BUSUR LISTRIK DC di kotak combiner disertai desis dan kilatan; kabel mulai meleleh.' },
        { t: 21, type: 'fire', sev: 'final', at: 'PV-801', pos: [250, 118], text: 'KEBAKARAN di kotak combiner dan kabel DC, merambat ke rumput kering di bawah larik surya.' },
      ],
      answer: { node: ['CB-801', 'PV-801'], param: ['E'], guide: ['low', 'other'] },
      hint: 'Tahanan isolasi kabel DC turun drastis. Arus mencari jalan lain melalui isolasi yang rusak.',
      causes: ['Isolasi kabel DC rusak karena digigit hewan, terkelupas, atau konektor longgar sehingga terjadi gangguan isolasi dan busur listrik', 'HVAC kontainer mati', 'SOC terlalu tinggi', 'Trafo step-up kepanasan'], causeAns: 0,
      cons: ['Busur listrik DC yang sulit padam menyulut kotak combiner, kabel, dan vegetasi di bawah larik', 'Suhu sel baterai turun', 'SOC naik', 'Tegangan jaringan naik'], consAns: 0,
      explain: 'Tahanan isolasi turun dari ribuan menjadi puluhan kilo-ohm, lalu daya PV turun. Busur listrik DC tidak memiliki titik nol arus seperti AC sehingga lebih sulit padam dan mudah menyulut material di sekitarnya. Proteksi yang tepat adalah deteksi busur listrik yang memutus sirkuit, pentanahan dan bonding rangka, serta inspeksi kabel berkala.' },
    { id: 'e4', effects: [{ var: 'VMIN', to: 2.0, delay: 1, dur: 10 }, { var: 'TC', to: 120, delay: 4, dur: 20 }],
      warnings: [
        { t: 12, type: 'heat', sev: 'warn', at: 'BT-801', pos: [380, 365], text: 'Satu modul di rak 5 memanas lokal, sementara modul lain masih normal.' },
        { t: 19, type: 'smoke', sev: 'crit', at: 'BT-801', pos: [372, 330], text: 'Off-gas putih keluar dari modul yang memanas dan mulai mengisi kontainer.' },
        { t: 27, type: 'fire', sev: 'final', at: 'BT-801', pos: [360, 360], big: true, text: 'KEBAKARAN BATERAI merambat ke seluruh rak dan mengancam kontainer BT-802 di sebelahnya.' },
      ],
      answer: { node: ['BT-801'], param: ['E', 'T'], guide: ['low', 'high'] },
      hint: 'Tegangan satu sel turun tajam tanpa perubahan pengisian. Ada hubung singkat di dalam sel itu sendiri.', hintVar: 'VMIN',
      causes: ['Cacat internal sel, misalnya kontaminasi atau dendrit litium, menyebabkan hubung singkat di dalam sel', 'Iradiasi matahari naik', 'Kabel DC PV rusak', 'Trafo step-up kelebihan beban'], causeAns: 0,
      cons: ['Sel memanas dan memasuki thermal runaway yang merambat ke modul lain dan kontainer di sebelahnya', 'Daya PV naik', 'Suhu kontainer turun', 'SOC naik tanpa dampak'], consAns: 0,
      explain: 'Tegangan sel minimum anjlok lalu suhu sel naik tanpa pemicu dari luar. Hubung singkat internal sulit dicegah saat operasi, sehingga deteksi dini dan mitigasi menjadi penting: deteksi off-gas, ventilasi exhaust, venting ledakan, pemadam berbasis air, dan dinding tahan api antarkontainer. Insiden BESS McMicken di Arizona tahun 2019 berawal dari kegagalan internal sel dan berakhir dengan ledakan gas yang terakumulasi di dalam kontainer.' },
  ],
  hotspots: [
    /* Tahap 3: pencegahan */
    { id: 'h31', stage: 3, x: 145, y: 302, label: 'Unit HVAC (cadangan otomatis)', accept: ['HVR'],
      why: 'Unit HVAC cadangan dengan pergantian otomatis menghilangkan titik kegagalan tunggal pada pendinginan kontainer.' },
    { id: 'h32', stage: 3, x: 222, y: 336, label: 'Dalam kontainer (sensor suhu udara)', accept: ['TT'],
      why: 'Alarm suhu udara kontainer memberi peringatan dini kegagalan pendinginan sebelum suhu sel naik.' },
    { id: 'h33', stage: 3, x: 335, y: 365, label: 'Rak baterai (BMS dan kontaktor)', accept: ['BMSB'],
      why: 'BMS dengan proteksi tegangan dan suhu menghentikan pengisian dan membuka kontaktor rak saat sel keluar batas aman.' },
    { id: 'h34', stage: 3, x: 340, y: 160, label: 'Kotak combiner DC (proteksi busur listrik)', accept: ['ARC'],
      why: 'Deteksi busur listrik DC memutus string dalam hitungan milidetik sebelum busur menyulut kabel dan vegetasi.' },
    { id: 'h35', stage: 3, x: 495, y: 365, label: 'Kabel DC rak ke PCS (proteksi arus lebih)', accept: ['OCR'],
      why: 'Sekering atau pemutus DC memutus hubung singkat eksternal pada sisi baterai sebelum kabel dan busbar terbakar.' },
    { id: 'h36', stage: 3, x: 60, y: 150, label: 'Rangka larik surya (pentanahan dan bonding)', accept: ['GRND'],
      why: 'Pentanahan dan bonding rangka mencegah tegangan sentuh dan mengarahkan arus gangguan, sehingga gangguan isolasi terdeteksi dan diputus.' },
    { id: 'h37', stage: 3, x: 772, y: 125, label: 'Trafo step-up TR-801 (sisi 20 kV)', accept: [],
      why: 'Proteksi trafo dan jaringan penting, tetapi tidak memutus ancaman thermal runaway dan busur DC yang teridentifikasi.' },
    { id: 'h38', stage: 3, x: 200, y: 42, label: 'Permukaan panel surya', accept: [],
      why: 'Perangkat di permukaan panel tidak menangani ancaman yang teridentifikasi. Kebersihan panel adalah urusan kinerja, bukan barier keselamatan proses.' },
    /* Tahap 4: mitigasi */
    { id: 'h41', stage: 4, x: 260, y: 322, label: 'Plafon kontainer (detektor off-gas)', accept: ['OGD'],
      why: 'Detektor off-gas mendeteksi gas sel sebelum asap terlihat, lalu memutus rak dan menyalakan ventilasi exhaust.' },
    { id: 'h42', stage: 4, x: 415, y: 322, label: 'Atap kontainer (panel venting ledakan)', accept: ['DVENT'],
      why: 'Panel venting mengarahkan bola api ke atas bila gas tersulut, sehingga pintu dan dinding kontainer tidak terlempar ke arah petugas (NFPA 68).' },
    { id: 'h43', stage: 4, x: 484, y: 334, label: 'Ujung kontainer (ventilasi exhaust darurat)', accept: ['EXV'],
      why: 'Ventilasi exhaust menjaga konsentrasi off-gas di bawah batas mudah terbakar (NFPA 69).' },
    { id: 'h44', stage: 4, x: 335, y: 368, label: 'Dalam kontainer (sistem pemadam)', accept: ['SPK'],
      why: 'Sistem berbasis air mendinginkan modul dan membatasi penjalaran thermal runaway. Pemadam gas bersih tidak mendinginkan sel sehingga api dapat menyala kembali.' },
    { id: 'h45', stage: 4, x: 222, y: 392, label: 'Dalam kontainer (detektor asap dan panas)', accept: ['SD'],
      why: 'Detektor asap dan panas memberi alarm kebakaran dan memicu sistem pemadam serta pemberitahuan ke regu pemadam.' },
    { id: 'h46', stage: 4, x: 240, y: 432, label: 'Antara BT-801 dan BT-802 (dinding tahan api)', accept: ['FWALL'],
      why: 'Dinding tahan api atau jarak pemisah mencegah kebakaran satu kontainer merambat ke kontainer lain (NFPA 855).' },
    { id: 'h47', stage: 4, x: 812, y: 440, label: 'Ruang kontrol (pemutus darurat BESS)', accept: ['ESD'],
      why: 'Pemutus darurat mengisolasi PCS dan rak dari sisi AC dan DC secara serentak dari lokasi aman.' },
    { id: 'h48', stage: 4, x: 968, y: 480, label: 'Titik kumpul dan alarm umum', accept: ['ALARM'],
      why: 'Petugas dan pemadam harus menjauh dari kontainer yang mengalami thermal runaway karena risiko ledakan gas.' },
    { id: 'h49', stage: 4, x: 150, y: 42, label: 'Larik surya (sprinkler)', accept: [],
      why: 'Larik surya di lapangan terbuka tidak memerlukan sprinkler. Risiko kebakaran rumput dikendalikan dengan pengelolaan vegetasi dan pemutusan busur listrik.' },
  ],
  inspect: [
    { id: 'BT-801', itpm: 'ELEC', why: 'Termografi rak, pemeriksaan keseimbangan tegangan sel, dan uji kapasitas mendeteksi sel menyimpang sebelum memicu thermal runaway.' },
    { id: 'HV-801', itpm: 'ROT', why: 'Pemeliharaan prediktif kompresor dan kipas HVAC mengurangi kegagalan pendinginan pada siang hari saat beban panas tertinggi.' },
    { id: 'INV-801', itpm: 'ELEC', why: 'Termografi dan pemeriksaan pemantauan isolasi pada inverter dan sisi DC mendeteksi sambungan panas dan isolasi yang menurun.' },
  ],
  budget: { 3: 26, 4: 30 },
  bowtie: {
    top: 'Thermal runaway baterai atau busur listrik DC pada PLTS dan BESS',
    threats: ['HVAC gagal, kontainer kepanasan', 'Overcharge karena BMS gagal', 'Gangguan isolasi kabel DC PV', 'Hubung singkat internal sel'],
    cons: ['Ledakan off-gas di kontainer', 'Kebakaran baterai merambat antarmodul', 'Kebakaran combiner dan vegetasi', 'Kebakaran merambat ke kontainer lain'],
  },
};
SCENARIOS.push(SCN_BESS);
