/* Skenario sektor Ketenagalistrikan: dimuat setelah js/data.js dan menambahkan diri ke SCENARIOS. */
/* =====================================================================
   KETENAGALISTRIKAN: Trafo Daya Gardu Induk 150/20 kV
   ===================================================================== */
const SCN_TRAFO = {
  id: 'trafo',
  title: 'Trafo Daya Gardu Induk 150/20 kV',
  subtitle: 'Trafo terendam minyak, pendingin ONAF, konservator, dan kubikel 20 kV',
  level: 'Menengah',
  sector: 'listrik',
  area: 'Transmisi dan Distribusi (Gardu Induk)',
  color: '#1f6fa8',
  kits: ['trafo'],
  op: 'Operasi Gardu Induk',
  overview: [
    'Gardu induk ini menurunkan tegangan transmisi 150 kV menjadi 20 kV untuk penyulang distribusi. Daya masuk melalui saluran transmisi dan pemutus tenaga (PMT) 150 kV ke dua trafo daya, yaitu TR-601 berkapasitas 60 MVA yang sedang dibebani dan TR-602 di sebelahnya.',
    'TR-601 adalah trafo terendam minyak dengan sekitar 30.000 liter minyak isolasi. Minyak mengisolasi belitan sekaligus membawa panas ke radiator yang ditiup kipas FN-601 (pendinginan ONAF). Konservator di atas tangki menampung pemuaian minyak. Suhu minyak, suhu belitan, level konservator, dan gas terlarut dipantau secara daring melalui SCADA.',
    'Sisi 20 kV trafo terhubung ke kubikel switchgear SWG-602 di dalam gedung, lalu ke penyulang pelanggan. Bahaya utama gardu induk adalah busur listrik dan kebakaran minyak trafo. Satu kebakaran trafo dapat memadamkan listrik ribuan pelanggan dan merambat ke peralatan di sekitarnya.',
  ],
  production: { label: 'Energi tersalurkan', unit: 'MWh', var: 'LD6', k: 0.009, dec: 1 },
  fluidNames: { power: 'Konduktor dan kabel daya' },
  zones: [
    { x: 300, y: 418, w: 270, h: 122, label: 'Gedung Switchgear 20 kV', labelPos: 'bottom' },
  ],
  /* area untuk titik pemasangan yang berada di dalam ruang, bukan pada peralatan atau pipa (tidak digambar) */
  areas: [
    { id: 'gedung-swg', name: 'Gedung Switchgear 20 kV', x: 300, y: 418, w: 270, h: 122 },
  ],
  equipment: [
    { id: 'LINE-601', type: 'sink', x: 150, y: 90, dir: 'left', name: 'Saluran Transmisi 150 kV',
      desc: 'Saluran udara tegangan tinggi yang memasok gardu induk dari jaringan transmisi.' },
    { id: 'PMT-601', type: 'panel', sub: 'PMT', x: 190, y: 62, w: 50, h: 56, name: 'PMT 150 kV',
      desc: 'Pemutus tenaga berisolasi gas SF6 yang memutus arus beban dan arus gangguan di sisi 150 kV atas perintah relai proteksi.' },
    { id: 'TR-601', type: 'transformer', x: 330, y: 200, w: 140, h: 110, name: 'Trafo Daya TR-601 60 MVA',
      desc: 'Trafo 150/20 kV terendam minyak dengan pendinginan ONAN/ONAF. Pada beban normal, suhu minyak atas sekitar 62 °C dan suhu titik terpanas belitan sekitar 78 °C. Konservator berada di atas tangki dan terhubung melalui pipa.',
      vars: ['TO', 'TW', 'GAS', 'LO', 'LD6'] },
    { id: 'TR-602', type: 'transformer', x: 620, y: 200, w: 110, h: 100, name: 'Trafo Daya TR-602',
      desc: 'Trafo kedua di sebelah TR-601 yang menjadi cadangan saat pemeliharaan. Kebakaran pada TR-601 dapat merambat ke trafo ini bila tidak ada pemisah.' },
    { id: 'FN-601', type: 'fan', x: 285, y: 345, name: 'Kipas Pendingin Radiator',
      desc: 'Kelompok kipas yang meniup radiator TR-601 saat suhu naik. Suplai listrik kipas berasal dari panel bantu gardu melalui MCB.' },
    { id: 'SWG-602', type: 'panel', x: 330, y: 448, w: 210, h: 60, name: 'Kubikel Switchgear 20 kV',
      desc: 'Deretan kubikel berisi PMT, relai, dan busbar 20 kV di dalam gedung. Busur listrik di dalam kubikel dapat menimbulkan ledakan busur (arc flash) yang sangat berbahaya bagi operator.', vars: ['IF', 'TSW'] },
    { id: 'FDR-603', type: 'sink', x: 848, y: 478, dir: 'right', name: 'Penyulang 20 kV ke Pelanggan',
      desc: 'Penyulang distribusi yang memasok kawasan permukiman dan industri.' },
    { id: 'CR-600', type: 'building', x: 120, y: 480, name: 'Gedung Kendali',
      desc: 'Berisi Ruang Kendali operator, panel proteksi, dan sistem SCADA gardu induk.' },
    { id: 'MP-600', type: 'muster', x: 900, y: 320, name: 'Titik Kumpul',
      desc: 'Area berkumpul saat evakuasi di luar switchyard.' },
  ],
  pipes: [
    { id: 'pw1', fluid: 'power', w: 5, pts: [[150, 90], [190, 90]], arrow: true },
    { id: 'bus', fluid: 'power', w: 5, pts: [[240, 90], [652, 90]] },
    { id: 'pw3', fluid: 'power', w: 4, pts: [[371, 90], [371, 166]] },
    { id: 'pw4', fluid: 'power', w: 4, pts: [[652, 90], [652, 166]] },
    { id: 'lv1', fluid: 'power', w: 5, pts: [[400, 310], [400, 448]] },
    { id: 'lv2', fluid: 'power', w: 5, pts: [[675, 300], [675, 400], [500, 400], [500, 448]] },
    { id: 'fdr', fluid: 'power', w: 5, pts: [[540, 478], [848, 478]], arrow: true },
  ],
  labels: [
    { x: 445, y: 80, text: 'Busbar 150 kV', size: 10 },
  ],
  vars: {
    TO:  { label: 'Suhu Minyak Atas TR-601', unit: '°C', normal: 62, min: 20, max: 140, hi: 85, hihi: 95, node: 'TR-601', x: 545, y: 212, tau: 6, noise: 0.15, dec: 1 },
    TW:  { label: 'Suhu Titik Terpanas Belitan', unit: '°C', normal: 78, min: 20, max: 180, hi: 105, hihi: 120, node: 'TR-601', x: 545, y: 240, tau: 5, noise: 0.2, dec: 1 },
    GAS: { label: 'Gas Terlarut dalam Minyak (TDCG)', unit: 'ppm', normal: 350, min: 0, max: 6000, hi: 720, hihi: 1920, node: 'TR-601', x: 545, y: 268, tau: 3, noise: 4, dec: 0 },
    LO:  { label: 'Level Minyak Konservator', unit: '%', normal: 60, min: 0, max: 100, lo: 30, lolo: 15, node: 'TR-601', x: 446, y: 128, tau: 4, noise: 0.2, dec: 0 },
    LD6: { label: 'Beban TR-601', unit: '%', normal: 65, min: 0, max: 140, hi: 105, hihi: 120, node: 'TR-601', x: 465, y: 362, tau: 2, noise: 0.3, dec: 0 },
    IF:  { label: 'Arus Penyulang 20 kV', unit: 'A', normal: 1200, min: 0, max: 12000, hi: 1800, hihi: 2400, node: 'SWG-602', x: 700, y: 455, tau: 0.8, noise: 6, dec: 0 },
    TSW: { label: 'Suhu Ruang Switchgear', unit: '°C', normal: 30, min: 15, max: 90, hi: 40, hihi: 50, node: 'SWG-602', x: 620, y: 512, tau: 4, noise: 0.1, dec: 1 },
  },
  trendVars: ['TW', 'GAS', 'LO', 'IF'],
  controls: [
    { id: 'load', label: 'Beban gardu', unit: '%', min: 30, max: 100, def: 65, step: 5,
      effects: [{ var: 'LD6', gain: 1 }, { var: 'TO', gain: 0.4 }, { var: 'TW', gain: 0.7 }, { var: 'IF', gain: 18 }] },
    { id: 'amb', label: 'Suhu lingkungan', unit: '°C', min: 24, max: 40, def: 32, step: 1,
      effects: [{ var: 'TO', gain: 1 }, { var: 'TW', gain: 1 }, { var: 'TSW', gain: 0.5 }] },
    { id: 'fan', label: 'Jumlah kipas pendingin aktif', unit: 'unit', min: 0, max: 8, def: 4, step: 1,
      effects: [{ var: 'TO', gain: -1.5 }, { var: 'TW', gain: -2 }] },
  ],
  quiz: [
    { q: 'Apa dua fungsi utama minyak di dalam trafo daya?', opts: ['Isolasi listrik dan media pendingin yang membawa panas belitan ke radiator', 'Isolasi listrik dan pelumas bagi mekanisme tap changer serta bantalan kipas pendingin', 'Media pendingin dan peredam getaran inti agar dengung trafo berkurang', 'Pencegah korosi tangki dan penyerap kelembapan dari udara luar yang masuk ke konservator'], ans: 0,
      why: 'Minyak mineral mengisi celah di antara belitan sebagai isolasi dan bersirkulasi membawa panas ke radiator. Kehilangan minyak berarti kehilangan isolasi sekaligus pendinginan.' },
    { q: 'Mengapa suhu titik terpanas belitan sangat penting dipantau?', opts: ['Laju penuaan isolasi kertas naik sangat cepat saat suhu titik terpanas melampaui batas', 'Suhu titik terpanas menentukan tegangan keluaran trafo sehingga harus dijaga stabil', 'Suhu minyak bagian atas sudah cukup mewakili, sedangkan titik terpanas hanya dipakai untuk mengatur kipas', 'Suhu titik terpanas yang tinggi menaikkan efisiensi trafo tetapi mempercepat penguapan minyak'], ans: 0,
      why: 'Menurut IEC 60076-7, laju penuaan isolasi kertas kira-kira berlipat dua setiap kenaikan sekitar 6 °C di atas suhu acuan. Panas berlebih yang dibiarkan memperpendek umur trafo dan memicu kegagalan isolasi.' },
    { q: 'Apa yang dideteksi relai Buchholz?', opts: ['Gas hasil penguraian minyak, aliran minyak mendadak, atau minyak yang hilang pada pipa ke konservator', 'Selisih arus sisi primer dan sekunder yang menandakan adanya gangguan di dalam belitan trafo', 'Suhu minyak bagian atas dan suhu belitan untuk menghidupkan kelompok kipas pendingin', 'Kenaikan tekanan mendadak di dalam tangki untuk membuka katup pelepas tekanan'], ans: 0,
      why: 'Relai Buchholz adalah proteksi mekanis khas trafo terendam minyak dengan konservator. Kontak pertama memberi alarm, kontak kedua men-trip trafo.' },
    { q: 'Mengapa hubung singkat harus diputus dalam hitungan milidetik?', opts: ['Energi busur listrik bertambah seiring lamanya gangguan sehingga ledakan dan kebakaran makin besar', 'Agar tegangan di penyulang lain tidak naik melebihi batas isolasi peralatan selama gangguan berlangsung', 'Karena pemutus hanya mampu memutus arus gangguan pada detik pertama', 'Agar relai tidak salah membaca arus beban normal sebagai arus gangguan pada siklus berikutnya'], ans: 0,
      why: 'Energi insiden arc flash sebanding dengan arus gangguan dan waktu pemutusan. Koordinasi relai, breaker failure, dan proteksi busur listrik membatasi energi tersebut.' },
    { q: 'Mengapa trafo yang berdekatan perlu dipisahkan dinding tahan api atau jarak aman?', opts: ['Agar kebakaran minyak pada satu trafo tidak merambat ke trafo lain sehingga pemadaman tidak meluas', 'Agar medan magnet antartrafo tidak saling mengganggu dan menaikkan rugi daya', 'Agar aliran udara pendingin radiator tidak terhalang oleh trafo di sebelahnya saat beban puncak', 'Agar dengung trafo tidak saling memperkuat dan melampaui batas kebisingan di permukiman sekitar'], ans: 0,
      why: 'NFPA 850 merekomendasikan dinding tahan api atau jarak pemisah untuk trafo terendam minyak, ditambah bak penampung minyak agar genangan api tidak meluas.' },
  ],
  events: [
    { id: 'e1', threat: 0, effects: [{ var: 'TW', to: 150, delay: 1, dur: 16 }, { var: 'TO', to: 112, delay: 2, dur: 16 }],
      warnings: [
        { t: 14, type: 'heat', sev: 'warn', at: 'TR-601', text: 'Radiator TR-601 sangat panas dan kipas pendingin FN-601 tidak berputar.' },
        { t: 20, type: 'smoke', sev: 'crit', at: 'TR-601', pos: [400, 178], text: 'Tercium bau minyak trafo hangus. Asap tipis keluar dari pernapasan silika gel konservator.' },
        { t: 27, type: 'fire', sev: 'final', at: 'TR-601', pos: [400, 236], text: 'Terjadi kebakaran trafo. Isolasi belitan rusak, busur listrik internal terjadi, dan minyak trafo terbakar.' },
      ],
      answer: { node: ['TR-601', 'FN-601'], param: ['T'], guide: ['high'] },
      hint: 'Beban trafo tidak berubah, tetapi panas tidak terbuang. Periksa sistem pendingin radiator.',
      causes: ['Kipas pendingin FN-601 berhenti karena MCB suplai kipas trip, sementara beban tetap tinggi', 'Tap changer berpindah posisi', 'Penyulang 20 kV dilepas', 'Suhu lingkungan turun'], causeAns: 0,
      cons: ['Isolasi kertas belitan menua cepat dan rusak, lalu terjadi busur listrik internal dan kebakaran minyak trafo', 'Beban penyulang naik', 'Level minyak konservator naik tanpa dampak', 'Tegangan 20 kV naik sedikit'], consAns: 0,
      explain: 'Suhu titik terpanas belitan naik terus, sementara beban tetap. Artinya, yang berubah adalah pendinginan, bukan beban. Menurut IEC 60076-7, laju penuaan isolasi kertas kira-kira berlipat dua setiap kenaikan sekitar 6 °C di atas suhu acuan. Proteksi yang tepat adalah indikator suhu belitan dengan alarm dan trip, didukung pemeliharaan kipas dan termografi.' },
    { id: 'e2', threat: 1, effects: [{ var: 'GAS', to: 4800, delay: 1, dur: 14 }],
      warnings: [
        { t: 8, type: 'vibration', sev: 'warn', at: 'TR-601', text: 'Dengung TR-601 berubah dan terdengar letupan kecil dari dalam tangki.' },
        { t: 14, type: 'arc', sev: 'crit', at: 'TR-601', pos: [400, 178], text: 'Terjadi busur listrik di dalam tangki. Minyak menyembur dari pernapasan konservator dan celah tutup tangki.' },
        { t: 21, type: 'explosion', sev: 'final', at: 'TR-601', pos: [400, 240], text: 'Tangki TR-601 meledak akibat busur listrik internal. Minyak yang terbakar menyembur ke sekeliling switchyard.' },
      ],
      answer: { node: ['TR-601'], param: ['C', 'E'], guide: ['aswell', 'high', 'other'] },
      hint: 'Gas terlarut dalam minyak naik cepat. Minyak sedang terurai oleh panas berlebih atau busur listrik di dalam tangki.',
      causes: ['Kegagalan isolasi di dalam trafo menimbulkan busur listrik yang menguraikan minyak menjadi gas', 'Beban penyulang turun', 'Suhu lingkungan naik', 'Kipas pendingin berputar terlalu cepat'], causeAns: 0,
      cons: ['Tekanan gas di dalam tangki naik mendadak, tangki robek atau meledak, dan minyak terbakar', 'Level konservator turun tanpa dampak', 'Arus penyulang naik sedikit', 'Trafo menjadi lebih dingin'], consAns: 0,
      explain: 'Kenaikan cepat gas terlarut, terutama asetilena dan hidrogen, menandakan busur listrik atau panas berlebih di dalam minyak (IEEE C57.104). Gangguan internal harus diputus dalam puluhan milidetik oleh relai diferensial dan relai Buchholz, dengan pressure relief device sebagai pelepas tekanan.' },
    { id: 'e3', threat: 2, effects: [{ var: 'IF', to: 9500, delay: 1, dur: 2 }, { var: 'TSW', to: 72, delay: 3, dur: 10 }],
      warnings: [
        { t: 3, type: 'vibration', sev: 'warn', at: 'SWG-602', text: 'Dentuman keras terdengar dari gedung switchgear dan lampu gardu berkedip.' },
        { t: 7, type: 'arc', sev: 'crit', at: 'SWG-602', pos: [435, 462], text: 'Busur listrik di kubikel penyulang 20 kV disertai kilatan cahaya. PMT penyulang tidak membuka.' },
        { t: 11, type: 'smoke', sev: 'crit', at: 'SWG-602', pos: [470, 440], text: 'Asap tebal memenuhi gedung switchgear, sementara arus gangguan tetap mengalir.' },
        { t: 16, type: 'fire', sev: 'final', at: 'SWG-602', pos: [435, 462], text: 'Terjadi kebakaran gedung switchgear. Busur listrik berkelanjutan membakar kubikel 20 kV dan kabel.' },
      ],
      answer: { node: ['SWG-602'], param: ['E', 'F'], guide: ['high'] },
      hint: 'Arus penyulang melonjak berlipat-lipat dan tidak kembali normal. Gangguan hubung singkat tidak diputus.',
      causes: ['Hubung singkat pada penyulang 20 kV tidak diputus karena relai atau PMT penyulang gagal bekerja', 'Kipas pendingin trafo mati', 'Minyak konservator berkurang', 'Suhu lingkungan naik'], causeAns: 0,
      cons: ['Busur listrik berkelanjutan di kubikel 20 kV menyebabkan ledakan busur, kebakaran gedung switchgear, dan pemadaman luas', 'Trafo menjadi lebih dingin', 'Gas terlarut turun', 'Level minyak naik'], consAns: 0,
      explain: 'Arus penyulang melonjak lebih dari tujuh kali normal dan bertahan, tanda hubung singkat yang tidak diputus. Koordinasi proteksi mensyaratkan relai arus lebih dan breaker failure yang memutus gangguan secara bertingkat, serta proteksi busur listrik yang memutus dalam hitungan milidetik untuk membatasi energi arc flash. Dalam HAZOP listrik, deviasi ini dibaca sebagai arus lebih tinggi.' },
    { id: 'e4', threat: 3, effects: [{ var: 'LO', to: 4, delay: 1, dur: 14 }],
      warnings: [
        { t: 13, type: 'spill', sev: 'warn', at: 'TR-601', pos: [400, 330], text: 'Minyak trafo merembes di dasar radiator. Genangan minyak terbentuk di bawah TR-601.' },
        { t: 19, type: 'arc', sev: 'crit', at: 'TR-601', pos: [400, 178], text: 'Terdengar bunyi letupan dari dalam TR-601. Level minyak di konservator tidak terlihat lagi.' },
        { t: 26, type: 'fire', sev: 'final', at: 'TR-601', pos: [400, 240], text: 'Terjadi kebakaran trafo. Belitan yang tidak lagi terendam minyak mengalami flashover dan minyak yang tumpah ikut terbakar.' },
      ],
      answer: { node: ['TR-601'], param: ['L'], guide: ['low'] },
      hint: 'Level minyak di konservator turun terus. Minyak keluar dari tangki melalui titik bocor.',
      causes: ['Gasket radiator atau katup drain bocor sehingga minyak trafo keluar sedikit demi sedikit', 'Beban trafo turun', 'Kipas pendingin bekerja terus', 'Arus penyulang naik'], causeAns: 0,
      cons: ['Bagian aktif trafo tidak lagi terendam minyak, isolasi gagal, lalu terjadi flashover dan kebakaran minyak', 'Suhu minyak turun', 'Gas terlarut turun', 'Tegangan naik tanpa dampak'], consAns: 0,
      explain: 'Level minyak konservator turun perlahan tanpa perubahan beban atau suhu. Minyak trafo berfungsi sebagai isolasi sekaligus pendingin. Relai Buchholz mendeteksi minyak yang hilang dan men-trip trafo, sementara alarm level konservator memberi peringatan lebih awal kepada operator.' },
    { id: 'e5', start: 12,
      hf: { type: 'lapse', team: 'mtc', threat: 0, title: 'Fuse kipas dicabut dan lupa dipasang kembali', factor: 'Fuse kipas tidak dipasang kembali setelah pekerjaan',
        roles: { wawan: 'Teknisi Listrik Gedung Kantor', raka: 'Operator Gardu Induk' },
        lesson: 'Pemicu langsungnya adalah lapse: Wawan berniat memasang kembali fuse, tetapi lupa karena terburu-buru pindah tugas. Konteksnya juga bermasalah karena pekerjaan di gardu dilakukan tanpa izin kerja oleh personel yang bukan tenaga teknik gardu. UU No. 30 Tahun 2009 Pasal 44 ayat 6 mewajibkan setiap tenaga teknik ketenagalistrikan memiliki sertifikat kompetensi. Lapse dicegah dengan daftar periksa pemulihan, penandaan pada komponen yang dilepas, dan uji fungsi sebelum serah terima.',
        controls: ['Pekerjaan di gardu hanya oleh tenaga teknik bersertifikat dengan izin kerja', 'Daftar periksa pemulihan dan penandaan pada komponen yang dilepas', 'Uji fungsi sistem pendingin sebelum serah terima pekerjaan'] },
      chat: [
        { t: 1, who: 'wawan', at: 'TR-601', text: 'Raka, saya akan merapikan kabel di kotak kontrol kipas TR-601 sekaligus membersihkannya.' },
        { t: 4, who: 'raka', at: 'CR-600', mood: 'ragu', text: 'Itu di dalam area gardu. Apakah sudah ada izin kerja dari supervisor gardu?' },
        { t: 7, who: 'wawan', at: 'TR-601', mood: 'santai', text: 'Hanya kabel kontrol 220 volt, bukan tegangan tinggi. Fuse kipas saya cabut dahulu agar aman, nanti saya pasang kembali.' },
        { t: 10, who: 'wawan', at: 'TR-601', mood: 'santai', text: 'Selesai, sudah rapi. Saya langsung ke gudang untuk mengambil pengikat kabel.' },
        { t: 13, who: 'raka', at: 'CR-600', text: 'Baik, terima kasih. Beban siang ini mulai naik karena semua pendingin ruangan pelanggan menyala.' },
        { t: 22, who: 'raka', at: 'CR-600', mood: 'ragu', text: 'Suhu belitan TR-601 naik terus, padahal tidak ada gangguan listrik di layar proteksi.' },
        { t: 27, who: 'raka', at: 'CR-600', mood: 'panik', text: 'Wawan, apakah fuse kipas sudah dipasang kembali?' },
      ],
      effects: [{ var: 'TW', to: 150, delay: 1, dur: 16 }, { var: 'TO', to: 112, delay: 2, dur: 16 }],
      warnings: [
        { t: 14, type: 'heat', sev: 'warn', at: 'TR-601', text: 'Radiator TR-601 sangat panas dan kipas pendingin FN-601 tidak berputar.' },
        { t: 20, type: 'smoke', sev: 'crit', at: 'TR-601', pos: [400, 178], text: 'Tercium bau minyak trafo hangus. Asap tipis keluar dari pernapasan silika gel konservator.' },
        { t: 27, type: 'fire', sev: 'final', at: 'TR-601', pos: [400, 236], text: 'Terjadi kebakaran trafo. Isolasi belitan rusak, busur listrik internal terjadi, dan minyak trafo terbakar.' },
      ],
      answer: { node: ['TR-601', 'FN-601'], param: ['T'], guide: ['high'] },
      hint: 'Suhu belitan naik tanpa gangguan listrik, seolah pendinginan berhenti. Baca kembali percakapan tentang pekerjaan di kotak kontrol kipas.',
      causes: ['Fuse rangkaian kipas pendingin dicabut saat pekerjaan tanpa izin dan lupa dipasang kembali', 'Motor kipas FN-601 terbakar karena bantalan macet', 'Radiator tersumbat debu sehingga pendinginan turun perlahan', 'Relai suhu belitan salah setel sehingga kipas tidak diperintah menyala'], causeAns: 0,
      cons: ['Belitan kepanasan sehingga isolasi kertas rusak, terjadi gangguan internal dan kebakaran minyak trafo', 'Trafo berhenti aman tanpa kerusakan karena proteksi suhu selalu bekerja tepat waktu', 'Tegangan penyulang naik karena trafo kepanasan', 'Minyak trafo mengental sehingga sirkulasi terhenti'], consAns: 0,
      explain: 'Suhu belitan dan minyak naik bersamaan seiring kenaikan beban, padahal tidak ada gangguan listrik. Tanpa kipas, kapasitas pendinginan ONAF turun ke tingkat ONAN sehingga trafo kelebihan beban termal. Pekerjaan pada rangkaian kontrol pendingin harus diakhiri dengan pemulihan dan uji fungsi.' },
    { id: 'e6', threat: 1, effects: [{ var: 'GAS', to: 2500, delay: 2, dur: 20 }],
      warnings: [
        { t: 11, type: 'leak', sev: 'warn', at: 'TR-601', pos: [400, 178], text: 'Silika gel pada pernapasan konservator TR-601 sudah berubah warna seluruhnya. Seal tutup konservator retak dan air hujan merembes masuk.' },
        { t: 18, type: 'vibration', sev: 'crit', at: 'TR-601', text: 'Desis dan letupan halus terdengar dari dalam tangki TR-601, tanda peluahan sebagian pada isolasi yang basah.' },
        { t: 26, type: 'fire', sev: 'final', at: 'TR-601', pos: [400, 236], text: 'Isolasi yang basah tembus. Busur listrik internal merobek tangki TR-601 dan minyak yang menyembur terbakar.' },
      ],
      answer: { node: ['TR-601'], param: ['C'], guide: ['aswell', 'high'] },
      hint: 'Gas terlarut naik perlahan tanpa perubahan beban, suhu, maupun level minyak. Perhatikan kondisi pernapasan konservator yang dilaporkan dari lapangan.',
      causes: ['Air hujan masuk melalui seal konservator yang retak dan silika gel yang jenuh sehingga minyak dan isolasi kertas basah lalu terjadi peluahan sebagian', 'Kipas pendingin berhenti sehingga belitan kepanasan walaupun beban tetap', 'Hubung singkat di penyulang 20 kV tidak diputus oleh relai arus lebih', 'Beban trafo naik melampaui kapasitas pengenal saat beban puncak'], causeAns: 0,
      cons: ['Kekuatan dielektrik minyak turun, isolasi tembus, lalu busur listrik internal merobek tangki dan membakar minyak', 'Minyak menjadi lebih dingin karena air ikut menyerap panas belitan', 'Level minyak konservator turun tanpa dampak pada isolasi', 'Arus penyulang turun karena beban pelanggan berkurang'], consAns: 0,
      explain: 'Gas terlarut naik perlahan, terutama hidrogen, tanpa perubahan beban, suhu, maupun level minyak. Seal konservator yang retak dan silika gel yang jenuh membuat air masuk ke dalam minyak. Ini adalah deviasi komposisi dengan guideword Serta (As well as), yaitu minyak tetap ada, tetapi disertai air yang tidak dikehendaki. Air menurunkan kekuatan dielektrik minyak dan kertas sehingga terjadi peluahan sebagian yang berujung pada kegagalan isolasi. Pemeriksaan silika gel, uji kadar air dan tegangan tembus minyak, serta DGA berkala mendeteksi kondisi ini lebih awal.' },
    { id: 'e7', start: 12,
      hf: { type: 'mistake', team: 'mtc', threat: 2, title: 'Setting relai penyulang memakai data CT lama karena gambar belum direvisi', factor: 'Setting relai memakai data CT lama dari gambar',
        roles: { bayu: 'Kontraktor Penggantian CT', wawan: 'Teknisi Proteksi', hendra: 'Supervisor Gardu Induk', raka: 'Operator Gardu Induk' },
        lesson: 'Wawan memasukkan setting relai sesuai gambar satu garis yang ia yakini benar, padahal CT sudah diganti dengan arus sekunder 1 ampere dan gambarnya belum direvisi. Tindakannya sesuai niat, tetapi rencananya keliru karena informasi yang dipakai sudah usang. Kesalahan seperti ini tergolong mistake. Akar masalahnya adalah manajemen perubahan: penggantian CT tidak diikuti pembaruan gambar, dan informasi dari kontraktor tidak sampai ke teknisi proteksi. Pencegahannya adalah revisi gambar dan setting sebelum peralatan dioperasikan, verifikasi data pelat nama CT di lapangan, serta uji injeksi primer sebelum penyulang diberi tegangan.',
        controls: ['Manajemen perubahan: gambar dan setting proteksi direvisi sebelum peralatan dioperasikan', 'Verifikasi data pelat nama CT di lapangan saat memasukkan setting relai', 'Uji injeksi primer dan uji fungsi trip sebelum penyulang diberi tegangan'] },
      chat: [
        { t: 1, who: 'bayu', at: 'SWG-602', text: 'Pak Hendra, penggantian CT penyulang sudah selesai. Arus sekunder CT baru 1 ampere, tetapi gambar satu garis belum sempat kami revisi.' },
        { t: 4, who: 'hendra', at: 'CR-600', text: 'Terima kasih. Wawan, tolong masukkan setting relai penyulang karena sore ini penyulang harus dioperasikan kembali.' },
        { t: 7, who: 'wawan', at: 'CR-600', text: 'Baik, Pak. Data CT saya ambil dari gambar satu garis, sekunder 5 ampere seperti biasa.' },
        { t: 10, who: 'hendra', at: 'CR-600', mood: 'santai', text: 'Bagus. Raka, silakan masukkan penyulang sekarang.' },
        { t: 16, who: 'raka', at: 'CR-600', mood: 'panik', text: 'Arus penyulang melonjak, tetapi PMT penyulang tidak membuka!' },
        { t: 20, who: 'wawan', at: 'CR-600', mood: 'ragu', text: 'Relai membaca arus gangguan jauh lebih kecil daripada yang sebenarnya. Apakah data CT berbeda dengan gambar?' },
        { t: 24, who: 'hendra', at: 'CR-600', mood: 'panik', text: 'Buka PMT incoming 20 kV dari panel sekarang! Semua keluar dari gedung switchgear!' },
      ],
      effects: [{ var: 'IF', to: 9000, delay: 1, dur: 2 }, { var: 'TSW', to: 70, delay: 3, dur: 10 }],
      warnings: [
        { t: 3, type: 'vibration', sev: 'warn', at: 'SWG-602', text: 'Terdengar ledakan kecil dari kubikel penyulang yang baru dioperasikan kembali.' },
        { t: 7, type: 'arc', sev: 'crit', at: 'SWG-602', pos: [435, 462], text: 'Kilatan busur listrik di kubikel penyulang. PMT penyulang tidak membuka walaupun arus gangguan sangat besar.' },
        { t: 11, type: 'smoke', sev: 'crit', at: 'SWG-602', pos: [470, 440], text: 'Asap tebal memenuhi gedung switchgear. Relai penyulang belum juga memberi perintah trip.' },
        { t: 16, type: 'fire', sev: 'final', at: 'SWG-602', pos: [435, 462], text: 'Busur listrik yang terus menyala membakar kubikel 20 kV dan kabel. Api merambat di dalam gedung switchgear.' },
      ],
      answer: { node: ['SWG-602'], param: ['E', 'F'], guide: ['high'] },
      hint: 'Arus gangguan sangat besar, tetapi relai penyulang tidak memberi perintah trip. Baca kembali percakapan tentang penggantian CT dan data yang dipakai untuk setting relai.',
      causes: ['Setting relai memakai data CT lama dari gambar yang belum direvisi sehingga relai membaca arus gangguan jauh lebih kecil dan tidak segera trip', 'Pegas mekanisme PMT penyulang tidak terisi sehingga PMT gagal membuka walaupun relai sudah memberi perintah trip', 'Baterai DC gardu habis sehingga relai proteksi kehilangan catu daya dan tidak bekerja sama sekali', 'Hubung singkat terjadi di sisi 150 kV sehingga relai penyulang memang tidak perlu bekerja'], causeAns: 0,
      cons: ['Busur listrik di kubikel tidak segera diputus sehingga terjadi ledakan busur, kebakaran gedung switchgear, dan pemadaman luas', 'Relai cadangan sisi 150 kV pasti memutus gangguan dalam milidetik sehingga tidak ada kerusakan berarti', 'Trafo TR-601 menjadi lebih dingin karena beban penyulang hilang', 'Level minyak konservator naik karena arus gangguan memanaskan minyak'], consAns: 0,
      explain: 'Arus penyulang melonjak berlipat-lipat dan bertahan karena relai penyulang tidak segera trip. Relai menghitung arus primer dari data CT yang dimasukkan dalam setting. Dengan data sekunder 5 ampere pada CT bersekunder 1 ampere, relai membaca arus lima kali lebih kecil dari arus sebenarnya sehingga elemen instan tidak bekerja. Deviasinya sama dengan hubung singkat yang tidak diputus sehingga proteksi busur listrik dan breaker failure tetap diperlukan sebagai lapisan cadangan.' },
    { id: 'e8', start: 12,
      hf: { type: 'slip', team: 'mtc', threat: 3, title: 'Sakelar arah mesin pompa minyak berada di posisi KURAS saat hendak mengisi konservator', factor: 'Sakelar pompa minyak salah posisi, minyak terkuras',
        roles: { wawan: 'Teknisi Pemeliharaan Trafo', dimas: 'Petugas Switchyard', raka: 'Operator Gardu Induk' },
        lesson: 'Wawan bermaksud mengisi minyak konservator, tetapi sakelar arah mesin pompa minyak berada di posisi KURAS. Dua posisi sakelar berdampingan dan labelnya sudah pudar sehingga tindakannya tidak sesuai niat. Kesalahan pelaksanaan seperti ini tergolong slip. Slip tidak dapat dicegah hanya dengan meminta orang lebih berhati-hati karena sumbernya ada pada desain peralatan dan cara kerja. Pencegahannya adalah label dan kode warna yang jelas pada sakelar arah, verifikasi arah aliran oleh orang kedua sebelum pompa ditinggal, serta alarm level konservator dan relai Buchholz yang men-trip trafo saat minyak berkurang.',
        controls: ['Label dan kode warna yang jelas pada sakelar arah mesin pompa minyak', 'Verifikasi arah aliran oleh orang kedua sebelum pompa ditinggal', 'Alarm level konservator rendah dan relai Buchholz yang men-trip trafo'] },
      chat: [
        { t: 1, who: 'raka', at: 'CR-600', text: 'Wawan, hasil inspeksi minggu lalu menyarankan minyak konservator TR-601 ditambah. Apakah bisa dikerjakan sore ini?' },
        { t: 4, who: 'wawan', at: 'TR-601', text: 'Bisa. Mesin pompa minyak sudah saya sambungkan ke katup pengisian konservator dan drum minyak baru juga siap.' },
        { t: 7, who: 'wawan', at: 'TR-601', mood: 'santai', text: 'Pompa sudah berjalan. Saya ke gudang dahulu untuk mengambil drum berikutnya.' },
        { t: 10, who: 'raka', at: 'CR-600', text: 'Baik, kabari saya jika sudah selesai.' },
        { t: 19, who: 'dimas', at: 'TR-601', mood: 'ragu', text: 'Drum di sebelah mesin pompa minyak makin penuh, bukan makin kosong. Apakah arah pompanya sudah benar?' },
        { t: 24, who: 'raka', at: 'CR-600', mood: 'panik', text: 'Level minyak konservator terus turun dan alarm level rendah berbunyi! Matikan pompa sekarang!' },
        { t: 28, who: 'wawan', at: 'TR-601', mood: 'panik', text: 'Sakelar arahnya berada di posisi KURAS! Labelnya pudar, saya kira posisi ISI.' },
      ],
      effects: [{ var: 'LO', to: 4, delay: 1, dur: 14 }],
      warnings: [
        { t: 13, type: 'spill', sev: 'warn', at: 'TR-601', pos: [400, 330], text: 'Drum penampung di sebelah mesin pompa meluap dan minyak trafo tumpah ke lapisan kerikil.' },
        { t: 19, type: 'arc', sev: 'crit', at: 'TR-601', pos: [400, 178], text: 'Terdengar bunyi letupan dari dalam TR-601. Level minyak di kaca konservator tidak terlihat lagi.' },
        { t: 26, type: 'fire', sev: 'final', at: 'TR-601', pos: [400, 240], text: 'Belitan yang tidak lagi terendam minyak mengalami flashover. Minyak yang tumpah di sekitar trafo ikut terbakar.' },
      ],
      answer: { node: ['TR-601'], param: ['L'], guide: ['low'] },
      hint: 'Level minyak konservator turun terus padahal sedang dilakukan pengisian minyak. Baca kembali percakapan tentang mesin pompa minyak dan drum di sebelahnya.',
      causes: ['Sakelar arah mesin pompa minyak berada di posisi KURAS sehingga minyak trafo terpompa keluar, bukan masuk', 'Gasket radiator bocor sehingga minyak keluar sedikit demi sedikit', 'Suhu minyak turun sehingga volume minyak menyusut dan level konservator turun', 'Indikator level konservator rusak sehingga level terbaca rendah palsu'], causeAns: 0,
      cons: ['Bagian aktif trafo tidak lagi terendam minyak, isolasi gagal, lalu terjadi flashover dan kebakaran minyak', 'Minyak baru tercampur dengan minyak lama tanpa dampak', 'Suhu belitan turun karena minyak bersirkulasi lebih cepat', 'Tegangan penyulang naik sedikit tanpa dampak keselamatan'], consAns: 0,
      explain: 'Level minyak konservator turun terus tanpa perubahan beban atau suhu, padahal yang direncanakan adalah pengisian. Minyak keluar karena mesin pompa bekerja ke arah yang salah. Deviasinya sama dengan kebocoran minyak, yaitu level kurang, sehingga alarm level konservator dan relai Buchholz yang men-trip trafo tetap diperlukan walaupun penyebabnya kesalahan manusia.' },
  ],
  variants: [
    ['e3', 'e1', 'e8', 'e6', 'e5'],
    ['e4', 'e3', 'e7', 'e2', 'e5'],
    ['e1', 'e6', 'e7', 'e3', 'e8'],
    ['e2', 'e1', 'e8', 'e4', 'e7'],
    ['e6', 'e4', 'e5', 'e2', 'e7'],
  ],
  hotspots: [
    /* Tahap 3: pencegahan, diurutkan menurut posisi baca pada P&ID (kiri ke kanan, atas ke bawah) */
    { id: 'h38', stage: 3, on: 'LINE-601', tap: [149, 96], x: 157, y: 126, label: 'Saluran transmisi 150 kV (sebelum PMT)', accept: [],
      why: 'Saluran transmisi berada di luar batas gardu dan dilindungi oleh pengelola transmisi. Perangkat di sini tidak melindungi trafo dan kubikel dari ancaman yang teridentifikasi.' },
    { id: 'h35', stage: 3, on: 'TR-601', tap: [472, 154], x: 450, y: 132, label: 'Konservator (indikator level minyak)', accept: ['LT'],
      why: 'Alarm level minyak rendah memberi peringatan dini kebocoran sebelum relai Buchholz harus men-trip trafo.' },
    { id: 'h32', stage: 3, on: 'TR-601', tap: [346, 168], x: 319, y: 184, label: 'Bushing TR-601 (CT sisi 150 dan 20 kV)', accept: ['DIFR'],
      why: 'Relai diferensial memutus kedua sisi trafo dalam puluhan milidetik saat terjadi gangguan internal, sebelum busur listrik menguraikan minyak dalam jumlah besar.' },
    { id: 'h31', stage: 3, on: 'TR-601', tap: [439, 182], x: 499, y: 166, label: 'Pipa tangki ke konservator (relai)', accept: ['BUCH'],
      why: 'Relai Buchholz pada pipa konservator mendeteksi gas hasil penguraian minyak dan minyak yang hilang, lalu memberi alarm dan men-trip trafo.' },
    { id: 'h33', stage: 3, on: 'TR-601', tap: [468, 200], x: 513, y: 226, label: 'Tutup tangki TR-601 (pelepas tekanan)', accept: ['PRD'],
      why: 'Pressure relief device melepas tekanan mendadak akibat busur listrik internal sehingga tangki tidak robek.' },
    { id: 'h34', stage: 3, on: 'TR-601', tap: [311, 236], x: 289, y: 258, label: 'Kantong termometer belitan TR-601', accept: ['WTI', 'TT'],
      why: 'Indikator suhu belitan menyalakan kipas bertahap, memberi alarm, dan men-trip trafo saat panas berlebih. Alarm suhu biasa diterima sebagai lapisan respons operator.' },
    { id: 'h37', stage: 3, on: 'SWG-602', tap: [360, 447], x: 347, y: 397, label: 'Kubikel 20 kV (proteksi busur listrik)', accept: ['ARC'],
      why: 'Proteksi busur listrik mendeteksi kilatan cahaya dan arus gangguan, lalu memutus dalam hitungan milidetik untuk membatasi energi arc flash.' },
    { id: 'h39', stage: 3, on: 'CR-600', tap: [152, 462], x: 183, y: 462, label: 'Gedung kendali (lampu indikator)', accept: [],
      why: 'Lampu indikator di Ruang Kendali bukan lapisan proteksi. Anggaran lebih baik dipakai untuk proteksi pada trafo dan kubikel.' },
    { id: 'h36', stage: 3, on: 'fdr', tap: [600, 478], x: 608, y: 508, label: 'PMT penyulang 20 kV (relai arus lebih)', accept: ['OCR'],
      why: 'Relai arus lebih dan gangguan tanah dengan fungsi breaker failure memutus hubung singkat penyulang secara bertingkat.' },
    /* Tahap 4: mitigasi, diurutkan menurut posisi baca pada P&ID (kiri ke kanan, atas ke bawah) */
    { id: 'h43', stage: 4, on: 'TR-601', tap: [311, 260], x: 289, y: 282, label: 'Sekeliling TR-601 (water spray)', accept: ['DELUGE'],
      why: 'Water spray otomatis mendinginkan tangki dan memadamkan kebakaran minyak setelah trafo diputus dari sumber listrik (NFPA 15).' },
    { id: 'h42', stage: 4, on: 'TR-601', tap: [486, 260], x: 517, y: 260, label: 'Antara TR-601 dan TR-602 (dinding tahan api)', accept: ['FWALL'],
      why: 'Dinding tahan api mencegah kebakaran TR-601 merambat ke TR-602 sehingga gardu tidak padam total (NFPA 850).' },
    { id: 'h47', stage: 4, on: 'TR-601', tap: [330, 308], x: 346, y: 335, label: 'Area trafo (detektor api)', accept: ['FD'],
      why: 'Detektor api mempercepat aktivasi water spray dan pemberitahuan ke regu pemadam.' },
    { id: 'h41', stage: 4, on: 'TR-601', tap: [440, 311], x: 440, y: 342, label: 'Di bawah TR-601 (bak penampung minyak)', accept: ['OPIT'],
      why: 'Bak penampung dengan lapisan kerikil menampung seluruh minyak trafo dan memadamkan minyak menyala yang jatuh sehingga genangan api tidak meluas.' },
    { id: 'h44', stage: 4, on: 'TR-601', tap: [478, 297], x: 494, y: 324, label: 'Tangki TR-601 (sistem injeksi nitrogen)', accept: ['NIFPS'],
      why: 'NIFPS membuang sebagian minyak dan menginjeksikan nitrogen saat gangguan internal terdeteksi sehingga tangki tidak meledak dan terbakar.' },
    { id: 'h48', stage: 4, on: 'MP-600', tap: [920, 320], x: 951, y: 320, label: 'Titik kumpul dan alarm umum', accept: ['ALARM'],
      why: 'Evakuasi terencana melindungi petugas dari ledakan tangki trafo dan asap kebakaran kabel.' },
    { id: 'h49', stage: 4, on: 'SWG-602', tap: [472, 447], x: 459, y: 397, label: 'Kubikel 20 kV (sprinkler air)', accept: [],
      why: 'Menyemprotkan air pada kubikel yang masih bertegangan berisiko bagi petugas dan peralatan. Ruang switchgear lebih tepat dilindungi deteksi asap dan pemadam gas bersih.' },
    { id: 'h46', stage: 4, on: 'gedung-swg', x: 320, y: 438, label: 'Gedung switchgear (pemadam gas)', accept: ['GAS'],
      why: 'Pemadam gas bersih tidak menghantarkan listrik dan tidak merusak peralatan sehingga cocok untuk ruang tertutup berisi kubikel.' },
    { id: 'h45', stage: 4, on: 'gedung-swg', x: 548, y: 438, label: 'Gedung switchgear (detektor asap)', accept: ['SD'],
      why: 'Detektor asap memberi peringatan dini kebakaran kabel dan kubikel serta memicu sistem pemadam gas.' },
  ],
  inspect: [
    { id: 'TR-601', itpm: 'ELEC', why: 'Uji DGA berkala mendeteksi panas berlebih dan busur listrik kecil sebelum menjadi gangguan besar, sementara termografi dan uji tahanan isolasi menilai kondisi trafo (IEEE C57.104).' },
    { id: 'FN-601', itpm: 'ROT', why: 'Kipas pendingin yang rusak tidak terlihat sampai trafo kepanasan saat beban puncak. Pemeliharaan prediktif menjaga kapasitas pendinginan.' },
    { id: 'SWG-602', itpm: 'ELEC', why: 'Termografi dan uji partial discharge pada kubikel mendeteksi sambungan panas dan isolasi yang menurun sebelum terjadi busur listrik.' },
  ],
  budget: { 3: 30, 4: 31 },
  bowtie: {
    top: 'Kegagalan isolasi dan busur listrik pada trafo daya atau kubikel 20 kV',
    threats: ['Kipas pendingin gagal, belitan kepanasan', 'Gangguan isolasi internal trafo', 'Hubung singkat penyulang tidak diputus', 'Kehilangan minyak trafo'],
    cons: ['Kebakaran minyak trafo', 'Ledakan tangki trafo', 'Kebakaran gedung switchgear', 'Flashover dan pemadaman luas'],
  },
};
SCENARIOS.push(SCN_TRAFO);
