/* Skenario sektor Ketenagalistrikan: dimuat setelah js/data.js dan menambahkan diri ke SCENARIOS. */
/* =====================================================================
   KETENAGALISTRIKAN: Boiler PLTU Batu Bara
   ===================================================================== */
const SCN_BOILER = {
  id: 'boiler',
  title: 'Boiler PLTU Batu Bara',
  subtitle: 'Ketel pipa air, drum uap, coal mill, burner, turbin dan generator 30 MW',
  level: 'Lanjutan',
  sector: 'listrik',
  area: 'Pembangkit Termal (PLTU)',
  color: '#2d5f86',
  kits: ['boiler'],
  op: 'Operasi Pembangkit',
  overview: [
    'Unit ini adalah boiler PLTU berkapasitas 30 MW. Batu bara dari stockpile diangkut konveyor CV-501 ke bunker BK-501, lalu digiling dan dikeringkan di coal mill ML-501 dengan udara primer panas dari kipas FN-502. Serbuk batu bara dibawa udara ke burner BRN-501 dan dibakar di ruang bakar FUR-501. Solar dari TK-502 dipakai untuk penyalaan awal.',
    'Dinding ruang bakar tersusun dari pipa-pipa berisi air (water wall). Air turun dari drum uap D-501 melalui downcomer, menyerap panas pembakaran, lalu kembali ke drum sebagai campuran uap dan air. Drum beroperasi pada 110 barg dengan tekanan desain 128 barg. Pompa P-501 memasok air umpan dari deaerator melalui economizer E-501, dan FCV-501 menjaga level drum 50 %.',
    'Uap dari drum memutar turbin TG-501 yang menggerakkan generator GEN-501. Gas buang ditarik kipas FN-501 melalui economizer ke cerobong ST-501 sehingga tekanan ruang bakar tetap sedikit negatif. Pipa dinding air hanya aman selama terendam air, dan serbuk batu bara yang tidak terbakar dapat meledak bila menumpuk di ruang bakar.',
  ],
  production: { label: 'Energi listrik dibangkitkan', unit: 'MWh', var: 'MW', k: 1 / 60, dec: 1 },
  fluidNames: { bulk: 'Batu bara mentah', coal: 'Serbuk batu bara dan udara primer', air: 'Udara primer panas', oil: 'Solar dan oli pelumas', water: 'Air umpan dan air ketel', steam: 'Uap', flue: 'Gas buang', power: 'Kabel daya ke jaringan' },
  equipment: [
    { id: 'CV-501', type: 'conveyor', x: 20, y: 36, w: 170, h: 0, name: 'Konveyor Batu Bara',
      desc: 'Mengangkut batu bara dari stockpile ke bunker. Logam asing seperti baut dan potongan besi dapat ikut terbawa bersama batu bara.' },
    { id: 'BK-501', type: 'silo', x: 50, y: 58, w: 90, h: 140, name: 'Bunker Batu Bara',
      desc: 'Menampung batu bara untuk sekitar 8 jam operasi. Batu bara yang tertahan lama dapat memanas sendiri dan membara.' },
    { id: 'ML-501', type: 'mill', x: 95, y: 300, name: 'Coal Mill (Pulverizer)',
      desc: 'Menggiling dan mengeringkan batu bara menjadi serbuk halus dengan udara primer panas. Suhu keluar normal 70 °C; di atas sekitar 90 °C risiko kebakaran dan ledakan debu batu bara meningkat tajam.', vars: ['TML'] },
    { id: 'FN-502', type: 'fan', x: 95, y: 432, name: 'Kipas Udara Primer',
      desc: 'Mengalirkan udara panas dari air heater ke mill untuk mengeringkan batu bara dan membawa serbuknya ke burner.' },
    { id: 'BRN-501', type: 'burner', x: 218, y: 380, name: 'Burner Batu Bara', flameVar: 'FLM',
      desc: 'Menyemburkan campuran serbuk batu bara dan udara ke ruang bakar. Saat ini nyala hanya dipantau operator melalui kamera ruang bakar, tanpa penutupan bahan bakar otomatis.' },
    { id: 'TK-502', type: 'tank', x: 140, y: 460, w: 60, h: 60, name: 'Tangki Solar Penyalaan',
      desc: 'Menyimpan solar untuk penyalaan awal boiler dan penstabil nyala saat beban rendah.' },
    { id: 'FUR-501', type: 'furnace', x: 250, y: 170, w: 170, h: 280, name: 'Ruang Bakar Boiler', flameVar: 'FLM',
      desc: 'Ruang bakar ketel pipa air dengan dinding membran (water wall). Tekanan ruang bakar dijaga sekitar minus 10 mmH2O oleh ID fan. Pipa dinding air hanya aman selama terendam air dari drum.', vars: ['FLM', 'PF5'] },
    { id: 'D-501', type: 'vessel', orient: 'h', x: 300, y: 60, w: 170, h: 50, name: 'Drum Uap D-501', level: 'LD5',
      desc: 'Memisahkan uap dari air ketel. Tekanan operasi 110 barg, tekanan desain 128 barg. Level normal dijaga 50 % oleh LIC-501 melalui FCV-501.', vars: ['LD5', 'PD5'] },
    { id: 'E-501', type: 'hx', x: 460, y: 300, name: 'Economizer E-501',
      desc: 'Memanaskan air umpan dengan sisa panas gas buang sebelum air masuk ke drum.' },
    { id: 'FN-501', type: 'fan', x: 530, y: 470, name: 'Kipas Gas Buang (ID Fan)',
      desc: 'Menarik gas buang sehingga tekanan ruang bakar tetap sedikit negatif dan api serta gas panas tidak keluar dari celah boiler.' },
    { id: 'ST-501', type: 'stack', x: 600, y: 500, h: 140, name: 'Cerobong',
      desc: 'Membuang gas buang ke atmosfer setelah melewati pengendali emisi.' },
    { id: 'P-501', type: 'pump', dir: 'left', x: 710, y: 300, name: 'Pompa Air Umpan P-501',
      desc: 'Pompa bertekanan tinggi yang memompa air dari deaerator ke drum. Unit ini mengandalkan satu pompa yang beroperasi.', vars: ['FW5'] },
    { id: 'FCV-501', type: 'valve', sub: 'control', x: 590, y: 300, tag: 'LIC', name: 'FCV-501 (Kendali Level Drum)',
      desc: 'Mengatur aliran air umpan untuk menjaga level drum 50 %.' },
    { id: 'DA-501', type: 'sink', x: 760, y: 300, dir: 'right', name: 'Air Umpan dari Deaerator',
      desc: 'Air umpan bebas oksigen bersuhu sekitar 150 °C dari deaerator.' },
    { id: 'TG-501', type: 'turbine', x: 620, y: 50, w: 100, h: 56, name: 'Turbin Uap TG-501',
      desc: 'Mengubah energi uap menjadi putaran untuk generator. Saat turbin trip, uap harus dialihkan melalui bypass atau pembakaran segera dikurangi.' },
    { id: 'GEN-501', type: 'generator', x: 752, y: 46, w: 110, h: 64, name: 'Generator 30 MW',
      desc: 'Generator sinkron yang menyalurkan daya ke jaringan transmisi 150 kV.', vars: ['MW'] },
    { id: 'GRID-501', type: 'sink', x: 848, y: 150, dir: 'right', name: 'Ke Jaringan 150 kV',
      desc: 'Daya listrik disalurkan melalui trafo generator ke jaringan transmisi.' },
    { id: 'TK-503', type: 'tank', x: 650, y: 150, w: 50, h: 52, name: 'Tangki Oli Pelumas Turbin',
      desc: 'Menyimpan oli pelumas bantalan turbin. Kebocoran oli ke permukaan panas adalah penyebab umum kebakaran di area turbin (NFPA 850).' },
    { id: 'CR-500', type: 'building', x: 700, y: 470, name: 'Ruang Kendali',
      desc: 'Operator memantau DCS boiler dan turbin. Lokasi tombol master fuel trip dan ESD.' },
    { id: 'MP-500', type: 'muster', x: 900, y: 480, name: 'Titik Kumpul',
      desc: 'Area berkumpul evakuasi di luar gedung boiler.' },
  ],
  pipes: [
    { id: 'c1', fluid: 'bulk', w: 7, pts: [[95, 206], [95, 278]] },
    { id: 'a1', fluid: 'air', w: 6, pts: [[95, 408], [95, 328]], arrow: true },
    { id: 'c2', fluid: 'coal', w: 6, pts: [[121, 300], [190, 300], [190, 380], [202, 380]], arrow: true },
    { id: 'o1', fluid: 'oil', w: 4, pts: [[200, 490], [226, 490], [226, 392]] },
    { id: 'dc', fluid: 'water', w: 6, pts: [[318, 110], [318, 170]] },
    { id: 'rs', fluid: 'steam', w: 6, pts: [[410, 170], [410, 110]] },
    { id: 'st1', fluid: 'steam', w: 7, pts: [[400, 60], [400, 30], [592, 30], [592, 78], [606, 78]], arrow: true },
    { id: 'pw', fluid: 'power', w: 5, pts: [[807, 110], [807, 150], [848, 150]], arrow: true },
    { id: 'fw1', fluid: 'water', w: 6, pts: [[760, 300], [732, 300]] },
    { id: 'fw2', fluid: 'water', w: 6, pts: [[688, 300], [488, 300]], arrow: true },
    { id: 'fw3', fluid: 'water', w: 6, pts: [[482, 280], [482, 100], [470, 100]], arrow: true },
    { id: 'fl1', fluid: 'flue', w: 8, pts: [[420, 190], [460, 190], [460, 272]] },
    { id: 'fl2', fluid: 'flue', w: 8, pts: [[460, 328], [460, 470], [508, 470]] },
    { id: 'fl3', fluid: 'flue', w: 8, pts: [[564, 455], [590, 455]] },
    { id: 'lo', fluid: 'oil', w: 3, pts: [[675, 150], [675, 106]] },
  ],
  labels: [
    { x: 520, y: 20, text: 'Uap utama 100 barg', size: 10 },
    { x: 505, y: 400, text: 'Gas buang', size: 10 },
  ],
  vars: {
    LD5: { label: 'Level Drum D-501', unit: '%', normal: 50, min: 0, max: 100, lo: 35, lolo: 20, hi: 65, hihi: 80, node: 'D-501', x: 245, y: 85, tau: 3, noise: 0.4, dec: 0 },
    PD5: { label: 'Tekanan Drum D-501', unit: 'barg', normal: 110, min: 0, max: 140, lo: 95, hi: 118, hihi: 124, node: 'D-501', x: 530, y: 62, tau: 4, noise: 0.2, dec: 1 },
    FW5: { label: 'Aliran Air Umpan', unit: 't/j', normal: 120, min: 0, max: 180, lo: 65, lolo: 40, node: 'P-501', x: 722, y: 260, tau: 2, noise: 0.8, dec: 0 },
    PF5: { label: 'Tekanan Ruang Bakar', unit: 'mmH2O', normal: -10, min: -150, max: 150, lo: -40, lolo: -80, hi: 10, hihi: 40, node: 'FUR-501', x: 335, y: 500, tau: 1.5, noise: 0.6, dec: 0 },
    FLM: { label: 'Intensitas Nyala Ruang Bakar', unit: '%', normal: 90, min: 0, max: 100, lo: 50, lolo: 30, node: 'FUR-501', x: 335, y: 250, tau: 1, noise: 0.8, dec: 0 },
    TML: { label: 'Suhu Keluar Coal Mill', unit: '°C', normal: 70, min: 20, max: 200, lo: 55, hi: 85, hihi: 95, node: 'ML-501', x: 178, y: 258, tau: 5, noise: 0.3, dec: 0 },
    MW:  { label: 'Daya Generator', unit: 'MW', normal: 30, min: 0, max: 40, lo: 10, node: 'GEN-501', x: 918, y: 108, tau: 2, noise: 0.1, dec: 1 },
  },
  trendVars: ['LD5', 'PD5', 'FLM', 'TML'],
  controls: [
    { id: 'load', label: 'Beban generator', unit: 'MW', min: 15, max: 35, def: 30, step: 1,
      effects: [{ var: 'MW', gain: 1 }, { var: 'FW5', gain: 3 }, { var: 'PD5', gain: -0.15 }, { var: 'FLM', gain: 1 }, { var: 'TML', gain: 0.2 }] },
    { id: 'drum', label: 'Set point level drum (LIC-501)', unit: '%', min: 40, max: 60, def: 50, step: 2,
      effects: [{ var: 'LD5', gain: 1 }] },
    { id: 'draft', label: 'Set point tekanan ruang bakar (ID fan)', unit: 'mmH2O', min: -20, max: -5, def: -10, step: 1,
      effects: [{ var: 'PF5', gain: 1 }] },
  ],
  quiz: [
    { q: 'Mengapa level air drum D-501 tidak boleh turun terlalu rendah?', opts: ['Pipa dinding air tetap menerima panas tetapi kehilangan pendinginan, sehingga logamnya kepanasan dan pecah', 'Tekanan uap turun drastis sehingga turbin kehilangan daya dan generator trip dari jaringan', 'Pompa air umpan akan kavitasi karena menghisap uap yang mengalir balik dari drum', 'Butiran air terbawa ke superheater dan turbin sehingga sudu turbin tererosi dan rusak berat'], ans: 0,
      why: 'Air di dalam pipa dinding membuang panas dari logam pipa. Ketel yang kekurangan air adalah penyebab klasik pecahnya pipa dan ledakan ketel, sehingga low water cut-off menjadi perlengkapan pengaman wajib.' },
    { q: 'Apa penyebab utama ledakan ruang bakar (furnace explosion) pada boiler batu bara?', opts: ['Bahan bakar yang tidak terbakar menumpuk setelah nyala padam, lalu tersulut serentak saat penyalaan ulang', 'Tekanan uap di drum melampaui desain sehingga dinding ruang bakar ikut pecah', 'Udara pembakaran berlebih membuat nyala terlalu panas sehingga dinding ruang bakar tertekan keluar', 'Pipa dinding air pecah dan air yang menguap mendadak meledakkan ruang bakar dari dalam'], ans: 0,
      why: 'NFPA 85 menekankan bahwa sebagian besar ledakan ruang bakar terjadi karena akumulasi bahan bakar. Burner management system menutup bahan bakar saat nyala hilang dan mewajibkan purge sebelum penyalaan ulang.' },
    { q: 'Mengapa tekanan ruang bakar dijaga sedikit negatif oleh ID fan?', opts: ['Agar api dan gas buang panas tidak menyembur keluar dari celah dan lubang intip ke area operator', 'Agar pembakaran lebih sempurna karena tekanan negatif menarik lebih banyak oksigen ke burner', 'Agar uap di pipa dinding air terbentuk pada suhu yang lebih rendah', 'Agar abu terbang tertahan di ruang bakar dan tidak terbawa ke cerobong maupun electrostatic precipitator'], ans: 0,
      why: 'Tekanan negatif membuat udara luar masuk ke ruang bakar, bukan sebaliknya. Bila ID fan mati, tekanan menjadi positif dan api dapat menyembur balik.' },
    { q: 'Mengapa suhu keluar coal mill dibatasi sekitar 70 °C?', opts: ['Di atas batas tertentu serbuk batu bara di dalam mill mudah membara, terbakar, dan meledak', 'Agar serbuk batu bara tidak terlalu kering sehingga tidak menggumpal dan menyumbat pipa ke burner', 'Agar burner tidak terlalu panas dan nyala tetap stabil pada beban rendah', 'Agar kandungan air batu bara tetap tinggi untuk menekan pembentukan emisi NOx di ruang bakar'], ans: 0,
      why: 'Mill berisi awan debu batu bara dan udara panas. Suhu berlebih, batu bara yang tertahan, atau logam asing yang memercik dapat memicu kebakaran dan ledakan mill.' },
    { q: 'Apa yang harus terjadi pada pembakaran saat turbin TG-501 trip?', opts: ['Pembakaran segera dikurangi atau dihentikan dan uap dialihkan, karena tekanan drum akan naik', 'Pembakaran dipertahankan karena PSV drum akan membuang kelebihan uap dengan aman ke atmosfer', 'Pompa air umpan dihentikan agar drum tidak terlalu penuh saat uap tidak dipakai turbin', 'Pembakaran dinaikkan sesaat agar turbin dapat disinkronkan kembali lebih cepat ke jaringan'], ans: 0,
      why: 'Tanpa konsumen uap, panas pembakaran menaikkan tekanan drum. Katup pengaman drum dan superheater adalah lapisan proteksi terakhir yang wajib ada pada setiap ketel uap.' },
  ],
  events: [
    { id: 'e1', threat: 0, effects: [{ var: 'FW5', to: 3, delay: 1, dur: 3 }, { var: 'LD5', to: 2, delay: 2, dur: 16 }, { var: 'PD5', to: 104, delay: 4, dur: 12 }],
      warnings: [
        { t: 10, type: 'vibration', sev: 'warn', at: 'P-501', text: 'Pompa air umpan P-501 berhenti; pipa air umpan bergetar dan terdengar hentakan (water hammer).' },
        { t: 17, type: 'heat', sev: 'crit', at: 'FUR-501', pos: [335, 225], text: 'Pipa dinding air di ruang bakar memerah; suhu logam pipa melonjak karena kekurangan air.' },
        { t: 24, type: 'explosion', sev: 'final', at: 'FUR-501', pos: [335, 300], text: 'PIPA BOILER PECAH: uap bertekanan tinggi menyembur di ruang bakar, casing boiler jebol dan uap panas memenuhi area operator.' },
      ],
      answer: { node: ['D-501', 'P-501', 'FCV-501'], param: ['L', 'F'], guide: ['low', 'none'] },
      hint: 'Air yang masuk ke drum berhenti, sementara uap terus keluar ke turbin. Periksa pasokan air umpan.',
      causes: ['Pompa air umpan P-501 trip atau FCV-501 gagal tertutup sehingga air umpan berhenti', 'Beban generator turun', 'Coal mill tersumbat', 'ID fan berputar terlalu cepat'], causeAns: 0,
      cons: ['Pipa dinding air kekurangan pendinginan, logam pipa terlalu panas lalu pecah, dan uap panas menyembur dengan potensi korban jiwa', 'Tekanan drum turun tanpa dampak lain', 'Daya generator naik', 'Suhu coal mill turun'], consAns: 0,
      explain: 'Aliran air umpan hilang lebih dulu, lalu level drum turun terus. Ketel yang kehabisan air sangat berbahaya karena pipa dinding air tetap menerima panas pembakaran tanpa pendinginan. Proteksi wajibnya adalah low water cut-off yang men-trip pembakaran secara otomatis, didukung alarm level dan check valve pada pompa air umpan.' },
    { id: 'e2', threat: 1, effects: [{ var: 'FLM', to: 3, delay: 1, dur: 2 }, { var: 'PF5', to: -60, delay: 1, dur: 4 }, { var: 'PD5', to: 99, delay: 2, dur: 14 }],
      warnings: [
        { t: 7, type: 'smoke', sev: 'warn', at: 'FUR-501', pos: [335, 205], text: 'Nyala api di ruang bakar padam; asap hitam pekat keluar dari lubang intip, tetapi serbuk batu bara masih terus dikirim ke burner.' },
        { t: 13, type: 'vibration', sev: 'crit', at: 'FUR-501', text: 'Dentuman kecil (puffing) dan fluktuasi tekanan di ruang bakar saat serbuk batu bara menumpuk.' },
        { t: 19, type: 'explosion', sev: 'final', at: 'FUR-501', pos: [335, 330], text: 'LEDAKAN RUANG BAKAR: awan serbuk batu bara yang terakumulasi tersulut serentak saat penyalaan ulang, dinding boiler jebol.' },
      ],
      answer: { node: ['FUR-501', 'BRN-501'], param: ['C', 'T'], guide: ['none', 'low'] },
      hint: 'Nyala api di ruang bakar hilang, tetapi bahan bakar tetap dikirim ke burner.', hintVar: 'FLM',
      causes: ['Nyala padam akibat batu bara basah atau gangguan suplai udara, sementara bahan bakar tidak dihentikan karena tidak ada sistem pengaman pembakaran', 'Pompa air umpan trip', 'Turbin trip', 'Level drum terlalu tinggi'], causeAns: 0,
      cons: ['Serbuk batu bara terakumulasi di ruang bakar lalu meledak saat penyalaan ulang, merusak boiler dan melukai pekerja', 'Daya generator naik', 'Level drum naik tanpa dampak', 'Coal mill menjadi lebih dingin'], consAns: 0,
      explain: 'Intensitas nyala turun ke hampir nol sementara bahan bakar tetap mengalir. Ledakan ruang bakar terjadi ketika bahan bakar yang tidak terbakar menumpuk lalu tersulut serentak. NFPA 85 mensyaratkan burner management system yang menutup bahan bakar dalam hitungan detik saat nyala hilang serta purge sebelum penyalaan ulang. Dalam HAZOP, kejadian ini dibaca sebagai deviasi reaksi pembakaran: tidak ada.' },
    { id: 'e3', threat: 2, effects: [{ var: 'TML', to: 150, delay: 2, dur: 18 }],
      warnings: [
        { t: 12, type: 'heat', sev: 'warn', at: 'ML-501', text: 'Casing coal mill ML-501 sangat panas dan cat mulai mengelupas.' },
        { t: 18, type: 'smoke', sev: 'crit', at: 'ML-501', pos: [95, 262], text: 'ASAP keluar dari seal coal mill dan pipa batu bara; tercium bau batu bara terbakar.' },
        { t: 25, type: 'explosion', sev: 'final', at: 'ML-501', pos: [100, 290], text: 'LEDAKAN COAL MILL: debu batu bara di dalam mill tersulut, pipa batu bara terlempar dan api menyambar ke area bunker.' },
      ],
      answer: { node: ['ML-501'], param: ['T'], guide: ['high'] },
      hint: 'Udara panas terus masuk ke mill, tetapi batu bara yang masuk berkurang sehingga panas tidak terserap.',
      causes: ['Pasokan batu bara ke mill terhenti atau damper udara panas gagal terbuka sehingga mill kepanasan', 'Pompa air umpan trip', 'Beban generator naik sedikit', 'Level drum turun'], causeAns: 0,
      cons: ['Batu bara di dalam mill membara dan terbakar, lalu meledak bersama debu batu bara dan merambat ke bunker', 'Daya generator naik', 'Tekanan drum naik tanpa dampak', 'Air umpan berhenti'], consAns: 0,
      explain: 'Suhu keluar mill naik terus tanpa perubahan pada sisi air dan uap. Ini pola mill kepanasan karena udara panas berlebih dibanding batu bara yang masuk. Proteksi yang tepat adalah trip suhu tinggi-tinggi yang menutup damper udara panas, analyzer CO untuk deteksi pembaraan dini, dan pemisah magnet untuk mencegah percikan dari logam asing.' },
    { id: 'e4', threat: 3, effects: [{ var: 'MW', to: 0, delay: 1, dur: 2 }, { var: 'PD5', to: 136, delay: 2, dur: 20 }],
      warnings: [
        { t: 10, type: 'vibration', sev: 'warn', at: 'TG-501', text: 'Turbin TG-501 trip; getaran keras dan suara uap mendesis pada jalur uap utama.' },
        { t: 17, type: 'leak', sev: 'crit', at: 'D-501', pos: [385, 56], text: 'Uap menyembur dari gasket manhole drum D-501 dengan suara memekakkan.' },
        { t: 25, type: 'explosion', sev: 'final', at: 'D-501', pos: [385, 90], text: 'LEDAKAN DRUM UAP: tekanan melampaui desain dan drum D-501 pecah.' },
      ],
      answer: { node: ['D-501', 'TG-501'], param: ['P'], guide: ['high'] },
      hint: 'Uap tidak lagi dipakai turbin, tetapi pembakaran masih berjalan penuh.',
      causes: ['Turbin trip sementara pembakaran tidak segera dikurangi dan katup bypass gagal membuka', 'Coal mill terlalu panas', 'Level drum terlalu tinggi', 'ID fan trip'], causeAns: 0,
      cons: ['Tekanan drum melampaui desain, drum atau pipa uap pecah dan melepaskan uap bertekanan tinggi', 'Daya generator naik', 'Suhu mill turun', 'Level drum naik tanpa dampak'], consAns: 0,
      explain: 'Daya generator turun mendadak lalu tekanan drum naik terus karena uap yang dihasilkan tidak memiliki tujuan. Katup pengaman pada drum dan superheater wajib ada pada setiap ketel uap, didukung alarm tekanan tinggi dan trip pembakaran otomatis.' },
    { id: 'e5', start: 10,
      hf: { type: 'mistake', team: 'ops', threat: 0, title: 'Pesawat uap dijaga helper tanpa lisensi', factor: 'Helper tanpa lisensi menghentikan pompa air umpan',
        roles: { dimas: 'Operator Boiler Berlisensi', raka: 'Operator Panel Unit' },
        lesson: 'Tindakan Tono adalah mistake: ia berniat melindungi pompa, tetapi tidak memahami bahwa air umpan adalah pendingin pipa dinding air. Akar masalahnya adalah operator berlisensi meninggalkan pos dan menyerahkan pesawat uap kepada orang yang tidak berwenang. Permenaker No. 4 Tahun 2025 tentang Operator Pesawat Uap mengatur bahwa pesawat uap dioperasikan oleh operator yang memiliki lisensi K3. Membisukan alarm kritis juga melanggar prinsip manajemen alarm.',
        controls: ['Pesawat uap hanya dioperasikan operator berlisensi K3 (Permenaker No. 4 Tahun 2025)', 'Serah terima tugas kepada operator berwenang setiap kali meninggalkan pos', 'Alarm kritis tidak boleh dibisukan tanpa tindakan (ANSI/ISA-18.2)'] },
      chat: [
        { t: 1, who: 'dimas', at: 'CR-500', text: 'Tono, aku ke kantin sebentar. Tolong jaga panel boiler ya, jangan ubah apa pun.' },
        { t: 4, who: 'tono', at: 'CR-500', mood: 'santai', text: 'Siap, aman. Aku sudah sering lihat cara kerjanya.' },
        { t: 7, who: 'tono', at: 'P-501', mood: 'ragu', text: 'Pompa air umpan P-501 bunyinya kasar. Kumatikan dulu biar tidak rusak, nanti kuhidupkan lagi.' },
        { t: 15, who: 'raka', at: 'CR-500', mood: 'ragu', text: 'Tono, kenapa P-501 berhenti? Aliran air umpan turun drastis di layar.' },
        { t: 18, who: 'tono', at: 'CR-500', mood: 'ragu', text: 'Lagi kuperiksa. Alarm di panel bunyi terus, suaranya kumatikan dulu ya, berisik.' },
        { t: 22, who: 'raka', at: 'CR-500', mood: 'panik', text: 'Level drum terus turun! Jangan matikan alarm. Dimas, cepat kembali ke boiler!' },
        { t: 26, who: 'dimas', at: 'D-501', mood: 'panik', text: 'Aku lari ke sana. Tono, jangan sentuh apa-apa lagi!' },
      ],
      effects: [{ var: 'FW5', to: 3, delay: 1, dur: 3 }, { var: 'LD5', to: 2, delay: 2, dur: 16 }, { var: 'PD5', to: 104, delay: 4, dur: 12 }],
      warnings: [
        { t: 10, type: 'vibration', sev: 'warn', at: 'P-501', text: 'Pipa air umpan bergetar dan terdengar hentakan (water hammer) setelah pompa P-501 dihentikan.' },
        { t: 17, type: 'heat', sev: 'crit', at: 'FUR-501', pos: [335, 225], text: 'Pipa dinding air di ruang bakar memerah; suhu logam pipa melonjak karena kekurangan air.' },
        { t: 24, type: 'explosion', sev: 'final', at: 'FUR-501', pos: [335, 300], text: 'PIPA BOILER PECAH: uap bertekanan tinggi menyembur di ruang bakar, casing boiler jebol dan uap panas memenuhi area operator.' },
      ],
      answer: { node: ['D-501', 'P-501', 'FCV-501'], param: ['L', 'F'], guide: ['low', 'none'] },
      hint: 'Aliran air umpan hilang karena pompa dihentikan, bukan karena kerusakan. Baca kembali obrolan tentang siapa yang menjaga panel boiler.',
      causes: ['Helper tanpa lisensi menghentikan pompa air umpan karena mengira pompa akan rusak, lalu membisukan alarm level drum', 'Pompa P-501 trip karena bantalan rusak dan pompa cadangan gagal start otomatis', 'FCV-501 menutup karena sinyal level drum terbaca terlalu tinggi', 'Deaerator kehabisan air sehingga pompa kehilangan isapan'], causeAns: 0,
      cons: ['Pipa dinding air kehilangan pendinginan, kepanasan, lalu pecah sehingga uap bertekanan menyembur ke area operator', 'Tekanan drum naik karena uap tidak terpakai', 'Produksi listrik naik sesaat karena uap lebih kering', 'Coal mill berhenti karena kekurangan udara primer'], consAns: 0,
      explain: 'Aliran air umpan turun ke nol lalu level drum turun terus. Saat level di bawah batas aman, pipa dinding air tetap menerima panas pembakaran tetapi tidak lagi didinginkan air. Membisukan alarm level menghapus kesempatan orang lain untuk bertindak.' },
    { id: 'e6', threat: 0, effects: [{ var: 'FW5', to: 168, delay: 1, dur: 8 }, { var: 'LD5', to: 10, delay: 2, dur: 15 }, { var: 'PF5', to: 16, delay: 4, dur: 7 }, { var: 'MW', to: 27, delay: 6, dur: 10 }],
      warnings: [
        { t: 13, type: 'smoke', sev: 'warn', at: 'ST-501', pos: [600, 380], text: 'Asap putih tebal berupa uap air keluar dari cerobong, dan air menetes dari hopper economizer E-501.' },
        { t: 19, type: 'heat', sev: 'crit', at: 'FUR-501', pos: [335, 225], text: 'Level drum sangat rendah walaupun pompa air umpan bekerja penuh. Pipa dinding air mulai memerah.' },
        { t: 26, type: 'explosion', sev: 'final', at: 'FUR-501', pos: [335, 300], text: 'Pipa dinding air yang kekurangan air pecah. Uap bertekanan tinggi menyembur dan casing boiler jebol.' },
      ],
      answer: { node: ['E-501', 'D-501'], param: ['F', 'L'], guide: ['other', 'high', 'low'] },
      hint: 'Pompa mengirim lebih banyak air umpan, tetapi level drum justru turun dan cerobong mengeluarkan asap putih. Pikirkan ke mana air umpan pergi sebelum sampai di drum.',
      causes: ['Tube economizer E-501 bocor sehingga sebagian air umpan terbuang ke saluran gas buang sebelum mencapai drum', 'Pompa air umpan P-501 trip sehingga aliran ke drum berhenti', 'FCV-501 macet tertutup sehingga air umpan tertahan', 'Transmitter level drum menyimpang sehingga level terbaca rendah palsu'], causeAns: 0,
      cons: ['Level drum turun hingga pipa dinding air kekurangan air, kepanasan, lalu pecah dan menyemburkan uap', 'Daya generator naik karena uap bertambah', 'Coal mill kepanasan karena udara primer berlebih', 'Tekanan drum naik melampaui desain'], consAns: 0,
      explain: 'Aliran air umpan justru naik, tetapi level drum turun dan cerobong mengeluarkan asap putih. Air umpan keluar melalui jalur yang tidak dirancang, yaitu tube economizer yang bocor ke saluran gas buang, sehingga air yang sampai ke drum berkurang. Ini deviasi aliran Other than yang berujung pada level drum rendah. Pemeriksaan ketebalan tube economizer dan pipa ketel, alarm selisih aliran air umpan dan uap, serta low water cut-off yang men-trip pembakaran memutus rantai ini.' },
    { id: 'e7', start: 12,
      hf: { type: 'lapse', team: 'mtc', threat: 1, title: 'Damper udara sekunder burner tidak dibuka kembali setelah pembersihan nozzle', factor: 'Damper udara burner lupa dibuka setelah perawatan',
        lesson: 'Joko menutup dan mengunci damper udara sekunder agar pembersihan nozzle aman, lalu menyatakan burner siap tanpa membukanya kembali. Ia tidak berniat melanggar prosedur; langkah pemulihan terlupa karena ia terburu-buru ke pekerjaan berikutnya. Kegagalan memori seperti ini tergolong lapse. Tanpa udara pembakaran yang cukup, nyala menjadi tidak stabil lalu padam sementara serbuk batu bara terus masuk ke ruang bakar. Pencegahnya adalah daftar periksa pemulihan dan pelepasan gembok isolasi yang diverifikasi operator, serta burner management system yang menutup bahan bakar saat nyala hilang.',
        controls: ['Daftar periksa pemulihan dan pelepasan gembok isolasi sebelum izin kerja ditutup', 'Verifikasi posisi damper bersama operator sebelum burner dinyalakan', 'Burner management system dengan flame scanner (NFPA 85)'] },
      chat: [
        { t: 1, who: 'hendra', at: 'CR-500', text: 'Joko, pembersihan nozzle burner BRN-501 sudah selesai? Beban mau dinaikkan lagi ke 30 MW.' },
        { t: 4, who: 'joko', at: 'BRN-501', text: 'Sudah, Pak. Nozzle sudah bersih. Selama dibersihkan, damper udara sekunder burner kututup dan kugembok.' },
        { t: 7, who: 'joko', at: 'BRN-501', mood: 'santai', text: 'Burner siap dipakai. Aku lanjut ke konveyor ya, sabuknya perlu disetel.' },
        { t: 10, who: 'raka', at: 'CR-500', text: 'Oke, terima kasih. Umpan batu bara kunaikkan bertahap.' },
        { t: 16, who: 'raka', at: 'CR-500', mood: 'ragu', text: 'Nyala di kamera ruang bakar meredup dan berkedip. Tekanan ruang bakar ikut turun.' },
        { t: 20, who: 'dimas', at: 'BRN-501', mood: 'ragu', text: 'Damper udara sekunder BRN-501 masih tertutup, gemboknya juga masih terpasang!' },
        { t: 24, who: 'raka', at: 'CR-500', mood: 'panik', text: 'Nyala padam, tapi serbuk batu bara masih masuk! Hentikan feeder, jangan dinyalakan ulang sebelum purge!' },
      ],
      effects: [{ var: 'FLM', to: 3, delay: 1, dur: 6 }, { var: 'PF5', to: -60, delay: 1, dur: 6 }, { var: 'PD5', to: 99, delay: 3, dur: 14 }],
      warnings: [
        { t: 8, type: 'smoke', sev: 'warn', at: 'FUR-501', pos: [335, 205], text: 'Nyala di ruang bakar padam. Asap hitam pekat keluar dari lubang intip, sementara serbuk batu bara terus masuk.' },
        { t: 14, type: 'vibration', sev: 'crit', at: 'FUR-501', text: 'Dentuman kecil (puffing) dan fluktuasi tekanan di ruang bakar saat serbuk batu bara menumpuk.' },
        { t: 21, type: 'explosion', sev: 'final', at: 'FUR-501', pos: [335, 330], text: 'Awan serbuk batu bara yang menumpuk tersulut serentak. Ledakan ruang bakar menjebol dinding boiler.' },
      ],
      answer: { node: ['FUR-501', 'BRN-501'], param: ['C', 'T'], guide: ['none', 'low'] },
      hint: 'Nyala meredup lalu padam tak lama setelah burner selesai dirawat, sementara bahan bakar tetap masuk. Baca kembali obrolan tentang langkah yang dilakukan selama pembersihan nozzle.', hintVar: 'FLM',
      causes: ['Damper udara sekunder BRN-501 masih tertutup dan tergembok setelah pembersihan nozzle sehingga nyala kekurangan udara dan padam', 'Batu bara terlalu basah sehingga nyala sulit dipertahankan', 'ID fan trip sehingga tekanan ruang bakar menjadi positif', 'Pompa air umpan trip sehingga level drum turun'], causeAns: 0,
      cons: ['Serbuk batu bara yang tidak terbakar menumpuk di ruang bakar lalu meledak saat tersulut kembali', 'Daya generator naik karena pembakaran lebih efisien', 'Level drum naik tanpa dampak', 'Coal mill menjadi lebih dingin'], consAns: 0,
      explain: 'Intensitas nyala meredup lalu padam dan tekanan ruang bakar turun, sementara bahan bakar tetap dikirim. Penyebabnya damper udara sekunder yang tertinggal tertutup setelah perawatan, sehingga pembakaran kekurangan udara. Polanya sama dengan nyala padam karena kegagalan teknis, sehingga burner management system yang menutup bahan bakar dan mewajibkan purge sebelum penyalaan ulang tetap diperlukan.' },
    { id: 'e8', start: 12,
      hf: { type: 'violation', team: 'ops', threat: 2, title: 'Suhu keluar mill dinaikkan melampaui batas SOP demi mengejar beban', factor: 'Suhu mill sengaja melampaui SOP demi beban',
        roles: { raka: 'Operator Panel Unit', dimas: 'Operator Boiler Berlisensi' },
        lesson: 'Raka tahu batas suhu keluar mill dalam SOP adalah 80 °C dan sudah diingatkan, tetapi sengaja melampauinya agar beban tidak turun. Penyimpangan yang disengaja dari aturan yang diketahui tergolong violation, dalam hal ini violation situasional akibat tekanan produksi. Batu bara basah memang menyulitkan operasi, tetapi jalan keluarnya adalah menurunkan beban atau mengelola stockpile, bukan menghapus margin keselamatan. Pencegahnya adalah batas operasi yang dikunci di sistem kendali, dukungan manajemen untuk menurunkan beban demi keselamatan, dan trip suhu tinggi-tinggi yang independen.',
        controls: ['Batas suhu keluar mill dikunci di sistem kendali', 'Dukungan manajemen untuk menurunkan beban demi keselamatan', 'Trip suhu tinggi-tinggi independen yang menutup damper udara panas'] },
      chat: [
        { t: 1, who: 'hendra', at: 'CR-500', text: 'Batu bara di stockpile basah sekali karena hujan semalam. Mill sering tersumbat, padahal beban harus tetap 30 MW.' },
        { t: 4, who: 'raka', at: 'CR-500', text: 'Suhu keluar mill kunaikkan ke 95 derajat saja, Pak, biar batu baranya cepat kering.' },
        { t: 7, who: 'dimas', at: 'ML-501', mood: 'ragu', text: 'Batas di SOP 80 derajat. Di atas 90 derajat serbuk batu bara mudah membara di dalam mill.' },
        { t: 10, who: 'raka', at: 'CR-500', mood: 'santai', text: 'Sekali ini saja, daripada mill tersumbat dan beban turun. Set point sudah kuubah, nanti kuturunkan lagi.' },
        { t: 25, who: 'raka', at: 'CR-500', mood: 'ragu', text: 'Suhu keluar mill sudah lewat 95 derajat dan masih naik.' },
        { t: 28, who: 'dimas', at: 'ML-501', mood: 'panik', text: 'Casing mill terasa panas dari jarak dua meter. Raka, turunkan set point sekarang!' },
        { t: 31, who: 'raka', at: 'CR-500', mood: 'panik', text: 'Ada asap dari seal mill! Damper udara panas kututup, semua menjauh dari mill!' },
      ],
      effects: [{ var: 'TML', to: 150, delay: 2, dur: 18 }],
      warnings: [
        { t: 12, type: 'heat', sev: 'warn', at: 'ML-501', text: 'Casing coal mill ML-501 sangat panas dan catnya mulai mengelupas.' },
        { t: 17, type: 'smoke', sev: 'crit', at: 'ML-501', pos: [95, 262], text: 'Asap keluar dari seal coal mill dan pipa batu bara. Tercium bau batu bara terbakar.' },
        { t: 24, type: 'explosion', sev: 'final', at: 'ML-501', pos: [100, 290], text: 'Debu batu bara di dalam mill tersulut dan meledak. Pipa batu bara terlempar dan api menyambar ke area bunker.' },
      ],
      answer: { node: ['ML-501'], param: ['T'], guide: ['high'] },
      hint: 'Suhu keluar mill naik bertahap tanpa kerusakan peralatan, tepat setelah ada keputusan untuk mengatasi batu bara basah. Baca kembali obrolan tentang set point dan batas SOP.',
      causes: ['Operator sengaja menaikkan set point suhu keluar mill melampaui batas SOP agar batu bara basah cepat kering dan beban tidak turun', 'Pasokan batu bara ke mill terhenti sehingga udara panas tidak terserap', 'Logam asing masuk ke mill dan memercikkan api', 'Analyzer CO mill menyimpang sehingga pembaraan tidak terdeteksi'], causeAns: 0,
      cons: ['Batu bara di dalam mill membara dan terbakar, lalu debu batu bara meledak dan api merambat ke bunker', 'Batu bara menjadi kering dan beban naik tanpa dampak keselamatan', 'Level drum naik karena uap bertambah', 'Pompa air umpan kavitasi'], consAns: 0,
      explain: 'Suhu keluar mill naik mengikuti set point yang dinaikkan, lalu terus naik melewatinya karena serbuk batu bara mulai membara, tanpa gangguan pada sisi air dan uap. Di atas sekitar 90 °C, serbuk batu bara di dalam mill mudah membara dan dapat meledak bersama debu. Batas SOP 80 °C adalah margin terhadap kondisi tersebut. Trip suhu tinggi-tinggi yang menutup damper udara panas, analyzer CO, dan sistem inerting tetap diperlukan karena batas operasi dapat dilanggar.' },
  ],
  variants: [
    ['e3', 'e4', 'e5', 'e6', 'e7'],
    ['e1', 'e6', 'e7', 'e4', 'e8'],
    ['e2', 'e4', 'e5', 'e6', 'e8'],
    ['e4', 'e2', 'e8', 'e1', 'e5'],
    ['e6', 'e2', 'e8', 'e3', 'e5'],
  ],
  hotspots: [
    /* Tahap 3: pencegahan */
    { id: 'h31', stage: 3, x: 282, y: 92, label: 'Nozzle level drum D-501', accept: ['LWCO'],
      why: 'Low water cut-off men-trip pembakaran sebelum pipa dinding air kekurangan air. Alarm level saja tidak cukup karena bergantung pada respons operator, sementara ketel kehilangan air dalam hitungan menit.' },
    { id: 'h32', stage: 3, x: 352, y: 50, label: 'Puncak drum D-501 (katup pengaman)', accept: ['PSV'],
      why: 'Katup pengaman pada drum adalah perlengkapan wajib ketel uap dan lapisan proteksi terakhir terhadap tekanan berlebih.' },
    { id: 'h33', stage: 3, x: 500, y: 30, label: 'Jalur uap utama (tekanan)', accept: ['SIS', 'PT'],
      why: 'SIF tekanan tinggi yang men-trip pembakaran menghentikan sumber panas sebelum katup pengaman membuka. Alarm tekanan diterima sebagai lapisan respons operator.' },
    { id: 'h34', stage: 3, x: 218, y: 350, label: 'Burner BRN-501 (pengaman pembakaran)', accept: ['BMS'],
      why: 'Burner management system dengan flame scanner menutup bahan bakar saat nyala padam dan mewajibkan purge sebelum penyalaan ulang, sehingga bahan bakar tidak menumpuk di ruang bakar (NFPA 85).' },
    { id: 'h35', stage: 3, x: 150, y: 300, label: 'Outlet coal mill (suhu)', accept: ['TSHH', 'TT'],
      why: 'Trip suhu tinggi-tinggi menutup damper udara panas dan membuka udara dingin sebelum batu bara di dalam mill membara. Alarm TT diterima sebagai lapisan operator.' },
    { id: 'h36', stage: 3, x: 50, y: 262, label: 'Outlet coal mill (CO)', accept: ['COD'],
      why: 'Kenaikan CO menandakan batu bara mulai membara jauh sebelum api terlihat, sehingga operator sempat melakukan inerting atau mengosongkan mill.' },
    { id: 'h37', stage: 3, x: 650, y: 300, label: 'Discharge pompa air umpan P-501', accept: ['NRV'],
      why: 'Check valve mencegah air ketel bertekanan tinggi mengalir balik ke pompa saat pompa berhenti.' },
    { id: 'h38', stage: 3, x: 165, y: 36, label: 'Konveyor batu bara ke bunker', accept: ['MAG'],
      why: 'Pemisah magnet menangkap logam asing sebelum masuk ke bunker dan mill, mencegah percikan api di dalam mill.' },
    { id: 'h39', stage: 3, x: 806, y: 182, label: 'Generator GEN-501 (sisi listrik)', accept: [],
      why: 'Proteksi generator penting, tetapi tidak memutus ancaman proses boiler yang teridentifikasi pada skenario ini.' },
    /* Tahap 4: mitigasi */
    { id: 'h41', stage: 4, x: 50, y: 335, label: 'Coal mill (inerting)', accept: ['INERT'],
      why: 'Injeksi uap atau CO2 menurunkan kadar oksigen di dalam mill saat pembaraan terdeteksi, mencegah kebakaran berkembang menjadi ledakan debu.' },
    { id: 'h42', stage: 4, x: 182, y: 130, label: 'Bunker dan konveyor (deteksi api)', accept: ['FD'],
      why: 'Detektor api atau panas linear pada area konveyor dan bunker mempercepat aktivasi pemadaman.' },
    { id: 'h43', stage: 4, x: 210, y: 64, label: 'Konveyor batu bara (pemadaman)', accept: ['DELUGE', 'FW'],
      why: 'Sabuk konveyor yang terbakar dapat merambatkan api sepanjang jalur batu bara. Deluge atau hidran membatasi penjalaran api.' },
    { id: 'h44', stage: 4, x: 748, y: 440, label: 'Ruang kendali (master fuel trip dan ESD)', accept: ['ESD'],
      why: 'Tombol darurat menghentikan seluruh bahan bakar, mill, dan kipas secara serentak dari lokasi aman.' },
    { id: 'h45', stage: 4, x: 218, y: 528, label: 'Tangki solar penyalaan (tanggul)', accept: ['DIKE'],
      why: 'Tanggul menampung tumpahan solar sehingga kebakaran genangan tidak meluas ke area boiler.' },
    { id: 'h46', stage: 4, x: 718, y: 150, label: 'Tangki oli pelumas turbin (water spray)', accept: ['DELUGE'],
      why: 'Kebakaran oli pelumas di area turbin dapat merusak turbin dan bangunan. Water spray otomatis direkomendasikan NFPA 850.' },
    { id: 'h47', stage: 4, x: 950, y: 480, label: 'Titik kumpul dan alarm umum', accept: ['ALARM'],
      why: 'Uap bertekanan tinggi dan ledakan dapat melukai banyak orang; alarm dan evakuasi terencana adalah lapisan terakhir.' },
    { id: 'h48', stage: 4, x: 232, y: 455, label: 'Area burner dan ruang bakar (hidran)', accept: ['FW'],
      why: 'Hidran dan monitor air dipakai tim tanggap darurat untuk memadamkan kebakaran bahan bakar di sekitar burner dan mendinginkan peralatan.' },
    { id: 'h49', stage: 4, x: 452, y: 50, label: 'Drum uap D-501 (sistem busa)', accept: [],
      why: 'Busa dipakai untuk kebakaran cairan mudah terbakar. Pelepasan uap dari drum bukan kebakaran dan tidak dimitigasi dengan busa.' },
  ],
  inspect: [
    { id: 'FUR-501', itpm: 'KETEL', why: 'Ketel uap wajib diperiksa dan diuji secara berkala oleh ahli K3 pesawat uap (Undang-Undang Uap 1930). Pengukuran ketebalan pipa dinding air mendeteksi penipisan akibat erosi dan korosi sebelum pipa pecah.' },
    { id: 'P-501', itpm: 'ROT', why: 'Pompa air umpan adalah satu-satunya sumber air ketel. Pemantauan getaran mengurangi peluang pompa trip mendadak.' },
    { id: 'ML-501', itpm: 'ROT', why: 'Pemantauan getaran dan suhu bantalan mill mendeteksi kerusakan mekanis yang dapat menimbulkan panas dan percikan.' },
  ],
  budget: { 3: 33, 4: 30 },
  bowtie: {
    top: 'Kehilangan kendali energi pada boiler PLTU (pecahnya pipa atau drum, ledakan ruang bakar atau mill)',
    threats: ['Air umpan hilang, level drum rendah', 'Nyala padam dengan bahan bakar tetap masuk', 'Coal mill kepanasan', 'Turbin trip, tekanan drum naik'],
    cons: ['Pipa boiler pecah, semburan uap panas', 'Ledakan ruang bakar', 'Kebakaran dan ledakan coal mill', 'Drum uap pecah'],
  },
};
SCENARIOS.push(SCN_BOILER);
