/* Skenario sektor Ketenagalistrikan: dimuat setelah js/data.js dan menambahkan diri ke SCENARIOS. */
/* =====================================================================
   KETENAGALISTRIKAN: Trafo Daya Gardu Induk 150/20 kV
   ===================================================================== */
const SCN_TRAFO = {
  id: 'trafo',
  title: 'Trafo Daya Gardu Induk 150/20 kV',
  subtitle: 'Trafo terendam minyak, pendingin ONAF, konservator, kubikel 20 kV',
  level: 'Menengah',
  sector: 'listrik',
  area: 'Transmisi & Distribusi (Gardu Induk)',
  color: '#1f6fa8',
  kits: ['trafo'],
  op: 'Operasi Gardu Induk',
  overview: [
    'Gardu induk ini menurunkan tegangan transmisi 150 kV menjadi 20 kV untuk penyulang distribusi. Daya masuk melalui saluran transmisi dan pemutus tenaga (PMT) 150 kV ke dua trafo daya, yaitu TR-601 berkapasitas 60 MVA yang sedang dibebani dan TR-602 di sebelahnya.',
    'TR-601 adalah trafo terendam minyak dengan sekitar 30.000 liter minyak isolasi. Minyak mengisolasi belitan sekaligus membawa panas ke radiator yang ditiup kipas FN-601 (pendinginan ONAF). Konservator di atas tangki menampung pemuaian minyak. Suhu minyak, suhu belitan, level konservator, dan gas terlarut dipantau secara daring melalui SCADA.',
    'Sisi 20 kV trafo terhubung ke kubikel switchgear SWG-602 di dalam gedung, lalu ke penyulang pelanggan. Bahaya utama gardu induk adalah busur listrik dan kebakaran minyak trafo. Satu kebakaran trafo dapat memadamkan listrik ribuan pelanggan dan merambat ke peralatan di sekitarnya.',
  ],
  production: { label: 'Energi tersalurkan', unit: 'MWh', var: 'LD6', k: 0.009, dec: 1 },
  fluidNames: { power: 'Konduktor dan kabel daya' },
  zones: [
    { x: 300, y: 418, w: 270, h: 122, label: 'Gedung Switchgear 20 kV', labelPos: 'bottom' },
  ],
  equipment: [
    { id: 'LINE-601', type: 'sink', x: 150, y: 90, dir: 'left', name: 'Saluran Transmisi 150 kV',
      desc: 'Saluran udara tegangan tinggi yang memasok gardu induk dari jaringan transmisi.' },
    { id: 'PMT-601', type: 'panel', sub: 'PMT', x: 190, y: 62, w: 50, h: 56, name: 'PMT 150 kV',
      desc: 'Pemutus tenaga berisolasi gas SF6 yang memutus arus beban dan arus gangguan di sisi 150 kV atas perintah relai proteksi.' },
    { id: 'TR-601', type: 'transformer', x: 330, y: 200, w: 140, h: 110, name: 'Trafo Daya TR-601 60 MVA',
      desc: 'Trafo 150/20 kV terendam minyak dengan pendinginan ONAN/ONAF. Pada beban normal, suhu minyak atas sekitar 62 °C dan suhu titik terpanas belitan sekitar 78 °C. Konservator berada di atas tangki dan terhubung melalui pipa.',
      vars: ['TO', 'TW', 'GAS', 'LO', 'LD6'] },
    { id: 'TR-602', type: 'transformer', x: 620, y: 200, w: 110, h: 100, name: 'Trafo Daya TR-602',
      desc: 'Trafo kedua di sebelah TR-601 yang menjadi cadangan saat pemeliharaan. Kebakaran pada TR-601 dapat merambat ke trafo ini bila tidak ada pemisah.' },
    { id: 'FN-601', type: 'fan', x: 285, y: 345, name: 'Kipas Pendingin Radiator',
      desc: 'Kelompok kipas yang meniup radiator TR-601 saat suhu naik. Suplai listrik kipas berasal dari panel bantu gardu melalui MCB.' },
    { id: 'SWG-602', type: 'panel', x: 330, y: 448, w: 210, h: 60, name: 'Kubikel Switchgear 20 kV',
      desc: 'Deretan kubikel berisi PMT, relai, dan busbar 20 kV di dalam gedung. Busur listrik di dalam kubikel dapat menimbulkan ledakan busur (arc flash) yang sangat berbahaya bagi operator.', vars: ['IF', 'TSW'] },
    { id: 'FDR-603', type: 'sink', x: 848, y: 478, dir: 'right', name: 'Penyulang 20 kV ke Pelanggan',
      desc: 'Penyulang distribusi yang memasok kawasan permukiman dan industri.' },
    { id: 'CR-600', type: 'building', x: 120, y: 480, name: 'Gedung Kontrol',
      desc: 'Ruang operator, panel proteksi, dan sistem SCADA gardu induk.' },
    { id: 'MP-600', type: 'muster', x: 900, y: 320, name: 'Titik Kumpul',
      desc: 'Area berkumpul evakuasi di luar switchyard.' },
  ],
  pipes: [
    { id: 'pw1', fluid: 'power', w: 5, pts: [[150, 90], [190, 90]], arrow: true },
    { id: 'bus', fluid: 'power', w: 5, pts: [[240, 90], [652, 90]] },
    { id: 'pw3', fluid: 'power', w: 4, pts: [[371, 90], [371, 166]] },
    { id: 'pw4', fluid: 'power', w: 4, pts: [[652, 90], [652, 166]] },
    { id: 'lv1', fluid: 'power', w: 5, pts: [[400, 310], [400, 448]] },
    { id: 'lv2', fluid: 'power', w: 5, pts: [[675, 300], [675, 400], [500, 400], [500, 448]] },
    { id: 'fdr', fluid: 'power', w: 5, pts: [[540, 478], [848, 478]], arrow: true },
  ],
  labels: [
    { x: 445, y: 80, text: 'Busbar 150 kV', size: 10 },
  ],
  vars: {
    TO:  { label: 'Suhu Minyak Atas TR-601', unit: '°C', normal: 62, min: 20, max: 140, hi: 85, hihi: 95, node: 'TR-601', x: 545, y: 212, tau: 6, noise: 0.15, dec: 1 },
    TW:  { label: 'Suhu Titik Terpanas Belitan', unit: '°C', normal: 78, min: 20, max: 180, hi: 105, hihi: 120, node: 'TR-601', x: 545, y: 240, tau: 5, noise: 0.2, dec: 1 },
    GAS: { label: 'Gas Terlarut dalam Minyak (TDCG)', unit: 'ppm', normal: 350, min: 0, max: 6000, hi: 720, hihi: 1920, node: 'TR-601', x: 545, y: 268, tau: 3, noise: 4, dec: 0 },
    LO:  { label: 'Level Minyak Konservator', unit: '%', normal: 60, min: 0, max: 100, lo: 30, lolo: 15, node: 'TR-601', x: 446, y: 128, tau: 4, noise: 0.2, dec: 0 },
    LD6: { label: 'Beban TR-601', unit: '%', normal: 65, min: 0, max: 140, hi: 105, hihi: 120, node: 'TR-601', x: 465, y: 362, tau: 2, noise: 0.3, dec: 0 },
    IF:  { label: 'Arus Penyulang 20 kV', unit: 'A', normal: 1200, min: 0, max: 12000, hi: 1800, hihi: 2400, node: 'SWG-602', x: 700, y: 455, tau: 0.8, noise: 6, dec: 0 },
    TSW: { label: 'Suhu Ruang Switchgear', unit: '°C', normal: 30, min: 15, max: 90, hi: 40, hihi: 50, node: 'SWG-602', x: 620, y: 512, tau: 4, noise: 0.1, dec: 1 },
  },
  trendVars: ['TW', 'GAS', 'LO', 'IF'],
  controls: [
    { id: 'load', label: 'Beban gardu', unit: '%', min: 30, max: 100, def: 65, step: 5,
      effects: [{ var: 'LD6', gain: 1 }, { var: 'TO', gain: 0.4 }, { var: 'TW', gain: 0.7 }, { var: 'IF', gain: 18 }] },
    { id: 'amb', label: 'Suhu lingkungan', unit: '°C', min: 24, max: 40, def: 32, step: 1,
      effects: [{ var: 'TO', gain: 1 }, { var: 'TW', gain: 1 }, { var: 'TSW', gain: 0.5 }] },
    { id: 'fan', label: 'Jumlah kipas pendingin aktif', unit: 'unit', min: 0, max: 8, def: 4, step: 1,
      effects: [{ var: 'TO', gain: -1.5 }, { var: 'TW', gain: -2 }] },
  ],
  quiz: [
    { q: 'Apa dua fungsi utama minyak di dalam trafo daya?', opts: ['Pelumas tap changer dan bahan bakar cadangan', 'Isolasi listrik dan media pendingin yang membawa panas belitan ke radiator', 'Pencegah karat dan peredam suara', 'Penambah kapasitas daya trafo'], ans: 1,
      why: 'Minyak mineral mengisi celah di antara belitan sebagai isolasi dan bersirkulasi membawa panas ke radiator. Kehilangan minyak berarti kehilangan isolasi sekaligus pendinginan.' },
    { q: 'Mengapa suhu titik terpanas belitan sangat penting dipantau?', opts: ['Karena menentukan warna minyak', 'Karena laju penuaan isolasi kertas naik sangat cepat saat suhu titik terpanas melampaui batas', 'Karena mempengaruhi tegangan transmisi 150 kV', 'Karena hanya menentukan kecepatan kipas'], ans: 1,
      why: 'Menurut IEC 60076-7, laju penuaan isolasi kertas kira-kira berlipat dua setiap kenaikan sekitar 6 °C di atas suhu acuan. Panas berlebih yang dibiarkan memperpendek umur trafo dan memicu kegagalan isolasi.' },
    { q: 'Apa yang dideteksi relai Buchholz?', opts: ['Arus beban penyulang', 'Gas hasil penguraian minyak, aliran minyak mendadak, atau minyak yang hilang pada pipa antara tangki dan konservator', 'Suhu lingkungan gardu', 'Tegangan sisi 150 kV'], ans: 1,
      why: 'Relai Buchholz adalah proteksi mekanis khas trafo terendam minyak dengan konservator. Kontak pertama memberi alarm, kontak kedua men-trip trafo.' },
    { q: 'Mengapa hubung singkat harus diputus dalam hitungan milidetik?', opts: ['Agar meteran listrik tetap akurat', 'Karena energi busur listrik bertambah seiring lamanya gangguan; semakin lama, semakin besar ledakan busur dan kebakaran', 'Agar trafo lebih dingin', 'Agar minyak tidak berubah warna'], ans: 1,
      why: 'Energi insiden arc flash sebanding dengan arus gangguan dan waktu pemutusan. Koordinasi relai, breaker failure, dan proteksi busur listrik membatasi energi tersebut.' },
    { q: 'Mengapa trafo yang berdekatan perlu dipisahkan dinding tahan api atau jarak aman?', opts: ['Agar lebih mudah dicat', 'Agar kebakaran minyak pada satu trafo tidak merambat ke trafo lain sehingga pemadaman tidak meluas', 'Agar dengung trafo berkurang', 'Agar beban terbagi rata'], ans: 1,
      why: 'NFPA 850 merekomendasikan dinding tahan api atau jarak pemisah untuk trafo terendam minyak, ditambah bak penampung minyak agar genangan api tidak meluas.' },
  ],
  events: [
    { id: 'e1', effects: [{ var: 'TW', to: 150, delay: 2, dur: 20 }, { var: 'TO', to: 112, delay: 3, dur: 20 }],
      warnings: [
        { t: 12, type: 'heat', sev: 'warn', at: 'TR-601', text: 'Radiator TR-601 sangat panas dan kipas pendingin FN-601 tidak berputar.' },
        { t: 19, type: 'smoke', sev: 'crit', at: 'TR-601', pos: [400, 178], text: 'Bau minyak trafo hangus; asap tipis keluar dari pernapasan silika gel konservator.' },
        { t: 27, type: 'fire', sev: 'final', at: 'TR-601', pos: [400, 236], text: 'KEBAKARAN TRAFO: isolasi belitan rusak, terjadi busur listrik internal dan minyak trafo terbakar.' },
      ],
      answer: { node: ['TR-601', 'FN-601'], param: ['T'], guide: ['high'] },
      hint: 'Beban trafo tidak berubah, tetapi panas tidak terbuang. Periksa sistem pendingin radiator.',
      causes: ['Kipas pendingin FN-601 berhenti karena MCB suplai kipas trip, sementara beban tetap tinggi', 'Tap changer berpindah posisi', 'Penyulang 20 kV dilepas', 'Suhu lingkungan turun'], causeAns: 0,
      cons: ['Isolasi kertas belitan menua cepat dan rusak, terjadi busur listrik internal dan kebakaran minyak trafo', 'Beban penyulang naik', 'Level minyak konservator naik tanpa dampak', 'Tegangan 20 kV naik sedikit'], consAns: 0,
      explain: 'Suhu titik terpanas belitan naik terus sementara beban tetap, sehingga yang berubah adalah pendinginan, bukan beban. Menurut IEC 60076-7, laju penuaan isolasi kertas kira-kira berlipat dua setiap kenaikan sekitar 6 °C di atas suhu acuan. Proteksi yang tepat adalah indikator suhu belitan dengan alarm dan trip, didukung pemeliharaan kipas dan termografi.' },
    { id: 'e2', effects: [{ var: 'GAS', to: 4800, delay: 1, dur: 14 }],
      warnings: [
        { t: 8, type: 'vibration', sev: 'warn', at: 'TR-601', text: 'Dengung TR-601 berubah dan terdengar letupan kecil dari dalam tangki.' },
        { t: 14, type: 'arc', sev: 'crit', at: 'TR-601', pos: [400, 178], text: 'BUSUR LISTRIK di dalam tangki: minyak menyembur dari pernapasan konservator dan celah tutup tangki.' },
        { t: 21, type: 'explosion', sev: 'final', at: 'TR-601', pos: [400, 240], text: 'LEDAKAN TANGKI TR-601 akibat busur listrik internal; minyak terbakar menyembur ke sekeliling switchyard.' },
      ],
      answer: { node: ['TR-601'], param: ['C', 'E'], guide: ['high', 'other'] },
      hint: 'Gas terlarut dalam minyak naik cepat. Minyak sedang terurai oleh panas berlebih atau busur listrik di dalam tangki.',
      causes: ['Kegagalan isolasi di dalam trafo menimbulkan busur listrik yang menguraikan minyak menjadi gas', 'Beban penyulang turun', 'Suhu lingkungan naik', 'Kipas pendingin terlalu cepat'], causeAns: 0,
      cons: ['Tekanan gas di dalam tangki naik mendadak, tangki robek atau meledak, dan minyak terbakar', 'Level konservator turun tanpa dampak', 'Arus penyulang naik sedikit', 'Trafo menjadi lebih dingin'], consAns: 0,
      explain: 'Kenaikan cepat gas terlarut, terutama asetilena dan hidrogen, menandakan busur listrik atau panas berlebih di dalam minyak (IEEE C57.104). Gangguan internal harus diputus dalam puluhan milidetik oleh relai diferensial dan relai Buchholz, dengan pressure relief device sebagai pelepas tekanan.' },
    { id: 'e3', effects: [{ var: 'IF', to: 9500, delay: 1, dur: 2 }, { var: 'TSW', to: 72, delay: 3, dur: 10 }],
      warnings: [
        { t: 3, type: 'arc', sev: 'crit', at: 'SWG-602', pos: [435, 462], text: 'Busur listrik di kubikel penyulang 20 kV disertai dentuman dan kilatan cahaya; PMT penyulang tidak membuka.' },
        { t: 9, type: 'smoke', sev: 'crit', at: 'SWG-602', pos: [470, 440], text: 'Asap tebal memenuhi gedung switchgear; arus gangguan tetap mengalir.' },
        { t: 16, type: 'fire', sev: 'final', at: 'SWG-602', pos: [435, 462], text: 'KEBAKARAN GEDUNG SWITCHGEAR: busur listrik berkelanjutan membakar kubikel 20 kV dan kabel.' },
      ],
      answer: { node: ['SWG-602'], param: ['E', 'F'], guide: ['high'] },
      hint: 'Arus penyulang melonjak berlipat-lipat dan tidak kembali normal. Gangguan hubung singkat tidak diputus.',
      causes: ['Hubung singkat pada penyulang 20 kV tidak diputus karena relai atau PMT penyulang gagal bekerja', 'Kipas pendingin trafo mati', 'Minyak konservator berkurang', 'Suhu lingkungan naik'], causeAns: 0,
      cons: ['Busur listrik berkelanjutan di kubikel 20 kV menyebabkan ledakan busur, kebakaran gedung switchgear, dan pemadaman luas', 'Trafo menjadi lebih dingin', 'Gas terlarut turun', 'Level minyak naik'], consAns: 0,
      explain: 'Arus penyulang melonjak lebih dari tujuh kali normal dan bertahan, tanda hubung singkat yang tidak diputus. Koordinasi proteksi mensyaratkan relai arus lebih dan breaker failure yang memutus gangguan secara bertingkat, serta proteksi busur listrik yang memutus dalam hitungan milidetik untuk membatasi energi arc flash. Dalam HAZOP listrik, deviasi ini dibaca sebagai arus lebih tinggi.' },
    { id: 'e4', effects: [{ var: 'LO', to: 4, delay: 2, dur: 20 }],
      warnings: [
        { t: 12, type: 'spill', sev: 'warn', at: 'TR-601', pos: [400, 330], text: 'Rembesan minyak trafo di dasar radiator; genangan minyak terbentuk di bawah TR-601.' },
        { t: 19, type: 'arc', sev: 'crit', at: 'TR-601', pos: [400, 178], text: 'Bunyi letupan dari dalam TR-601; level minyak di konservator tidak terlihat lagi.' },
        { t: 26, type: 'fire', sev: 'final', at: 'TR-601', pos: [400, 240], text: 'KEBAKARAN TRAFO: belitan yang tidak lagi terendam minyak mengalami flashover dan minyak yang tumpah ikut terbakar.' },
      ],
      answer: { node: ['TR-601'], param: ['L'], guide: ['low'] },
      hint: 'Level minyak di konservator turun terus. Minyak keluar dari tangki melalui titik bocor.',
      causes: ['Gasket radiator atau katup drain bocor sehingga minyak trafo keluar sedikit demi sedikit', 'Beban trafo turun', 'Kipas pendingin bekerja terus', 'Arus penyulang naik'], causeAns: 0,
      cons: ['Bagian aktif trafo tidak lagi terendam minyak, isolasi gagal, terjadi flashover dan kebakaran minyak', 'Suhu minyak turun', 'Gas terlarut turun', 'Tegangan naik tanpa dampak'], consAns: 0,
      explain: 'Level minyak konservator turun perlahan tanpa perubahan beban atau suhu. Minyak trafo berfungsi sebagai isolasi sekaligus pendingin. Relai Buchholz mendeteksi minyak yang hilang dan men-trip trafo, sementara alarm level konservator memberi peringatan lebih awal kepada operator.' },
  ],
  hotspots: [
    /* Tahap 3: pencegahan */
    { id: 'h31', stage: 3, x: 416, y: 186, label: 'Pipa tangki ke konservator (relai)', accept: ['BUCH'],
      why: 'Relai Buchholz pada pipa konservator mendeteksi gas hasil penguraian minyak dan minyak yang hilang, lalu memberi alarm dan men-trip trafo.' },
    { id: 'h32', stage: 3, x: 300, y: 140, label: 'Panel proteksi trafo (CT sisi 150 dan 20 kV)', accept: ['DIFR'],
      why: 'Relai diferensial memutus kedua sisi trafo dalam puluhan milidetik saat terjadi gangguan internal, sebelum busur listrik menguraikan minyak dalam jumlah besar.' },
    { id: 'h33', stage: 3, x: 482, y: 192, label: 'Tutup tangki TR-601 (pelepas tekanan)', accept: ['PRD'],
      why: 'Pressure relief device melepas tekanan mendadak akibat busur listrik internal sehingga tangki tidak robek.' },
    { id: 'h34', stage: 3, x: 316, y: 192, label: 'Kantong termometer belitan TR-601', accept: ['WTI', 'TT'],
      why: 'Indikator suhu belitan menyalakan kipas bertahap, memberi alarm, dan men-trip trafo saat panas berlebih. Alarm suhu biasa diterima sebagai lapisan respons operator.' },
    { id: 'h35', stage: 3, x: 500, y: 150, label: 'Konservator (indikator level minyak)', accept: ['LT'],
      why: 'Alarm level minyak rendah memberi peringatan dini kebocoran sebelum relai Buchholz harus men-trip trafo.' },
    { id: 'h36', stage: 3, x: 600, y: 478, label: 'PMT penyulang 20 kV (relai arus lebih)', accept: ['OCR'],
      why: 'Relai arus lebih dan gangguan tanah dengan fungsi breaker failure memutus hubung singkat penyulang secara bertingkat.' },
    { id: 'h37', stage: 3, x: 316, y: 478, label: 'Kubikel 20 kV (proteksi busur listrik)', accept: ['ARC'],
      why: 'Proteksi busur listrik mendeteksi kilatan cahaya dan arus gangguan, lalu memutus dalam hitungan milidetik untuk membatasi energi arc flash.' },
    { id: 'h38', stage: 3, x: 820, y: 150, label: 'Pagar switchyard', accept: [],
      why: 'Pagar dan rambu penting untuk keamanan, tetapi bukan barier terhadap ancaman yang teridentifikasi pada trafo dan kubikel.' },
    { id: 'h39', stage: 3, x: 175, y: 445, label: 'Gedung kontrol (lampu indikator)', accept: [],
      why: 'Lampu indikator di ruang kontrol bukan lapisan proteksi. Anggaran lebih baik dipakai untuk proteksi pada trafo dan kubikel.' },
    /* Tahap 4: mitigasi */
    { id: 'h41', stage: 4, x: 400, y: 345, label: 'Di bawah TR-601 (bak penampung minyak)', accept: ['OPIT'],
      why: 'Bak penampung dengan lapisan kerikil menampung seluruh minyak trafo dan memadamkan minyak menyala yang jatuh, sehingga genangan api tidak meluas.' },
    { id: 'h42', stage: 4, x: 545, y: 252, label: 'Antara TR-601 dan TR-602 (dinding tahan api)', accept: ['FWALL'],
      why: 'Dinding tahan api mencegah kebakaran TR-601 merambat ke TR-602 sehingga gardu tidak padam total (NFPA 850).' },
    { id: 'h43', stage: 4, x: 288, y: 250, label: 'Sekeliling TR-601 (water spray)', accept: ['DELUGE'],
      why: 'Water spray otomatis mendinginkan tangki dan memadamkan kebakaran minyak setelah trafo diputus dari sumber listrik (NFPA 15).' },
    { id: 'h44', stage: 4, x: 488, y: 302, label: 'Tangki TR-601 (sistem injeksi nitrogen)', accept: ['NIFPS'],
      why: 'NIFPS membuang sebagian minyak dan menginjeksikan nitrogen saat gangguan internal terdeteksi, mencegah tangki meledak dan terbakar.' },
    { id: 'h45', stage: 4, x: 525, y: 432, label: 'Gedung switchgear (detektor asap)', accept: ['SD'],
      why: 'Detektor asap memberi peringatan dini kebakaran kabel dan kubikel serta memicu sistem pemadam gas.' },
    { id: 'h46', stage: 4, x: 556, y: 520, label: 'Gedung switchgear (pemadam gas)', accept: ['GAS'],
      why: 'Pemadam gas bersih tidak menghantarkan listrik dan tidak merusak peralatan, cocok untuk ruang tertutup berisi kubikel.' },
    { id: 'h47', stage: 4, x: 238, y: 300, label: 'Area trafo (detektor api)', accept: ['FD'],
      why: 'Detektor api mempercepat aktivasi water spray dan pemberitahuan ke regu pemadam.' },
    { id: 'h48', stage: 4, x: 950, y: 320, label: 'Titik kumpul dan alarm umum', accept: ['ALARM'],
      why: 'Evakuasi terencana melindungi petugas dari ledakan tangki trafo dan asap kebakaran kabel.' },
    { id: 'h49', stage: 4, x: 478, y: 432, label: 'Kubikel 20 kV (sprinkler air)', accept: [],
      why: 'Menyemprotkan air pada kubikel yang masih bertegangan berisiko bagi petugas dan peralatan. Ruang switchgear lebih tepat dilindungi deteksi asap dan pemadam gas bersih.' },
  ],
  inspect: [
    { id: 'TR-601', itpm: 'ELEC', why: 'Uji DGA berkala mendeteksi panas berlebih dan busur listrik kecil sebelum menjadi gangguan besar, sementara termografi dan uji tahanan isolasi menilai kondisi trafo (IEEE C57.104).' },
    { id: 'FN-601', itpm: 'ROT', why: 'Kipas pendingin yang rusak tidak terlihat sampai trafo kepanasan saat beban puncak. Pemeliharaan prediktif menjaga kapasitas pendinginan.' },
    { id: 'SWG-602', itpm: 'ELEC', why: 'Termografi dan uji partial discharge pada kubikel mendeteksi sambungan panas dan isolasi yang menurun sebelum terjadi busur listrik.' },
  ],
  budget: { 3: 30, 4: 31 },
  bowtie: {
    top: 'Kegagalan isolasi dan busur listrik pada trafo daya atau kubikel 20 kV',
    threats: ['Kipas pendingin gagal, belitan kepanasan', 'Gangguan isolasi internal trafo', 'Hubung singkat penyulang tidak diputus', 'Kebocoran minyak trafo'],
    cons: ['Kebakaran minyak trafo', 'Ledakan tangki trafo', 'Kebakaran gedung switchgear', 'Flashover dan pemadaman luas'],
  },
};
SCENARIOS.push(SCN_TRAFO);
