/* Skenario sektor Manufaktur: dimuat setelah js/data.js dan menambahkan diri ke SCENARIOS. */
/* =====================================================================
   MANUFAKTUR: Lini Produksi Pakan Ternak (Debu Mudah Terbakar)
   ===================================================================== */
const SCN_DEBU = {
  id: 'debu',
  title: 'Lini Produksi Pakan Ternak',
  subtitle: 'Silo jagung, bucket elevator, hammer mill, dust collector (bahaya ledakan debu)',
  level: 'Menengah',
  sector: 'manufaktur',
  area: 'Industri Pangan dan Pakan',
  color: '#8a6d3b',
  kits: ['debu'],
  overview: [
    'Lini produksi ini mengolah jagung menjadi pakan ternak dengan kapasitas 20 ton/jam. Jagung dari silo SL-901 dibawa konveyor CV-901 ke bucket elevator BE-901 yang mengangkatnya ke hammer mill HM-901 untuk digiling. Hasil gilingan dikirim ke mixer dan pellet mill.',
    'Elevator dan mill menghasilkan debu halus yang disedot sistem aspirasi melalui ducting ke dust collector DC-901, lalu udara bersih dibuang kipas FN-901 melalui cerobong. Debu yang terkumpul di hopper dust collector dikembalikan ke aliran produk.',
    'Debu jagung dan tepung yang terdispersi di udara dapat meledak bila bertemu sumber nyala seperti gesekan sabuk, percikan logam, permukaan panas, atau listrik statis. Ledakan di dalam peralatan dapat mengangkat debu yang menumpuk di gedung dan memicu ledakan sekunder yang lebih besar.',
  ],
  production: { label: 'Pakan diproduksi', unit: 't', var: 'FPR', k: 1 / 60, dec: 1 },
  fluidNames: { bulk: 'Jagung dan hasil gilingan', air: 'Udara aspirasi berdebu' },
  zones: [
    { x: 200, y: 20, w: 320, h: 360, label: 'Gedung Produksi', labelPos: 'bottom' },
  ],
  equipment: [
    { id: 'SL-901', type: 'silo', x: 40, y: 60, w: 110, h: 200, name: 'Silo Jagung SL-901', level: 'LSL', levelFill: 'bulk',
      desc: 'Silo baja berkapasitas sekitar 2.000 ton. Jagung dengan kadar air di atas sekitar 14 persen yang tersimpan lama dapat memanas dengan sendirinya.', vars: ['LSL', 'TSL'] },
    { id: 'CV-901', type: 'conveyor', x: 95, y: 300, w: 135, h: 0, name: 'Konveyor Jagung CV-901',
      desc: 'Membawa jagung dari silo ke boot bucket elevator.' },
    { id: 'BE-901', type: 'elevator', x: 250, y: 70, w: 28, h: 250, name: 'Bucket Elevator BE-901',
      desc: 'Mengangkat jagung setinggi sekitar 30 meter dengan mangkuk pada sabuk. Sabuk yang selip atau bergeser akan bergesekan dengan pulley dan casing.', vars: ['SBE', 'TBR'] },
    { id: 'HM-901', type: 'mill', x: 400, y: 190, name: 'Hammer Mill HM-901',
      desc: 'Penggiling palu berputar sekitar 3.000 rpm dengan motor 200 kW. Logam asing atau umpan berlebih menimbulkan percikan dan panas gesekan.', vars: ['VHM', 'IHM', 'FPR'] },
    { id: 'DC-901', type: 'filter', x: 560, y: 60, w: 120, h: 180, name: 'Dust Collector DC-901',
      desc: 'Kolektor kantong (bag filter) yang menyaring debu dari udara aspirasi. Di dalamnya selalu terdapat awan debu halus yang mudah meledak.', vars: ['TDC', 'DPF'] },
    { id: 'FN-901', type: 'fan', x: 760, y: 90, name: 'Kipas Aspirasi FN-901',
      desc: 'Menyedot udara berdebu dari elevator dan mill melalui dust collector.' },
    { id: 'ST-901', type: 'stack', x: 830, y: 250, h: 190, name: 'Cerobong',
      desc: 'Membuang udara bersih dari dust collector ke atmosfer.' },
    { id: 'PM-901', type: 'sink', x: 848, y: 330, dir: 'right', name: 'Ke Mixer dan Pellet Mill',
      desc: 'Hasil gilingan diteruskan ke mixer, conditioner uap, dan pellet mill.' },
    { id: 'CR-900', type: 'building', x: 720, y: 460, name: 'Ruang Kontrol',
      desc: 'Operator memantau lini produksi dan sistem aspirasi.' },
    { id: 'MP-900', type: 'muster', x: 920, y: 470, name: 'Titik Kumpul',
      desc: 'Area berkumpul evakuasi di luar gedung produksi.' },
  ],
  pipes: [
    { id: 's1', fluid: 'bulk', w: 7, pts: [[95, 262], [95, 293]] },
    { id: 's2', fluid: 'bulk', w: 7, pts: [[288, 94], [400, 94], [400, 168]], arrow: true },
    { id: 's3', fluid: 'bulk', w: 7, pts: [[400, 222], [400, 330], [848, 330]], arrow: true },
    { id: 'd1', fluid: 'air', w: 6, pts: [[288, 66], [288, 36], [530, 36], [530, 100], [560, 100]], arrow: true },
    { id: 'd2', fluid: 'air', w: 6, pts: [[426, 182], [480, 182], [480, 130], [560, 130]], arrow: true },
    { id: 'd3', fluid: 'air', w: 6, pts: [[680, 90], [738, 90]] },
    { id: 'd4', fluid: 'air', w: 6, pts: [[794, 74], [820, 74]] },
    { id: 'd5', fluid: 'bulk', w: 5, pts: [[620, 244], [620, 330]] },
  ],
  labels: [
    { x: 397, y: 26, text: 'Ducting aspirasi', size: 10 },
  ],
  vars: {
    LSL: { label: 'Isi Silo Jagung', unit: '%', normal: 70, min: 0, max: 100, lo: 15, hi: 92, node: 'SL-901', x: 95, y: 36, tau: 6, noise: 0.1, dec: 0 },
    TSL: { label: 'Suhu Tumpukan Silo', unit: '°C', normal: 30, min: 15, max: 120, hi: 45, hihi: 55, node: 'SL-901', x: 192, y: 150, tau: 6, noise: 0.1, dec: 1 },
    SBE: { label: 'Kecepatan Sabuk Elevator', unit: '%', normal: 100, min: 0, max: 120, lo: 85, lolo: 70, node: 'BE-901', x: 330, y: 250, tau: 1.5, noise: 0.3, dec: 0 },
    TBR: { label: 'Suhu Bantalan Head Pulley', unit: '°C', normal: 45, min: 20, max: 200, hi: 70, hihi: 85, node: 'BE-901', x: 330, y: 125, tau: 4, noise: 0.2, dec: 0 },
    VHM: { label: 'Getaran Hammer Mill', unit: 'mm/s', normal: 3.0, min: 0, max: 20, hi: 7.1, hihi: 11.2, node: 'HM-901', x: 470, y: 222, tau: 1, noise: 0.1, dec: 1 },
    IHM: { label: 'Arus Motor Hammer Mill', unit: 'A', normal: 150, min: 0, max: 300, hi: 190, hihi: 220, node: 'HM-901', x: 470, y: 250, tau: 1.5, noise: 1, dec: 0 },
    TDC: { label: 'Suhu Masuk Dust Collector', unit: '°C', normal: 38, min: 15, max: 150, hi: 60, hihi: 75, node: 'DC-901', x: 730, y: 160, tau: 2, noise: 0.2, dec: 0 },
    DPF: { label: 'Beda Tekanan Dust Collector', unit: 'mmH2O', normal: 120, min: 0, max: 300, lo: 50, hi: 180, node: 'DC-901', x: 730, y: 188, tau: 3, noise: 0.8, dec: 0 },
    FPR: { label: 'Laju Produksi', unit: 't/j', normal: 20, min: 0, max: 40, lo: 8, node: 'HM-901', x: 700, y: 300, tau: 2, noise: 0.1, dec: 1 },
  },
  trendVars: ['SBE', 'VHM', 'TSL', 'IHM'],
  controls: [
    { id: 'feed', label: 'Laju umpan hammer mill', unit: 't/j', min: 10, max: 30, def: 20, step: 1,
      effects: [{ var: 'FPR', gain: 1 }, { var: 'IHM', gain: 3 }, { var: 'VHM', gain: 0.05 }] },
    { id: 'aspir', label: 'Bukaan damper aspirasi', unit: '%', min: 40, max: 100, def: 80, step: 5,
      effects: [{ var: 'DPF', gain: 1.2 }, { var: 'TDC', gain: -0.05 }] },
    { id: 'moist', label: 'Kadar air jagung masuk silo', unit: '%', min: 12, max: 18, def: 14, step: 0.5,
      effects: [{ var: 'TSL', gain: 1.5 }] },
  ],
  quiz: [
    { q: 'Lima unsur apa yang harus ada bersamaan agar ledakan debu terjadi (pentagon ledakan debu)?', opts: ['Air, panas, bahan, oksigen, dan tekanan', 'Debu mudah terbakar sebagai bahan bakar, oksigen, sumber nyala, dispersi debu menjadi awan, dan ruang terkurung', 'Listrik, gas, debu, air, dan logam', 'Suhu tinggi, kelembapan, angin, debu, dan cahaya'], ans: 1,
      why: 'Menghilangkan salah satu unsur pentagon mencegah ledakan. Itulah dasar pengendalian sumber nyala, aspirasi, kebersihan, inerting, dan venting (NFPA 652).' },
    { q: 'Mengapa ledakan sekunder sering lebih merusak daripada ledakan primer?', opts: ['Karena terjadi di luar gedung', 'Karena gelombang ledakan primer mengangkat debu yang menumpuk di lantai dan balok menjadi awan besar yang kemudian tersulut', 'Karena memakai bahan bakar gas', 'Karena terjadi lebih lambat'], ans: 1,
      why: 'Lapisan debu tipis di permukaan gedung sudah cukup untuk membentuk awan yang dapat meledak. Kebersihan (housekeeping) adalah barier yang sangat penting.' },
    { q: 'Apa fungsi pemisah magnet sebelum hammer mill?', opts: ['Mengeringkan jagung', 'Menangkap logam asing sebelum masuk mill sehingga tidak terjadi percikan api', 'Mengukur laju umpan', 'Mendinginkan mill'], ans: 1,
      why: 'Logam yang terhantam palu berputar menimbulkan percikan panas yang dapat terbawa ke ducting dan dust collector.' },
    { q: 'Mengapa jagung lembap yang disimpan lama di silo berbahaya?', opts: ['Karena menjadi lebih berat', 'Karena aktivitas mikroba dan oksidasi dapat memanaskan tumpukan hingga membara dan menghasilkan gas mudah terbakar', 'Karena hanya menyumbat konveyor', 'Karena warnanya berubah'], ans: 1,
      why: 'Pemanasan spontan berlangsung lambat dan tidak terlihat dari luar. Kabel suhu dan pemantauan CO memberi peringatan dini.' },
    { q: 'Apa fungsi panel venting ledakan pada dust collector?', opts: ['Membuang debu ke luar secara rutin', 'Membuka pada tekanan rendah saat ledakan sehingga tekanan dan bola api diarahkan ke area aman dan peralatan tidak pecah', 'Menambah aliran udara aspirasi', 'Mencegah debu masuk ke dust collector'], ans: 1,
      why: 'Venting tidak mencegah ledakan, tetapi membatasi tekanan di dalam peralatan. Area buangan vent harus aman dari orang (NFPA 68).' },
  ],
  events: [
    { id: 'e1', effects: [{ var: 'SBE', to: 62, delay: 1, dur: 6 }, { var: 'TBR', to: 140, delay: 3, dur: 18 }],
      warnings: [
        { t: 10, type: 'heat', sev: 'warn', at: 'BE-901', pos: [264, 80], text: 'Bau karet terbakar di sekitar kepala bucket elevator BE-901.' },
        { t: 17, type: 'smoke', sev: 'crit', at: 'BE-901', pos: [264, 70], text: 'Asap keluar dari casing elevator; debu di dalamnya mulai membara.' },
        { t: 24, type: 'explosion', sev: 'final', at: 'BE-901', pos: [270, 160], text: 'LEDAKAN DEBU di bucket elevator BE-901, disusul ledakan sekunder dari debu yang menumpuk di lantai dan balok gedung produksi.' },
      ],
      answer: { node: ['BE-901'], param: ['F', 'T'], guide: ['low', 'high'] },
      hint: 'Kecepatan sabuk turun dibanding pulley penggerak, tanda sabuk selip. Gesekan selip menghasilkan panas.',
      causes: ['Sabuk elevator selip atau bergeser karena kelebihan muatan atau tegangan sabuk kurang, sehingga bergesekan dengan pulley dan casing', 'Kadar air jagung terlalu tinggi', 'Damper aspirasi terlalu terbuka', 'Silo terlalu penuh'], causeAns: 0,
      cons: ['Gesekan memanaskan sabuk dan debu hingga menyala, lalu terjadi ledakan debu primer di elevator dan ledakan sekunder di gedung', 'Laju produksi naik', 'Suhu silo turun', 'Getaran mill turun'], consAns: 0,
      explain: 'Kecepatan sabuk turun lalu suhu bantalan head pulley naik. Bucket elevator tercatat sebagai lokasi ledakan primer yang paling sering pada fasilitas biji-bijian. Ledakan primer mengangkat debu yang menumpuk di gedung sehingga terjadi ledakan sekunder yang jauh lebih merusak, seperti pada bencana Imperial Sugar tahun 2008. Proteksi yang tepat adalah monitor kecepatan dan kelurusan sabuk yang menghentikan motor, sensor suhu bantalan, dan kebersihan gedung.' },
    { id: 'e2', effects: [{ var: 'VHM', to: 14, delay: 1, dur: 4 }, { var: 'TDC', to: 88, delay: 4, dur: 12 }],
      warnings: [
        { t: 6, type: 'vibration', sev: 'warn', at: 'HM-901', text: 'Suara benturan logam keras dari dalam hammer mill HM-901.' },
        { t: 12, type: 'heat', sev: 'crit', at: 'DC-901', pos: [600, 118], text: 'Percikan api terlihat di ducting aspirasi menuju dust collector; suhu masuk naik.' },
        { t: 19, type: 'explosion', sev: 'final', at: 'DC-901', pos: [620, 118], text: 'LEDAKAN di dust collector DC-901: kantong filter terbakar dan panel dinding terlempar.' },
      ],
      answer: { node: ['HM-901', 'DC-901'], param: ['C', 'T'], guide: ['other', 'high'] },
      hint: 'Getaran mill melonjak tiba-tiba disertai bunyi logam. Ada benda asing yang seharusnya tidak ikut masuk ke mesin.',
      causes: ['Logam asing seperti baut atau potongan besi ikut masuk ke hammer mill dan memercikkan api', 'Kadar air jagung tinggi', 'Sabuk elevator selip', 'Silo terlalu penuh'], causeAns: 0,
      cons: ['Percikan terbawa ke ducting dan menyulut debu di dust collector sehingga terjadi kebakaran dan ledakan', 'Laju produksi naik', 'Suhu silo naik tanpa dampak', 'Kecepatan elevator naik'], consAns: 0,
      explain: 'Getaran mill melonjak lalu suhu masuk dust collector naik. Ini pola percikan dari logam asing yang terbawa aliran aspirasi. Dust collector berisi awan debu halus sehingga sangat mudah meledak. Proteksi yang tepat adalah pemisah magnet sebelum mill dan deteksi percikan dengan pemadam otomatis di ducting (NFPA 61). Dalam HAZOP, kejadian ini dibaca sebagai komposisi umpan selain dari yang seharusnya.' },
    { id: 'e3', effects: [{ var: 'TSL', to: 80, delay: 2, dur: 20 }],
      warnings: [
        { t: 12, type: 'heat', sev: 'warn', at: 'SL-901', text: 'Bau hangus dan uap keluar dari ventilasi atap silo SL-901.' },
        { t: 19, type: 'smoke', sev: 'crit', at: 'SL-901', pos: [95, 66], text: 'Asap keluar dari atap silo; jagung di bagian tengah menggumpal dan menghitam.' },
        { t: 27, type: 'explosion', sev: 'final', at: 'SL-901', pos: [95, 140], text: 'LEDAKAN SILO SL-901 saat pengosongan: bara di dalam tumpukan menyulut debu dan gas pirolisis.' },
      ],
      answer: { node: ['SL-901'], param: ['T'], guide: ['high'] },
      hint: 'Suhu tumpukan naik tanpa sumber panas dari luar. Material di dalam silo memanas dengan sendirinya.',
      causes: ['Jagung lembap tersimpan terlalu lama sehingga aktivitas mikroba dan oksidasi memanaskan tumpukan (pemanasan spontan)', 'Hammer mill kemasukan logam', 'Sabuk elevator selip', 'Damper aspirasi tertutup'], causeAns: 0,
      cons: ['Tumpukan membara, terbentuk gas pirolisis dan debu, lalu meledak saat silo dikosongkan atau dibuka', 'Laju produksi naik', 'Getaran mill naik', 'Dust collector menjadi lebih bersih'], consAns: 0,
      explain: 'Suhu tumpukan naik perlahan tanpa perubahan pada peralatan lain. Pemanasan spontan biji-bijian lembap dapat berkembang menjadi pembaraan yang tidak terlihat dari luar. Proteksi yang tepat adalah kabel sensor suhu di dalam tumpukan, analyzer CO di ruang kepala silo, dan sistem inerting untuk memadamkan pembaraan dengan aman.' },
    { id: 'e4', effects: [{ var: 'IHM', to: 245, delay: 1, dur: 6 }, { var: 'VHM', to: 9, delay: 2, dur: 6 }],
      warnings: [
        { t: 8, type: 'vibration', sev: 'warn', at: 'HM-901', text: 'Hammer mill tersumbat; motor berdengung berat dan saringan penuh.' },
        { t: 14, type: 'smoke', sev: 'crit', at: 'HM-901', pos: [400, 168], text: 'Asap keluar dari saringan hammer mill; bahan di dalamnya mulai hangus.' },
        { t: 21, type: 'fire', sev: 'final', at: 'HM-901', pos: [400, 186], text: 'KEBAKARAN di dalam hammer mill merambat ke ducting aspirasi.' },
      ],
      answer: { node: ['HM-901'], param: ['F', 'E'], guide: ['high'] },
      hint: 'Arus motor mill naik tajam karena bahan yang masuk lebih banyak daripada yang dapat digiling.',
      causes: ['Umpan ke hammer mill berlebih atau saringan tersumbat sehingga mill tercekik (choke)', 'Jagung terlalu kering', 'Sabuk elevator selip', 'Silo hampir kosong'], causeAns: 0,
      cons: ['Gesekan berlebih memanaskan bahan hingga membara, lalu terjadi kebakaran mill yang merambat ke ducting', 'Suhu silo turun', 'Laju produksi naik dengan aman', 'Dust collector menjadi lebih bersih'], consAns: 0,
      explain: 'Arus motor mill melonjak lalu getaran naik. Mill yang tercekik menggiling bahan berulang-ulang sehingga panas gesekan menumpuk. Proteksi yang tepat adalah pembatas laju umpan berbasis arus motor dan relai beban lebih yang menghentikan motor.' },
  ],
  hotspots: [
    /* Tahap 3: pencegahan */
    { id: 'h31', stage: 3, x: 306, y: 165, label: 'Casing elevator (monitor sabuk)', accept: ['BAM'],
      why: 'Monitor kecepatan dan kelurusan sabuk menghentikan motor saat sabuk selip atau bergeser, sebelum gesekan menyulut debu (NFPA 61).' },
    { id: 'h32', stage: 3, x: 224, y: 84, label: 'Bantalan head pulley (suhu)', accept: ['TT'],
      why: 'Sensor suhu bantalan memberi peringatan dini kerusakan bantalan dan gesekan di kepala elevator.' },
    { id: 'h33', stage: 3, x: 350, y: 94, label: 'Spout sebelum hammer mill (magnet)', accept: ['MAG'],
      why: 'Pemisah magnet menangkap logam asing sebelum masuk mill sehingga tidak terjadi percikan.' },
    { id: 'h34', stage: 3, x: 515, y: 130, label: 'Ducting aspirasi mill (deteksi percikan)', accept: ['SDE'],
      why: 'Deteksi percikan dan pemadam otomatis memadamkan bara di dalam ducting sebelum mencapai dust collector.' },
    { id: 'h35', stage: 3, x: 70, y: 190, label: 'Dalam tumpukan silo (kabel suhu)', accept: ['TT', 'COD'],
      why: 'Kabel sensor suhu di dalam tumpukan mendeteksi pemanasan spontan. Analyzer CO juga diterima sebagai deteksi dini pembaraan.' },
    { id: 'h36', stage: 3, x: 130, y: 72, label: 'Ruang kepala silo (CO)', accept: ['COD', 'TT'],
      why: 'Kenaikan CO di ruang kepala silo menandakan pembaraan jauh sebelum asap terlihat.' },
    { id: 'h37', stage: 3, x: 350, y: 200, label: 'Feeder hammer mill (pembatas laju umpan)', accept: ['FT', 'OCR'],
      why: 'Pembatas laju umpan berbasis arus motor mencegah mill tercekik. Relai beban lebih yang menghentikan motor juga diterima.' },
    { id: 'h38', stage: 3, x: 700, y: 225, label: 'Dust collector (grounding)', accept: ['GRND'],
      why: 'Pentanahan rangka dan bonding kantong filter mencegah muatan statis menjadi sumber nyala di dalam dust collector (NFPA 652).' },
    { id: 'h39', stage: 3, x: 560, y: 330, label: 'Jalur produk ke pellet mill', accept: [],
      why: 'Jalur produk ini tidak terkait dengan skenario yang teridentifikasi. Anggaran lebih baik dipakai pada elevator, mill, silo, dan dust collector.' },
    /* Tahap 4: mitigasi */
    { id: 'h41', stage: 4, x: 590, y: 48, label: 'Dust collector (panel venting ledakan)', accept: ['DVENT'],
      why: 'Panel venting membatasi tekanan ledakan di dust collector dan mengarahkan bola api ke area aman di luar gedung (NFPA 68).' },
    { id: 'h42', stage: 4, x: 530, y: 72, label: 'Ducting masuk dust collector (isolasi ledakan)', accept: ['EISO'],
      why: 'Katup isolasi menutup ducting dalam hitungan milidetik sehingga ledakan tidak merambat ke gedung produksi (NFPA 69).' },
    { id: 'h43', stage: 4, x: 226, y: 210, label: 'Bucket elevator (venting atau supresi)', accept: ['DVENT', 'SUPP'],
      why: 'Elevator di dalam gedung dilindungi venting ke luar atau supresi kimia agar ledakan primer tidak memicu ledakan sekunder.' },
    { id: 'h44', stage: 4, x: 446, y: 200, label: 'Hammer mill (supresi ledakan)', accept: ['SUPP'],
      why: 'Supresi kimia memadamkan ledakan di dalam mill pada tahap awal sebelum tekanannya merusak peralatan dan gedung.' },
    { id: 'h45', stage: 4, x: 170, y: 232, label: 'Silo SL-901 (inerting)', accept: ['INERT'],
      why: 'Injeksi nitrogen atau CO2 memadamkan pembaraan di dalam silo tanpa mengaduk debu menjadi awan.' },
    { id: 'h46', stage: 4, x: 470, y: 282, label: 'Gedung produksi (detektor api)', accept: ['FD'],
      why: 'Detektor api atau panas mempercepat aktivasi pemadaman dan evakuasi.' },
    { id: 'h47', stage: 4, x: 330, y: 300, label: 'Gedung produksi (hidran atau sprinkler)', accept: ['FW', 'SPK'],
      why: 'Hidran atau sprinkler mengendalikan kebakaran di gedung. Semprotan air harus diarahkan agar tidak mengaduk debu menjadi awan.' },
    { id: 'h48', stage: 4, x: 965, y: 470, label: 'Titik kumpul dan alarm umum', accept: ['ALARM'],
      why: 'Ledakan debu dapat meruntuhkan bagian gedung; evakuasi terencana melindungi pekerja.' },
    { id: 'h49', stage: 4, x: 772, y: 430, label: 'Area produksi (pemadam api ringan)', accept: ['APAR'],
      why: 'APAR memungkinkan operator memadamkan api kecil pada tahap awal, misalnya kebakaran motor atau panel.' },
    { id: 'h40', stage: 4, x: 872, y: 150, label: 'Cerobong dust collector (sistem busa)', accept: [],
      why: 'Busa tidak efektif untuk kebakaran debu di dalam peralatan dan dapat mengaduk debu. Perangkat di sini tidak menangani ancaman utama.' },
  ],
  inspect: [
    { id: 'BE-901', itpm: 'ROT', why: 'Pemantauan getaran dan suhu bantalan elevator mendeteksi kerusakan bantalan dan sabuk sebelum menjadi sumber nyala.' },
    { id: 'HM-901', itpm: 'ROT', why: 'Pemantauan getaran hammer mill mendeteksi ketidakseimbangan palu dan kerusakan bantalan.' },
    { id: 'FN-901', itpm: 'ROT', why: 'Kipas aspirasi yang andal menjaga debu tetap di dalam sistem tertutup dan tidak menumpuk di gedung.' },
  ],
  budget: { 3: 29, 4: 33 },
  bowtie: {
    top: 'Ledakan debu jagung di peralatan produksi pakan',
    threats: ['Sabuk elevator selip dan bergesekan', 'Logam asing masuk hammer mill', 'Pemanasan spontan di silo', 'Hammer mill tercekik'],
    cons: ['Ledakan elevator dan ledakan sekunder gedung', 'Ledakan dust collector', 'Ledakan silo', 'Kebakaran mill dan ducting'],
  },
};
SCENARIOS.push(SCN_DEBU);
