/* Skenario sektor Manufaktur: dimuat setelah js/data.js dan menambahkan diri ke SCENARIOS. */
/* =====================================================================
   MANUFAKTUR: Lini Produksi Pakan Ternak (Debu Mudah Terbakar)
   ===================================================================== */
const SCN_DEBU = {
  id: 'debu',
  title: 'Lini Produksi Pakan Ternak',
  subtitle: 'Silo jagung, bucket elevator, hammer mill, dust collector (bahaya ledakan debu)',
  level: 'Menengah',
  sector: 'manufaktur',
  area: 'Industri Pangan dan Pakan',
  color: '#8a6d3b',
  kits: ['debu'],
  overview: [
    'Lini produksi ini mengolah jagung menjadi pakan ternak dengan kapasitas 20 ton/jam. Jagung dari silo SL-901 dibawa konveyor CV-901 ke bucket elevator BE-901 yang mengangkatnya ke hammer mill HM-901 untuk digiling. Hasil gilingan dikirim ke mixer dan pellet mill.',
    'Elevator dan mill menghasilkan debu halus yang disedot sistem aspirasi melalui ducting ke dust collector DC-901, lalu udara bersih dibuang kipas FN-901 melalui cerobong. Debu yang terkumpul di hopper dust collector dikembalikan ke aliran produk.',
    'Debu jagung dan tepung yang terdispersi di udara dapat meledak bila bertemu sumber nyala seperti gesekan sabuk, percikan logam, permukaan panas, atau listrik statis. Ledakan di dalam peralatan dapat mengangkat debu yang menumpuk di gedung dan memicu ledakan sekunder yang lebih besar.',
  ],
  production: { label: 'Pakan diproduksi', unit: 't', var: 'FPR', k: 1 / 60, dec: 1 },
  fluidNames: { bulk: 'Jagung dan hasil gilingan', air: 'Udara aspirasi berdebu' },
  zones: [
    { x: 200, y: 20, w: 320, h: 360, label: 'Gedung Produksi', labelPos: 'bottom' },
  ],
  /* area untuk titik pemasangan yang berada di dalam ruang, bukan pada peralatan atau pipa (tidak digambar) */
  areas: [
    { id: 'gedung-produksi', name: 'Gedung Produksi', x: 200, y: 20, w: 320, h: 360 },
  ],
  equipment: [
    { id: 'SL-901', type: 'silo', x: 40, y: 60, w: 110, h: 200, name: 'Silo Jagung SL-901', level: 'LSL', levelFill: 'bulk',
      desc: 'Silo baja berkapasitas sekitar 2.000 ton. Jagung dengan kadar air di atas sekitar 14 persen yang tersimpan lama dapat memanas dengan sendirinya.', vars: ['LSL', 'TSL'] },
    { id: 'CV-901', type: 'conveyor', x: 95, y: 300, w: 135, h: 0, name: 'Konveyor Jagung CV-901',
      desc: 'Membawa jagung dari silo ke boot bucket elevator.' },
    { id: 'BE-901', type: 'elevator', x: 250, y: 70, w: 28, h: 250, name: 'Bucket Elevator BE-901',
      desc: 'Mengangkat jagung setinggi sekitar 30 meter dengan mangkuk pada sabuk. Sabuk yang selip atau bergeser akan bergesekan dengan pulley dan casing.', vars: ['SBE', 'TBR'] },
    { id: 'HM-901', type: 'mill', x: 400, y: 190, name: 'Hammer Mill HM-901',
      desc: 'Penggiling palu berputar sekitar 3.000 rpm dengan motor 200 kW. Logam asing atau umpan berlebih menimbulkan percikan dan panas gesekan.', vars: ['VHM', 'IHM', 'FPR'] },
    { id: 'DC-901', type: 'filter', x: 560, y: 60, w: 120, h: 180, name: 'Dust Collector DC-901',
      desc: 'Kolektor kantong (bag filter) yang menyaring debu dari udara aspirasi. Di dalamnya selalu terdapat awan debu halus yang mudah meledak.', vars: ['TDC', 'DPF'] },
    { id: 'FN-901', type: 'fan', x: 760, y: 90, name: 'Kipas Aspirasi FN-901',
      desc: 'Menyedot udara berdebu dari elevator dan mill melalui dust collector.' },
    { id: 'ST-901', type: 'stack', x: 830, y: 250, h: 190, name: 'Cerobong',
      desc: 'Membuang udara bersih dari dust collector ke atmosfer.' },
    { id: 'PM-901', type: 'sink', x: 848, y: 330, dir: 'right', name: 'Ke Mixer dan Pellet Mill',
      desc: 'Hasil gilingan diteruskan ke mixer, conditioner uap, dan pellet mill.' },
    { id: 'CR-900', type: 'building', x: 720, y: 460, name: 'Ruang Kontrol',
      desc: 'Operator memantau lini produksi dan sistem aspirasi.' },
    { id: 'MP-900', type: 'muster', x: 920, y: 470, name: 'Titik Kumpul',
      desc: 'Area berkumpul evakuasi di luar gedung produksi.' },
  ],
  pipes: [
    { id: 's1', fluid: 'bulk', w: 7, pts: [[95, 262], [95, 293]] },
    { id: 's2', fluid: 'bulk', w: 7, pts: [[288, 94], [400, 94], [400, 168]], arrow: true },
    { id: 's3', fluid: 'bulk', w: 7, pts: [[400, 222], [400, 330], [848, 330]], arrow: true },
    { id: 'd1', fluid: 'air', w: 6, pts: [[288, 66], [288, 36], [530, 36], [530, 100], [560, 100]], arrow: true },
    { id: 'd2', fluid: 'air', w: 6, pts: [[426, 182], [480, 182], [480, 130], [560, 130]], arrow: true },
    { id: 'd3', fluid: 'air', w: 6, pts: [[680, 90], [738, 90]] },
    { id: 'd4', fluid: 'air', w: 6, pts: [[794, 74], [820, 74]] },
    { id: 'd5', fluid: 'bulk', w: 5, pts: [[620, 244], [620, 330]] },
  ],
  labels: [
    { x: 397, y: 26, text: 'Ducting aspirasi', size: 10 },
  ],
  vars: {
    LSL: { label: 'Isi Silo Jagung', unit: '%', normal: 70, min: 0, max: 100, lo: 15, hi: 92, node: 'SL-901', x: 95, y: 36, tau: 6, noise: 0.1, dec: 0 },
    TSL: { label: 'Suhu Tumpukan Silo', unit: '°C', normal: 30, min: 15, max: 120, hi: 45, hihi: 55, node: 'SL-901', x: 192, y: 150, tau: 6, noise: 0.1, dec: 1 },
    SBE: { label: 'Kecepatan Sabuk Elevator', unit: '%', normal: 100, min: 0, max: 120, lo: 85, lolo: 70, node: 'BE-901', x: 330, y: 250, tau: 1.5, noise: 0.3, dec: 0 },
    TBR: { label: 'Suhu Bantalan Head Pulley', unit: '°C', normal: 45, min: 20, max: 200, hi: 70, hihi: 85, node: 'BE-901', x: 330, y: 125, tau: 4, noise: 0.2, dec: 0 },
    VHM: { label: 'Getaran Hammer Mill', unit: 'mm/s', normal: 3.0, min: 0, max: 20, hi: 7.1, hihi: 11.2, node: 'HM-901', x: 470, y: 222, tau: 1, noise: 0.1, dec: 1 },
    IHM: { label: 'Arus Motor Hammer Mill', unit: 'A', normal: 150, min: 0, max: 300, hi: 190, hihi: 220, node: 'HM-901', x: 470, y: 250, tau: 1.5, noise: 1, dec: 0 },
    TDC: { label: 'Suhu Masuk Dust Collector', unit: '°C', normal: 38, min: 15, max: 150, hi: 60, hihi: 75, node: 'DC-901', x: 730, y: 160, tau: 2, noise: 0.2, dec: 0 },
    DPF: { label: 'Beda Tekanan Dust Collector', unit: 'mmH2O', normal: 120, min: 0, max: 300, lo: 50, hi: 180, node: 'DC-901', x: 730, y: 188, tau: 3, noise: 0.8, dec: 0 },
    FPR: { label: 'Laju Produksi', unit: 't/j', normal: 20, min: 0, max: 40, lo: 8, node: 'HM-901', x: 700, y: 300, tau: 2, noise: 0.1, dec: 1 },
  },
  trendVars: ['SBE', 'VHM', 'TSL', 'IHM'],
  controls: [
    { id: 'feed', label: 'Laju umpan hammer mill', unit: 't/j', min: 10, max: 30, def: 20, step: 1,
      effects: [{ var: 'FPR', gain: 1 }, { var: 'IHM', gain: 3 }, { var: 'VHM', gain: 0.05 }] },
    { id: 'aspir', label: 'Bukaan damper aspirasi', unit: '%', min: 40, max: 100, def: 80, step: 5,
      effects: [{ var: 'DPF', gain: 1.2 }, { var: 'TDC', gain: -0.05 }] },
    { id: 'moist', label: 'Kadar air jagung masuk silo', unit: '%', min: 12, max: 18, def: 14, step: 0.5,
      effects: [{ var: 'TSL', gain: 1.5 }] },
  ],
  quiz: [
    { q: 'Lima unsur apa yang harus ada bersamaan agar ledakan debu terjadi (pentagon ledakan debu)?', opts: ['Debu mudah terbakar, oksigen, sumber nyala, dispersi debu menjadi awan, dan ruang terkurung', 'Debu mudah terbakar, oksigen, sumber nyala, kelembapan rendah, dan suhu ruang tinggi', 'Debu mudah terbakar, oksigen, sumber nyala, reaksi berantai, dan tekanan tinggi di dalam peralatan', 'Debu mudah terbakar, udara, panas, listrik statis, dan ukuran partikel halus'], ans: 0,
      why: 'Menghilangkan salah satu unsur pentagon mencegah ledakan. Itulah dasar pengendalian sumber nyala, aspirasi, kebersihan, inerting, dan venting (NFPA 652).' },
    { q: 'Mengapa ledakan sekunder sering lebih merusak daripada ledakan primer?', opts: ['Gelombang ledakan primer mengangkat debu yang menumpuk di lantai dan balok menjadi awan besar', 'Ledakan sekunder terjadi di luar peralatan sehingga tidak tertahan dinding apa pun dan langsung mengenai orang', 'Ledakan sekunder dipicu gas pirolisis yang terbentuk dari debu yang terbakar setelah ledakan primer', 'Ledakan primer merusak sistem aspirasi sehingga udara masuk dan memperbesar nyala di dalam mill'], ans: 0,
      why: 'Lapisan debu tipis di permukaan gedung sudah cukup untuk membentuk awan yang dapat meledak. Kebersihan (housekeeping) adalah barier yang sangat penting.' },
    { q: 'Apa fungsi pemisah magnet sebelum hammer mill?', opts: ['Menangkap logam asing sebelum masuk mill sehingga tidak terjadi percikan api', 'Mencegah logam merusak saringan mill, karena percikan tidak cukup panas untuk menyalakan debu jagung', 'Memisahkan butiran jagung yang terlalu besar agar beban motor mill tetap stabil', 'Menghilangkan muatan listrik statis dari aliran jagung sebelum digiling di hammer mill'], ans: 0,
      why: 'Logam yang terhantam palu berputar menimbulkan percikan panas yang dapat terbawa ke ducting dan dust collector.' },
    { q: 'Mengapa jagung lembap yang disimpan lama di silo berbahaya?', opts: ['Aktivitas mikroba dan oksidasi dapat memanaskan tumpukan hingga membara dan menghasilkan gas mudah terbakar', 'Kelembapan menaikkan berat jenis jagung sehingga dinding silo menerima beban melebihi desain', 'Uap air dari jagung lembap mengembun di atap silo dan membentuk awan debu yang mudah meledak saat kering', 'Jamur pada jagung lembap menghasilkan metana dalam jumlah besar seperti yang terjadi pada digester biogas'], ans: 0,
      why: 'Pemanasan spontan berlangsung lambat dan tidak terlihat dari luar. Kabel suhu dan pemantauan CO memberi peringatan dini.' },
    { q: 'Apa fungsi panel venting ledakan pada dust collector?', opts: ['Membuka pada tekanan rendah saat ledakan sehingga tekanan dan bola api diarahkan ke area aman', 'Mencegah ledakan dengan membuang debu halus secara berkala sebelum mencapai konsentrasi berbahaya', 'Memadamkan nyala di dalam dust collector dengan memasukkan udara dingin dari luar', 'Menahan tekanan ledakan di dalam dust collector agar bola api tidak keluar dan membahayakan gedung produksi'], ans: 0,
      why: 'Venting tidak mencegah ledakan, tetapi membatasi tekanan di dalam peralatan. Area buangan vent harus aman dari orang (NFPA 68).' },
  ],
  events: [
    { id: 'e1', threat: 0, effects: [{ var: 'SBE', to: 62, delay: 1, dur: 6 }, { var: 'TBR', to: 140, delay: 3, dur: 18 }],
      warnings: [
        { t: 10, type: 'heat', sev: 'warn', at: 'BE-901', pos: [264, 80], text: 'Bau karet terbakar di sekitar kepala bucket elevator BE-901.' },
        { t: 17, type: 'smoke', sev: 'crit', at: 'BE-901', pos: [264, 70], text: 'Asap keluar dari casing elevator; debu di dalamnya mulai membara.' },
        { t: 24, type: 'explosion', sev: 'final', at: 'BE-901', pos: [270, 160], text: 'LEDAKAN DEBU di bucket elevator BE-901, disusul ledakan sekunder dari debu yang menumpuk di lantai dan balok gedung produksi.' },
      ],
      answer: { node: ['BE-901'], param: ['F', 'T'], guide: ['low', 'high'] },
      hint: 'Kecepatan sabuk turun dibanding pulley penggerak, tanda sabuk selip. Gesekan selip menghasilkan panas.',
      causes: ['Sabuk elevator selip atau bergeser karena kelebihan muatan atau tegangan sabuk kurang, sehingga bergesekan dengan pulley dan casing', 'Kadar air jagung terlalu tinggi', 'Damper aspirasi terlalu terbuka', 'Silo terlalu penuh'], causeAns: 0,
      cons: ['Gesekan memanaskan sabuk dan debu hingga menyala, lalu terjadi ledakan debu primer di elevator dan ledakan sekunder di gedung', 'Laju produksi naik', 'Suhu silo turun', 'Getaran mill turun'], consAns: 0,
      explain: 'Kecepatan sabuk turun lalu suhu bantalan head pulley naik. Bucket elevator tercatat sebagai lokasi ledakan primer yang paling sering pada fasilitas biji-bijian. Ledakan primer mengangkat debu yang menumpuk di gedung sehingga terjadi ledakan sekunder yang jauh lebih merusak, seperti pada bencana Imperial Sugar tahun 2008. Proteksi yang tepat adalah monitor kecepatan dan kelurusan sabuk yang menghentikan motor, sensor suhu bantalan, dan kebersihan gedung.' },
    { id: 'e2', threat: 1, effects: [{ var: 'VHM', to: 14, delay: 1, dur: 4 }, { var: 'TDC', to: 88, delay: 4, dur: 12 }],
      warnings: [
        { t: 6, type: 'vibration', sev: 'warn', at: 'HM-901', text: 'Suara benturan logam keras dari dalam hammer mill HM-901.' },
        { t: 12, type: 'heat', sev: 'crit', at: 'DC-901', pos: [600, 118], text: 'Percikan api terlihat di ducting aspirasi menuju dust collector; suhu masuk naik.' },
        { t: 19, type: 'explosion', sev: 'final', at: 'DC-901', pos: [620, 118], text: 'LEDAKAN di dust collector DC-901: kantong filter terbakar dan panel dinding terlempar.' },
      ],
      answer: { node: ['HM-901', 'DC-901'], param: ['C', 'T'], guide: ['aswell', 'high'] },
      hint: 'Getaran mill melonjak tiba-tiba disertai bunyi logam. Ada benda asing yang seharusnya tidak ikut masuk ke mesin.',
      causes: ['Logam asing seperti baut atau potongan besi ikut masuk ke hammer mill dan memercikkan api', 'Kadar air jagung tinggi', 'Sabuk elevator selip', 'Silo terlalu penuh'], causeAns: 0,
      cons: ['Percikan terbawa ke ducting dan menyulut debu di dust collector sehingga terjadi kebakaran dan ledakan', 'Laju produksi naik', 'Suhu silo naik tanpa dampak', 'Kecepatan elevator naik'], consAns: 0,
      explain: 'Getaran mill melonjak lalu suhu masuk dust collector naik. Ini pola percikan dari logam asing yang terbawa aliran aspirasi. Dust collector berisi awan debu halus sehingga sangat mudah meledak. Proteksi yang tepat adalah pemisah magnet sebelum mill dan deteksi percikan dengan pemadam otomatis di ducting (NFPA 61). Menurut makna guideword CCPS, kejadian ini dibaca sebagai komposisi umpan yang disertai material asing (As well as), bukan penggantian material secara menyeluruh (Other than).' },
    { id: 'e3', threat: 2, effects: [{ var: 'TSL', to: 80, delay: 1, dur: 16 }],
      warnings: [
        { t: 14, type: 'heat', sev: 'warn', at: 'SL-901', text: 'Bau hangus dan uap keluar dari ventilasi atap silo SL-901.' },
        { t: 20, type: 'smoke', sev: 'crit', at: 'SL-901', pos: [95, 66], text: 'Asap keluar dari atap silo; jagung di bagian tengah menggumpal dan menghitam.' },
        { t: 27, type: 'explosion', sev: 'final', at: 'SL-901', pos: [95, 140], text: 'LEDAKAN SILO SL-901 saat pengosongan: bara di dalam tumpukan menyulut debu dan gas pirolisis.' },
      ],
      answer: { node: ['SL-901'], param: ['T'], guide: ['high'] },
      hint: 'Suhu tumpukan naik tanpa sumber panas dari luar. Material di dalam silo memanas dengan sendirinya.',
      causes: ['Jagung lembap tersimpan terlalu lama sehingga aktivitas mikroba dan oksidasi memanaskan tumpukan (pemanasan spontan)', 'Hammer mill kemasukan logam', 'Sabuk elevator selip', 'Damper aspirasi tertutup'], causeAns: 0,
      cons: ['Tumpukan membara, terbentuk gas pirolisis dan debu, lalu meledak saat silo dikosongkan atau dibuka', 'Laju produksi naik', 'Getaran mill naik', 'Dust collector menjadi lebih bersih'], consAns: 0,
      explain: 'Suhu tumpukan naik perlahan tanpa perubahan pada peralatan lain. Pemanasan spontan biji-bijian lembap dapat berkembang menjadi pembaraan yang tidak terlihat dari luar. Proteksi yang tepat adalah kabel sensor suhu di dalam tumpukan, analyzer CO di ruang kepala silo, dan sistem inerting untuk memadamkan pembaraan dengan aman.' },
    { id: 'e4', threat: 3, effects: [{ var: 'IHM', to: 245, delay: 1, dur: 6 }, { var: 'VHM', to: 9, delay: 2, dur: 6 }],
      warnings: [
        { t: 8, type: 'vibration', sev: 'warn', at: 'HM-901', text: 'Hammer mill tersumbat; motor berdengung berat dan saringan penuh.' },
        { t: 14, type: 'smoke', sev: 'crit', at: 'HM-901', pos: [400, 168], text: 'Asap keluar dari saringan hammer mill; bahan di dalamnya mulai hangus.' },
        { t: 21, type: 'fire', sev: 'final', at: 'HM-901', pos: [400, 186], text: 'KEBAKARAN di dalam hammer mill merambat ke ducting aspirasi.' },
      ],
      answer: { node: ['HM-901'], param: ['F', 'E'], guide: ['high'] },
      hint: 'Arus motor mill naik tajam karena bahan yang masuk lebih banyak daripada yang dapat digiling.',
      causes: ['Umpan ke hammer mill berlebih atau saringan tersumbat sehingga mill tercekik (choke)', 'Jagung terlalu kering', 'Sabuk elevator selip', 'Silo hampir kosong'], causeAns: 0,
      cons: ['Gesekan berlebih memanaskan bahan hingga membara, lalu terjadi kebakaran mill yang merambat ke ducting', 'Suhu silo turun', 'Laju produksi naik dengan aman', 'Dust collector menjadi lebih bersih'], consAns: 0,
      explain: 'Arus motor mill melonjak lalu getaran naik. Mill yang tercekik menggiling bahan berulang-ulang sehingga panas gesekan menumpuk. Proteksi yang tepat adalah pembatas laju umpan berbasis arus motor dan relai beban lebih yang menghentikan motor.' },
    { id: 'e5', start: 12,
      hf: { type: 'violation', team: 'mgmt', threat: 0, title: 'Interlock sabuk dijumper demi target produksi', factor: 'Sensor kecepatan sabuk dijumper tanpa izin bypass',
        lesson: 'Ini violation situasional: tekanan target membuat supervisor memerintahkan jumper, dan operator memasangnya walaupun itu bukan kewenangannya. Interlock yang sering trip seharusnya diperbaiki, bukan dilumpuhkan, dan setiap bypass memerlukan izin tertulis, batas waktu, serta pengamanan pengganti. Pola seperti ini berulang kali muncul dalam investigasi ledakan debu, ketika pengaman dianggap mengganggu produksi.',
        controls: ['Bypass interlock hanya dengan izin tertulis, batas waktu, dan pengamanan pengganti', 'Perbaikan sensor oleh teknisi berwenang sebelum elevator dijalankan', 'Target produksi tidak boleh mengalahkan batas operasi aman'] },
      chat: [
        { t: 1, who: 'hendra', at: 'CR-900', text: 'Order pakan 200 ton harus keluar hari ini. Elevator jangan sampai trip lagi seperti kemarin.' },
        { t: 4, who: 'dimas', at: 'BE-901', mood: 'ragu', text: 'Sensor kecepatan sabuk BE-901 sering trip sendiri. Teknisi instrumen baru masuk besok.' },
        { t: 7, who: 'hendra', at: 'CR-900', mood: 'santai', text: 'Pasang jumper saja dulu di sensornya. Yang penting produksi jalan.' },
        { t: 10, who: 'dimas', at: 'BE-901', mood: 'santai', text: 'Oke, sudah kujumper. Elevator jalan terus tanpa trip.' },
        { t: 13, who: 'raka', at: 'CR-900', text: 'Laju umpan kunaikkan ke 24 ton per jam ya, biar target terkejar.' },
        { t: 19, who: 'dimas', at: 'BE-901', mood: 'ragu', text: 'Sabuk elevator terdengar mencicit di bagian atas.' },
        { t: 25, who: 'raka', at: 'CR-900', mood: 'panik', text: 'Suhu bantalan head pulley naik terus! Hentikan elevator sekarang!' },
      ],
      effects: [{ var: 'FPR', to: 24, delay: 0.5, dur: 3 }, { var: 'SBE', to: 62, delay: 2, dur: 6 }, { var: 'TBR', to: 140, delay: 4, dur: 18 }],
      warnings: [
        { t: 11, type: 'heat', sev: 'warn', at: 'BE-901', pos: [264, 80], text: 'Bau karet terbakar di sekitar kepala bucket elevator BE-901.' },
        { t: 18, type: 'smoke', sev: 'crit', at: 'BE-901', pos: [264, 70], text: 'Asap keluar dari casing elevator; debu di dalamnya mulai membara.' },
        { t: 25, type: 'explosion', sev: 'final', at: 'BE-901', pos: [270, 160], text: 'LEDAKAN DEBU di bucket elevator BE-901, disusul ledakan sekunder dari debu yang menumpuk di lantai dan balok gedung produksi.' },
      ],
      answer: { node: ['BE-901'], param: ['F', 'T'], guide: ['low', 'high'] },
      hint: 'Kecepatan sabuk turun dan suhu bantalan naik, tetapi elevator tidak berhenti otomatis. Pengaman yang seharusnya memutus motor sedang dilumpuhkan. Baca kembali obrolan tentang sensor yang sering trip.',
      causes: ['Sensor kecepatan sabuk dijumper atas instruksi supervisor sehingga elevator tetap berjalan saat sabuk selip karena beban naik', 'Sabuk elevator aus dan putus sehingga motor berputar tanpa beban', 'Bantalan head pulley kekurangan pelumas sehingga suhu naik perlahan', 'Hammer mill tersumbat sehingga umpan elevator tertahan'], causeAns: 0,
      cons: ['Gesekan sabuk yang selip menyulut debu di dalam elevator, terjadi ledakan primer dan ledakan sekunder di gedung', 'Produksi naik sesuai target tanpa dampak keselamatan', 'Motor elevator berhenti sendiri karena kelebihan beban sehingga sistem aman', 'Silo jagung kosong lebih cepat dari rencana'], consAns: 0,
      explain: 'Kecepatan sabuk turun relatif terhadap pulley penggerak, lalu suhu bantalan head pulley naik tajam. Monitor kecepatan sabuk seharusnya memutus motor saat sabuk selip, tetapi sensornya sudah dijumper. Beban yang dinaikkan untuk mengejar target memperbesar kemungkinan selip.' },
    { id: 'e6', threat: 3, effects: [{ var: 'DPF', to: 4, delay: 1, dur: 3 }, { var: 'TDC', to: 33, delay: 2, dur: 6 }],
      warnings: [
        { t: 8, type: 'dust', sev: 'warn', at: 'HM-901', pos: [400, 168], text: 'Debu menyembur dari celah casing elevator dan corong hammer mill. Gedung produksi mulai berkabut debu.' },
        { t: 15, type: 'dust', sev: 'crit', at: 'BE-901', pos: [330, 200], big: true, text: 'Awan debu tebal memenuhi gedung produksi dan lampu tampak buram. Debu mengendap tebal di balok dan lantai.' },
        { t: 23, type: 'explosion', sev: 'final', at: 'HM-901', pos: [380, 250], text: 'Awan debu di gedung produksi tersulut permukaan panas motor hammer mill. Ledakan menghancurkan dinding gedung produksi.' },
      ],
      answer: { node: ['FN-901', 'DC-901'], param: ['F', 'P'], guide: ['none', 'reverse', 'low'] },
      hint: 'Beda tekanan dust collector turun hampir nol, padahal elevator dan mill tetap berjalan. Pikirkan ke mana debu pergi bila tidak ada lagi yang menyedotnya.',
      causes: ['Kipas aspirasi FN-901 trip karena motornya kelebihan beban, sementara elevator dan hammer mill tetap berjalan karena tidak ada interlock', 'Kantong filter dust collector tersumbat sehingga beda tekanan naik', 'Logam asing masuk hammer mill dan memercikkan api', 'Sabuk elevator selip karena kelebihan muatan'], causeAns: 0,
      cons: ['Debu keluar dari peralatan dan memenuhi gedung, lalu awan debu tersulut sehingga terjadi ledakan di gedung produksi', 'Dust collector menjadi lebih bersih karena tidak ada aliran', 'Laju produksi naik karena energi kipas tidak terpakai', 'Suhu silo turun karena aliran udara berhenti'], consAns: 0,
      explain: 'Beda tekanan dust collector turun hampir nol karena tidak ada lagi aliran udara aspirasi, sementara elevator dan mill tetap berjalan. Debu yang seharusnya tersedot ke dust collector justru keluar dari celah peralatan ke dalam gedung. Ini deviasi aliran Tidak ada (No) pada aspirasi dan Kebalikan (Reverse) pada arah debu. Debu yang mengendap di gedung menjadi bahan bakar ledakan sekunder, sehingga NFPA 654 menekankan pengendalian debu yang lolos dan kebersihan gedung. Interlock yang menghentikan elevator dan mill saat kipas aspirasi berhenti memutus rantai ini.' },
    { id: 'e7', start: 12,
      hf: { type: 'slip', team: 'ops', threat: 3, title: 'Set point laju umpan terketik 42 t/j, bukan 24 t/j', factor: 'Set point umpan salah ketik, angka tertukar',
        lesson: 'Raka bermaksud memasukkan 24 ton per jam, tetapi yang terketik 42 karena urutan angkanya tertukar. Niatnya benar, pelaksanaannya meleset, sehingga tergolong slip. Slip seperti ini mudah terjadi saat operator mengetik sambil memikirkan pekerjaan lain, dan sulit dicegah hanya dengan imbauan agar lebih teliti. Pencegahnya adalah batas masukan pada sistem kendali yang menolak set point di luar kapasitas, konfirmasi untuk perubahan besar, dan pembatas umpan otomatis berbasis arus motor mill.',
        controls: ['Batas masukan set point di sistem kendali sesuai kapasitas mill', 'Konfirmasi ulang untuk perubahan set point yang besar', 'Pembatas umpan otomatis berbasis arus motor dan relai beban lebih'] },
      chat: [
        { t: 1, who: 'hendra', at: 'CR-900', text: 'Raka, laju umpan hammer mill naikkan ke 24 ton per jam ya, order hari ini banyak.' },
        { t: 4, who: 'raka', at: 'CR-900', text: 'Siap, Pak. Kuketik set point umpan sekarang.' },
        { t: 7, who: 'raka', at: 'CR-900', mood: 'santai', text: 'Sudah masuk. Aku lanjut isi laporan produksi shift.' },
        { t: 10, who: 'dimas', at: 'PM-901', text: 'Oke, aku cek area pellet mill dulu.' },
        { t: 20, who: 'dimas', at: 'HM-901', mood: 'ragu', text: 'Hammer mill berdengung berat sekali, padahal umpannya cuma dinaikkan sedikit.' },
        { t: 24, who: 'raka', at: 'CR-900', mood: 'panik', text: 'Set point umpan di layar 42, bukan 24! Angkanya tertukar waktu kuketik.' },
        { t: 28, who: 'hendra', at: 'CR-900', mood: 'panik', text: 'Hentikan umpan dan mill sekarang, siapkan APAR di area mill!' },
      ],
      effects: [{ var: 'FPR', to: 38, delay: 1, dur: 3 }, { var: 'IHM', to: 250, delay: 2, dur: 6 }, { var: 'VHM', to: 9, delay: 3, dur: 6 }],
      warnings: [
        { t: 8, type: 'vibration', sev: 'warn', at: 'HM-901', text: 'Motor hammer mill meraung berat dan bahan menumpuk di corong umpan.' },
        { t: 14, type: 'smoke', sev: 'crit', at: 'HM-901', pos: [400, 168], text: 'Asap keluar dari saringan hammer mill. Bahan yang tertahan mulai hangus.' },
        { t: 21, type: 'fire', sev: 'final', at: 'HM-901', pos: [400, 186], text: 'Bahan yang membara di dalam hammer mill menyala dan api merambat ke ducting aspirasi.' },
      ],
      answer: { node: ['HM-901'], param: ['F', 'E'], guide: ['high'] },
      hint: 'Laju umpan dan arus motor mill naik jauh melampaui yang diminta. Baca kembali obrolan tentang set point umpan yang dimasukkan.',
      causes: ['Set point laju umpan terketik 42 t/j, bukan 24 t/j, sehingga mill tercekik', 'Saringan hammer mill robek sehingga bahan kasar lolos', 'Logam asing masuk hammer mill dan memercikkan api', 'Sabuk elevator selip sehingga umpan ke mill berkurang'], causeAns: 0,
      cons: ['Mill tercekik, gesekan memanaskan bahan hingga membara, lalu kebakaran merambat ke ducting', 'Produksi naik hampir dua kali lipat dengan aman', 'Motor mill berhenti sendiri tanpa kerusakan apa pun', 'Suhu tumpukan silo turun karena jagung cepat keluar'], consAns: 0,
      explain: 'Laju umpan melonjak jauh melampaui yang diminta, lalu arus motor dan getaran mill naik. Polanya sama dengan mill yang tercekik, tetapi penyebabnya adalah angka set point yang tertukar saat diketik. Pembatas umpan berbasis arus motor dan relai beban lebih tetap diperlukan karena kesalahan masukan dapat terjadi kapan saja.' },
    { id: 'e8', start: 12,
      hf: { type: 'mistake', team: 'mgmt', threat: 2, title: 'Jagung basah diterima ke silo karena dikira dapat dikeringkan kipas aerasi', factor: 'Jagung basah disimpan, dikira kering oleh aerasi',
        lesson: 'Hendra yakin kipas aerasi akan mengeringkan jagung basah, padahal aerasi pada silo hanya menurunkan dan meratakan suhu tumpukan, bukan mengeringkan biji. Keputusannya sesuai niat tetapi didasari pemahaman yang keliru, sehingga tergolong mistake. Jagung berkadar air sekitar 17 persen menjadi tempat aktivitas mikroba dan jamur yang menghasilkan panas, sehingga tumpukan memanas dengan sendirinya. Pencegahnya adalah batas kadar air penerimaan yang tertulis dan diukur pada setiap truk, pengeringan dengan dryer sebelum disimpan, serta pemantauan suhu tumpukan dan CO di ruang kepala silo.',
        controls: ['Batas kadar air penerimaan tertulis dan diukur pada setiap truk', 'Jagung basah dikeringkan dengan dryer sebelum masuk silo penyimpanan', 'Kabel sensor suhu tumpukan dan analyzer CO di ruang kepala silo'] },
      chat: [
        { t: 1, who: 'dimas', at: 'SL-901', text: 'Pak, jagung dari pemasok baru kadar airnya 17 persen, lebih basah dari biasanya.' },
        { t: 4, who: 'hendra', at: 'CR-900', mood: 'santai', text: 'Tidak apa-apa, masukkan saja ke silo. Nanti kipas aerasi yang mengeringkan.' },
        { t: 7, who: 'dimas', at: 'SL-901', text: 'Baik, Pak. Kipas aerasi silo kunyalakan setelah jagungnya masuk.' },
        { t: 10, who: 'raka', at: 'CR-900', text: 'Jagung dari pemasok baru sudah masuk ke SL-901, sekitar 300 ton.' },
        { t: 22, who: 'raka', at: 'CR-900', mood: 'ragu', text: 'Suhu tumpukan silo naik terus walaupun kipas aerasi menyala.' },
        { t: 27, who: 'dimas', at: 'SL-901', mood: 'panik', text: 'Jagung di bagian atas silo menggumpal dan berjamur, tumpukannya terasa panas!' },
        { t: 31, who: 'hendra', at: 'CR-900', mood: 'panik', text: 'Hentikan pengeluaran dari silo dan jangan buka pintu bawah. Hubungi tim pemadam!' },
      ],
      effects: [{ var: 'TSL', to: 80, delay: 1, dur: 16 }],
      warnings: [
        { t: 14, type: 'heat', sev: 'warn', at: 'SL-901', text: 'Uap hangat dan bau apak jamur keluar dari ventilasi atap silo SL-901.' },
        { t: 20, type: 'smoke', sev: 'crit', at: 'SL-901', pos: [95, 66], text: 'Asap keluar dari atap silo. Jagung di bagian tengah tumpukan menghitam dan membara.' },
        { t: 27, type: 'explosion', sev: 'final', at: 'SL-901', pos: [95, 140], text: 'Bara di dalam tumpukan menyulut debu dan gas pirolisis saat silo dibuka. Ledakan merobek atap silo SL-901.' },
      ],
      answer: { node: ['SL-901'], param: ['T'], guide: ['high'] },
      hint: 'Suhu tumpukan silo naik tanpa sumber panas dari luar, setelah ada keputusan tentang jagung yang diterima. Baca kembali obrolan tentang kadar air jagung dan kipas aerasi.',
      causes: ['Jagung berkadar air tinggi diterima ke silo karena dikira dapat dikeringkan kipas aerasi, sehingga tumpukan memanas dengan sendirinya', 'Sabuk elevator selip sehingga panas gesekan merambat ke silo', 'Logam asing masuk hammer mill dan memercikkan api ke arah silo', 'Sensor suhu silo menyimpang sehingga suhu terbaca tinggi palsu'], causeAns: 0,
      cons: ['Tumpukan membara, terbentuk gas pirolisis dan debu, lalu meledak saat silo dikosongkan atau dibuka', 'Jagung menjadi kering dan siap diproses tanpa dampak', 'Kipas aerasi mendinginkan tumpukan sehingga suhu kembali normal', 'Laju produksi naik karena jagung lebih lunak digiling'], consAns: 0,
      explain: 'Suhu tumpukan naik perlahan tanpa sumber panas dari luar, polanya sama dengan pemanasan spontan. Jagung basah yang diterima menjadi sumber panas dari aktivitas mikroba dan jamur, sedangkan kipas aerasi tidak dirancang untuk mengeringkan biji. Kabel sensor suhu di dalam tumpukan, analyzer CO, dan sistem inerting tetap diperlukan karena keputusan penerimaan bahan dapat keliru.' },
  ],
  variants: [
    ['e3', 'e2', 'e5', 'e6', 'e7'],
    ['e2', 'e1', 'e8', 'e6', 'e7'],
    ['e4', 'e2', 'e8', 'e6', 'e5'],
    ['e1', 'e4', 'e8', 'e2', 'e7'],
    ['e6', 'e4', 'e5', 'e3', 'e7'],
  ],
  hotspots: [
    /* Tahap 3: pencegahan, diurutkan menurut posisi baca pada P&ID (kiri ke kanan, atas ke bawah) */
    { id: 'h36', stage: 3, on: 'SL-901', tap: [96, 49], x: 74, y: 27, label: 'Ruang kepala silo (CO)', accept: ['COD', 'TT'],
      why: 'Kenaikan CO di ruang kepala silo menandakan pembaraan jauh sebelum asap terlihat.' },
    { id: 'h32', stage: 3, on: 'BE-901', tap: [251, 69], x: 221, y: 77, label: 'Bantalan head pulley (suhu)', accept: ['TT'],
      why: 'Sensor suhu bantalan memberi peringatan dini kerusakan bantalan dan gesekan di kepala elevator.' },
    { id: 'h34', stage: 3, on: 'd2', tap: [519, 130], x: 497, y: 92, label: 'Ducting aspirasi mill (deteksi percikan)', accept: ['SDE'],
      why: 'Deteksi percikan dan pemadam otomatis memadamkan bara di dalam ducting sebelum mencapai dust collector.' },
    { id: 'h33', stage: 3, on: 's2', tap: [400, 130], x: 431, y: 130, label: 'Spout sebelum hammer mill (magnet)', accept: ['MAG'],
      why: 'Pemisah magnet menangkap logam asing sebelum masuk mill sehingga tidak terjadi percikan.' },
    { id: 'h35', stage: 3, on: 'SL-901', tap: [150, 188], x: 181, y: 188, label: 'Dalam tumpukan silo (kabel suhu)', accept: ['TT', 'COD'],
      why: 'Kabel sensor suhu di dalam tumpukan mendeteksi pemanasan spontan. Analyzer CO juga diterima sebagai deteksi dini pembaraan.' },
    { id: 'h31', stage: 3, on: 'BE-901', tap: [278, 200], x: 309, y: 200, label: 'Casing elevator (monitor sabuk)', accept: ['BAM'],
      why: 'Monitor kecepatan dan kelurusan sabuk menghentikan motor saat sabuk selip atau bergeser, sebelum gesekan menyulut debu (NFPA 61).' },
    { id: 'h37', stage: 3, on: 'HM-901', tap: [373, 192], x: 358, y: 165, label: 'Feeder hammer mill (pembatas laju umpan)', accept: ['FT', 'OCR'],
      why: 'Pembatas laju umpan berbasis arus motor mencegah mill tercekik. Relai beban lebih yang menghentikan motor juga diterima.' },
    { id: 'h38', stage: 3, on: 'DC-901', tap: [672, 200], x: 703, y: 200, label: 'Dust collector (grounding)', accept: ['GRND'],
      why: 'Pentanahan rangka dan bonding kantong filter mencegah muatan statis menjadi sumber nyala di dalam dust collector (NFPA 652).' },
    { id: 'h39', stage: 3, on: 's3', tap: [559, 330], x: 567, y: 360, label: 'Jalur produk ke pellet mill', accept: [],
      why: 'Jalur produk ini tidak terkait dengan skenario yang teridentifikasi. Anggaran lebih baik dipakai pada elevator, mill, silo, dan dust collector.' },
    /* Tahap 4: mitigasi, diurutkan menurut posisi baca pada P&ID (kiri ke kanan, atas ke bawah) */
    { id: 'h41', stage: 4, on: 'DC-901', tap: [620, 59], x: 598, y: 37, label: 'Dust collector (panel venting ledakan)', accept: ['DVENT'],
      why: 'Panel venting membatasi tekanan ledakan di dust collector dan mengarahkan bola api ke area aman di luar gedung (NFPA 68).' },
    { id: 'h42', stage: 4, on: 'd1', tap: [530, 69], x: 500, y: 77, label: 'Ducting masuk dust collector (isolasi ledakan)', accept: ['EISO'],
      why: 'Katup isolasi menutup ducting dalam hitungan milidetik sehingga ledakan tidak merambat ke gedung produksi (NFPA 69).' },
    { id: 'h40', stage: 4, on: 'ST-901', tap: [838, 136], x: 869, y: 136, label: 'Cerobong dust collector (sistem busa)', accept: [],
      why: 'Busa tidak efektif untuk kebakaran debu di dalam peralatan dan dapat mengaduk debu. Perangkat di sini tidak menangani ancaman utama.' },
    { id: 'h45', stage: 4, on: 'SL-901', tap: [150, 180], x: 181, y: 180, label: 'Silo SL-901 (inerting)', accept: ['INERT'],
      why: 'Injeksi nitrogen atau CO2 memadamkan pembaraan di dalam silo tanpa mengaduk debu menjadi awan.' },
    { id: 'h43', stage: 4, on: 'BE-901', tap: [249, 200], x: 227, y: 222, label: 'Bucket elevator (venting atau supresi)', accept: ['DVENT', 'SUPP'],
      why: 'Elevator di dalam gedung dilindungi venting ke luar atau supresi kimia agar ledakan primer tidak memicu ledakan sekunder.' },
    { id: 'h44', stage: 4, on: 'HM-901', tap: [426, 200], x: 453, y: 216, label: 'Hammer mill (supresi ledakan)', accept: ['SUPP'],
      why: 'Supresi kimia memadamkan ledakan di dalam mill pada tahap awal sebelum tekanannya merusak peralatan dan gedung.' },
    { id: 'h47', stage: 4, on: 'gedung-produksi', x: 328, y: 300, label: 'Gedung produksi (hidran atau sprinkler)', accept: ['FW', 'SPK'],
      why: 'Hidran atau sprinkler mengendalikan kebakaran di gedung. Semprotan air harus diarahkan agar tidak mengaduk debu menjadi awan.' },
    { id: 'h46', stage: 4, on: 'gedung-produksi', x: 444, y: 280, label: 'Gedung produksi (detektor api)', accept: ['FD'],
      why: 'Detektor api atau panas mempercepat aktivasi pemadaman dan evakuasi.' },
    { id: 'h49', stage: 4, on: 'gedung-produksi', x: 500, y: 296, label: 'Gedung produksi (pemadam api ringan)', accept: ['APAR'],
      why: 'APAR memungkinkan operator memadamkan api kecil pada tahap awal, misalnya kebakaran motor atau panel.' },
    { id: 'h48', stage: 4, on: 'MP-900', tap: [940, 468], x: 971, y: 468, label: 'Titik kumpul dan alarm umum', accept: ['ALARM'],
      why: 'Ledakan debu dapat meruntuhkan bagian gedung; evakuasi terencana melindungi pekerja.' },
  ],
  inspect: [
    { id: 'BE-901', itpm: 'ROT', why: 'Pemantauan getaran dan suhu bantalan elevator mendeteksi kerusakan bantalan dan sabuk sebelum menjadi sumber nyala.' },
    { id: 'HM-901', itpm: 'ROT', why: 'Pemantauan getaran hammer mill mendeteksi ketidakseimbangan palu dan kerusakan bantalan.' },
    { id: 'FN-901', itpm: 'ROT', why: 'Kipas aspirasi yang andal menjaga debu tetap di dalam sistem tertutup dan tidak menumpuk di gedung.' },
  ],
  budget: { 3: 29, 4: 33 },
  bowtie: {
    top: 'Ledakan debu jagung di peralatan produksi pakan',
    threats: ['Sabuk elevator selip dan bergesekan', 'Logam asing masuk hammer mill', 'Pemanasan spontan di silo', 'Mill tercekik atau aspirasi gagal'],
    cons: ['Ledakan elevator dan ledakan sekunder gedung', 'Ledakan dust collector', 'Ledakan silo', 'Kebakaran mill dan ducting'],
  },
};
SCENARIOS.push(SCN_DEBU);
