/* Skenario sektor Manufaktur: dimuat setelah js/data.js dan menambahkan diri ke SCENARIOS. */
/* =====================================================================
   MANUFAKTUR: Sistem Refrigerasi Amonia Cold Storage
   ===================================================================== */
const SCN_AMONIA = {
  id: 'amonia',
  title: 'Refrigerasi Amonia Cold Storage',
  subtitle: 'Kompresor screw, kondensor evaporatif, receiver, separator hisap, evaporator ruang beku',
  level: 'Lanjutan',
  sector: 'manufaktur',
  area: 'Industri Makanan Beku',
  color: '#5a5f9e',
  kits: ['amonia'],
  op: 'Operasi Refrigerasi',
  overview: [
    'Unit ini adalah sistem refrigerasi amonia untuk cold storage produk beku dengan muatan amonia sekitar 3 ton. Kompresor screw K-1001 menghisap uap amonia bertekanan rendah dari separator hisap V-1002 dan menekannya ke kondensor evaporatif E-1001 di atap. Di kondensor, uap mengembun pada tekanan sekitar 12,5 barg dengan bantuan semprotan air dari pompa P-1002 dan aliran udara kipas.',
    'Amonia cair ditampung di receiver tekanan tinggi V-1001, lalu dialirkan melalui LCV-1001 ke separator hisap. Pompa P-1001 mengalirkan amonia cair bersuhu sekitar minus 30 °C ke evaporator EV-1001 di ruang beku yang dijaga minus 25 °C. Campuran cair dan uap kembali ke separator.',
    'Secara berkala, es pada koil evaporator dicairkan dengan gas panas dari discharge kompresor melalui katup XV-1003 (defrost). Amonia adalah refrigeran yang efisien tetapi beracun, dengan nilai ambang batas 25 ppm, dan dapat terbakar pada konsentrasi tinggi di ruang tertutup. Pelepasan besar dapat membahayakan pekerja dan permukiman di sekitar pabrik.',
  ],
  production: { label: 'Energi pendinginan', unit: 'kWh', var: 'QC', k: 1 / 60 },
  fluidNames: { gas: 'Uap amonia (hisap, discharge, gas panas defrost)', nh3: 'Amonia cair', cw: 'Air kondensor evaporatif' },
  zones: [
    { x: 190, y: 175, w: 470, h: 345, label: 'Ruang Mesin Amonia', labelPos: 'bottom' },
    { x: 680, y: 300, w: 295, h: 235, label: 'Ruang Beku -25 °C', labelPos: 'bottom' },
  ],
  equipment: [
    { id: 'E-1001', type: 'cooler', x: 230, y: 50, w: 170, h: 70, fans: 2, name: 'Kondensor Evaporatif E-1001',
      desc: 'Mengembunkan uap amonia bertekanan tinggi dengan semprotan air dan aliran udara dari kipas. Tekanan desain sisi tinggi sekitar 21 barg.', vars: ['PHP', 'FCD'] },
    { id: 'P-1002', type: 'pump', x: 170, y: 95, name: 'Pompa Air Kondensor P-1002',
      desc: 'Mensirkulasikan air dari bak kondensor ke nozel semprot di atas koil.' },
    { id: 'K-1001', type: 'compressor', x: 280, y: 300, name: 'Kompresor Screw K-1001',
      desc: 'Kompresor screw berinjeksi oli 400 kW. Oli menyerap panas kompresi dan didinginkan oleh pendingin oli. Kompresor tidak boleh menghisap cairan amonia.', vars: ['TDK'] },
    { id: 'V-1001', type: 'vessel', orient: 'h', x: 330, y: 200, w: 140, h: 50, name: 'Receiver Tekanan Tinggi V-1001', level: 'LRC',
      desc: 'Menampung amonia cair hasil kondensasi pada sekitar 12,5 barg. Bejana tekan dengan inventori amonia terbesar di sistem.', vars: ['LRC'] },
    { id: 'LCV-1001', type: 'valve', sub: 'control', x: 530, y: 225, tag: 'LIC', name: 'LCV-1001 (Kendali Level Separator)',
      desc: 'Mengatur aliran amonia cair dari receiver ke separator hisap untuk menjaga level separator 30 %.' },
    { id: 'V-1002', type: 'vessel', orient: 'h', x: 480, y: 320, w: 160, h: 56, name: 'Separator Hisap V-1002', level: 'LSD',
      desc: 'Bejana tekanan rendah yang memisahkan cairan dan uap amonia. Level normal 30 % agar kompresor hanya menghisap uap.', vars: ['PLP', 'LSD'] },
    { id: 'P-1001', type: 'pump', x: 640, y: 430, name: 'Pompa Amonia Cair P-1001',
      desc: 'Mengalirkan amonia cair dingin dari separator ke evaporator ruang beku.' },
    { id: 'EV-1001', type: 'cooler', x: 740, y: 380, w: 150, h: 60, fans: 2, name: 'Evaporator Ruang Beku EV-1001',
      desc: 'Koil bersirip dengan kipas yang mendinginkan udara ruang beku. Es pada koil dicairkan secara berkala dengan gas panas.', vars: ['PEV', 'TCR', 'QC'] },
    { id: 'XV-1003', type: 'valve', sub: 'control', x: 600, y: 160, tag: 'XV', name: 'XV-1003 (Katup Gas Panas Defrost)',
      desc: 'Katup solenoid yang memasukkan gas panas dari discharge kompresor ke koil evaporator saat defrost. Saat ini katup dibuka penuh secara mendadak oleh timer.' },
    { id: 'CR-1000', type: 'building', x: 110, y: 470, name: 'Ruang Kontrol',
      desc: 'Operator memantau tekanan, suhu, dan level sistem amonia. Lokasi tombol ESD.' },
    { id: 'MP-1000', type: 'muster', x: 110, y: 360, name: 'Titik Kumpul',
      desc: 'Area berkumpul pada arah angin yang aman, jauh dari kondensor di atap dan ruang mesin.' },
  ],
  pipes: [
    { id: 'hg1', fluid: 'gas', w: 6, pts: [[280, 272], [280, 120]], arrow: true },
    { id: 'liq1', fluid: 'nh3', w: 5, pts: [[380, 120], [380, 200]], arrow: true },
    { id: 'liq2', fluid: 'nh3', w: 5, pts: [[470, 225], [560, 225], [560, 320]], arrow: true },
    { id: 'suc', fluid: 'gas', w: 7, pts: [[500, 320], [500, 300], [308, 300]], arrow: true },
    { id: 'liq3', fluid: 'nh3', w: 5, pts: [[600, 376], [600, 430], [618, 430]] },
    { id: 'liq4', fluid: 'nh3', w: 5, pts: [[662, 430], [740, 430]], arrow: true },
    { id: 'ret', fluid: 'gas', w: 6, pts: [[748, 382], [748, 340], [640, 340]], arrow: true },
    { id: 'df', fluid: 'gas', w: 4, dashed: true, pts: [[280, 160], [720, 160], [720, 395], [740, 395]] },
    { id: 'cwp', fluid: 'cw', w: 4, pts: [[192, 95], [230, 95]] },
  ],
  labels: [
    { x: 470, y: 150, text: 'Gas panas defrost', size: 10 },
    { x: 315, y: 30, text: 'Atap', size: 10 },
  ],
  vars: {
    PHP: { label: 'Tekanan Kondensasi', unit: 'barg', normal: 12.5, min: 0, max: 25, hi: 15.5, hihi: 17.5, node: 'E-1001', x: 470, y: 85, tau: 4, noise: 0.03, dec: 1 },
    LRC: { label: 'Level Receiver V-1001', unit: '%', normal: 50, min: 0, max: 100, lo: 20, hi: 80, node: 'V-1001', x: 400, y: 272, tau: 5, noise: 0.2, dec: 0 },
    PLP: { label: 'Tekanan Hisap', unit: 'barg', normal: 0.5, min: -0.5, max: 4, lo: 0.1, hi: 1.5, node: 'V-1002', x: 520, y: 400, tau: 3, noise: 0.01, dec: 2 },
    LSD: { label: 'Level Separator Hisap V-1002', unit: '%', normal: 30, min: 0, max: 100, hi: 60, hihi: 75, node: 'V-1002', x: 520, y: 428, tau: 4, noise: 0.3, dec: 0 },
    TDK: { label: 'Suhu Discharge Kompresor', unit: '°C', normal: 70, min: 0, max: 160, lo: 45, hi: 90, hihi: 100, node: 'K-1001', x: 205, y: 300, tau: 4, noise: 0.2, dec: 0 },
    FCD: { label: 'Aliran Air Kondensor', unit: 'm³/j', normal: 60, min: 0, max: 100, lo: 30, lolo: 15, node: 'E-1001', x: 140, y: 60, tau: 2, noise: 0.4, dec: 0 },
    PEV: { label: 'Tekanan Koil Evaporator', unit: 'barg', normal: 0.4, min: -0.5, max: 25, hi: 8, hihi: 12, node: 'EV-1001', x: 815, y: 490, tau: 0.6, noise: 0.01, dec: 1 },
    TCR: { label: 'Suhu Ruang Beku', unit: '°C', normal: -25, min: -40, max: 10, hi: -18, node: 'EV-1001', x: 900, y: 335, tau: 6, noise: 0.05, dec: 1 },
    QC:  { label: 'Beban Pendinginan', unit: 'kW', normal: 600, min: 0, max: 1000, node: 'EV-1001', x: 880, y: 518, tau: 3, noise: 2, dec: 0 },
  },
  trendVars: ['PHP', 'LSD', 'TDK', 'PEV'],
  controls: [
    { id: 'load', label: 'Beban pendinginan ruang beku', unit: 'kW', min: 300, max: 800, def: 600, step: 50,
      effects: [{ var: 'QC', gain: 1 }, { var: 'PHP', gain: 0.004 }, { var: 'TDK', gain: 0.02 }, { var: 'PLP', gain: 0.001 }] },
    { id: 'tset', label: 'Set point suhu ruang beku', unit: '°C', min: -30, max: -18, def: -25, step: 1,
      effects: [{ var: 'TCR', gain: 1 }, { var: 'PLP', gain: 0.06 }] },
    { id: 'wet', label: 'Suhu bola basah udara luar', unit: '°C', min: 22, max: 30, def: 26, step: 1,
      effects: [{ var: 'PHP', gain: 0.35 }, { var: 'TDK', gain: 1 }] },
  ],
  quiz: [
    { q: 'Mengapa amonia banyak dipakai sebagai refrigeran industri?', opts: ['Efisiensi termodinamikanya tinggi dan tidak merusak ozon, tetapi beracun dan dapat terbakar', 'Efisiensinya tinggi dan tidak beracun pada konsentrasi kerja, sehingga cocok untuk ruang tertutup', 'Tidak merusak ozon dan tidak dapat terbakar, sehingga risiko utamanya hanya kebocoran dingin', 'Murah dan tekanan kerjanya rendah, sehingga sistemnya tidak memerlukan bejana bertekanan maupun katup pengaman'], ans: 0,
      why: 'Amonia (R-717) efisien dan ramah ozon, sehingga umum di industri makanan beku. Konsekuensinya, sistem amonia memerlukan pengelolaan keselamatan proses yang ketat.' },
    { q: 'Apa fungsi separator hisap V-1002?', opts: ['Memisahkan cairan amonia dari uap sehingga hanya uap yang terhisap kompresor', 'Menampung amonia cair hasil kondensasi pada tekanan tinggi sebelum dialirkan ke evaporator', 'Memisahkan oli kompresor dari uap amonia sebelum masuk kondensor', 'Menurunkan tekanan amonia cair dari receiver menjadi tekanan evaporator ruang beku'], ans: 0,
      why: 'Cairan yang terhisap kompresor menyebabkan liquid slugging yang dapat merusak kompresor dan melepaskan amonia.' },
    { q: 'Mengapa hentakan hidraulik (hydraulic shock) berbahaya pada sistem amonia?', opts: ['Gelombang tekanan sesaat dapat jauh melampaui tekanan desain dan meretakkan koil, katup, atau pipa', 'Hentakan membuat kompresor menghisap cairan sehingga terjadi liquid slugging di dalam silinder', 'Getaran berulang melonggarkan baut flens sehingga amonia hanya merembes perlahan', 'Penurunan tekanan mendadak membuat amonia membeku dan menyumbat koil evaporator di ruang beku'], ans: 0,
      why: 'Insiden pelepasan amonia di Millard Refrigerated Services, Alabama, tahun 2010 yang diselidiki CSB dipicu hentakan hidraulik saat siklus defrost.' },
    { q: 'Berapa nilai ambang batas (NAB) amonia di tempat kerja menurut Permenaker No. 5 Tahun 2018?', opts: ['25 ppm', '35 ppm', '50 ppm', '300 ppm'], ans: 0,
      why: 'NAB amonia 25 ppm untuk paparan 8 jam. Angka 35 ppm adalah batas paparan singkat menurut ACGIH, 50 ppm batas paparan OSHA, dan sekitar 300 ppm adalah nilai IDLH menurut NIOSH, yaitu konsentrasi yang langsung berbahaya bagi jiwa.' },
    { q: 'Mengapa pelepasan katup pengaman amonia tidak boleh langsung ke area kerja?', opts: ['Amonia beracun, sehingga pelepasan diarahkan ke titik aman atau sistem penanganan seperti tangki difusi air', 'Amonia lebih berat dari udara sehingga pelepasan akan menggenang lama di lantai area kerja', 'Pelepasan ke area kerja akan langsung menyala karena amonia mudah terbakar di udara terbuka', 'Pelepasan ke area kerja tidak berbahaya, tetapi dilarang karena amonia mahal dan harus didaur ulang'], ans: 0,
      why: 'IIAR 2 mengatur titik buang katup pengaman. Amonia sangat mudah larut dalam air sehingga tangki difusi dan tirai air efektif menurunkan konsentrasi pelepasan.' },
  ],
  events: [
    { id: 'e1', threat: 0, effects: [{ var: 'FCD', to: 0, delay: 1, dur: 3 }, { var: 'PHP', to: 20.5, delay: 2, dur: 22 }],
      warnings: [
        { t: 12, type: 'vibration', sev: 'warn', at: 'K-1001', text: 'Kompresor K-1001 bekerja berat; suara dan getaran meningkat.' },
        { t: 18, type: 'toxic', sev: 'crit', at: 'E-1001', pos: [315, 62], text: 'GAS AMONIA: bau sangat menyengat dari atap; sambungan kondensor mulai bocor.' },
        { t: 26, type: 'toxic', sev: 'final', at: 'E-1001', pos: [330, 118], big: true, text: 'Sambungan kondensor pecah; awan amonia besar menyebar ke area produksi dan permukiman di sekitar pabrik.' },
      ],
      answer: { node: ['E-1001', 'P-1002'], param: ['P', 'F'], guide: ['high', 'none'] },
      hint: 'Panas tidak lagi dibuang di kondensor. Periksa air dan kipas kondensor evaporatif.',
      causes: ['Pompa air atau kipas kondensor evaporatif berhenti sehingga uap amonia tidak terkondensasi', 'Beban ruang beku turun', 'Level separator turun', 'Suhu ruang beku terlalu rendah'], causeAns: 0,
      cons: ['Tekanan sisi tinggi melampaui desain, sambungan atau koil kondensor pecah dan melepaskan amonia beracun', 'Suhu ruang beku turun lebih cepat', 'Kompresor bekerja lebih ringan', 'Level receiver naik tanpa dampak'], consAns: 0,
      explain: 'Aliran air kondensor hilang lalu tekanan kondensasi naik terus. Tanpa pembuangan panas, kompresor terus menekan uap ke kondensor. Proteksi yang tepat adalah sakelar tekanan tinggi yang menghentikan kompresor, alarm tekanan, dan katup pengaman yang dibuang ke sistem penanganan amonia (IIAR 2, ASHRAE 15).' },
    { id: 'e2', threat: 1, effects: [{ var: 'LSD', to: 98, delay: 2, dur: 16 }, { var: 'TDK', to: 38, delay: 6, dur: 10 }],
      warnings: [
        { t: 14, type: 'vibration', sev: 'warn', at: 'K-1001', text: 'Bunyi ketukan keras (liquid knocking) dari kompresor; bunga es terbentuk di pipa hisap.' },
        { t: 20, type: 'leak', sev: 'crit', at: 'K-1001', pos: [280, 262], text: 'Seal poros kompresor rusak; uap amonia putih menyembur di ruang mesin.' },
        { t: 27, type: 'toxic', sev: 'final', at: 'K-1001', pos: [300, 300], big: true, text: 'Casing kompresor retak; pelepasan amonia besar memenuhi ruang mesin dan operator terpapar.' },
      ],
      answer: { node: ['V-1002', 'K-1001', 'LCV-1001'], param: ['L'], guide: ['high'] },
      hint: 'Cairan amonia terus menumpuk di separator hisap hingga terbawa ke kompresor.',
      causes: ['LCV-1001 macet terbuka atau pompa amonia trip sehingga separator hisap terisi cairan berlebih', 'Air kondensor hilang', 'Suhu ruang beku naik', 'Katup defrost terbuka'], causeAns: 0,
      cons: ['Cairan amonia terbawa ke kompresor (liquid slugging), kompresor rusak dan melepaskan amonia di ruang mesin', 'Tekanan kondensasi turun tanpa dampak', 'Suhu ruang beku turun', 'Level receiver naik'], consAns: 0,
      explain: 'Level separator hisap naik terus lalu suhu discharge kompresor turun tajam, tanda cairan ikut terhisap. Kompresor tidak dirancang menekan cairan sehingga dapat rusak berat. Proteksi yang tepat adalah alarm dan trip level tinggi-tinggi separator yang menghentikan kompresor.' },
    { id: 'e3', threat: 2, effects: [{ var: 'PEV', to: 18, delay: 1, dur: 3 }, { var: 'TCR', to: -12, delay: 4, dur: 10 }],
      warnings: [
        { t: 5, type: 'vibration', sev: 'warn', at: 'EV-1001', text: 'Dentuman keras (hydraulic shock) di pipa evaporator saat katup gas panas dibuka untuk defrost.' },
        { t: 11, type: 'leak', sev: 'crit', at: 'EV-1001', pos: [815, 402], text: 'Koil evaporator retak; kabut amonia putih memenuhi ruang beku.' },
        { t: 18, type: 'toxic', sev: 'final', at: 'EV-1001', pos: [822, 420], big: true, text: 'Pekerja di dalam ruang beku terpapar amonia konsentrasi tinggi; evakuasi dan penyelamatan darurat diperlukan.' },
      ],
      answer: { node: ['EV-1001', 'XV-1003'], param: ['P'], guide: ['high'] },
      hint: 'Tekanan koil melonjak sesaat ketika gas panas dimasukkan ke koil yang masih berisi cairan dingin.',
      causes: ['Katup gas panas dibuka mendadak saat koil evaporator belum dikosongkan, sehingga terjadi hentakan hidraulik', 'Air kondensor hilang', 'Separator hisap kosong', 'Beban ruang beku turun'], causeAns: 0,
      cons: ['Koil atau pipa evaporator retak dan melepaskan amonia di ruang beku tempat pekerja berada', 'Suhu ruang beku turun', 'Tekanan kondensasi turun', 'Kompresor bekerja lebih ringan'], consAns: 0,
      explain: 'Tekanan koil melonjak dalam hitungan detik saat defrost dimulai. Hentakan hidraulik terjadi ketika gas panas mendorong cairan dingin dengan kecepatan tinggi atau mengembun mendadak dan menciptakan gelombang tekanan. Insiden pelepasan amonia di Millard Refrigerated Services, Alabama, tahun 2010 dipicu mekanisme ini. Proteksi yang tepat adalah interlock urutan defrost dengan katup gas panas yang membuka bertahap.' },
    { id: 'e4', threat: 3, effects: [{ var: 'TDK', to: 125, delay: 1, dur: 16 }],
      warnings: [
        { t: 13, type: 'heat', sev: 'warn', at: 'K-1001', text: 'Pendingin oli kompresor tidak bekerja; pipa discharge sangat panas dan oli menghitam.' },
        { t: 19, type: 'leak', sev: 'crit', at: 'K-1001', pos: [280, 262], text: 'Uap amonia dan oli keluar dari seal poros kompresor yang kepanasan.' },
        { t: 26, type: 'toxic', sev: 'final', at: 'K-1001', pos: [300, 300], big: true, text: 'Pelepasan amonia di ruang mesin; operator terpapar dan konsentrasi melampaui batas bahaya.' },
      ],
      answer: { node: ['K-1001'], param: ['T'], guide: ['high'] },
      hint: 'Suhu discharge naik tanpa perubahan tekanan kondensasi. Panas kompresi tidak lagi diserap sistem oli.',
      causes: ['Pendingin oli kompresor gagal sehingga suhu discharge dan oli naik', 'Pompa amonia trip', 'Katup defrost dibuka', 'Suhu ruang beku turun'], causeAns: 0,
      cons: ['Oli rusak dan seal kompresor gagal sehingga amonia bocor di ruang mesin', 'Tekanan hisap turun tanpa dampak', 'Level separator naik', 'Ruang beku menjadi lebih dingin'], consAns: 0,
      explain: 'Suhu discharge naik terus tanpa perubahan tekanan kondensasi. Pada kompresor screw berinjeksi oli, oli menyerap panas kompresi. Bila pendinginan oli gagal, oli rusak dan seal poros cepat aus. Proteksi yang tepat adalah alarm dan trip suhu discharge tinggi-tinggi yang menghentikan kompresor.' },
    { id: 'e5', start: 13,
      hf: { type: 'mistake', team: 'mtc', threat: 2, title: 'Defrost dipercepat dengan membuka katup manual', factor: 'Katup gas panas dibuka manual oleh teknisi belum kompeten',
        roles: { tono: 'Teknisi Baru (Masa Orientasi)', joko: 'Teknisi Refrigerasi Senior' },
        lesson: 'Tono melakukan mistake berbasis pengetahuan: niatnya mempercepat defrost, tetapi ia tidak memahami bahwa koil harus dikosongkan dan tekanannya disamakan terlebih dahulu. Pekerjaan pada sistem amonia di luar kompetensinya juga menunjukkan lemahnya pendampingan pekerja baru. Senior sudah mengingatkan, tetapi terlambat. Kontrolnya adalah pembatasan pekerjaan sistem amonia pada teknisi kompeten, pengendalian akses ke stem darurat, dan pelatihan khusus bahaya hentakan hidraulik.',
        controls: ['Pekerjaan sistem amonia hanya oleh teknisi refrigerasi kompeten', 'Defrost mengikuti urutan otomatis; pembukaan manual memerlukan prosedur dan izin', 'Pendampingan dan pelatihan pekerja baru tentang hentakan hidraulik'] },
      chat: [
        { t: 1, who: 'hendra', at: 'CR-1000', text: 'Koil evaporator ruang beku penuh es. Produk dari kapal masuk jam sembilan, ruang harus sudah dingin.' },
        { t: 4, who: 'tono', at: 'XV-1003', mood: 'santai', text: 'Defrost otomatis lama sekali. Katup gas panas XV-1003 kubuka manual saja pakai stem darurat.' },
        { t: 7, who: 'joko', at: 'V-1001', mood: 'ragu', text: 'Tono, tunggu. Koil harus dikosongkan dulu dan tekanannya disamakan sebelum gas panas masuk.' },
        { t: 10, who: 'tono', at: 'XV-1003', mood: 'santai', text: 'Tenang, kubuka sekaligus penuh biar esnya cepat cair.' },
        { t: 15, who: 'raka', at: 'CR-1000', mood: 'ragu', text: 'Siapa yang membuka XV-1003? Urutan defrost di panel belum berjalan.' },
        { t: 18, who: 'joko', at: 'EV-1001', mood: 'panik', text: 'Tono, tutup! Jangan dibuka sekaligus!' },
        { t: 26, who: 'raka', at: 'CR-1000', mood: 'panik', text: 'Detektor amonia ruang beku berbunyi! Semua keluar dari ruang beku sekarang!' },
      ],
      effects: [{ var: 'PEV', to: 18, delay: 1, dur: 3 }, { var: 'TCR', to: -12, delay: 4, dur: 10 }],
      warnings: [
        { t: 5, type: 'vibration', sev: 'warn', at: 'EV-1001', text: 'Dentuman keras (hydraulic shock) di pipa evaporator saat gas panas masuk sekaligus.' },
        { t: 11, type: 'leak', sev: 'crit', at: 'EV-1001', pos: [815, 402], text: 'Koil evaporator retak; kabut amonia putih memenuhi ruang beku.' },
        { t: 18, type: 'toxic', sev: 'final', at: 'EV-1001', pos: [822, 420], big: true, text: 'Pekerja di dalam ruang beku terpapar amonia konsentrasi tinggi; evakuasi dan penyelamatan darurat diperlukan.' },
      ],
      answer: { node: ['EV-1001', 'XV-1003'], param: ['P'], guide: ['high'] },
      hint: 'Tekanan koil melonjak dalam hitungan detik saat gas panas masuk. Katupnya dibuka tanpa melalui urutan otomatis. Baca kembali obrolan tentang cara mempercepat defrost.',
      causes: ['Teknisi baru membuka penuh katup gas panas secara manual sebelum koil dikosongkan karena tidak memahami bahaya hentakan hidraulik', 'Pengendali urutan defrost rusak sehingga katup gas panas membuka terlalu cepat', 'Katup pengaman evaporator macet tertutup sehingga tekanan tidak dapat dilepas', 'Es tebal pada koil menyumbat aliran gas panas sehingga tekanan naik perlahan'], causeAns: 0,
      cons: ['Gelombang tekanan meretakkan koil atau pipa evaporator sehingga amonia lepas di ruang beku tempat pekerja berada', 'Es mencair lebih cepat dan ruang beku siap lebih awal', 'Kompresor menghisap cairan lalu berhenti otomatis tanpa kebocoran', 'Suhu ruang beku turun karena gas panas mendinginkan koil'], consAns: 0,
      explain: 'Tekanan koil melonjak tajam sesaat setelah katup gas panas dibuka. Gas panas yang dimasukkan sekaligus ke koil yang masih berisi cairan dingin mendorong atau mengembunkan cairan secara mendadak sehingga timbul hentakan hidraulik. Insiden Millard Refrigerated Services tahun 2010 yang diselidiki CSB berawal dari mekanisme serupa.' },
    { id: 'e6', threat: 0, effects: [{ var: 'PHP', to: 18.5, delay: 1, dur: 16 }, { var: 'TDK', to: 88, delay: 3, dur: 16 }],
      warnings: [
        { t: 14, type: 'vibration', sev: 'warn', at: 'K-1001', text: 'Kompresor bekerja berat dan arus motornya tinggi, padahal pompa air dan kipas kondensor berjalan normal.' },
        { t: 20, type: 'leak', sev: 'crit', at: 'E-1001', pos: [315, 62], text: 'Katup pengaman sisi tekanan tinggi mulai mendesis dan bau amonia tercium di atap.' },
        { t: 27, type: 'toxic', sev: 'final', at: 'E-1001', pos: [330, 118], big: true, text: 'Katup pengaman membuka penuh dan flens kondensor bocor. Awan amonia menyebar dari atap ke area produksi.' },
      ],
      answer: { node: ['E-1001'], param: ['C', 'P'], guide: ['aswell', 'high'] },
      hint: 'Tekanan kondensasi naik perlahan, padahal aliran air dan kipas kondensor normal. Pikirkan gas lain yang dapat ikut berada di sisi tekanan tinggi dan menghalangi pengembunan.',
      causes: ['Udara dan gas tak terkondensasi menumpuk di kondensor karena purger otomatis rusak, sehingga pengembunan amonia terhambat', 'Pompa air kondensor P-1002 berhenti sehingga koil tidak tersemprot air', 'Level separator hisap naik sehingga cairan terhisap ke kompresor', 'Pendingin oli kompresor gagal sehingga suhu discharge naik'], causeAns: 0,
      cons: ['Tekanan sisi tinggi naik hingga katup pengaman membuka atau flens bocor, sehingga amonia lepas ke atap dan area sekitar', 'Kapasitas pendinginan naik karena tekanan sisi tinggi lebih besar', 'Suhu ruang beku turun lebih cepat dari biasanya', 'Level receiver naik tanpa dampak keselamatan'], consAns: 0,
      explain: 'Tekanan kondensasi naik perlahan dan suhu discharge ikut naik, sementara aliran air kondensor tetap normal. Udara yang masuk ke sistem, misalnya melalui seal di sisi tekanan rendah atau saat perbaikan, tidak dapat mengembun dan menumpuk di kondensor sehingga menghalangi pengembunan amonia. Ini deviasi komposisi Serta (As well as): amonia disertai udara yang tidak dikehendaki. Purger udara otomatis membuang gas tak terkondensasi, sedangkan alarm dan sakelar tekanan tinggi yang menghentikan kompresor tetap diperlukan sebagai lapisan pengaman.' },
    { id: 'e7', start: 12,
      hf: { type: 'slip', team: 'ops', threat: 0, title: 'Breaker pompa air kondensor yang sedang beroperasi dimatikan alih-alih pompa cadangan', factor: 'Breaker pompa yang salah dimatikan saat isolasi',
        lesson: 'Dimas bermaksud mengisolasi breaker pompa cadangan P-1002B, tetapi yang ia matikan adalah breaker P-1002 yang letaknya bersebelahan dan labelnya kecil. Niatnya benar, tindakannya mengenai objek yang salah, sehingga tergolong slip. Slip seperti ini dicegah dengan desain dan cara kerja, bukan imbauan: label yang besar dan berwarna, verifikasi identitas peralatan bersama orang kedua sebelum isolasi, serta uji coba start setelah gembok dipasang untuk memastikan peralatan yang benar sudah terisolasi. Alarm aliran air kondensor dan sakelar tekanan tinggi yang menghentikan kompresor tetap diperlukan.',
        controls: ['Label breaker yang besar, jelas, dan berkode warna di panel MCC', 'Verifikasi identitas peralatan bersama orang kedua dan uji coba start setelah isolasi', 'Alarm aliran air kondensor dan sakelar tekanan tinggi yang menghentikan kompresor'] },
      chat: [
        { t: 1, who: 'joko', at: 'P-1002', text: 'Dimas, seal pompa cadangan P-1002B mau kuganti. Tolong isolasi breaker-nya di panel MCC dan pasang gembok.' },
        { t: 4, who: 'dimas', at: 'CR-1000', text: 'Siap. Breaker P-1002 dan P-1002B letaknya bersebelahan, labelnya kecil sekali.' },
        { t: 7, who: 'dimas', at: 'CR-1000', mood: 'santai', text: 'Breaker sudah kumatikan dan kugembok. Silakan mulai, Joko.' },
        { t: 10, who: 'joko', at: 'P-1002', text: 'Oke, aku mulai bongkar pompa cadangan.' },
        { t: 20, who: 'raka', at: 'CR-1000', mood: 'ragu', text: 'Aliran air kondensor hampir nol di layar dan tekanan kondensasi mulai naik.' },
        { t: 24, who: 'dimas', at: 'CR-1000', mood: 'panik', text: 'Astaga, breaker yang kumatikan ternyata P-1002, pompa yang sedang jalan!' },
        { t: 28, who: 'raka', at: 'CR-1000', mood: 'panik', text: 'Tekanan kondensasi terus naik! Hidupkan lagi P-1002 sekarang dan kurangi beban kompresor!' },
      ],
      effects: [{ var: 'FCD', to: 0, delay: 1, dur: 3 }, { var: 'PHP', to: 20.5, delay: 2, dur: 22 }],
      warnings: [
        { t: 12, type: 'vibration', sev: 'warn', at: 'K-1001', text: 'Kipas kondensor tetap berputar, tetapi koil kering tanpa semprotan air dan kompresor bekerja berat.' },
        { t: 18, type: 'toxic', sev: 'crit', at: 'E-1001', pos: [315, 62], text: 'Bau amonia sangat menyengat dari atap. Sambungan kondensor mulai bocor.' },
        { t: 26, type: 'toxic', sev: 'final', at: 'E-1001', pos: [330, 118], big: true, text: 'Sambungan kondensor pecah. Awan amonia besar menyebar ke area produksi dan permukiman.' },
      ],
      answer: { node: ['E-1001', 'P-1002'], param: ['P', 'F'], guide: ['high', 'none'] },
      hint: 'Aliran air kondensor hilang tepat setelah pekerjaan isolasi pompa. Baca kembali obrolan tentang breaker yang dimatikan.',
      causes: ['Operator mematikan breaker pompa air kondensor yang sedang beroperasi karena tertukar dengan breaker pompa cadangan yang letaknya bersebelahan', 'Motor pompa P-1002 terbakar karena bantalannya macet', 'Bak air kondensor kosong karena katup air make-up tertutup', 'Transmitter aliran air kondensor rusak sehingga aliran terbaca nol palsu'], causeAns: 0,
      cons: ['Tekanan sisi tinggi melampaui desain, sambungan kondensor pecah, dan amonia beracun lepas ke area produksi dan permukiman', 'Kompresor berhenti sendiri tanpa kebocoran karena bebannya turun', 'Suhu ruang beku turun karena kompresor bekerja lebih berat', 'Pompa cadangan menyala otomatis sehingga tidak ada dampak'], consAns: 0,
      explain: 'Aliran air kondensor turun ke nol lalu tekanan kondensasi naik terus, polanya sama dengan kegagalan pompa air kondensor. Bedanya, pompa tidak rusak: breaker-nya dimatikan karena tertukar dengan pompa cadangan. Isolasi energi yang benar mencakup verifikasi identitas peralatan dan uji coba start, sementara sakelar tekanan tinggi tetap menjadi pengaman terakhir kompresor.' },
    { id: 'e8', start: 12,
      hf: { type: 'violation', team: 'mgmt', threat: 3, title: 'Setting trip suhu discharge kompresor dinaikkan tanpa MOC demi beban pendinginan', factor: 'Setting trip suhu discharge dinaikkan tanpa MOC',
        roles: { hendra: 'Supervisor Produksi', joko: 'Teknisi Refrigerasi' },
        lesson: 'Hendra tahu setting trip adalah batas aman yang tidak boleh diubah sembarangan, tetapi memerintahkan menaikkannya agar kompresor tidak berhenti sebelum kapal datang. Joko melaksanakannya walaupun tahu akar masalahnya adalah pendingin oli yang kotor. Penyimpangan yang disengaja dari aturan yang diketahui tergolong violation. Mengubah setting trip sama dengan menghapus lapisan proteksi, karena kompresor dibiarkan bekerja melewati batas yang ditetapkan pabrikan. Pencegahnya adalah pengendalian perubahan setting melalui MOC, akses setting yang dikunci, dan perencanaan pemeliharaan agar pembersihan pendingin oli tidak dikalahkan jadwal produksi.',
        controls: ['Perubahan setting trip hanya melalui MOC dengan kajian teknis', 'Akses parameter trip dikunci dan setiap perubahan tercatat', 'Pemeliharaan pendingin oli terjadwal sehingga tidak dikalahkan target produksi'] },
      chat: [
        { t: 1, who: 'hendra', at: 'CR-1000', text: 'Kompresor K-1001 sudah tiga kali trip suhu discharge siang ini. Kapal ikan datang sore, ruang beku tidak boleh hangat.' },
        { t: 4, who: 'joko', at: 'K-1001', mood: 'ragu', text: 'Pendingin olinya kotor, Pak. Harus dibersihkan, tapi kompresor perlu berhenti dua jam.' },
        { t: 7, who: 'hendra', at: 'CR-1000', mood: 'santai', text: 'Tidak bisa berhenti sekarang. Naikkan saja setting trip suhunya ke 130 derajat sampai akhir bulan.' },
        { t: 10, who: 'joko', at: 'K-1001', mood: 'santai', text: 'Oke, setting trip sudah kunaikkan. Kompresor tidak akan trip lagi.' },
        { t: 26, who: 'raka', at: 'CR-1000', mood: 'ragu', text: 'Suhu discharge sudah lewat batas trip yang lama dan terus naik.' },
        { t: 29, who: 'dimas', at: 'K-1001', mood: 'ragu', text: 'Oli di kaca intip kompresor menghitam dan baunya hangus!' },
        { t: 32, who: 'raka', at: 'CR-1000', mood: 'panik', text: 'Detektor amonia ruang mesin berbunyi! Hentikan kompresor manual dan semua keluar!' },
      ],
      effects: [{ var: 'TDK', to: 125, delay: 1, dur: 16 }],
      warnings: [
        { t: 13, type: 'heat', sev: 'warn', at: 'K-1001', text: 'Pendingin oli kompresor kotor dan sangat panas. Kompresor tetap berjalan melewati suhu trip lamanya.' },
        { t: 19, type: 'leak', sev: 'crit', at: 'K-1001', pos: [280, 262], text: 'Seal poros kompresor yang kepanasan bocor. Uap amonia dan asap oli keluar di ruang mesin.' },
        { t: 26, type: 'toxic', sev: 'final', at: 'K-1001', pos: [300, 300], big: true, text: 'Pelepasan amonia memenuhi ruang mesin. Operator terpapar dan konsentrasi melampaui batas bahaya.' },
      ],
      answer: { node: ['K-1001'], param: ['T'], guide: ['high'] },
      hint: 'Suhu discharge naik melewati batas trip yang lama, tetapi kompresor tidak berhenti. Baca kembali obrolan tentang setting trip dan pendingin oli.',
      causes: ['Setting trip suhu discharge sengaja dinaikkan tanpa MOC sehingga kompresor terus bekerja walaupun pendingin oli kotor', 'Air kondensor hilang sehingga tekanan kondensasi naik', 'Cairan amonia terhisap ke kompresor dari separator hisap', 'Katup gas panas defrost dibuka mendadak'], causeAns: 0,
      cons: ['Oli rusak dan seal poros kompresor gagal sehingga amonia bocor di ruang mesin', 'Kompresor bekerja lebih efisien pada suhu tinggi', 'Ruang beku menjadi lebih dingin karena kompresor tidak pernah trip', 'Tekanan hisap turun tanpa dampak keselamatan'], consAns: 0,
      explain: 'Suhu discharge naik terus tanpa perubahan tekanan kondensasi, polanya sama dengan kegagalan pendinginan oli. Bedanya, kompresor tidak berhenti karena setting trip-nya sengaja dinaikkan. Trip suhu discharge adalah lapisan proteksi terhadap kerusakan oli dan seal, sehingga setting-nya hanya boleh diubah melalui MOC dengan kajian teknis.' },
  ],
  variants: [
    ['e4', 'e6', 'e7', 'e2', 'e5'],
    ['e6', 'e2', 'e7', 'e3', 'e8'],
    ['e1', 'e2', 'e8', 'e4', 'e5'],
    ['e2', 'e4', 'e5', 'e1', 'e7'],
    ['e3', 'e4', 'e8', 'e6', 'e7'],
  ],
  hotspots: [
    /* Tahap 3: pencegahan */
    { id: 'h31', stage: 3, x: 280, y: 236, label: 'Discharge kompresor (sakelar tekanan tinggi)', accept: ['HPCO'],
      why: 'Sakelar tekanan tinggi menghentikan kompresor sebelum tekanan mencapai set katup pengaman, sehingga amonia tidak perlu dilepas.' },
    { id: 'h32', stage: 3, x: 440, y: 192, label: 'Receiver V-1001 (katup pengaman)', accept: ['PSV'],
      why: 'Katup pengaman pada receiver wajib melindungi bejana bertekanan dari tekanan berlebih, termasuk akibat paparan api (IIAR 2).' },
    { id: 'h33', stage: 3, x: 414, y: 130, label: 'Kondensor (transmitter tekanan)', accept: ['PT'],
      why: 'Alarm tekanan kondensasi memberi peringatan dini kegagalan air atau kipas kondensor.' },
    { id: 'h34', stage: 3, x: 482, y: 360, label: 'Separator hisap V-1002 (level)', accept: ['LSHH', 'LT'],
      why: 'Trip level tinggi-tinggi menghentikan kompresor sebelum cairan terhisap. Alarm level diterima sebagai lapisan respons operator.' },
    { id: 'h35', stage: 3, x: 234, y: 268, label: 'Discharge kompresor (suhu)', accept: ['TSHH', 'TT'],
      why: 'Trip suhu discharge tinggi-tinggi menghentikan kompresor saat pendinginan oli gagal. Alarm suhu diterima sebagai lapisan operator.' },
    { id: 'h36', stage: 3, x: 650, y: 160, label: 'Katup gas panas defrost (interlock urutan)', accept: ['DEFI'],
      why: 'Interlock urutan defrost memastikan koil dikosongkan dan tekanan disamakan sebelum gas panas masuk secara bertahap, mencegah hentakan hidraulik.' },
    { id: 'h37', stage: 3, x: 700, y: 430, label: 'Discharge pompa amonia P-1001', accept: ['NRV'],
      why: 'Check valve mencegah aliran balik amonia dari evaporator ke pompa yang berhenti.' },
    { id: 'h38', stage: 3, x: 950, y: 480, label: 'Pintu ruang beku', accept: [],
      why: 'Pintu ruang beku penting untuk efisiensi energi dan jalur evakuasi, tetapi bukan barier terhadap ancaman proses yang teridentifikasi.' },
    { id: 'h39', stage: 3, x: 210, y: 95, label: 'Pipa air kondensor', accept: [],
      why: 'Air kondensor bukan bahan berbahaya. Ancaman tekanan tinggi ditangani pada sisi amonia, bukan dengan perangkat pada pipa air.' },
    /* Tahap 4: mitigasi */
    { id: 'h41', stage: 4, x: 240, y: 380, label: 'Ruang mesin (detektor amonia)', accept: ['GD'],
      why: 'Detektor amonia di ruang mesin memicu alarm, ventilasi darurat, dan penghentian kompresor (IIAR 2).' },
    { id: 'h42', stage: 4, x: 210, y: 195, label: 'Ruang mesin (ventilasi darurat)', accept: ['EXV'],
      why: 'Ventilasi darurat menjaga konsentrasi amonia di bawah batas mudah terbakar dan mengurangi paparan di ruang mesin.' },
    { id: 'h43', stage: 4, x: 950, y: 410, label: 'Ruang beku (detektor amonia)', accept: ['GD'],
      why: 'Detektor amonia di ruang beku memberi peringatan segera kepada pekerja di dalam ruang dingin yang tertutup.' },
    { id: 'h44', stage: 4, x: 470, y: 185, label: 'Outlet katup pengaman receiver (penanganan amonia)', accept: ['SCRUB'],
      why: 'Pelepasan katup pengaman diarahkan ke tangki difusi air atau scrubber sehingga amonia tidak langsung lepas ke atmosfer.' },
    { id: 'h45', stage: 4, x: 492, y: 225, label: 'Jalur cair keluar receiver (isolasi jarak jauh)', accept: ['EIV'],
      why: 'Katup isolasi jarak jauh (king valve) menghentikan aliran amonia cair dari inventori terbesar ke titik bocor.' },
    { id: 'h46', stage: 4, x: 160, y: 448, label: 'Ruang kontrol (ESD)', accept: ['ESD'],
      why: 'ESD menghentikan kompresor, pompa, dan menutup katup isolasi secara serentak dari luar ruang mesin.' },
    { id: 'h47', stage: 4, x: 440, y: 50, label: 'Atap kondensor (tirai semprot air)', accept: ['WCUR'],
      why: 'Tirai air menyerap amonia yang lepas di atap sehingga konsentrasi yang terbawa angin ke permukiman berkurang.' },
    { id: 'h48', stage: 4, x: 60, y: 425, label: 'Pos jaga (SCBA dan detektor personal)', accept: ['SCBA'],
      why: 'Alat bantu napas memungkinkan regu tanggap darurat masuk ke area amonia untuk penyelamatan dan isolasi.' },
    { id: 'h49', stage: 4, x: 160, y: 360, label: 'Titik kumpul (arah angin) dan alarm umum', accept: ['ALARM'],
      why: 'Evakuasi harus melawan atau menyamping arah angin. Warga sekitar juga perlu diberi peringatan pada pelepasan besar.' },
    { id: 'h40', stage: 4, x: 900, y: 485, label: 'Ruang beku (sprinkler)', accept: [],
      why: 'Sprinkler air pada ruang beku bersuhu minus 25 °C berisiko membeku dan tidak menangani pelepasan amonia. Deteksi dan ventilasi lebih tepat.' },
  ],
  inspect: [
    { id: 'V-1001', itpm: 'VESSEL', why: 'Receiver adalah bejana tekan dengan inventori amonia terbesar. Pemeriksaan dan pengujian berkala diwajibkan Permenaker No. 37 Tahun 2016.' },
    { id: 'V-1002', itpm: 'VESSEL', why: 'Separator hisap bertekanan rendah tetapi berisi banyak amonia cair. Korosi di bawah isolasi adalah penyebab kebocoran yang umum.' },
    { id: 'K-1001', itpm: 'ROT', why: 'Pemantauan getaran dan analisis oli kompresor mendeteksi keausan bantalan dan seal sebelum amonia bocor.' },
  ],
  budget: { 3: 29, 4: 32 },
  bowtie: {
    top: 'Pelepasan amonia dari sistem refrigerasi',
    threats: ['Kondensor gagal, tekanan tinggi naik', 'Cairan terhisap ke kompresor', 'Hentakan hidraulik saat defrost', 'Pendinginan oli kompresor gagal'],
    cons: ['Awan amonia ke area produksi dan permukiman', 'Pelepasan di ruang mesin, operator terpapar', 'Pelepasan di ruang beku, pekerja terjebak', 'Kebocoran seal kompresor'],
  },
};
SCENARIOS.push(SCN_AMONIA);
