/* Skenario sektor Migas: dimuat setelah js/data.js dan menambahkan diri ke SCENARIOS. */
/* =====================================================================
   MIGAS: Penyimpanan dan Pengisian LPG (Hilir)
   ===================================================================== */
const SCN_LPG = {
  id: 'lpg',
  title: 'Penyimpanan & Pengisian LPG',
  subtitle: 'Tangki bullet bertekanan, pompa pengisian, loading bay truk',
  level: 'Lanjutan',
  sector: 'migas',
  area: 'Hilir Migas / Distribusi',
  color: '#26323d',
  overview: [
    'Terminal ini menerima LPG cair dari pipa kilang (12 barg) ke tangki bullet V-301 berkapasitas 100 m³ yang beroperasi pada 7 barg dan suhu lingkungan 30 °C. Batas pengisian maksimum tangki adalah 85 % untuk menyisakan ruang ekspansi termal.',
    'LPG dipompa P-301 (50 m³/jam) melalui loading arm ke truk tangki di loading bay. Uap yang terdesak dari truk dikembalikan ke V-301 oleh kompresor vapor return K-301 agar tidak dilepas ke udara.',
    'LPG adalah gas cair mudah terbakar yang disimpan di atas titik didihnya. Pelepasan cairan menghasilkan awan uap yang lebih berat dari udara, dan tangki yang terpapar api berisiko BLEVE (Boiling Liquid Expanding Vapour Explosion).',
  ],
  production: { label: 'LPG tersalurkan', unit: 'm³', var: 'FL', k: 1 / 60 },
  equipment: [
    { id: 'PL-300', type: 'sink', x: 135, y: 200, dir: 'left', name: 'Pipa LPG dari Kilang',
      desc: 'Suplai LPG cair 12 barg dari kilang. Pengisian tangki dilakukan secara berkala (batch).' },
    { id: 'XV-300', type: 'valve', sub: 'manual', x: 178, y: 200, name: 'Katup Isolasi Inlet',
      desc: 'Katup manual yang dibuka saat pengisian tangki dari pipa kilang.' },
    { id: 'V-301', type: 'vessel', orient: 'h', x: 220, y: 150, w: 300, h: 100, name: 'Tangki Bullet LPG V-301', level: 'L3',
      desc: 'Bejana tekan horizontal 100 m³, tekanan operasi 7 barg (tergantung suhu), tekanan desain 17,5 barg. Batas isi maksimum 85 %. Dilengkapi level gauge dan pressure gauge lokal.',
      vars: ['P3', 'L3', 'T3'] },
    { id: 'P-301', type: 'pump', x: 450, y: 330, name: 'Pompa Pengisian P-301',
      desc: 'Pompa sentrifugal LPG 50 m³/jam. Seal mekanis adalah titik kebocoran yang umum.' },
    { id: 'XV-301', type: 'valve', sub: 'manual', x: 560, y: 330, name: 'Katup Loading Arm',
      desc: 'Katup manual pada loading arm yang dibuka operator saat truk tersambung.' },
    { id: 'TR-301', type: 'truck', x: 660, y: 310, w: 200, h: 80, name: 'Truk Tangki LPG', level: 'LTR',
      desc: 'Truk tangki 20 m³. Pengisian dihentikan pada 80 % berdasarkan pembacaan operator di meter truk. Truk harus di-grounding dan roda diganjal.', vars: ['LTR'] },
    { id: 'K-301', type: 'compressor', x: 620, y: 120, name: 'Kompresor Vapor Return K-301',
      desc: 'Mengembalikan uap LPG dari truk ke V-301 selama pengisian agar tidak dilepas ke atmosfer.' },
    { id: 'CR-300', type: 'building', x: 110, y: 420, name: 'Ruang Kendali',
      desc: 'Pusat pemantauan dan tombol ESD terminal.' },
    { id: 'MP-300', type: 'muster', x: 900, y: 520, name: 'Titik Kumpul',
      desc: 'Area berkumpul evakuasi, minimal 100 m dari tangki.' },
  ],
  pipes: [
    { id: 'in1', fluid: 'lpg', w: 6, pts: [[135, 200], [220, 200]] },
    { id: 'l1', fluid: 'lpg', w: 6, pts: [[370, 250], [370, 330], [430, 330]] },
    { id: 'l2', fluid: 'lpg', w: 6, pts: [[470, 330], [620, 330], [620, 350], [660, 350]] },
    { id: 'vr1', fluid: 'gas', w: 4, pts: [[760, 310], [760, 120], [648, 120]] },
    { id: 'vr2', fluid: 'gas', w: 4, pts: [[592, 120], [400, 120], [400, 150]], arrow: true },
  ],
  labels: [
    { x: 760, y: 430, text: 'Loading Bay', size: 12 },
    { x: 500, y: 100, text: 'Vapor return', size: 10 },
  ],
  vars: {
    P3:  { label: 'Tekanan V-301', unit: 'barg', normal: 7.0, min: 0, max: 20, lo: 4, hi: 10, hihi: 14, node: 'V-301', x: 240, y: 125, tau: 4, noise: 0.03, dec: 1 },
    L3:  { label: 'Level V-301', unit: '%', normal: 70, min: 0, max: 100, lo: 20, hi: 85, hihi: 90, node: 'V-301', x: 440, y: 270, tau: 5, noise: 0.2, dec: 0 },
    T3:  { label: 'Suhu V-301', unit: '°C', normal: 30, min: 0, max: 100, hi: 45, hihi: 55, node: 'V-301', x: 500, y: 125, tau: 5, noise: 0.1, dec: 1 },
    FL:  { label: 'Aliran Pengisian', unit: 'm³/j', normal: 50, min: 0, max: 120, lo: 20, hi: 65, hihi: 80, node: 'P-301', x: 545, y: 385, tau: 1.5, noise: 0.5, dec: 0 },
    LTR: { label: 'Level Truk', unit: '%', normal: 55, min: 0, max: 100, hi: 80, hihi: 88, node: 'TR-301', x: 760, y: 410, tau: 3, noise: 0.2, dec: 0 },
    PB:  { label: 'Tekanan Loading Arm', unit: 'barg', normal: 9.0, min: 0, max: 15, lo: 5, node: 'XV-301', x: 640, y: 290, tau: 1.5, noise: 0.05, dec: 1 },
  },
  trendVars: ['P3', 'L3', 'FL', 'LTR'],
  controls: [
    { id: 'pump', label: 'Kecepatan pompa pengisian', unit: '%', min: 40, max: 120, def: 100, step: 5,
      effects: [{ var: 'FL', gain: 0.5 }, { var: 'PB', gain: 0.03 }] },
    { id: 'amb', label: 'Suhu lingkungan', unit: '°C', min: 20, max: 45, def: 30, step: 1,
      effects: [{ var: 'T3', gain: 1 }, { var: 'P3', gain: 0.25 }] },
    { id: 'fill', label: 'Target isi tangki V-301', unit: '%', min: 40, max: 85, def: 70, step: 5,
      effects: [{ var: 'L3', gain: 1 }] },
  ],
  quiz: [
    { q: 'Mengapa tangki LPG tidak boleh diisi melebihi 85 %?', opts: ['Menyisakan ruang uap bagi pemuaian cairan agar tangki tidak mengalami tekanan hidrostatik berlebih saat suhu naik', 'Menyisakan ruang uap agar tekanan isap pompa pengisian tetap stabil selama loading berlangsung', 'Di atas 85 % pembacaan level gauge tidak lagi akurat karena terganggu gelembung uap LPG yang mendidih', 'Memberi ruang bagi uap yang dikembalikan kompresor dari truk tangki selama pengisian'], ans: 0,
      why: 'LPG cair memuai cukup besar terhadap suhu. Tanpa ruang uap, kenaikan suhu kecil menghasilkan tekanan sangat besar (liquid full).' },
    { q: 'Mengapa tekanan V-301 berubah mengikuti suhu lingkungan?', opts: ['LPG disimpan sebagai cairan pada tekanan uap jenuhnya, yang naik saat suhu naik', 'Udara di ruang uap tangki memuai saat panas sehingga tekanan di dalam tangki ikut naik', 'Kompresor vapor return otomatis menaikkan tekanan tangki saat suhu siang hari naik', 'Tekanan pipa dari kilang berubah mengikuti suhu lingkungan lalu diteruskan ke dalam tangki'], ans: 0,
      why: 'Tekanan tangki adalah tekanan uap jenuh campuran propana-butana pada suhu cairan. Pemanasan eksternal (api) menaikkan tekanan dengan cepat.' },
    { q: 'Apa fungsi kompresor vapor return K-301?', opts: ['Mengembalikan uap yang terdesak dari truk ke tangki penyimpanan agar tidak dilepas ke udara', 'Mendinginkan LPG di dalam tangki dengan mengompresi uapnya kembali menjadi cair', 'Menaikkan tekanan tangki V-301 agar LPG tetap berfase cair pada siang hari yang panas', 'Mengalirkan kelebihan uap LPG ke flare setiap kali tekanan tangki mendekati tekanan set PSV pada siang hari'], ans: 0,
      why: 'Tanpa vapor return, setiap pengisian melepaskan uap LPG mudah terbakar di loading bay.' },
    { q: 'Apa itu BLEVE dan kapan dapat terjadi pada V-301?', opts: ['Pecahnya bejana berisi cairan di atas titik didihnya karena dinding melemah saat terpapar api', 'Ledakan awan uap LPG di udara terbuka setelah kebocoran besar tersulut sumber api di sekitar', 'Pecahnya tangki akibat tekanan hidrostatik karena tangki terisi penuh cairan tanpa ruang uap', 'Semburan api dari kebocoran bertekanan yang langsung menyala pada sambungan pipa'], ans: 0,
      why: 'BLEVE adalah skenario bencana utama fasilitas LPG (contoh: San Juanico 1984, Feyzin 1966). Pencegahannya: relief, pendinginan dinding bejana, dan isolasi cepat.' },
    { q: 'Mengapa awan uap LPG sangat berbahaya di loading bay?', opts: ['Uap LPG lebih berat dari udara, menyebar rendah dan jauh, lalu dapat menyala pada sumber api jauh dari titik bocor', 'Uap LPG lebih ringan dari udara sehingga cepat naik dan terkumpul di bawah atap kanopi loading bay', 'Uap LPG sangat beracun sehingga paparan singkat langsung melumpuhkan pekerja di loading bay', 'Uap LPG sangat dingin sehingga bahaya utamanya adalah radang dingin pada kulit dan mata pekerja yang terpapar langsung'], ans: 0,
      why: 'Densitas uap propana sekitar 1,5 kali udara. Sumber nyala seperti mesin truk atau listrik statis dapat memicu flash fire.' },
  ],
  events: [
    { id: 'e1', effects: [{ var: 'LTR', to: 98, delay: 2, dur: 18 }],
      warnings: [
        { t: 16, type: 'leak', sev: 'warn', at: 'TR-301', pos: [820, 300], text: 'Uap LPG keluar dari katup relief truk tangki disertai suara mendesis.' },
        { t: 21, type: 'leak', sev: 'crit', at: 'TR-301', pos: [780, 392], big: true, text: 'LPG cair menyembur dari relief truk; kabut putih menyebar rendah di loading bay.' },
        { t: 27, type: 'fire', sev: 'final', at: 'TR-301', pos: [760, 362], text: 'FLASH FIRE di loading bay: awan uap LPG tersulut oleh mesin truk.' },
      ],
      answer: { node: ['TR-301'], param: ['L'], guide: ['high'] },
      hint: 'Pengisian truk tidak berhenti pada batas 80 persen. Pikirkan siapa atau apa yang seharusnya menghentikan pompa.',
      causes: ['Operator tidak menghentikan pengisian pada 80 % (kesalahan manusia) atau meter level truk gagal', 'Kompresor K-301 trip', 'Suhu lingkungan naik', 'Katup XV-300 terbuka'], causeAns: 0,
      cons: ['Truk terisi penuh cairan, LPG keluar dari relief truk, awan uap di loading bay dan flash fire', 'Tekanan V-301 naik', 'Pompa kavitasi', 'Level V-301 naik'], consAns: 0,
      explain: 'Level truk naik melampaui 80 % tanpa deviasi lain. Pengisian bergantung pada pengamatan operator; proteksi overfill otomatis pada truk (LSHH menghentikan pompa) diperlukan.' },
    { id: 'e2', effects: [{ var: 'T3', to: 68, delay: 2, dur: 24 }, { var: 'P3', to: 18.5, delay: 4, dur: 24 }],
      warnings: [
        { t: 4, type: 'fire', sev: 'warn', at: 'P-301', pos: [450, 300], text: 'Api kecil terlihat di area pompa P-301 dan menjilat sisi bawah tangki V-301.' },
        { t: 14, type: 'heat', sev: 'crit', at: 'V-301', text: 'Dinding tangki V-301 memanas; cat terbakar dan mengelupas.' },
        { t: 22, type: 'leak', sev: 'crit', at: 'V-301', pos: [460, 146], text: 'Gas LPG menyembur dari sambungan flens atas V-301 akibat tekanan tinggi.' },
        { t: 30, type: 'explosion', sev: 'final', at: 'V-301', text: 'BLEVE: tangki V-301 pecah dan membentuk bola api besar.' },
      ],
      answer: { node: ['V-301'], param: ['P', 'T'], guide: ['high'] },
      hint: 'Suhu cairan naik tanpa perubahan pada proses pengisian. Cari sumber panas dari luar tangki.',
      causes: ['Pemanasan eksternal: kebakaran di dekat tangki atau paparan panas yang berlebihan', 'Pompa P-301 terlalu cepat', 'Kompresor K-301 memompa terlalu banyak uap', 'Katup inlet tertutup'], causeAns: 0,
      cons: ['Tekanan uap naik melewati desain, dinding bejana melemah, BLEVE dengan bola api dan fragmen', 'Level tangki naik', 'Truk terisi lebih cepat', 'Aliran pengisian turun'], consAns: 0,
      explain: 'Suhu cairan naik lalu tekanan naik mengikuti kurva tekanan uap. Ini pola paparan panas eksternal. Mitigasi: PSV, water spray pendingin, dan isolasi jarak jauh.' },
    { id: 'e3', effects: [{ var: 'FL', to: 110, delay: 1, dur: 2 }, { var: 'PB', to: 1.5, delay: 1, dur: 2 }, { var: 'LTR', to: 50, delay: 2, dur: 10 }],
      warnings: [
        { t: 3, type: 'leak', sev: 'crit', at: 'XV-301', pos: [600, 345], text: 'Selang loading arm putus! LPG cair menyembur dari sambungan.' },
        { t: 10, type: 'leak', sev: 'crit', at: 'TR-301', pos: [700, 450], big: true, text: 'Awan uap LPG menyebar rendah menuju jalan dan area parkir truk.' },
        { t: 18, type: 'explosion', sev: 'final', at: 'TR-301', pos: [700, 430], text: 'LEDAKAN awan uap (VCE) di loading bay setelah awan uap menemukan sumber nyala.' },
      ],
      answer: { node: ['XV-301', 'TR-301', 'P-301'], param: ['F', 'P'], guide: ['high', 'low'] },
      hint: 'Aliran melonjak sementara tekanan loading arm anjlok. Pikirkan akibatnya bila sambungan ke truk terlepas.',
      causes: ['Loading arm atau selang putus (misalnya truk bergerak saat masih tersambung) sehingga aliran bebas ke atmosfer', 'Truk penuh', 'Tangki V-301 kosong', 'Kompresor berhenti'], causeAns: 0,
      cons: ['Pelepasan LPG cair besar, awan uap berat menyebar, flash fire atau VCE di loading bay', 'Tekanan V-301 naik', 'Level truk naik cepat', 'Pompa berhenti sendiri'], consAns: 0,
      explain: 'Aliran melonjak sementara tekanan loading arm anjlok: tanda hilangnya tahanan hilir karena pipa atau selang putus. Kejadian ini berkembang terlalu cepat untuk respons operator, sehingga diperlukan barier otomatis seperti excess flow valve, breakaway coupling, dan ROSOV.' },
    { id: 'e4', effects: [{ var: 'L3', to: 98, delay: 2, dur: 18 }, { var: 'P3', to: 13.5, delay: 14, dur: 8 }],
      warnings: [
        { t: 17, type: 'vibration', sev: 'warn', at: 'V-301', text: 'Suara benturan cairan dan getaran pada pipa inlet V-301.' },
        { t: 23, type: 'leak', sev: 'crit', at: 'V-301', pos: [232, 200], text: 'LPG cair bocor dari sambungan flens inlet V-301; kabut putih menyelimuti sekitar tangki.' },
        { t: 29, type: 'explosion', sev: 'final', at: 'V-301', pos: [250, 200], text: 'Sambungan nozzle V-301 pecah akibat tekanan hidrostatik; LPG terlepas dan meledak.' },
      ],
      answer: { node: ['V-301', 'XV-300'], param: ['L'], guide: ['high'] },
      hint: 'Pengisian dari kilang tetap berjalan walaupun tangki hampir penuh. Pikirkan kemungkinan pembacaan level yang keliru.',
      causes: ['Pengisian dari kilang tidak dihentikan karena level gauge gagal (membaca rendah palsu)', 'Pompa P-301 trip', 'Suhu lingkungan turun', 'Kompresor K-301 memompa uap ke tangki'], causeAns: 0,
      cons: ['Tangki penuh cairan (liquid full), tekanan hidrostatik naik tajam dengan sedikit kenaikan suhu, bejana pecah atau PSV melepaskan cairan LPG', 'Truk tidak dapat diisi', 'Pompa kavitasi', 'Suhu tangki turun'], consAns: 0,
      explain: 'Level naik melampaui 85 % lalu tekanan ikut naik tanpa kenaikan suhu: tanda ruang uap hampir habis. Proteksi overfill independen (LSHH menutup inlet) sangat penting.' },
    { id: 'e5', start: 11,
      hf: { type: 'violation', team: 'ext', threat: 0, title: 'Sopir mengisi sendiri dan melepas sensor overfill', factor: 'Pengisian oleh sopir dan sensor overfill dicabut',
        roles: { dimas: 'Operator Filling', raka: 'Operator Panel Terminal' },
        lesson: 'Agus melakukan violation rutin: pelanggaran yang sudah dianggap biasa karena selama ini tidak pernah terjadi apa-apa (normalisasi penyimpangan). Pengoperasian pengisian bukan kewenangan sopir, dan mencabut sensor overfill berarti melumpuhkan barier. Operator filling juga meninggalkan pengisian tanpa serah terima. Kontrolnya adalah pembagian kewenangan yang tegas, kunci akses panel pengisian, sensor overfill yang terinterlock dengan pompa, dan pemeriksaan truk sebelum pengisian.',
        controls: ['Hanya operator filling berwenang yang mengoperasikan pengisian', 'Sensor overfill terinterlock dengan pompa dan tidak dapat dilepas tanpa izin bypass', 'Pengawasan terus-menerus selama pengisian dan serah terima bila operator meninggalkan pos'] },
      chat: [
        { t: 1, who: 'dimas', at: 'TR-301', text: 'Agus, truk sudah tersambung. Aku ke musala sebentar, pengisian kumulai setelah kembali ya.' },
        { t: 3, who: 'agus', at: 'TR-301', mood: 'santai', text: 'Santai, aku sudah biasa. Biar cepat, kujalankan sendiri saja.' },
        { t: 6, who: 'agus', at: 'TR-301', mood: 'santai', text: 'Sensor overfill truk ini sering bunyi sendiri. Kabelnya kucabut dulu biar pengisian tidak berhenti.' },
        { t: 9, who: 'raka', at: 'CR-300', mood: 'ragu', text: 'Loading bay kok sudah mengalir? Dimas, kamu yang buka?' },
        { t: 11, who: 'agus', at: 'TR-301', mood: 'santai', text: 'Aku yang jalankan, Raka. Tenang, nanti kuhentikan kalau sudah 85 persen.' },
        { t: 22, who: 'raka', at: 'CR-300', mood: 'ragu', text: 'Agus, level truk sudah lewat 80 persen. Hentikan sekarang!' },
        { t: 26, who: 'raka', at: 'CR-300', mood: 'panik', text: 'Agus tidak menjawab! Dimas, cepat ke loading bay!' },
      ],
      effects: [{ var: 'LTR', to: 98, delay: 1, dur: 17 }],
      warnings: [
        { t: 15, type: 'leak', sev: 'warn', at: 'TR-301', pos: [820, 300], text: 'Uap LPG keluar dari katup relief truk tangki disertai suara mendesis.' },
        { t: 20, type: 'leak', sev: 'crit', at: 'TR-301', pos: [780, 392], big: true, text: 'LPG cair menyembur dari relief truk; kabut putih menyebar rendah di loading bay.' },
        { t: 26, type: 'fire', sev: 'final', at: 'TR-301', pos: [760, 362], text: 'FLASH FIRE di loading bay: awan uap LPG tersulut oleh mesin truk yang masih menyala.' },
      ],
      answer: { node: ['TR-301'], param: ['L'], guide: ['high'] },
      hint: 'Level truk terus naik melewati batas pengisian, padahal operator filling tidak berada di tempat. Baca kembali obrolan tentang siapa yang menjalankan pengisian.',
      causes: ['Sopir truk menjalankan pengisian sendiri dan mencabut kabel sensor overfill agar pengisian tidak terhenti', 'Sensor overfill truk rusak karena usia pakai dan tidak terdeteksi saat inspeksi', 'Operator panel salah memasukkan target volume pengisian di sistem batch', 'Katup XV-301 bocor sehingga LPG tetap mengalir setelah pengisian selesai'], causeAns: 0,
      cons: ['Truk terisi penuh cairan, katup pengaman truk membuka dan melepaskan LPG di loading bay', 'Pengisian berhenti otomatis tanpa dampak karena tekanan truk naik', 'Tekanan tangki V-301 naik karena uap tidak kembali dari truk', 'Pompa P-301 kavitasi karena tangki V-301 cepat kosong'], consAns: 0,
      explain: 'Level truk naik terus tanpa ada yang menghentikan. Sensor overfill yang dicabut menghilangkan trip otomatis, dan pengisian berjalan tanpa operator yang berwenang. Truk yang terisi penuh cairan melepaskan LPG melalui katup pengaman, membentuk awan uap yang lebih berat dari udara di loading bay.' },
  ],
  hotspots: [
    { id: 'h31', stage: 3, x: 460, y: 138, label: 'Nozzle puncak V-301 (relief)', accept: ['PSV'],
      why: 'PSV pada tangki LPG wajib untuk overpressure akibat paparan panas; ukurannya mengikuti laju penguapan saat kebakaran (API 2510).' },
    { id: 'h32', stage: 3, x: 340, y: 138, label: 'Nozzle level V-301', accept: ['LSHH', 'LT'],
      why: 'Trip level tinggi-tinggi menutup inlet saat 85 %, independen dari level gauge. Alarm level diterima sebagai lapisan operator.' },
    { id: 'h33', stage: 3, x: 212, y: 228, label: 'Jalur inlet dari kilang', accept: ['NRV'],
      why: 'Check valve mencegah aliran balik ke pipa kilang dan membatasi inventori yang lepas bila pipa inlet pecah.' },
    { id: 'h34', stage: 3, x: 400, y: 300, label: 'Outlet cairan V-301 (sebelum pompa)', accept: ['EFV'],
      why: 'Excess flow valve menutup otomatis bila aliran melonjak akibat pipa hilir putus.' },
    { id: 'h35', stage: 3, x: 610, y: 370, label: 'Loading arm ke truk', accept: ['BRK'],
      why: 'Breakaway coupling menutup kedua sisi bila truk bergerak saat masih tersambung.' },
    { id: 'h36', stage: 3, x: 700, y: 410, label: 'Area truk (statis)', accept: ['GRND'],
      why: 'Grounding dengan interlock pompa menghilangkan sumber nyala statis dan memastikan truk tersambung dengan benar sebelum pengisian.' },
    { id: 'h37', stage: 3, x: 820, y: 300, label: 'Puncak truk tangki (overfill)', accept: ['LSHH'],
      why: 'Proteksi overfill otomatis pada truk menghentikan pompa pada 80 % tanpa bergantung pada operator.' },
    { id: 'h38', stage: 3, x: 560, y: 95, label: 'Jalur vapor return', accept: [],
      why: 'Jalur uap berdiameter kecil dan bertekanan rendah; perangkat tambahan di sini tidak menangani skenario utama.' },
    { id: 'h39', stage: 3, x: 270, y: 215, label: 'Nozzle tekanan V-301', accept: ['PT'],
      why: 'Alarm tekanan tinggi memberi peringatan dini paparan panas atau overfill ke operator.' },
    /* Tahap 4 */
    { id: 'h41', stage: 4, x: 370, y: 90, label: 'Di atas V-301 (pendinginan)', accept: ['DELUGE'],
      why: 'Water spray menjaga dinding tangki tetap dingin saat terpapar api, mitigasi utama BLEVE (NFPA 58, API 2510).' },
    { id: 'h42', stage: 4, x: 330, y: 365, label: 'Outlet V-301 (isolasi jarak jauh)', accept: ['EIV'],
      why: 'ROSOV menghentikan sumber kebocoran dari jarak aman, termasuk saat kebakaran di pompa.' },
    { id: 'h43', stage: 4, x: 520, y: 290, label: 'Area pompa P-301 (deteksi gas)', accept: ['GD'],
      why: 'Seal pompa adalah titik bocor umum; detektor gas memicu ESD sebelum awan uap membesar.' },
    { id: 'h44', stage: 4, x: 900, y: 360, label: 'Loading bay (deteksi gas)', accept: ['GD'],
      why: 'Loading bay adalah area pelepasan paling mungkin; deteksi gas di ketinggian rendah penting karena uap LPG berat.' },
    { id: 'h45', stage: 4, x: 150, y: 460, label: 'Ruang kendali (ESD)', accept: ['ESD'],
      why: 'ESD menghentikan pompa, kompresor, dan menutup ROSOV serentak.' },
    { id: 'h46', stage: 4, x: 240, y: 300, label: 'Area tangki (deteksi api)', accept: ['FD'],
      why: 'Detektor nyala mengaktifkan deluge secara otomatis dalam hitungan detik.' },
    { id: 'h47', stage: 4, x: 620, y: 440, label: 'Loading bay (pemadaman)', accept: ['FW'],
      why: 'Monitor air mendinginkan truk dan peralatan sekitar serta mengurai awan uap.' },
    { id: 'h48', stage: 4, x: 840, y: 520, label: 'Titik kumpul dan alarm umum', accept: ['ALARM'],
      why: 'Evakuasi cepat karena radius BLEVE dapat mencapai ratusan meter.' },
    { id: 'h49', stage: 4, x: 480, y: 215, label: 'Permukaan V-301 (sistem busa)', accept: [],
      why: 'Busa tidak efektif untuk LPG karena cairan mendidih pada suhu lingkungan; pendinginan air adalah pendekatan yang benar.' },
  ],
  inspect: [
    { id: 'V-301', itpm: 'VESSEL', why: 'Tangki LPG adalah bejana tekan; pemeriksaan dan pengujian berkala (Permenaker No. 37 Tahun 2016) mendeteksi korosi dan retak yang dapat memicu pelepasan besar.' },
    { id: 'P-301', itpm: 'ROT', why: 'Seal mekanis pompa LPG adalah titik bocor yang umum. Pemantauan getaran dan inspeksi seal mencegah kebocoran.' },
  ],
  budget: { 3: 30, 4: 28 },
  bowtie: {
    top: 'Pelepasan LPG dari sistem penyimpanan dan pengisian',
    threats: ['Overfill truk tangki', 'Paparan panas eksternal pada V-301', 'Putusnya loading arm', 'Overfill tangki V-301 (liquid full)'],
    cons: ['Flash fire di loading bay', 'BLEVE dengan bola api dan fragmen', 'Ledakan awan uap (VCE)', 'Pecahnya tangki'],
  },
};
SCENARIOS.push(SCN_LPG);
