/* Skenario sektor Petrokimia: dimuat setelah js/data.js dan menambahkan diri ke SCENARIOS. */
/* =====================================================================
   PETROKIMIA: Reaktor Batch Eksotermik
   ===================================================================== */
const SCN_REACTOR = {
  id: 'reactor',
  title: 'Reaktor Batch Eksotermik',
  subtitle: 'Reaktor berjaket pendingin, kondensor refluks, umpan monomer',
  level: 'Menengah',
  sector: 'petrokimia',
  area: 'Petrokimia (Polimer)',
  color: '#1565a6',
  overview: [
    'Unit ini memproduksi resin melalui reaksi polimerisasi eksotermik di reaktor batch R-201 berkapasitas 10 m³. Monomer dari tangki umpan TK-201 dipompa oleh P-201 dan laju umpannya diatur FCV-201 (2 m³/jam) agar panas reaksi seimbang dengan kapasitas pendinginan.',
    'Panas reaksi dibuang melalui jaket pendingin yang dialiri air pendingin dari pompa P-203 (30 m³/jam) dan diatur TCV-201 untuk menjaga suhu reaktor 80 °C. Agitator M-201 menjaga homogenitas campuran dan perpindahan panas ke jaket.',
    'Uap pelarut dikondensasi oleh kondensor refluks E-201 dan dikembalikan ke reaktor, sedangkan gas tak terkondensasi dibuang melalui vent. Produk dipompa P-202 ke tangki produk TK-202. Uap monomer bersifat beracun dan mudah terbakar. Suhu onset runaway monomer sekitar 110 °C dan tekanan desain reaktor 6 barg.',
  ],
  fluidNames: { chem: 'Monomer dan pelarut', toxic: 'Uap monomer beracun', cw: 'Air pendingin', product: 'Produk resin' },
  production: { label: 'Resin diproduksi', unit: 'kg', var: 'FA', k: 15 },
  equipment: [
    { id: 'TK-201', type: 'tank', x: 50, y: 70, w: 100, h: 100, name: 'Tangki Umpan Monomer TK-201',
      desc: 'Tangki atmosferik berisi monomer mudah terbakar dan reaktif (titik nyala 10 °C). Ruang uap dapat membentuk campuran mudah terbakar.' },
    { id: 'P-201', type: 'pump', x: 160, y: 210, name: 'Pompa Umpan P-201',
      desc: 'Pompa perpindahan positif (positive displacement) dengan rentang laju 0 hingga 5 m³/jam. Laju umpan diatur FCV-201.' },
    { id: 'FCV-201', type: 'valve', sub: 'control', x: 265, y: 210, tag: 'FIC', name: 'FCV-201 (Kendali Laju Umpan)',
      desc: 'Katup kendali laju umpan monomer dengan set point 2 m³/jam. Laju umpan menentukan laju pelepasan panas reaksi.' },
    { id: 'R-201', type: 'reactor', x: 400, y: 230, w: 160, h: 210, name: 'Reaktor Batch R-201', level: 'L2',
      desc: 'Bejana berjaket 10 m³ dengan agitator. Suhu operasi 80 °C, tekanan operasi 1,5 barg, tekanan desain 6 barg. Suhu onset runaway sekitar 110 °C. Di atas suhu ini, laju reaksi dan tekanan naik secara eksponensial.',
      vars: ['T2', 'P2', 'L2'] },
    { id: 'M-201', type: 'motor', x: 505, y: 205, name: 'Agitator M-201',
      desc: 'Motor pengaduk dengan putaran 100 rpm. Tanpa pengadukan, perpindahan panas ke jaket turun drastis dan reaktan dapat terakumulasi.' },
    { id: 'TCV-201', type: 'valve', sub: 'control', x: 300, y: 420, tag: 'TIC', name: 'TCV-201 (Kendali Suhu)',
      desc: 'Katup kendali aliran air pendingin ke jaket. Loop TIC-201 menjaga suhu reaktor 80 °C.' },
    { id: 'P-203', type: 'pump', x: 210, y: 420, name: 'Pompa Air Pendingin P-203',
      desc: 'Pompa sentrifugal 30 m³/jam yang mengalirkan air dari menara pendingin. Pendinginan hanya bergantung pada pompa ini (tanpa cadangan).' },
    { id: 'E-201', type: 'hx', x: 640, y: 120, name: 'Kondensor Refluks E-201',
      desc: 'Mengondensasi uap pelarut dan mengembalikannya ke reaktor sehingga membantu membuang panas (sekitar 30 % beban). Kondensor ini didinginkan dengan air pendingin.' },
    { id: 'VNT-201', type: 'sink', x: 835, y: 120, dir: 'right', name: 'Vent ke Atmosfer',
      desc: 'Jalur pembuangan gas tak terkondensasi tanpa pengolahan. Pelepasan uap monomer dalam jumlah besar bersifat beracun dan mudah terbakar.' },
    { id: 'P-202', type: 'pump', x: 560, y: 480, name: 'Pompa Produk P-202',
      desc: 'Memindahkan produk resin ke tangki produk setelah batch selesai.' },
    { id: 'TK-202', type: 'tank', x: 700, y: 400, w: 100, h: 100, name: 'Tangki Produk TK-202',
      desc: 'Tangki atmosferik untuk produk resin, yaitu bahan mudah terbakar kelas II.' },
    { id: 'CW-IN', type: 'sink', x: 150, y: 420, dir: 'left', name: 'Air Pendingin dari Menara',
      desc: 'Suplai air pendingin 30 °C dari menara pendingin.' },
    { id: 'CW-OUT', type: 'sink', x: 150, y: 270, dir: 'left', name: 'Air Pendingin Kembali',
      desc: 'Air pendingin kembali ke menara dengan suhu 40 °C.' },
    { id: 'CR-200', type: 'building', x: 870, y: 300, name: 'Ruang Kendali',
      desc: 'Pusat pemantauan DCS dan lokasi tombol ESD.' },
    { id: 'MP-200', type: 'muster', x: 880, y: 520, name: 'Titik Kumpul',
      desc: 'Area berkumpul saat evakuasi.' },
  ],
  pipes: [
    { id: 'f1', fluid: 'chem', w: 6, pts: [[100, 170], [100, 210], [140, 210]] },
    { id: 'f2', fluid: 'chem', w: 6, pts: [[180, 210], [450, 210], [450, 230]] },
    { id: 'cw1', fluid: 'cw', w: 5, pts: [[150, 420], [190, 420]] },
    { id: 'cw2', fluid: 'cw', w: 5, pts: [[230, 420], [400, 420]] },
    { id: 'cw3', fluid: 'cw', w: 5, pts: [[400, 270], [152, 270]], arrow: true },
    { id: 'v1', fluid: 'toxic', w: 5, pts: [[530, 230], [530, 120], [612, 120]] },
    { id: 'v2', fluid: 'toxic', w: 5, pts: [[668, 120], [830, 120]], arrow: true },
    { id: 'rf', fluid: 'chem', w: 3, dashed: true, legend: 'Refluks kondensat monomer', pts: [[640, 148], [640, 190], [545, 190], [545, 230]] },
    { id: 'pr1', fluid: 'product', w: 6, pts: [[480, 440], [480, 480], [540, 480]] },
    { id: 'pr2', fluid: 'product', w: 6, pts: [[580, 480], [720, 480], [720, 410]] },
  ],
  labels: [
    { x: 600, y: 178, text: 'Refluks', size: 10 },
    { x: 370, y: 335, text: 'Jaket', size: 10 },
  ],
  vars: {
    T2:  { label: 'Suhu Reaktor R-201', unit: '°C', normal: 80, min: 0, max: 160, lo: 65, hi: 92, hihi: 105, node: 'R-201', x: 330, y: 300, tau: 6, noise: 0.15, dec: 1 },
    P2:  { label: 'Tekanan Reaktor R-201', unit: 'barg', normal: 1.5, min: 0, max: 8, hi: 3, hihi: 4.5, node: 'R-201', x: 640, y: 300, tau: 3, noise: 0.03, dec: 2 },
    L2:  { label: 'Level Reaktor R-201', unit: '%', normal: 60, min: 0, max: 100, lo: 30, hi: 80, hihi: 92, node: 'R-201', x: 480, y: 462, tau: 5, noise: 0.3, dec: 0 },
    FCW: { label: 'Aliran Air Pendingin', unit: 'm³/j', normal: 30, min: 0, max: 50, lo: 18, lolo: 8, node: 'P-203', x: 330, y: 472, tau: 2, noise: 0.3, dec: 0 },
    FA:  { label: 'Laju Umpan Monomer', unit: 'm³/j', normal: 2.0, min: 0, max: 6, hi: 3, hihi: 4, node: 'FCV-201', x: 345, y: 240, tau: 2, noise: 0.03, dec: 2 },
    NAG: { label: 'Putaran Agitator', unit: 'rpm', normal: 100, min: 0, max: 150, lo: 60, node: 'M-201', x: 640, y: 215, tau: 1.5, noise: 0.5, dec: 0 },
  },
  trendVars: ['T2', 'P2', 'FA', 'FCW'],
  controls: [
    { id: 'fa', label: 'Set point laju umpan (FIC-201)', unit: 'm³/j', min: 0.5, max: 4, def: 2, step: 0.25,
      effects: [{ var: 'FA', gain: 1 }, { var: 'T2', gain: 6 }, { var: 'P2', gain: 0.25 }] },
    { id: 'cw', label: 'Set point aliran pendingin', unit: 'm³/j', min: 10, max: 45, def: 30, step: 5,
      effects: [{ var: 'FCW', gain: 1 }, { var: 'T2', gain: -0.6 }] },
    { id: 'ag', label: 'Putaran agitator', unit: 'rpm', min: 40, max: 140, def: 100, step: 10,
      effects: [{ var: 'NAG', gain: 1 }, { var: 'T2', gain: -0.08 }] },
  ],
  quiz: [
    { q: 'Mengapa laju umpan monomer dibatasi 2 m³/jam?', opts: ['Agar laju pelepasan panas reaksi tidak melebihi kapasitas pendinginan jaket dan kondensor', 'Agar waktu tinggal monomer cukup lama sehingga konversi dan mutu produk akhir tercapai', 'Agar tekanan reaktor tetap di bawah tekanan pecah rupture disc selama pengisian berlangsung', 'Agar pompa P-201 bekerja pada titik efisiensi terbaiknya dan tidak mengalami kavitasi'], ans: 0,
      why: 'Pada reaksi eksotermik semi-batch, laju umpan adalah pengendali utama laju pelepasan panas. Umpan berlebih berarti akumulasi reaktan dan potensi runaway.' },
    { q: 'Apa yang terjadi bila suhu reaktor melewati suhu onset sekitar 110 °C?', opts: ['Laju reaksi dan pelepasan panas naik eksponensial sehingga suhu dan tekanan tidak terkendali', 'Reaksi melambat karena monomer mulai menguap dan keluar melalui kondensor refluks E-201', 'Suhu selalu stabil dengan sendirinya karena panas diserap oleh penguapan pelarut di reaktor', 'Katalis terurai sehingga reaksi berhenti dan reaktor aman untuk didinginkan'], ans: 0,
      why: 'Di atas onset, pelepasan panas melampaui pembuangan panas sehingga suhu dan tekanan naik dengan cepat. Inilah mekanisme kecelakaan Seveso dan T2 Laboratories.' },
    { q: 'Perangkat mana yang termasuk sistem kendali proses dasar (BPCS), bukan lapisan proteksi?', opts: ['TCV-201 dan loop pengendali suhu TIC-201', 'Trip suhu tinggi-tinggi yang menghentikan umpan melalui SIS', 'Rupture disc yang melepas tekanan reaktor ke sistem penampung', 'Detektor gas dan sistem deluge di area reaktor'], ans: 0,
      why: 'Loop kendali suhu menjaga kondisi normal. Lapisan proteksi harus independen dari BPCS agar kegagalan BPCS tidak sekaligus menghilangkan proteksi (IEC 61511).' },
    { q: 'Apa peran agitator M-201 terhadap keselamatan proses?', opts: ['Menjaga perpindahan panas ke jaket dan mencegah akumulasi reaktan yang tidak tercampur', 'Mempercepat reaksi agar batch cepat selesai sehingga waktu paparan bahaya berkurang', 'Menurunkan tekanan reaktor dengan memecah gelembung uap yang terbentuk di permukaan cairan', 'Hanya menjaga mutu produk karena seluruh pendinginan sudah ditangani oleh jaket reaktor'], ans: 0,
      why: 'Kegagalan agitator menurunkan koefisien perpindahan panas dan dapat membuat lapisan reaktan menumpuk, lalu bereaksi serentak saat pengadukan berjalan kembali.' },
    { q: 'Ke mana uap pelarut dari reaktor dialirkan pada kondisi normal?', opts: ['Ke kondensor refluks E-201, kondensat kembali ke reaktor dan gas tak terkondensasi ke vent', 'Ke kondensor refluks E-201, lalu seluruh kondensat dikirim ke tangki produk TK-202', 'Langsung ke vent melalui rupture disc agar tekanan reaktor tetap rendah', 'Ke jaket pendingin, tempat uap mengembun dan menyerahkan panasnya ke air pendingin yang mengalir'], ans: 0,
      why: 'Kondensor refluks adalah bagian dari sistem pembuangan panas. Kehilangan pendingin kondensor menaikkan tekanan reaktor.' },
  ],
  events: [
    { id: 'e1', threat: 0, effects: [{ var: 'FCW', to: 2, delay: 1, dur: 3 }, { var: 'T2', to: 135, delay: 4, dur: 22 }, { var: 'P2', to: 6.8, delay: 12, dur: 14 }],
      warnings: [
        { t: 13, type: 'heat', sev: 'warn', at: 'R-201', pos: [480, 330], text: 'Dinding reaktor R-201 terasa sangat panas dan cat jaket mulai menggelembung.' },
        { t: 21, type: 'toxic', sev: 'crit', at: 'VNT-201', pos: [900, 104], text: 'Kebocoran gas beracun. Uap monomer keluar dari vent dan gasket tutup reaktor. Bau menyengat tercium di area reaktor.' },
        { t: 28, type: 'explosion', sev: 'final', at: 'R-201', pos: [470, 236], text: 'Terjadi ledakan pada sambungan tutup reaktor R-201 akibat reaksi runaway. Uap beracun menyebar ke area sekitar.' },
      ],
      answer: { node: ['R-201', 'P-203'], param: ['T', 'F'], guide: ['high', 'low', 'none'] },
      hint: 'Panas reaksi tidak lagi terbuang melalui jaket. Periksa sumber air pendingin.',
      causes: ['Pompa air pendingin P-203 trip sehingga panas reaksi tidak terbuang', 'Agitator berputar terlalu cepat', 'Level reaktor terlalu rendah', 'Vent tersumbat'], causeAns: 0,
      cons: ['Reaksi runaway dengan suhu dan tekanan naik eksponensial, bejana pecah, lalu uap beracun dan mudah terbakar terlepas', 'Produk terlalu encer', 'Pompa produk mengalami kavitasi', 'Tangki umpan kosong'], consAns: 0,
      explain: 'Aliran pendingin hilang lebih dulu, lalu suhu dan tekanan naik. Urutan kejadian menunjukkan bahwa penyebab awalnya adalah kehilangan pendinginan, yaitu deviasi aliran dengan guideword Tidak ada (No). Jawaban suhu tinggi di R-201 juga diterima sebagai deviasi utama.' },
    { id: 'e2', threat: 1, effects: [{ var: 'FA', to: 4.5, delay: 1, dur: 4 }, { var: 'T2', to: 124, delay: 6, dur: 22 }, { var: 'P2', to: 5.6, delay: 14, dur: 14 }],
      warnings: [
        { t: 15, type: 'heat', sev: 'warn', at: 'R-201', pos: [480, 330], text: 'Panas berlebih di sekitar reaktor R-201. Air pendingin yang keluar dari jaket sangat panas.' },
        { t: 22, type: 'leak', sev: 'crit', at: 'R-201', pos: [432, 238], text: 'Uap monomer menyembur dari gasket manhole R-201 disertai suara mendesis.' },
        { t: 29, type: 'fire', sev: 'final', at: 'R-201', pos: [480, 300], text: 'Uap monomer tersulut dan terjadi kebakaran di area reaktor R-201.' },
      ],
      answer: { node: ['R-201', 'FCV-201'], param: ['F', 'T'], guide: ['high'] },
      hint: 'Monomer masuk lebih cepat daripada kemampuan sistem membuang panas. Periksa katup kendali laju umpan.',
      causes: ['FCV-201 terbuka berlebih (kegagalan katup atau kesalahan set point operator) sehingga umpan melampaui kapasitas pendinginan', 'Air pendingin terlalu dingin', 'Kondensor E-201 terlalu efektif', 'Agitator berhenti'], causeAns: 0,
      cons: ['Akumulasi monomer, pelepasan panas melebihi pendinginan, reaksi runaway, dan overpressure', 'Level reaktor turun', 'Produk hanya tidak memenuhi spesifikasi tanpa dampak keselamatan', 'Pompa umpan rusak'], consAns: 0,
      explain: 'Laju umpan naik lebih dari dua kali nilai normal, lalu diikuti kenaikan suhu. Pembatasan laju umpan (FT dengan pembatas) dan TSHH adalah proteksi yang tepat.' },
    { id: 'e3', threat: 2, effects: [{ var: 'P2', to: 6.9, delay: 1, dur: 18 }, { var: 'T2', to: 98, delay: 8, dur: 14 }],
      warnings: [
        { t: 12, type: 'heat', sev: 'warn', at: 'E-201', text: 'Kondensor E-201 terasa panas dan tidak ada aliran gas yang keluar dari ujung vent.' },
        { t: 19, type: 'leak', sev: 'crit', at: 'R-201', pos: [540, 238], text: 'Uap pelarut bocor dari flens dan gasket bagian atas R-201 dengan suara mendesis keras.' },
        { t: 26, type: 'explosion', sev: 'final', at: 'R-201', pos: [480, 234], text: 'Terjadi ledakan pada sambungan flens atas R-201 akibat tekanan melampaui desain 6 barg.' },
      ],
      answer: { node: ['R-201', 'E-201', 'VNT-201'], param: ['P'], guide: ['high'] },
      hint: 'Uap pelarut tidak memiliki jalan keluar. Periksa jalur vent dan kondensor.',
      causes: ['Jalur vent tersumbat atau kondensor E-201 kehilangan pendingin sehingga uap tidak terkondensasi', 'Umpan dihentikan', 'Agitator terlalu lambat', 'Level terlalu rendah'], causeAns: 0,
      cons: ['Tekanan melampaui desain 6 barg, bejana pecah atau flens bocor, lalu uap mudah terbakar terlepas', 'Suhu reaktor turun', 'Produk menjadi lebih kental', 'Pompa produk trip'], consAns: 0,
      explain: 'Tekanan naik lebih dulu tanpa perubahan umpan atau pendingin jaket. Penyebabnya berada di sistem vent dan kondensor. Perangkat pelepas tekanan (PSV atau RD) wajib tersedia.' },
    { id: 'e4', threat: 3, effects: [{ var: 'FA', to: 3, delay: 1, dur: 3 }, { var: 'L2', to: 98, delay: 2, dur: 18 }],
      warnings: [
        { t: 17, type: 'vibration', sev: 'warn', at: 'E-201', text: 'Terjadi hentakan cairan (liquid hammer) pada jalur uap menuju kondensor E-201.' },
        { t: 22, type: 'spill', sev: 'crit', at: 'VNT-201', pos: [900, 168], text: 'Monomer cair tumpah dari ujung vent ke area di bawahnya.' },
        { t: 28, type: 'toxic', sev: 'final', at: 'VNT-201', pos: [880, 150], text: 'Uap monomer beracun menyebar luas dari tumpahan. Pekerja di area harus segera dievakuasi.' },
      ],
      answer: { node: ['R-201'], param: ['L'], guide: ['high'] },
      hint: 'Umpan terus masuk walaupun batas batch terlampaui. Pikirkan kemungkinan pembacaan level yang keliru.', hintVar: 'L2',
      causes: ['Transmitter level gagal dan membaca rendah palsu sehingga umpan terus masuk melampaui batas batch', 'Kondensor bocor', 'Air pendingin masuk ke reaktor', 'Pompa produk terlalu cepat'], causeAns: 0,
      cons: ['Reaktor terisi penuh, ruang uap hilang, cairan masuk ke kondensor dan vent, lalu monomer tumpah', 'Suhu turun drastis', 'Agitator berputar lebih cepat', 'Tekanan jaket naik'], consAns: 0,
      explain: 'Level naik melebihi batas batch. Proteksi overfill yang independen (LSHH yang menghentikan P-201) diperlukan karena loop level BPCS sudah gagal.' },
    { id: 'e5', start: 17,
      hf: { type: 'violation', team: 'mgmt', threat: 1, title: 'Resep dan set trip diubah tanpa MOC', factor: 'Laju umpan dan set trip dinaikkan tanpa MOC',
        lesson: 'Kasus ini merupakan violation situasional yang didorong oleh tekanan produksi. Supervisor memberi instruksi di luar kewenangannya karena perubahan resep dan set trip SIS harus melalui Management of Change dan persetujuan teknik proses. Teknisi sebenarnya sudah mengingatkan, tetapi belum ada budaya yang membuat pekerja berani menghentikan pekerjaan. Pengendaliannya adalah MOC yang ditegakkan, pembatasan akses perubahan set trip, dan hak setiap pekerja untuk menolak instruksi yang melanggar batas operasi aman.',
        controls: ['Perubahan resep dan set trip wajib melalui Management of Change', 'Akses perubahan set trip SIS dibatasi dan tercatat', 'Hak menghentikan pekerjaan (stop work authority) bagi setiap pekerja'] },
      chat: [
        { t: 1, who: 'hendra', at: 'CR-200', text: 'Batch ini harus selesai sebelum pukul sepuluh. Truk pelanggan sudah menunggu di gerbang.' },
        { t: 4, who: 'raka', at: 'CR-200', mood: 'ragu', text: 'Pak Hendra, umpan monomer sudah 2 m³/jam. Itu batas maksimum dalam resep.' },
        { t: 7, who: 'hendra', at: 'CR-200', mood: 'santai', text: 'Naikkan saja ke 4 m³/jam. Bulan lalu kita pernah mencobanya dan hasilnya aman.' },
        { t: 10, who: 'wawan', at: 'FCV-201', mood: 'ragu', text: 'Set trip aliran juga harus dinaikkan agar tidak trip. Pak Hendra, perubahan ini seharusnya melalui MOC.' },
        { t: 13, who: 'hendra', at: 'CR-200', mood: 'santai', text: 'Tidak apa-apa, saya yang bertanggung jawab. Formulirnya menyusul.' },
        { t: 16, who: 'raka', at: 'CR-200', mood: 'ragu', text: 'Baik, Pak. FCV-201 saya buka ke 4 m³/jam.' },
        { t: 27, who: 'raka', at: 'CR-200', mood: 'ragu', text: 'Suhu reaktor terus naik, padahal TCV-201 sudah terbuka penuh.' },
        { t: 33, who: 'raka', at: 'CR-200', mood: 'panik', text: 'Tekanan reaktor ikut naik! Pak Hendra, apakah umpan saya hentikan sekarang?' },
      ],
      effects: [{ var: 'FA', to: 4.5, delay: 1, dur: 3 }, { var: 'T2', to: 124, delay: 5, dur: 22 }, { var: 'P2', to: 5.6, delay: 13, dur: 14 }],
      warnings: [
        { t: 14, type: 'heat', sev: 'warn', at: 'R-201', pos: [480, 330], text: 'Panas berlebih di sekitar reaktor R-201. Air pendingin yang keluar dari jaket sangat panas.' },
        { t: 21, type: 'leak', sev: 'crit', at: 'R-201', pos: [432, 238], text: 'Uap monomer menyembur dari gasket manhole R-201 disertai suara mendesis.' },
        { t: 28, type: 'fire', sev: 'final', at: 'R-201', pos: [480, 300], text: 'Uap monomer tersulut dan terjadi kebakaran di area reaktor R-201.' },
      ],
      answer: { node: ['R-201', 'FCV-201'], param: ['F', 'T'], guide: ['high'] },
      hint: 'Aliran umpan naik dua kali lipat tanpa gangguan peralatan, lalu suhu dan tekanan reaktor mengikuti. Baca kembali percakapan tentang target produksi dan batas resep.',
      causes: ['Laju umpan dinaikkan melampaui batas resep dan set trip diubah atas instruksi supervisor tanpa MOC', 'FCV-201 terbuka penuh karena kerusakan positioner', 'Aliran air pendingin jaket berkurang karena pompa P-203 aus', 'Agitator M-201 melambat sehingga panas reaksi tidak tersebar merata'], causeAns: 0,
      cons: ['Panas reaksi melampaui kapasitas pendinginan sehingga terjadi reaksi runaway dan kehilangan kontainmen reaktor', 'Batch selesai lebih cepat dengan mutu produk yang sedikit menurun', 'Tangki umpan TK-201 kosong sebelum batch selesai', 'Kondensor E-201 tersumbat oleh polimer'], consAns: 0,
      explain: 'Laju umpan naik, lalu suhu dan tekanan reaktor ikut naik walaupun katup pengendali suhu sudah terbuka penuh. Batas umpan 2 m³/jam ditetapkan agar laju pelepasan panas reaksi tidak melampaui kapasitas pendinginan. Menaikkan umpan sekaligus menaikkan set trip berarti melepas dua lapisan proteksi bersamaan.' },
    { id: 'e6', threat: 1, effects: [{ var: 'NAG', to: 0, delay: 1, dur: 2 }, { var: 'T2', to: 74, delay: 2, dur: 6 }, { var: 'T2', to: 134, delay: 12, dur: 12 }, { var: 'P2', to: 6.5, delay: 13, dur: 12 }],
      warnings: [
        { t: 10, type: 'vibration', sev: 'warn', at: 'M-201', text: 'Terdengar dentang dari gearbox M-201. Motor berputar tanpa beban, tetapi poros pengaduk berhenti.' },
        { t: 19, type: 'leak', sev: 'crit', at: 'R-201', pos: [432, 238], text: 'Suhu reaktor melonjak tajam dan uap monomer menyembur dari gasket tutup R-201.' },
        { t: 26, type: 'explosion', sev: 'final', at: 'R-201', pos: [470, 236], text: 'Monomer yang terakumulasi bereaksi serentak. Sambungan tutup R-201 pecah dan uap beracun menyebar.' },
      ],
      answer: { node: ['R-201', 'M-201'], param: ['C', 'T'], guide: ['partof', 'none', 'high'] },
      hint: 'Pengadukan berhenti, tetapi umpan tetap masuk. Suhu reaktor yang sempat turun bukan tanda aman. Pikirkan apa yang terjadi pada monomer yang tidak tercampur.',
      causes: ['Kopling agitator M-201 patah sehingga pengadukan berhenti dan monomer yang terus diumpankan menumpuk tanpa bereaksi', 'Pompa air pendingin P-203 trip sehingga panas reaksi tidak terbuang', 'FCV-201 macet terbuka sehingga laju umpan melampaui resep', 'Transmitter suhu reaktor menyimpang sehingga suhu terbaca turun'], causeAns: 0,
      cons: ['Monomer yang terakumulasi bereaksi serentak sehingga terjadi reaksi runaway dengan kenaikan suhu dan tekanan yang sangat cepat', 'Batch tertunda tanpa dampak keselamatan karena reaksi berhenti', 'Produk menjadi lebih encer dan harus diproses ulang', 'Tangki umpan TK-201 meluap karena umpan tertahan'], consAns: 0,
      explain: 'Putaran agitator jatuh ke nol, suhu reaktor sempat turun, lalu melonjak tajam. Tanpa pengadukan, monomer yang terus diumpankan tidak bereaksi merata sehingga hanya sebagian reaksi yang berlangsung (Part of) dan reaktan menumpuk. Saat akhirnya bereaksi, panasnya terlepas sekaligus melampaui kemampuan jaket. Penurunan suhu awal sering disalahartikan sebagai kondisi aman. Interlock agitator yang menghentikan umpan saat pengaduk berhenti memutus rantai ini, sedangkan injeksi quench dan perangkat pelepas tekanan menjadi lapisan berikutnya.' },
    { id: 'e7', start: 12,
      hf: { type: 'slip', team: 'ops', threat: 0, title: 'Output TCV-201 diturunkan karena faceplate tertukar dengan FIC-201', factor: 'Faceplate TIC-201 tertukar saat menurunkan umpan',
        lesson: 'Raka bermaksud menurunkan laju umpan pada faceplate FIC-201, tetapi yang terbuka di layar adalah faceplate TIC-201 yang letak dan bentuknya serupa. Niatnya benar, tetapi tindakannya mengenai sasaran yang salah sehingga tergolong slip. Mengubah pengendali ke mode manual juga menghilangkan koreksi otomatis dari loop suhu. Pencegahannya adalah desain HMI yang membedakan faceplate kritis menurut ANSI/ISA-101, konfirmasi tag sebelum perubahan, umpan balik yang jelas setelah perubahan, serta trip aliran pendingin rendah yang menghentikan umpan.',
        controls: ['Desain faceplate HMI yang membedakan pengendali kritis (ANSI/ISA-101)', 'Konfirmasi tag dan nilai sebelum perubahan disimpan', 'Trip aliran pendingin rendah yang menghentikan umpan'] },
      chat: [
        { t: 1, who: 'hendra', at: 'CR-200', text: 'Pak Raka, mutu batch kemarin kurang baik. Tolong turunkan dulu umpan monomer ke sekitar 1,5 m³/jam.' },
        { t: 4, who: 'raka', at: 'CR-200', text: 'Baik, Pak. Karena layar sedang penuh dengan tren, faceplate saya buka dari daftar tag.' },
        { t: 7, who: 'raka', at: 'CR-200', mood: 'santai', text: 'Sudah saya ubah ke mode manual dan saya turunkan ke 15 persen. Nanti saya naikkan lagi secara bertahap.' },
        { t: 10, who: 'wawan', at: 'FCV-201', text: 'Pak Raka, saya di FCV-201. Bukaan katup umpan masih sama seperti tadi pagi.' },
        { t: 15, who: 'raka', at: 'CR-200', mood: 'ragu', text: 'Aliran air pendingin jaket turun drastis, padahal yang saya ubah tadi adalah umpan.' },
        { t: 19, who: 'wawan', at: 'TCV-201', mood: 'ragu', text: 'TCV-201 hampir tertutup dan modenya manual. Faceplate yang Bapak ubah adalah TIC-201, bukan FIC-201!' },
        { t: 23, who: 'raka', at: 'CR-200', mood: 'panik', text: 'Suhu reaktor mendekati 90 derajat dan terus naik! TIC-201 saya kembalikan ke mode otomatis sekarang!' },
      ],
      effects: [{ var: 'FCW', to: 5, delay: 1, dur: 3 }, { var: 'T2', to: 132, delay: 4, dur: 22 }, { var: 'P2', to: 6.6, delay: 12, dur: 14 }],
      warnings: [
        { t: 13, type: 'heat', sev: 'warn', at: 'R-201', pos: [480, 330], text: 'Dinding reaktor R-201 terasa sangat panas. Air pendingin yang keluar dari jaket hampir tidak mengalir.' },
        { t: 21, type: 'toxic', sev: 'crit', at: 'VNT-201', pos: [900, 104], text: 'Uap monomer beracun keluar dari vent dan gasket tutup reaktor. Bau menyengat di area reaktor.' },
        { t: 28, type: 'explosion', sev: 'final', at: 'R-201', pos: [470, 236], text: 'Reaksi runaway memecahkan sambungan tutup R-201. Uap beracun dan mudah terbakar menyebar ke area sekitar.' },
      ],
      answer: { node: ['R-201', 'TCV-201'], param: ['T', 'F'], guide: ['high', 'low'] },
      hint: 'Aliran air pendingin jaket turun tanpa pompa yang trip, tepat setelah ada perubahan di layar operator. Baca kembali percakapan tentang pengendali mana yang sebenarnya diubah.',
      causes: ['Operator panel mengubah TIC-201 ke mode manual dan menurunkan output TCV-201 karena faceplate tertukar dengan FIC-201', 'Pompa air pendingin P-203 trip sehingga aliran ke jaket hilang', 'Strainer air pendingin dari menara tersumbat lumut', 'Agitator M-201 berhenti sehingga perpindahan panas ke jaket turun'], causeAns: 0,
      cons: ['Panas reaksi tidak terbuang sehingga terjadi reaksi runaway, tekanan melampaui desain, dan uap beracun terlepas', 'Laju umpan turun sehingga batch hanya tertunda', 'Air pendingin kembali ke menara terlalu dingin', 'Produk resin terlalu kental untuk dipompa'], consAns: 0,
      explain: 'Aliran air pendingin jaket turun drastis padahal pompa P-203 tetap berjalan, lalu suhu dan tekanan reaktor naik. Penyebabnya adalah output TCV-201 yang diturunkan secara manual karena faceplate tertukar. Polanya sama dengan kehilangan air pendingin sehingga trip aliran pendingin rendah dan trip suhu tinggi-tinggi tetap diperlukan sebagai lapisan proteksi yang tidak bergantung pada ketelitian operator.' },
    { id: 'e8', start: 12,
      hf: { type: 'lapse', team: 'mtc', threat: 2, title: 'Spade blind di jalur vent tidak dilepas setelah pembersihan kondensor', factor: 'Spade blind vent tidak dilepas setelah perawatan',
        lesson: 'Joko memasang spade blind di jalur vent untuk mengisolasi kondensor saat dibersihkan, lalu menyatakan pekerjaan selesai tanpa melepasnya kembali. Ia tidak berniat melanggar prosedur. Langkah pemulihan terlupa karena tidak tercatat. Kegagalan memori seperti ini tergolong lapse. Spade yang tertinggal mengubah jalur vent menjadi jalan buntu, dan beban keselamatan langsung berpindah ke perangkat pelepas tekanan. Pencegahannya adalah register isolasi yang mencatat setiap spade, daftar periksa pelepasan isolasi sebelum izin kerja ditutup, dan verifikasi bersama operator.',
        controls: ['Register isolasi yang mencatat setiap spade blind dan posisinya', 'Daftar periksa pelepasan isolasi sebelum izin kerja ditutup', 'Verifikasi lapangan bersama operator sebelum unit dijalankan'] },
      chat: [
        { t: 1, who: 'hendra', at: 'CR-200', text: 'Pak Joko, apakah pembersihan kondensor E-201 kemarin sudah tuntas? Batch berikutnya akan segera dimulai.' },
        { t: 4, who: 'joko', at: 'E-201', text: 'Sudah, Pak. Tube sudah bersih dan tutup kondensor sudah dipasang rapat dengan gasket baru.' },
        { t: 7, who: 'joko', at: 'E-201', mood: 'santai', text: 'Kemarin saya memasang spade di flens vent agar uap tidak berbalik saat pembersihan. Yang penting, izin kerja sudah saya tutup.' },
        { t: 10, who: 'raka', at: 'CR-200', text: 'Baik, terima kasih. Saya mulai operasi reaktor seperti biasa.' },
        { t: 16, who: 'raka', at: 'CR-200', mood: 'ragu', text: 'Tekanan R-201 naik perlahan, padahal umpan dan air pendingin normal. Aliran gas dari vent juga tidak terlihat.' },
        { t: 20, who: 'dimas', at: 'VNT-201', mood: 'ragu', text: 'Saya di jalur vent. Spade blind masih terpasang di flens setelah E-201 dan belum dilepas!' },
        { t: 24, who: 'raka', at: 'CR-200', mood: 'panik', text: 'Tekanan sudah melewati 3 barg dan terus naik! Hentikan umpan dan panggil Pak Joko untuk melepas spade sekarang!' },
      ],
      effects: [{ var: 'P2', to: 6.9, delay: 2, dur: 22 }, { var: 'T2', to: 98, delay: 8, dur: 14 }],
      warnings: [
        { t: 14, type: 'heat', sev: 'warn', at: 'E-201', text: 'Kondensor E-201 terasa panas dan tidak ada gas yang keluar dari ujung vent.' },
        { t: 19, type: 'leak', sev: 'crit', at: 'R-201', pos: [540, 238], text: 'Uap pelarut bocor dari flens dan gasket bagian atas R-201 dengan suara mendesis keras.' },
        { t: 26, type: 'explosion', sev: 'final', at: 'R-201', pos: [480, 234], text: 'Sambungan flens atas R-201 pecah karena tekanan melampaui desain 6 barg. Uap pelarut tersulut.' },
      ],
      answer: { node: ['R-201', 'E-201', 'VNT-201'], param: ['P'], guide: ['high'] },
      hint: 'Tekanan reaktor naik walaupun umpan dan pendingin normal, dan tidak ada gas keluar dari vent. Baca kembali percakapan tentang pekerjaan pembersihan kondensor.',
      causes: ['Spade blind yang dipasang saat pembersihan kondensor tidak dilepas kembali sehingga jalur vent tertutup', 'Kondensor E-201 tersumbat polimer sehingga uap tidak terkondensasi', 'Laju umpan monomer melampaui resep sehingga panas reaksi berlebih', 'Transmitter tekanan reaktor menyimpang sehingga tekanan terbaca naik'], causeAns: 0,
      cons: ['Tekanan melampaui desain 6 barg sehingga flens atau bejana gagal dan uap mudah terbakar terlepas', 'Suhu reaktor turun sehingga reaksi berhenti', 'Produk menjadi terlalu encer', 'Pompa produk P-202 trip'], consAns: 0,
      explain: 'Tekanan reaktor naik lebih dulu tanpa perubahan umpan atau pendingin jaket, dan vent tidak mengeluarkan gas. Polanya sama dengan vent terblokir, tetapi penyebabnya spade blind yang tertinggal setelah perawatan. Isolasi yang tidak dipulihkan adalah penyebab klasik kecelakaan saat unit mulai dijalankan (start-up) sehingga perangkat pelepas tekanan tetap wajib sebagai lapisan yang tidak bergantung pada pemulihan isolasi.' },
  ],
  variants: [
    ['e4', 'e2', 'e8', 'e6', 'e7'],
    ['e6', 'e4', 'e5', 'e1', 'e8'],
    ['e3', 'e6', 'e7', 'e4', 'e5'],
    ['e2', 'e6', 'e7', 'e3', 'e8'],
    ['e1', 'e4', 'e8', 'e2', 'e5'],
  ],
  hotspots: [
    /* Tahap 3: pencegahan, diurutkan menurut posisi baca pada P&ID (kiri ke kanan, atas ke bawah) */
    { id: 'h37', stage: 3, on: 'TK-201', tap: [100, 57], x: 78, y: 35, label: 'Ruang uap TK-201', accept: ['N2'],
      why: 'Blanketing nitrogen menjaga ruang uap tangki monomer berada di luar rentang mudah terbakar.' },
    { id: 'h33', stage: 3, on: 'f2', tap: [351, 210], x: 343, y: 180, label: 'Jalur umpan sebelum reaktor', accept: ['FT'],
      why: 'Pembatas laju umpan mencegah pelepasan panas melebihi kapasitas pendinginan (prinsip semi-batch yang aman).' },
    { id: 'h35', stage: 3, on: 'M-201', tap: [520, 194], x: 489, y: 163, label: 'Motor agitator M-201', accept: ['AGI'],
      why: 'Interlock agitator menghentikan umpan bila pengaduk mati agar reaktan tidak terakumulasi.' },
    { id: 'h38', stage: 3, on: 'f1', tap: [100, 210], x: 70, y: 218, label: 'Sisi isap pompa P-201', accept: [],
      why: 'Titik ini tidak terkait dengan skenario yang teridentifikasi. Perangkat tambahan di sini menghabiskan anggaran tanpa menurunkan risiko utama.' },
    { id: 'h32', stage: 3, on: 'R-201', tap: [422, 231], x: 386, y: 241, label: 'Nozzle puncak R-201 (pelepas tekanan)', accept: ['RD', 'PSV'],
      why: 'Perangkat pelepas tekanan diperlukan untuk menghadapi overpressure. Rupture disc cocok untuk kenaikan tekanan yang sangat cepat pada reaksi runaway, tetapi PSV juga diterima.' },
    { id: 'h31', stage: 3, on: 'R-201', tap: [389, 340], x: 371, y: 372, label: 'Nozzle suhu R-201', accept: ['TSHH', 'TT'],
      why: 'Trip suhu tinggi-tinggi menghentikan umpan dan membuka pendingin darurat sebelum onset runaway. Alarm TT diterima sebagai lapisan respons operator meskipun lebih lemah.' },
    { id: 'h36', stage: 3, on: 'R-201', tap: [570, 380], x: 601, y: 380, label: 'Nozzle level R-201', accept: ['LSHH', 'LT'],
      why: 'Proteksi overfill yang independen dari transmitter level BPCS.' },
    { id: 'h34', stage: 3, on: 'cw2', tap: [359, 420], x: 367, y: 450, label: 'Jalur air pendingin ke jaket', accept: ['FSLL'],
      why: 'Kehilangan pendingin adalah pemicu runaway yang paling sering. Trip aliran rendah menghentikan umpan secara otomatis.' },
    { id: 'h39', stage: 3, on: 'pr2', tap: [649, 480], x: 657, y: 510, label: 'Sisi tekan pompa produk P-202', accept: ['NRV'],
      why: 'Katup searah (check valve) mencegah aliran balik produk. Ini perbaikan kecil yang tepat, tetapi prioritas tetap pada reaktor.' },
    /* Tahap 4: mitigasi, diurutkan menurut posisi baca pada P&ID (kiri ke kanan, atas ke bawah) */
    { id: 'h44', stage: 4, on: 'TK-201', tap: [150, 164], x: 172, y: 142, label: 'Sekeliling TK-201', accept: ['DIKE'],
      why: 'Tanggul menampung tumpahan monomer dari tangki umpan.' },
    { id: 'h47', stage: 4, on: 'f2', tap: [222, 210], x: 214, y: 180, label: 'Jalur umpan (isolasi jarak jauh)', accept: ['EIV'],
      why: 'Menghentikan suplai monomer ke area kebocoran dari jarak aman.' },
    { id: 'h42', stage: 4, on: 'v2', tap: [749, 120], x: 757, y: 150, label: 'Jalur vent setelah E-201', accept: ['SCRUB'],
      why: 'Pelepasan darurat uap monomer harus dinetralkan sebelum ke atmosfer untuk melindungi pekerja dan masyarakat.' },
    { id: 'h41', stage: 4, on: 'R-201', tap: [400, 256], x: 373, y: 241, label: 'Nozzle injeksi R-201', accept: ['QUENCH'],
      why: 'Quench atau inhibitor menghentikan reaksi runaway yang sudah dimulai ketika pencegahan gagal.' },
    { id: 'h40', stage: 4, on: 'cw3', tap: [229, 270], x: 237, y: 300, label: 'Jalur air pendingin kembali', accept: [],
      why: 'Air pendingin bukan bahan berbahaya. Perangkat mitigasi di sini tidak menurunkan risiko.' },
    { id: 'h43', stage: 4, on: 'R-201', tap: [570, 320], x: 601, y: 320, label: 'Area reaktor (deteksi gas)', accept: ['GD'],
      why: 'Detektor gas mendeteksi kebocoran uap monomer di area reaktor.' },
    { id: 'h46', stage: 4, on: 'CR-200', tap: [840, 319], x: 818, y: 297, label: 'Ruang Kendali (ESD)', accept: ['ESD'],
      why: 'ESD menghentikan umpan dan pompa serta mengaktifkan quench dari jarak aman.' },
    { id: 'h49', stage: 4, on: 'TK-202', tap: [748, 387], x: 726, y: 365, label: 'Atap TK-202', accept: ['FOAM', 'FW'],
      why: 'Isi tangki produk mudah terbakar. Busa atau monitor air memadamkan api dan mendinginkan tangki.' },
    { id: 'h45', stage: 4, on: 'R-201', tap: [440, 441], x: 440, y: 472, label: 'Area bawah reaktor (deteksi api)', accept: ['FD'],
      why: 'Detektor nyala memicu deluge dan ESD bila kebocoran produk terbakar.' },
    { id: 'h48', stage: 4, on: 'MP-200', tap: [859, 520], x: 828, y: 520, label: 'Titik Kumpul dan alarm umum', accept: ['ALARM'],
      why: 'Perlindungan orang melalui evakuasi terencana.' },
  ],
  inspect: [
    { id: 'R-201', itpm: 'VESSEL', why: 'Reaktor adalah bejana tekan berjaket. Pemeriksaan berkala mendeteksi korosi, erosi, dan retak pada dinding serta jaket (Permenaker No. 37 Tahun 2016).' },
    { id: 'P-203', itpm: 'ROT', why: 'Pompa air pendingin adalah satu-satunya sumber pendinginan. Perawatan prediktif mengurangi peluang pompa trip, pemicu utama reaksi runaway.' },
    { id: 'M-201', itpm: 'ROT', why: 'Kegagalan agitator menurunkan perpindahan panas dan memicu akumulasi reaktan. Pemantauan getaran motor dan gearbox mencegah kegagalan mendadak.' },
  ],
  budget: { 3: 31, 4: 34 },
  bowtie: {
    top: 'Reaksi runaway dan kehilangan kontainmen reaktor R-201',
    threats: ['Kehilangan air pendingin', 'Laju umpan berlebih atau akumulasi monomer', 'Vent dan kondensor terblokir', 'Overfill reaktor'],
    cons: ['Pecahnya bejana dan ledakan', 'Pelepasan uap beracun ke lingkungan', 'Kebakaran area reaktor', 'Tumpahan monomer'],
  },
};
SCENARIOS.push(SCN_REACTOR);
