/* Skenario sektor Properti: dimuat setelah js/data.js dan menambahkan diri ke SCENARIOS. */
/* =====================================================================
   PROPERTI (KONSTRUKSI EPC): Asphalt Mixing Plant Proyek Jalan
   ===================================================================== */
const SCN_AMP = {
  id: 'amp',
  title: 'Asphalt Mixing Plant Proyek Jalan',
  subtitle: 'Cold bin, drum pengering dan burner, baghouse, hot elevator, tangki aspal dengan pemanas oli termal',
  level: 'Menengah',
  sector: 'properti',
  area: 'Konstruksi EPC Jalan',
  color: '#5b6770',
  kits: ['amp'],
  op: 'Operasi AMP',
  overview: [
    'Unit pencampur aspal (Asphalt Mixing Plant, AMP) jenis takaran ini memasok campuran beraspal panas untuk proyek jalan dengan kapasitas sekitar 160 ton/jam. Agregat dari cold bin CB-101 dibawa konveyor CV-101 ke drum pengering DR-101, dipanaskan oleh burner BRN-101 hingga sekitar 165 °C, lalu diangkat hot elevator HE-101 ke menara pencampur MX-101.',
    'Gas pembakaran dan debu dari drum disedot ID fan FN-101 melalui baghouse BH-101 sebelum dibuang ke cerobong. Aspal di tangki TK-201 dijaga sekitar 160 °C oleh oli termal dari pemanas HTR-201 yang disirkulasikan pompa P-201. Burner drum memakai solar dari tangki TK-101.',
    'AMP umumnya dibangun sementara di lokasi proyek dengan jadwal yang padat, sehingga pengaman pembakaran sering dianggap penghambat produksi. Padahal bahayanya serupa dengan unit proses: ledakan ruang bakar, semburan balik api, kebakaran filter debu, dan kegagalan sistem pemanas fluida. Keselamatan konstruksi di Indonesia dikelola melalui Sistem Manajemen Keselamatan Konstruksi (Permen PUPR No. 10 Tahun 2021).',
  ],
  production: { label: 'Campuran aspal diproduksi', unit: 't', var: 'FAG', k: 1.05 / 60, dec: 1 },
  fluidNames: { agg: 'Agregat (dingin dan panas)', flue: 'Gas pembakaran dan debu', oil: 'Solar (bahan bakar burner)', asphalt: 'Aspal panas', hotoil: 'Oli termal (hot oil)', mix: 'Campuran beraspal panas' },
  equipment: [
    { id: 'ST-101', type: 'stack', x: 40, y: 250, h: 200, w: 22, name: 'Cerobong ST-101',
      desc: 'Membuang gas pembakaran yang sudah disaring baghouse ke atmosfer.' },
    { id: 'FN-101', type: 'fan', x: 100, y: 226, dir: 'left', name: 'ID Fan FN-101',
      desc: 'Kipas isap yang menyedot gas pembakaran dan debu dari drum melalui baghouse, sehingga tekanan di ujung burner tetap sedikit negatif.', vars: ['IDF'] },
    { id: 'BH-101', type: 'filter', x: 150, y: 40, w: 120, h: 150, name: 'Baghouse BH-101',
      desc: 'Filter kantong yang menangkap debu halus dari gas pembakaran drum. Kantong filter berbahan aramid memiliki batas suhu operasi sekitar 200 °C.', vars: ['TBH'] },
    { id: 'CB-101', type: 'silo', x: 20, y: 330, w: 96, h: 110, name: 'Cold Bin Agregat CB-101',
      desc: 'Hopper agregat dingin berbagai ukuran dengan pengumpan bawah yang mengatur proporsi umpan.' },
    { id: 'CV-101', type: 'conveyor', x: 90, y: 230, w: 220, h: 240, name: 'Konveyor Umpan CV-101',
      desc: 'Membawa agregat dingin dari cold bin ke ujung umpan drum pengering.', vars: ['FAG'] },
    { id: 'DR-101', type: 'drum', x: 322, y: 200, w: 210, h: 56, name: 'Drum Pengering DR-101',
      desc: 'Drum berputar yang mengeringkan dan memanaskan agregat dengan aliran berlawanan arah terhadap nyala burner. Bagian dalamnya selalu berisi gas panas, debu, dan kabut bahan bakar bila nyala tidak sempurna.', vars: ['PDR', 'TAG'] },
    { id: 'BRN-101', type: 'burner', x: 560, y: 228, dir: 'left', name: 'Burner Drum BRN-101', flameVar: 'FLM',
      desc: 'Burner solar sekitar 15 MW yang menembakkan nyala ke dalam drum dari ujung keluaran agregat.', vars: ['FLM', 'FFU'] },
    { id: 'HE-101', type: 'elevator', x: 610, y: 60, w: 26, h: 236, name: 'Hot Elevator HE-101',
      desc: 'Mengangkat agregat panas dari drum ke saringan dan hot bin di puncak menara pencampur.' },
    { id: 'MX-101', type: 'mixer', x: 690, y: 100, w: 120, h: 170, name: 'Menara Pencampur MX-101',
      desc: 'Berisi saringan getar, hot bin, timbangan agregat dan aspal, serta pugmill yang mencampur agregat panas dengan aspal.' },
    { id: 'TRK-101', type: 'sink', x: 760, y: 312, dir: 'right', name: 'Ke Truk Pengangkut',
      desc: 'Campuran beraspal panas dimuat ke dump truck untuk dihampar di lokasi pekerjaan jalan.' },
    { id: 'TK-101', type: 'tank', x: 330, y: 360, w: 70, h: 90, name: 'Tangki Solar TK-101',
      desc: 'Tangki solar 20.000 liter untuk burner drum.' },
    { id: 'P-101', type: 'pump', x: 450, y: 430, name: 'Pompa Bahan Bakar P-101',
      desc: 'Mengalirkan solar dari tangki ke burner drum melalui katup pengatur bahan bakar.' },
    { id: 'TK-201', type: 'tank', x: 690, y: 380, w: 90, h: 100, name: 'Tangki Aspal TK-201',
      desc: 'Tangki aspal 50 ton yang dipanaskan koil oli termal hingga sekitar 160 °C agar aspal cukup encer untuk dipompa ke menara pencampur.', vars: ['TAS'] },
    { id: 'HTR-201', type: 'heater', x: 900, y: 400, w: 72, h: 90, name: 'Pemanas Oli Termal HTR-201',
      desc: 'Pemanas berbahan bakar solar yang memanaskan oli termal di dalam koil hingga sekitar 220 °C. Oli harus terus mengalir agar koil tidak kepanasan.', vars: ['TOL'] },
    { id: 'P-201', type: 'pump', x: 830, y: 480, name: 'Pompa Oli Termal P-201',
      desc: 'Mensirkulasikan oli termal dari pemanas ke koil tangki aspal dan kembali ke pemanas.', vars: ['FOL'] },
    { id: 'CR-100', type: 'building', x: 520, y: 500, name: 'Ruang Kontrol',
      desc: 'Operator mengatur produksi, burner, dan takaran campuran dari ruang kontrol. Lokasi tombol ESD.' },
    { id: 'MP-100', type: 'muster', x: 940, y: 160, name: 'Titik Kumpul',
      desc: 'Area berkumpul evakuasi di luar jalur truk dan jauh dari drum serta tangki.' },
  ],
  pipes: [
    { id: 'a1', fluid: 'agg', w: 6, pts: [[68, 444], [68, 470], [83, 470]] },
    { id: 'a2', fluid: 'agg', w: 6, pts: [[317, 226], [334, 226]] },
    { id: 'a3', fluid: 'agg', w: 6, pts: [[512, 262], [512, 284], [602, 284]], arrow: true },
    { id: 'a4', fluid: 'agg', w: 6, pts: [[640, 58], [710, 58], [710, 100]], arrow: true },
    { id: 'g1', fluid: 'flue', w: 8, pts: [[336, 204], [336, 110], [270, 110]], arrow: true },
    { id: 'g2', fluid: 'flue', w: 8, pts: [[150, 80], [100, 80], [100, 204]] },
    { id: 'g3', fluid: 'flue', w: 8, pts: [[66, 210], [51, 210]] },
    { id: 'o1', fluid: 'oil', w: 4, pts: [[400, 430], [428, 430]] },
    { id: 'o2', fluid: 'oil', w: 4, pts: [[472, 430], [566, 430], [566, 239]], arrow: true },
    { id: 'b1', fluid: 'asphalt', w: 5, pts: [[735, 370], [735, 340], [672, 340], [672, 160], [690, 160]], arrow: true },
    { id: 'm1', fluid: 'mix', w: 6, pts: [[750, 243], [750, 312], [760, 312]] },
    { id: 'h1', fluid: 'hotoil', w: 4, pts: [[900, 418], [780, 418]], arrow: true },
    { id: 'h2', fluid: 'hotoil', w: 4, pts: [[780, 460], [794, 460], [794, 480], [808, 480]] },
    { id: 'h3', fluid: 'hotoil', w: 4, pts: [[852, 480], [900, 480]], arrow: true },
  ],
  labels: [],
  vars: {
    FLM: { label: 'Intensitas Nyala Burner', unit: '%', normal: 90, min: 0, max: 100, lo: 50, lolo: 30, node: 'BRN-101', x: 560, y: 180, tau: 1, noise: 0.8, dec: 0 },
    FFU: { label: 'Aliran Solar ke Burner', unit: 'L/j', normal: 600, min: 0, max: 1200, hi: 950, node: 'BRN-101', x: 520, y: 400, tau: 1.5, noise: 3, dec: 0 },
    TBH: { label: 'Suhu Gas Masuk Baghouse', unit: '°C', normal: 150, min: 20, max: 400, lo: 110, hi: 190, hihi: 205, node: 'BH-101', x: 390, y: 150, tau: 3, noise: 0.5, dec: 0 },
    PDR: { label: 'Tekanan Ujung Burner Drum', unit: 'mmH2O', normal: -8, min: -40, max: 40, hi: -2, hihi: 2, node: 'DR-101', x: 460, y: 302, tau: 1, noise: 0.3, dec: 0 },
    TAG: { label: 'Suhu Agregat Panas', unit: '°C', normal: 165, min: 20, max: 300, lo: 140, hi: 185, node: 'DR-101', x: 460, y: 330, tau: 4, noise: 0.4, dec: 0 },
    FAG: { label: 'Aliran Agregat Dingin', unit: 't/j', normal: 160, min: 0, max: 250, lo: 100, lolo: 60, node: 'CV-101', x: 250, y: 400, tau: 1.5, noise: 0.8, dec: 0 },
    IDF: { label: 'Arus Motor ID Fan', unit: 'A', normal: 180, min: 0, max: 300, lo: 120, lolo: 60, node: 'FN-101', x: 175, y: 262, tau: 0.8, noise: 1, dec: 0 },
    TOL: { label: 'Suhu Oli Termal Keluar Pemanas', unit: '°C', normal: 220, min: 20, max: 400, hi: 250, hihi: 270, node: 'HTR-201', x: 936, y: 340, tau: 3, noise: 0.4, dec: 0 },
    FOL: { label: 'Aliran Oli Termal', unit: 'm³/j', normal: 40, min: 0, max: 80, lo: 25, lolo: 15, node: 'P-201', x: 836, y: 440, tau: 1, noise: 0.3, dec: 0 },
    TAS: { label: 'Suhu Aspal di Tangki', unit: '°C', normal: 160, min: 20, max: 250, lo: 140, hi: 180, node: 'TK-201', x: 735, y: 510, tau: 8, noise: 0.2, dec: 0 },
  },
  trendVars: ['FLM', 'PDR', 'TBH', 'TOL'],
  controls: [
    { id: 'prod', label: 'Laju produksi campuran', unit: 't/j', min: 100, max: 200, def: 160, step: 10,
      effects: [{ var: 'FAG', gain: 1 }, { var: 'FFU', gain: 2.5 }, { var: 'IDF', gain: 0.4 }] },
    { id: 'tag', label: 'Set point suhu agregat panas', unit: '°C', min: 150, max: 180, def: 165, step: 5,
      effects: [{ var: 'TAG', gain: 1 }, { var: 'FFU', gain: 6 }, { var: 'TBH', gain: 0.8 }] },
    { id: 'moist', label: 'Kadar air agregat', unit: '%', min: 2, max: 7, def: 4, step: 0.5,
      effects: [{ var: 'FFU', gain: 40 }, { var: 'TAG', gain: -2 }] },
  ],
  quiz: [
    { q: 'Mengapa drum dan saluran gas buang harus dipurging sebelum burner dinyalakan ulang?', opts: ['Agar drum lebih cepat panas', 'Untuk membuang uap atau kabut bahan bakar yang tertinggal sehingga tidak terbentuk campuran yang meledak saat penyalaan', 'Agar agregat lebih kering', 'Untuk membersihkan kantong filter'], ans: 1,
      why: 'Ledakan saat penyalaan ulang adalah pola kecelakaan yang berulang pada tungku dan pengering berbahan bakar. NFPA 86 mensyaratkan purging dengan udara segar sebelum penyalaan.' },
    { q: 'Apa fungsi ID fan pada AMP?', opts: ['Meniupkan udara pembakaran ke burner', 'Menyedot gas pembakaran dan debu dari drum melalui baghouse sehingga tekanan di ujung burner tetap negatif', 'Mendinginkan agregat panas', 'Memompa aspal ke menara pencampur'], ans: 1,
      why: 'Tekanan negatif mencegah api dan gas panas keluar ke arah operator. Bila ID fan mati, burner harus berhenti otomatis.' },
    { q: 'Mengapa suhu gas masuk baghouse harus dijaga dalam rentang tertentu?', opts: ['Agar cerobong tidak berasap sama sekali', 'Karena kantong filter memiliki batas suhu operasi dan debu berminyak di dalamnya mudah terbakar, sedangkan suhu terlalu rendah membuat uap air mengembun dan menyumbat kantong', 'Agar ID fan bekerja lebih ringan', 'Karena aturan lalu lintas truk'], ans: 1,
      why: 'Batas atas melindungi kantong dari kebakaran, sedangkan batas bawah mencegah kondensasi. Keduanya dipantau dari suhu masuk baghouse.' },
    { q: 'Mengapa busa berbasis air harus sangat hati-hati dipakai pada kebakaran tangki aspal panas?', opts: ['Karena busa terlalu mahal', 'Karena air di dalam busa mendidih seketika saat menyentuh aspal di atas 100 °C sehingga aspal panas meluap dan menyembur (frothing atau slop-over)', 'Karena busa tidak dapat menutup permukaan cairan', 'Karena aspal tidak dapat terbakar'], ans: 1,
      why: 'Pada tangki aspal panas, pencegahan melalui pengendalian suhu, pemeliharaan pemanas, dan tanggul lebih diutamakan. Pemadaman dilakukan petugas terlatih dengan media dan cara yang sesuai.' },
    { q: 'Apa yang terjadi bila pompa oli termal berhenti sementara burner pemanas tetap menyala?', opts: ['Oli menjadi lebih dingin', 'Oli di dalam koil kepanasan, terurai membentuk endapan karbon, dan dapat memecahkan koil sehingga oli panas terbakar', 'Tangki aspal menjadi lebih panas dengan aman', 'Tidak ada dampak'], ans: 1,
      why: 'Karena itu pemanas oli termal wajib dilengkapi trip aliran rendah dan trip suhu tinggi yang menghentikan burner pemanas.' },
  ],
  events: [
    { id: 'e1', effects: [{ var: 'FLM', to: 2, delay: 1, dur: 2 }, { var: 'TAG', to: 120, delay: 3, dur: 14 }, { var: 'TBH', to: 95, delay: 3, dur: 12 }],
      warnings: [
        { t: 7, type: 'smoke', sev: 'warn', at: 'BRN-101', text: 'Nyala burner padam; kabut solar putih keluar dari ujung burner ke dalam drum.' },
        { t: 13, type: 'leak', sev: 'crit', at: 'DR-101', pos: [470, 226], text: 'Bau solar sangat kuat di sekitar drum; operator bersiap menyalakan ulang burner tanpa purging.' },
        { t: 20, type: 'explosion', sev: 'final', at: 'DR-101', pos: [450, 228], big: true, text: 'LEDAKAN di drum pengering saat burner dinyalakan ulang; bola api menyembur dari ujung drum dan saluran ke baghouse.' },
      ],
      answer: { node: ['BRN-101', 'DR-101'], param: ['C', 'T'], guide: ['none', 'low'] },
      hint: 'Nyala burner hilang dan suhu agregat turun, tetapi aliran solar ke burner tetap normal.', hintVar: 'FLM',
      causes: ['Nyala burner padam (flameout) karena gangguan udara pembakaran atau atomisasi, sementara katup bahan bakar tetap terbuka', 'ID fan berhenti', 'Pompa oli termal trip', 'Cold bin kosong'], causeAns: 0,
      cons: ['Kabut solar terkumpul di dalam drum dan meledak saat burner dinyalakan ulang tanpa purging', 'Suhu agregat naik', 'Produksi naik tanpa dampak', 'Tekanan drum turun tanpa dampak'], consAns: 0,
      explain: 'Intensitas nyala turun ke nol lalu suhu agregat dan gas buang ikut turun, sementara aliran solar tetap normal. Bahan bakar yang tidak terbakar membentuk campuran mudah meledak di dalam drum dan saluran gas buang, lalu meledak saat penyalaan ulang tanpa purging. Proteksi yang tepat adalah sistem manajemen burner (BMS) dengan flame scanner yang menutup katup bahan bakar dalam hitungan detik dan memaksa purging sebelum penyalaan ulang (NFPA 86).' },
    { id: 'e2', effects: [{ var: 'IDF', to: 0, delay: 1, dur: 2 }, { var: 'PDR', to: 30, delay: 2, dur: 10 }],
      warnings: [
        { t: 6, type: 'vibration', sev: 'warn', at: 'FN-101', text: 'ID fan FN-101 berbunyi kasar lalu berhenti; burner masih menyala penuh.' },
        { t: 12, type: 'heat', sev: 'crit', at: 'DR-101', pos: [530, 214], text: 'Gas panas dan debu menyembur keluar dari celah seal drum dan ujung burner.' },
        { t: 19, type: 'fire', sev: 'final', at: 'BRN-101', pos: [570, 228], big: true, text: 'Semburan balik api dari ujung burner membakar platform operator dan kabel di sekitar drum.' },
      ],
      answer: { node: ['FN-101', 'DR-101'], param: ['P', 'E'], guide: ['high', 'none'] },
      hint: 'Arus motor ID fan turun ke nol dan tekanan di ujung burner berubah dari negatif menjadi positif.',
      causes: ['ID fan trip karena gangguan motor atau bantalan, sementara burner tetap menyala', 'Burner padam', 'Cold bin kosong', 'Pompa oli termal trip'], causeAns: 0,
      cons: ['Tekanan drum menjadi positif sehingga api dan gas panas menyembur balik ke arah operator', 'Suhu baghouse turun tanpa dampak', 'Produksi naik', 'Suhu aspal naik'], consAns: 0,
      explain: 'Arus ID fan turun ke nol lalu tekanan di ujung burner berubah dari negatif menjadi positif. Tanpa isapan ID fan, gas pembakaran tidak lagi tersedot ke baghouse dan mencari jalan keluar melalui celah seal dan ujung burner, tempat operator bekerja. Proteksi yang tepat adalah interlock draft yang menghentikan burner bila ID fan mati atau tekanan drum menjadi positif.' },
    { id: 'e3', effects: [{ var: 'FAG', to: 30, delay: 1, dur: 5 }, { var: 'TBH', to: 260, delay: 3, dur: 16 }, { var: 'TAG', to: 230, delay: 3, dur: 14 }],
      warnings: [
        { t: 10, type: 'heat', sev: 'warn', at: 'BH-101', text: 'Suhu gas masuk baghouse melewati batas kantong filter; casing baghouse terasa sangat panas.' },
        { t: 16, type: 'smoke', sev: 'crit', at: 'ST-101', pos: [40, 70], text: 'Asap gelap keluar dari cerobong dan pintu inspeksi baghouse.' },
        { t: 23, type: 'fire', sev: 'final', at: 'BH-101', pos: [210, 96], big: true, text: 'KEBAKARAN BAGHOUSE: kantong filter dan debu berlapis minyak terbakar, api keluar dari hopper.' },
      ],
      answer: { node: ['BH-101', 'CV-101', 'DR-101'], param: ['T', 'F'], guide: ['high', 'low'] },
      hint: 'Aliran agregat dingin turun tajam, tetapi burner tetap menyala dengan laju yang sama. Panas yang tidak terserap agregat terbawa ke baghouse.',
      causes: ['Umpan agregat terhenti karena cold bin kosong atau konveyor berhenti, sementara burner tetap menyala penuh', 'ID fan berhenti', 'Pompa oli termal trip', 'Aspal terlalu dingin'], causeAns: 0,
      cons: ['Gas buang yang terlalu panas membakar kantong filter dan debu di baghouse', 'Suhu agregat turun', 'Tekanan drum turun tanpa dampak', 'Produksi naik'], consAns: 0,
      explain: 'Aliran agregat turun lalu suhu gas masuk baghouse naik melewati batas kantong filter, yang umumnya sekitar 200 °C untuk bahan aramid. Debu halus yang bercampur sisa bahan bakar atau aspal di kantong filter mudah tersulut. Proteksi yang tepat adalah pembatas laju bahan bakar berdasarkan umpan agregat, trip suhu tinggi-tinggi di saluran masuk baghouse yang menghentikan burner, dan detektor api di baghouse.' },
    { id: 'e4', effects: [{ var: 'FOL', to: 3, delay: 1, dur: 3 }, { var: 'TOL', to: 330, delay: 2, dur: 18 }, { var: 'TAS', to: 145, delay: 6, dur: 16 }],
      warnings: [
        { t: 10, type: 'vibration', sev: 'warn', at: 'P-201', text: 'Pompa oli termal P-201 berhenti; burner pemanas HTR-201 tetap menyala.' },
        { t: 16, type: 'smoke', sev: 'crit', at: 'HTR-201', pos: [936, 362], text: 'Asap putih tebal keluar dari cerobong pemanas; oli di dalam koil mulai terurai karena panas berlebih.' },
        { t: 24, type: 'fire', sev: 'final', at: 'HTR-201', pos: [936, 440], big: true, text: 'KEBAKARAN PEMANAS OLI TERMAL: koil pecah, oli panas menyembur dan terbakar di sekitar HTR-201 dan tangki aspal.' },
      ],
      answer: { node: ['P-201', 'HTR-201'], param: ['F', 'T'], guide: ['none', 'high'] },
      hint: 'Aliran oli termal hilang, tetapi suhu oli keluar pemanas terus naik. Panas dari burner tidak lagi terbawa keluar dari koil.',
      causes: ['Pompa oli termal trip sementara burner pemanas tetap menyala', 'ID fan berhenti', 'Cold bin kosong', 'Burner drum padam'], causeAns: 0,
      cons: ['Oli di dalam koil kepanasan dan terurai, koil pecah, dan oli panas terbakar', 'Suhu aspal naik dengan aman', 'Produksi naik', 'Tekanan drum turun tanpa dampak'], consAns: 0,
      explain: 'Aliran oli termal turun ke hampir nol lalu suhu oli keluar pemanas naik tajam. Oli yang diam di dalam koil terus menyerap panas burner hingga terurai, membentuk endapan karbon, dan melemahkan koil hingga pecah. Oli panas di atas titik nyalanya langsung terbakar saat keluar. Proteksi yang tepat adalah trip aliran rendah dan trip suhu tinggi-tinggi yang menghentikan burner pemanas.' },
  ],
  hotspots: [
    /* Tahap 3: pencegahan */
    { id: 'h31', stage: 3, x: 588, y: 196, label: 'Burner drum BRN-101 (sistem manajemen burner)', accept: ['BMS'],
      why: 'BMS memantau nyala dengan flame scanner, menutup katup bahan bakar ganda saat nyala hilang, dan memaksa purging sebelum penyalaan ulang (NFPA 86).' },
    { id: 'h32', stage: 3, x: 142, y: 226, label: 'ID fan FN-101 (interlock draft ke burner)', accept: ['DFI'],
      why: 'Interlock draft menghentikan burner saat ID fan mati atau tekanan drum menjadi positif, sehingga api tidak menyembur balik ke operator.' },
    { id: 'h33', stage: 3, x: 296, y: 110, label: 'Saluran gas ke baghouse (suhu tinggi-tinggi)', accept: ['TSHH', 'TT'],
      why: 'Trip suhu tinggi-tinggi menghentikan burner sebelum gas buang membakar kantong filter. Alarm suhu diterima sebagai lapisan respons operator.' },
    { id: 'h34', stage: 3, x: 250, y: 296, label: 'Konveyor umpan agregat (aliran dan pembatas bahan bakar)', accept: ['FT'],
      why: 'Pengukur aliran agregat yang terhubung ke pengendali burner menurunkan laju bahan bakar saat umpan berkurang atau terhenti.' },
    { id: 'h35', stage: 3, x: 876, y: 480, label: 'Sirkuit oli termal (trip aliran rendah)', accept: ['FSLL'],
      why: 'Trip aliran rendah menghentikan burner pemanas saat sirkulasi oli hilang, sebelum oli di dalam koil kepanasan.' },
    { id: 'h36', stage: 3, x: 866, y: 418, label: 'Outlet pemanas oli termal (suhu tinggi-tinggi)', accept: ['TSHH', 'TT'],
      why: 'Trip suhu tinggi-tinggi pada oli keluar pemanas adalah lapisan kedua bila trip aliran gagal. Alarm suhu diterima sebagai lapisan operator.' },
    { id: 'h38', stage: 3, x: 826, y: 354, label: 'Area pemuatan truk', accept: [],
      why: 'Area pemuatan truk penting untuk keselamatan lalu lintas dan bahaya tertabrak, tetapi bukan lokasi ancaman kebakaran atau ledakan yang teridentifikasi.' },
    { id: 'h39', stage: 3, x: 40, y: 96, label: 'Puncak cerobong', accept: [],
      why: 'Pemantauan emisi di cerobong penting untuk izin lingkungan, tetapi tidak mencegah ancaman kebakaran atau ledakan yang teridentifikasi.' },
    /* Tahap 4: mitigasi */
    { id: 'h41', stage: 4, x: 210, y: 160, label: 'Baghouse BH-101 (detektor api dan panas)', accept: ['FD'],
      why: 'Detektor api dan panas di baghouse memicu penghentian burner dan ID fan agar kebakaran kantong tidak terus diberi udara.' },
    { id: 'h42', stage: 4, x: 365, y: 470, label: 'Tangki solar TK-101 (tanggul)', accept: ['DIKE'],
      why: 'Tanggul menampung solar bila tangki atau pipa bocor sehingga tidak mengalir ke area burner dan jalur kendaraan.' },
    { id: 'h43', stage: 4, x: 735, y: 470, label: 'Tangki aspal TK-201 (tanggul)', accept: ['DIKE'],
      why: 'Tanggul menahan aspal dan oli termal panas bila tangki atau koil bocor, sehingga tumpahan panas tidak meluas.' },
    { id: 'h44', stage: 4, x: 958, y: 400, label: 'Pemanas oli termal HTR-201 (detektor api)', accept: ['FD'],
      why: 'Detektor api di pemanas oli termal memicu penghentian burner dan pompa serta memanggil regu pemadam lebih cepat.' },
    { id: 'h45', stage: 4, x: 292, y: 165, label: 'Area drum dan baghouse (hidran dan monitor)', accept: ['FW'],
      why: 'Hidran dan monitor air mendinginkan struktur dan mengendalikan kebakaran di sekitar drum dan baghouse.' },
    { id: 'h46', stage: 4, x: 580, y: 496, label: 'Ruang kontrol (ESD)', accept: ['ESD'],
      why: 'ESD menghentikan burner drum, pemanas oli termal, dan pompa bahan bakar secara serentak dari ruang kontrol.' },
    { id: 'h47', stage: 4, x: 940, y: 112, label: 'Titik kumpul dan alarm umum', accept: ['ALARM'],
      why: 'Lokasi AMP sering dekat permukiman dan jalan umum, sehingga alarm dan rencana evakuasi harus mencakup pekerja, sopir truk, dan tamu.' },
    { id: 'h48', stage: 4, x: 470, y: 300, label: 'Platform burner (APAR)', accept: ['APAR'],
      why: 'APAR di dekat burner memungkinkan operator memadamkan api kecil pada tahap awal, misalnya tetesan solar yang terbakar.' },
    { id: 'h40', stage: 4, x: 735, y: 410, label: 'Tangki aspal panas TK-201 (sistem busa)', accept: [],
      why: 'Air di dalam busa mendidih seketika saat menyentuh aspal di atas 100 °C sehingga aspal panas dapat meluap dan menyembur (frothing atau slop-over). Pengendalian suhu dan tanggul lebih tepat.' },
  ],
  inspect: [
    { id: 'TK-201', itpm: 'VESSEL', why: 'Tangki aspal dan koil pemanasnya mengalami siklus panas setiap hari. Pemeriksaan dan pengujian tangki timbun berkala diatur Permenaker No. 37 Tahun 2016.' },
    { id: 'FN-101', itpm: 'ROT', why: 'Pemantauan getaran ID fan mendeteksi ketidakseimbangan akibat tumpukan debu dan kerusakan bantalan sebelum fan trip saat burner menyala.' },
    { id: 'P-201', itpm: 'ROT', why: 'Pompa oli termal yang andal menjaga sirkulasi koil pemanas. Kegagalannya langsung mengancam koil.' },
  ],
  budget: { 3: 28, 4: 28 },
  bowtie: {
    top: 'Kebakaran atau ledakan di unit AMP',
    threats: ['Burner padam lalu dinyalakan ulang tanpa purging', 'ID fan mati saat burner menyala', 'Umpan agregat terhenti, gas buang terlalu panas', 'Pompa oli termal trip'],
    cons: ['Ledakan di drum pengering', 'Semburan balik api ke operator', 'Kebakaran baghouse', 'Kebakaran pemanas oli termal'],
  },
};
SCENARIOS.push(SCN_AMP);
