/* Skenario sektor Properti: dimuat setelah js/data.js dan menambahkan diri ke SCENARIOS. */
/* =====================================================================
   PROPERTI: Sistem Proteksi Kebakaran Gedung Komersial
   ===================================================================== */
const SCN_GEDUNG = {
  id: 'gedung',
  title: 'Proteksi Kebakaran Gedung Komersial',
  subtitle: 'Dapur restoran LPG, ruang genset, panel LVMDP, pompa kebakaran, tangga darurat',
  level: 'Pemula',
  sector: 'properti',
  area: 'Gedung Komersial',
  color: '#b5523b',
  kits: ['gedung'],
  op: 'Operasi Gedung',
  overview: [
    'Gedung komersial ini terdiri atas tiga lantai dan satu basement: restoran di lantai 3, perkantoran di lantai 2, lobi dan ritel di lantai 1, serta ruang mekanikal dan elektrikal di basement. Pada jam sibuk, gedung berisi ratusan penghuni dan pengunjung yang sebagian besar tidak mengenal bahaya instalasi di balik dinding dan plafon.',
    'Dapur restoran memakai LPG dari rak tabung LPG-301 di halaman yang dialirkan melalui pipa tegak dan regulator REG-301 ke kompor di bawah hood KC-301. Uap masak berlemak disedot kipas EF-301 di atap. Listrik dari PLN dibagi oleh panel utama LVMDP PNL-101. Saat PLN padam, genset GEN-101 mengambil alih dengan solar dari tangki harian TK-101 yang diisi pompa P-101 dari tangki pendam TK-100.',
    'Pompa kebakaran FP-101 mengambil air dari tangki TK-201 dan menjaga tekanan pipa tegak. Kebakaran gedung jarang dibahas sebagai keselamatan proses, padahal pola kegagalannya serupa: kebocoran bahan mudah terbakar, panas berlebih, dan barier yang tidak terpelihara. Data Dinas Gulkarmat DKI Jakarta mencatat korsleting listrik sebagai penyebab kebakaran terbanyak.',
  ],
  production: { label: 'Energi listrik tersalurkan', unit: 'kWh', var: 'IP', k: 0.0098 },
  fluidNames: { lpg: 'LPG (fase gas setelah regulator)', flue: 'Udara exhaust dapur berlemak', oil: 'Solar (bahan bakar genset)', power: 'Kabel daya listrik', fw: 'Air pemadam kebakaran' },
  ground: 372,
  zones: [
    { style: 'building', x: 150, y: 62, w: 640, h: 470, floors: [168, 270, 372],
      labels: [[78, 'Lantai 3: Restoran'], [184, 'Lantai 2: Perkantoran'], [286, 'Lantai 1: Lobi dan Ritel'], [388, 'Basement']] },
    { x: 562, y: 66, w: 44, h: 462, fill: 'rgba(102,187,106,0.12)' },
  ],
  equipment: [
    { id: 'LPG-301', type: 'cylinders', x: 14, y: 274, w: 116, h: 72, n: 4, name: 'Rak Tabung LPG-301',
      desc: 'Empat tabung LPG 50 kg di ruang tabung berventilasi di halaman, terhubung ke manifold dan pipa tegak menuju dapur lantai 3. LPG lebih berat dari udara sehingga kebocoran mengalir ke bawah dan berkumpul di lantai.' },
    { id: 'REG-301', type: 'valve', sub: 'control', x: 205, y: 128, name: 'Regulator LPG REG-301',
      desc: 'Regulator tekanan rendah yang menurunkan tekanan LPG dari tabung menjadi tekanan kerja kompor sekitar 28 mbar, di bawah batas tekanan keluaran regulator tekanan rendah sebesar 5 kPa (50 mbar). Dari pipa, LPG masuk ke kompor melalui selang fleksibel.', vars: ['FL', 'PL'] },
    { id: 'KC-301', type: 'hood', x: 330, y: 92, w: 130, h: 66, name: 'Hood dan Kompor Dapur KC-301',
      desc: 'Deretan kompor dengan hood di atasnya yang menangkap uap masak berlemak. Lemak yang terbawa menempel di filter dan dinding ducting, lalu menjadi bahan bakar bila tersulut.', vars: ['TD'] },
    { id: 'EF-301', type: 'fan', x: 432, y: 36, name: 'Kipas Exhaust Dapur EF-301',
      desc: 'Kipas di atap yang menyedot uap masak dari hood melalui ducting dan membuangnya ke udara luar.' },
    { id: 'CR-100', type: 'building', x: 360, y: 322, name: 'Ruang Kendali Kebakaran',
      desc: 'Lokasi panel induk alarm kebakaran (MCFA) dan komunikasi darurat gedung, dijaga petugas selama 24 jam.' },
    { id: 'PLN-100', type: 'sink', x: 140, y: 412, dir: 'left', name: 'Dari Gardu PLN 20 kV',
      desc: 'Pasokan listrik dari gardu distribusi PLN melalui transformator 20 kV ke 400 V.' },
    { id: 'TK-100', type: 'vessel', orient: 'h', x: 14, y: 452, w: 118, h: 40, name: 'Tangki Pendam Solar TK-100',
      desc: 'Tangki solar 20.000 liter yang ditanam di bawah tanah halaman gedung.' },
    { id: 'P-101', type: 'pump', x: 178, y: 472, name: 'Pompa Transfer Solar P-101',
      desc: 'Memompa solar dari tangki pendam ke tangki harian. Pompa seharusnya berhenti saat sakelar level tangki harian bekerja.' },
    { id: 'TK-101', type: 'vessel', x: 222, y: 414, w: 44, h: 74, name: 'Tangki Harian Solar TK-101', level: 'LD',
      desc: 'Tangki harian 1.000 liter di dalam ruang genset yang menyuplai solar langsung ke mesin.', vars: ['LD'] },
    { id: 'GEN-101', type: 'generator', x: 300, y: 446, w: 96, h: 54, name: 'Genset GEN-101 1.000 kVA',
      desc: 'Genset diesel cadangan yang menyala otomatis saat PLN padam dan diuji berbeban secara berkala. Permukaan knalpotnya jauh lebih panas daripada suhu nyala sendiri solar, sekitar 210 sampai 260 °C.' },
    { id: 'PNL-101', type: 'panel', sub: 'LVMDP', x: 410, y: 440, w: 110, h: 60, name: 'Panel Utama LVMDP PNL-101',
      desc: 'Panel utama tegangan rendah 400 V yang membagi daya dari PLN atau genset ke seluruh gedung. Sambungan busbar dan terminal yang kendur memanas walaupun arus beban normal.', vars: ['TP', 'IP'] },
    { id: 'FP-101', type: 'pump', x: 700, y: 470, dir: 'left', name: 'Paket Pompa Kebakaran FP-101',
      desc: 'Paket pompa kebakaran berisi pompa utama listrik, pompa diesel cadangan, dan pompa jockey yang menjaga tekanan pipa tegak dan sprinkler.', vars: ['PS'] },
    { id: 'TK-201', type: 'tank', x: 812, y: 262, w: 90, h: 100, name: 'Tangki Air Pemadam TK-201', level: 'LW',
      desc: 'Cadangan air khusus pemadam kebakaran yang tidak boleh dipakai untuk keperluan lain.', vars: ['LW'] },
    { id: 'MP-100', type: 'muster', x: 958, y: 326, name: 'Titik Kumpul',
      desc: 'Area berkumpul evakuasi di halaman, jauh dari gedung dan rak tabung LPG.' },
  ],
  pipes: [
    { id: 'lpg1', fluid: 'lpg', w: 4, pts: [[134, 286], [142, 286], [142, 128], [193, 128]], arrow: true },
    { id: 'lpg2', fluid: 'lpg', w: 4, pts: [[217, 128], [300, 128], [300, 148], [334, 148]], arrow: true },
    { id: 'duct', fluid: 'flue', w: 8, pts: [[395, 86], [395, 36], [410, 36]] },
    { id: 'fo1', fluid: 'oil', w: 4, pts: [[132, 472], [156, 472]] },
    { id: 'fo2', fluid: 'oil', w: 4, pts: [[200, 472], [210, 472], [210, 426], [222, 426]], arrow: true },
    { id: 'fo3', fluid: 'oil', w: 4, pts: [[266, 478], [300, 478]] },
    { id: 'pw1', fluid: 'power', w: 5, pts: [[140, 412], [146, 412], [146, 402], [470, 402], [470, 440]], arrow: true },
    { id: 'pw2', fluid: 'power', w: 5, pts: [[396, 468], [410, 468]] },
    { id: 'fw1', fluid: 'fw', w: 6, pts: [[857, 370], [857, 470], [722, 470]], arrow: true },
    { id: 'fw2', fluid: 'fw', w: 6, pts: [[678, 470], [628, 470], [628, 96]], arrow: true },
  ],
  labels: [
    { x: 584, y: 80, text: 'Tangga', size: 9.5 },
    { x: 584, y: 92, text: 'Darurat', size: 9.5 },
    { x: 275, y: 388, text: 'Ruang Genset', size: 10 },
    { x: 465, y: 388, text: 'Ruang Panel', size: 10 },
    { x: 700, y: 388, text: 'Ruang Pompa Kebakaran', size: 10 },
  ],
  vars: {
    FL: { label: 'Laju Aliran LPG ke Dapur', unit: 'kg/j', normal: 6, min: 0, max: 20, hi: 10, node: 'REG-301', x: 72, y: 112, tau: 1.5, noise: 0.05, dec: 1 },
    PL: { label: 'Tekanan LPG Setelah Regulator', unit: 'mbar', normal: 28, min: 0, max: 40, lo: 24, node: 'REG-301', x: 72, y: 140, tau: 1.5, noise: 0.1, dec: 0 },
    TD: { label: 'Suhu Ducting Exhaust Dapur', unit: '°C', normal: 45, min: 20, max: 400, hi: 90, hihi: 150, node: 'KC-301', x: 290, y: 40, tau: 2, noise: 0.3, dec: 0 },
    LD: { label: 'Level Tangki Harian TK-101', unit: '%', normal: 60, min: 0, max: 100, lo: 20, hi: 90, hihi: 95, node: 'TK-101', x: 250, y: 518, tau: 3, noise: 0.2, dec: 0 },
    IP: { label: 'Arus Beban Panel LVMDP', unit: 'A', normal: 1400, min: 0, max: 3200, hi: 2200, hihi: 2600, node: 'PNL-101', x: 420, y: 420, tau: 2, noise: 6, dec: 0 },
    TP: { label: 'Suhu Busbar Panel LVMDP', unit: '°C', normal: 55, min: 20, max: 200, hi: 80, hihi: 95, node: 'PNL-101', x: 515, y: 420, tau: 3, noise: 0.2, dec: 0 },
    PS: { label: 'Tekanan Pipa Tegak', unit: 'bar', normal: 8, min: 0, max: 14, lo: 6, node: 'FP-101', x: 700, y: 420, tau: 2, noise: 0.03, dec: 1 },
    LW: { label: 'Level Tangki Air Pemadam', unit: '%', normal: 95, min: 0, max: 100, lo: 80, node: 'TK-201', x: 857, y: 232, tau: 6, noise: 0.05, dec: 0 },
  },
  trendVars: ['FL', 'LD', 'TP', 'TD'],
  controls: [
    { id: 'cook', label: 'Jumlah kompor menyala', unit: 'unit', min: 2, max: 8, def: 5, step: 1,
      effects: [{ var: 'FL', gain: 1.2 }, { var: 'PL', gain: -0.4 }, { var: 'TD', gain: 4 }] },
    { id: 'load', label: 'Beban listrik gedung', unit: '%', min: 40, max: 100, def: 70, step: 5,
      effects: [{ var: 'IP', gain: 20 }, { var: 'TP', gain: 0.3 }] },
    { id: 'fill', label: 'Set point pengisian tangki harian', unit: '%', min: 40, max: 80, def: 60, step: 5,
      effects: [{ var: 'LD', gain: 1 }] },
  ],
  quiz: [
    { q: 'Mengapa kebocoran LPG di dapur sangat berbahaya walaupun jumlahnya kecil?', opts: ['LPG lebih berat dari udara sehingga menggenang di lantai dan dapat meledak pada konsentrasi sekitar 2 sampai 10 persen', 'LPG lebih ringan dari udara sehingga terkumpul di plafon dan meledak saat lampu dinyalakan', 'LPG sangat beracun sehingga kebocoran kecil langsung menyebabkan keracunan massal pada pekerja dapur', 'LPG baru dapat meledak bila konsentrasinya di atas 50 persen sehingga kebocoran kecil relatif aman'], ans: 0,
      why: 'Genangan LPG di lantai dapat tersulut oleh nyala kompor, sakelar listrik, atau percikan lain. Karena itu detektor LPG dipasang dekat lantai.' },
    { q: 'Mengapa sambungan busbar yang kendur tidak memicu relai arus lebih?', opts: ['Arus beban tetap normal, sedangkan panas timbul akibat tahanan kontak yang naik di titik sambungan', 'Relai arus lebih hanya aktif saat genset menyala dan tidak bekerja saat suplai berasal dari PLN', 'Sambungan kendur menurunkan arus sehingga relai membaca kondisi beban ringan', 'Relai sudah bereaksi, tetapi pemutusnya sengaja ditunda oleh koordinasi proteksi agar tidak trip bersamaan'], ans: 0,
      why: 'Titik panas pada sambungan kendur dideteksi dengan pemantauan suhu atau inspeksi termografi inframerah berkala, bukan dengan relai arus lebih.' },
    { q: 'Apa fungsi sistem presurisasi tangga darurat?', opts: ['Menjaga tekanan udara di dalam tangga lebih tinggi daripada koridor sehingga asap tidak masuk', 'Menyedot asap dari koridor melalui tangga lalu membuangnya ke atap gedung', 'Menyuplai udara segar ke lantai yang terbakar agar penghuni dapat bernapas sambil menunggu tim penyelamat', 'Menjaga pintu tangga tertutup rapat dengan membuat tekanan di dalam tangga lebih rendah dari koridor'], ans: 0,
      why: 'Menghirup asap adalah penyebab kematian terbanyak pada kebakaran gedung. Tangga yang bebas asap menjadi jalur penyelamatan utama bagi penghuni.' },
    { q: 'Mengapa api minyak goreng di dapur tidak boleh disiram air?', opts: ['Air yang mengenai minyak panas langsung menguap dan memercikkan minyak menyala sehingga api membesar', 'Air tidak cukup dingin untuk menurunkan suhu minyak di bawah titik nyalanya', 'Air menghantarkan listrik dari kompor induksi dan peralatan dapur sehingga petugas tersengat saat memadamkan', 'Air membuat minyak mengapung dan apinya terbawa ke saluran pembuangan'], ans: 0,
      why: 'Sistem wet chemical pada hood dan APAR khusus minyak masak membentuk lapisan penutup yang mendinginkan minyak dan mencegah api menyala kembali (NFPA 17A).' },
    { q: 'Berapa kali APAR wajib diperiksa menurut Permenakertrans No. Per.04/MEN/1980?', opts: ['Dua kali dalam setahun, yaitu pemeriksaan jangka 6 bulan dan jangka 12 bulan', 'Sekali setahun, bersamaan dengan uji tekan tabung oleh pihak ketiga yang ditunjuk', 'Setiap tiga bulan, dengan penggantian isi setiap kali diperiksa', 'Setiap lima tahun, karena tabung APAR modern dirancang bebas perawatan selama masa pakainya'], ans: 0,
      why: 'APAR yang tidak terpelihara dapat gagal saat dibutuhkan. Pemeriksaan meliputi isi, tekanan, segel, selang, dan kondisi tabung.' },
  ],
  events: [
    { id: 'e1', threat: 0, effects: [{ var: 'FL', to: 12, delay: 1, dur: 10 }, { var: 'PL', to: 21, delay: 2, dur: 10 }],
      warnings: [
        { t: 11, type: 'leak', sev: 'warn', at: 'KC-301', pos: [300, 150], text: 'Bau gas LPG di dapur restoran; terdengar desis dari selang kompor yang retak.' },
        { t: 17, type: 'leak', sev: 'crit', at: 'KC-301', pos: [330, 156], text: 'Bau gas sangat kuat; LPG yang lebih berat dari udara menggenang di lantai dapur.' },
        { t: 25, type: 'explosion', sev: 'final', at: 'KC-301', pos: [380, 130], big: true, text: 'LEDAKAN GAS di dapur restoran lantai 3 saat kompor dinyalakan; dinding partisi runtuh dan api menjalar ke area makan.' },
      ],
      answer: { node: ['KC-301', 'REG-301'], param: ['F', 'P'], guide: ['high', 'low'] },
      hint: 'Aliran LPG naik padahal jumlah kompor tidak bertambah, dan tekanan setelah regulator turun. Gas mengalir ke tempat yang bukan kompor.',
      causes: ['Selang fleksibel kompor retak atau sambungannya lepas sehingga LPG bocor ke ruang dapur', 'Beban listrik gedung naik', 'Filter hood kotor', 'Tangki harian solar terlalu penuh'], causeAns: 0,
      cons: ['LPG menggenang di lantai dapur hingga konsentrasinya masuk rentang mudah meledak, lalu tersulut dan meledak', 'Suhu ducting turun', 'Tekanan pipa tegak naik', 'Nyala kompor membesar tanpa dampak'], consAns: 0,
      explain: 'Aliran LPG naik tanpa penambahan kompor lalu tekanan setelah regulator turun, pola khas kebocoran di hilir regulator. Uap LPG sekitar 1,5 sampai 2 kali lebih berat dari udara sehingga berkumpul di lantai dan sudut ruangan, dengan rentang mudah meledak sekitar 2 sampai 10 persen di udara. Proteksi yang tepat adalah detektor gas dekat lantai dengan katup solenoid otomatis, excess flow valve di outlet tabung, serta pemeriksaan selang dan regulator secara berkala.' },
    { id: 'e2', threat: 1, effects: [{ var: 'LD', to: 100, delay: 1, dur: 13 }],
      warnings: [
        { t: 15, type: 'spill', sev: 'warn', at: 'TK-101', pos: [244, 420], text: 'Solar menetes dari pipa vent tangki harian TK-101; bau solar tercium di ruang genset.' },
        { t: 21, type: 'spill', sev: 'crit', at: 'TK-101', pos: [262, 500], text: 'Solar meluap dari tangki harian dan menggenang di lantai hingga mendekati genset yang sedang diuji.' },
        { t: 27, type: 'fire', sev: 'final', at: 'GEN-101', pos: [320, 470], big: true, text: 'KEBAKARAN di ruang genset: solar yang meluap tersulut knalpot panas; asap tebal masuk ke basement dan tangga.' },
      ],
      answer: { node: ['TK-101', 'P-101'], param: ['L'], guide: ['high'] },
      hint: 'Level tangki harian terus naik melewati set point pengisian. Pompa transfer tidak berhenti.',
      causes: ['Sakelar level tangki harian macet sehingga pompa transfer terus mengisi hingga meluap', 'Selang LPG kompor retak', 'Sambungan busbar kendur', 'Filter hood kotor'], causeAns: 0,
      cons: ['Solar meluap ke lantai ruang genset dan tersulut permukaan knalpot yang panas sehingga terjadi kebakaran', 'Genset berhenti tanpa dampak', 'Tekanan LPG turun', 'Suhu busbar naik'], consAns: 0,
      explain: 'Level tangki harian naik terus melewati set point. Pompa transfer seharusnya berhenti oleh sakelar level, tetapi sakelar macet. Solar yang meluap mudah tersulut oleh knalpot genset yang suhunya jauh di atas suhu nyala sendiri solar, sekitar 210 sampai 260 °C. Proteksi yang tepat adalah trip level tinggi-tinggi independen yang menghentikan pompa transfer, tanggul penampung di sekeliling tangki harian, dan sprinkler ruang genset.' },
    { id: 'e3', threat: 2, effects: [{ var: 'TP', to: 150, delay: 2, dur: 20 }],
      warnings: [
        { t: 12, type: 'heat', sev: 'warn', at: 'PNL-101', text: 'Bau isolasi kabel terbakar di ruang panel; pintu panel LVMDP terasa panas saat disentuh.' },
        { t: 19, type: 'smoke', sev: 'crit', at: 'PNL-101', pos: [465, 446], text: 'Asap keluar dari celah panel LVMDP PNL-101; terdengar desis dan letupan kecil.' },
        { t: 27, type: 'fire', sev: 'final', at: 'PNL-101', pos: [465, 466], big: true, text: 'BUSUR LISTRIK dan KEBAKARAN di panel LVMDP; listrik gedung padam dan asap menyebar ke basement.' },
      ],
      answer: { node: ['PNL-101'], param: ['T'], guide: ['high'] },
      hint: 'Suhu busbar naik terus, padahal arus beban tetap normal. Panas timbul di satu titik, bukan karena beban berlebih.',
      causes: ['Sambungan baut busbar atau terminal kabel kendur sehingga tahanan kontak naik dan memanas', 'Beban listrik melebihi kapasitas panel', 'Tangki harian meluap', 'Selang LPG retak'], causeAns: 0,
      cons: ['Titik panas melelehkan isolasi lalu terjadi busur listrik dan kebakaran panel yang memadamkan listrik gedung', 'Arus beban turun tanpa dampak', 'Tekanan pipa tegak naik', 'Suhu ducting naik'], consAns: 0,
      explain: 'Suhu busbar naik sementara arus beban tetap normal. Sambungan yang kendur menaikkan tahanan kontak sehingga panas terpusat di satu titik, dan relai arus lebih tidak bereaksi karena arusnya tidak berlebih. Korsleting dan gangguan listrik tercatat sebagai penyebab kebakaran terbanyak di DKI Jakarta menurut Dinas Gulkarmat. Proteksi yang tepat adalah pemantauan suhu busbar, inspeksi termografi inframerah berkala, dan pengencangan baut sesuai torsi pabrikan (Permenaker No. 12 Tahun 2015, NFPA 70B).' },
    { id: 'e4', threat: 3, effects: [{ var: 'TD', to: 320, delay: 2, dur: 16 }],
      warnings: [
        { t: 9, type: 'heat', sev: 'warn', at: 'KC-301', pos: [395, 112], text: 'Api dari wajan menyambar ke dalam hood KC-301; filter hood terlihat hitam penuh lemak.' },
        { t: 15, type: 'smoke', sev: 'crit', at: 'EF-301', pos: [432, 30], text: 'Asap tebal keluar dari kipas exhaust di atap; dinding ducting terasa sangat panas.' },
        { t: 23, type: 'fire', sev: 'final', at: 'KC-301', pos: [395, 80], big: true, text: 'KEBAKARAN DUCTING: lemak di dalam ducting terbakar, api merambat ke atap dan plafon di sekitar shaft.' },
      ],
      answer: { node: ['KC-301', 'EF-301'], param: ['T'], guide: ['high'] },
      hint: 'Suhu ducting exhaust naik jauh di atas suhu uap masak normal. Ada yang terbakar di dalam saluran.',
      causes: ['Endapan lemak di filter hood dan ducting tersulut api dari kompor', 'Selang LPG retak', 'Tangki harian meluap', 'Beban listrik naik'], causeAns: 0,
      cons: ['Api merambat di dalam ducting hingga atap dan menyulut bahan mudah terbakar di sekitar shaft', 'Suhu dapur turun', 'Tekanan LPG naik tanpa dampak', 'Kipas exhaust berhenti tanpa dampak'], consAns: 0,
      explain: 'Suhu ducting melonjak dalam waktu singkat. Lemak yang mengendap di filter dan dinding ducting adalah bahan bakar yang siap menyala dan sulit dijangkau pemadaman manual. Proteksi yang tepat adalah filter lemak yang dibersihkan rutin, pembersihan ducting berkala, sistem pemadam wet chemical pada hood, dan ducting di dalam shaft tahan api (NFPA 96, NFPA 17A).' },
    { id: 'e5', start: 13,
      hf: { type: 'violation', team: 'ktr', threat: 3, title: 'Pekerjaan panas tenant tanpa izin dan alarm dimatikan', factor: 'Pengelasan tanpa izin kerja panas dan zona alarm dimatikan',
        roles: { yanto: 'Petugas Security Ruang Kendali', rudi: 'Teknisi Gedung (Shift Pagi)', bayu: 'Kontraktor Tenant' },
        lesson: 'Bayu melakukan violation demi mengejar waktu, dan security ikut melanggar karena menonaktifkan zona detektor tanpa prosedur penonaktifan (impairment). Pengelola gedung juga tidak mengawasi kontraktor tenant. PP No. 50 Tahun 2012 mensyaratkan sistem izin kerja untuk pekerjaan berisiko tinggi. Izin kerja panas mencakup pembersihan bahan mudah terbakar, alat pemadam di lokasi, dan penjaga api selama serta setelah pekerjaan (NFPA 51B). Penonaktifan sistem proteksi kebakaran harus disetujui, dibatasi waktunya, dan disertai pengamanan pengganti.',
        controls: ['Izin kerja panas dari pengelola gedung, pembersihan lemak, dan penjaga api (NFPA 51B)', 'Penonaktifan sistem proteksi kebakaran hanya melalui prosedur impairment yang disetujui', 'Pengawasan kontraktor tenant oleh pengelola gedung'] },
      chat: [
        { t: 1, who: 'lina', at: 'KC-301', text: 'Bayu, dudukan ducting di atas kompor goyang. Tolong dilas sebelum restoran buka jam sebelas.' },
        { t: 4, who: 'bayu', at: 'KC-301', mood: 'santai', text: 'Siap. Kalau urus izin kerja panas ke pengelola gedung, prosesnya lama. Kukerjakan sekarang saja.' },
        { t: 7, who: 'bayu', at: 'KC-301', mood: 'santai', text: 'Yanto, zona detektor lantai 3 tolong dimatikan dulu ya. Asap las nanti bikin alarm bunyi.' },
        { t: 10, who: 'yanto', at: 'CR-100', text: 'Oke, zona lantai 3 kumatikan sementara. Kabari kalau sudah selesai.' },
        { t: 13, who: 'rudi', at: 'CR-100', mood: 'ragu', text: 'Yanto, siapa yang minta zona lantai 3 dimatikan? Tidak ada formulir penonaktifan di meja.' },
        { t: 19, who: 'bayu', at: 'EF-301', mood: 'santai', text: 'Ada percikan yang masuk ke celah ducting, tapi kayaknya aman.' },
        { t: 25, who: 'lina', at: 'KC-301', mood: 'panik', text: 'Asap keluar dari plafon dapur! Bayu, matikan lasnya!' },
      ],
      effects: [{ var: 'TD', to: 320, delay: 2, dur: 16 }],
      warnings: [
        { t: 9, type: 'heat', sev: 'warn', at: 'KC-301', pos: [395, 112], text: 'Percikan las masuk ke celah ducting di atas hood KC-301; dinding ducting yang penuh lemak mulai berasap.' },
        { t: 15, type: 'smoke', sev: 'crit', at: 'EF-301', pos: [432, 30], text: 'Asap tebal keluar dari kipas exhaust di atap, padahal alarm lantai 3 tidak berbunyi.' },
        { t: 23, type: 'fire', sev: 'final', at: 'KC-301', pos: [395, 80], big: true, text: 'KEBAKARAN DUCTING: lemak di dalam ducting terbakar, api merambat ke atap dan plafon di sekitar shaft tanpa peringatan dini.' },
      ],
      answer: { node: ['KC-301', 'EF-301'], param: ['T'], guide: ['high'] },
      hint: 'Suhu ducting naik tajam saat ada pekerjaan panas di dekat ducting berlemak, sementara detektor di lantai itu sedang tidak aktif. Baca kembali obrolan antara tenant, kontraktor, dan security.',
      causes: ['Kontraktor tenant mengelas dudukan ducting tanpa izin kerja panas dan tanpa membersihkan lemak, sementara zona detektor sengaja dimatikan', 'Api dari wajan menyambar ke hood karena filter lemak kotor', 'Motor kipas exhaust EF-301 kepanasan lalu terbakar', 'Korsleting pada panel lampu dapur menyulut plafon'], causeAns: 0,
      cons: ['Percikan las menyulut endapan lemak, api merambat di ducting sementara deteksi dan alarm terlambat', 'Dudukan ducting menjadi kokoh dan restoran buka tepat waktu', 'Asap las memicu alarm palsu di lantai lain', 'Kipas exhaust berhenti sehingga dapur menjadi panas'], consAns: 0,
      explain: 'Suhu ducting naik cepat setelah pengelasan dimulai di dekat ducting yang penuh endapan lemak. Pekerjaan panas tanpa izin berarti tidak ada pembersihan area, tidak ada penjaga api, dan zona detektor dimatikan tanpa prosedur sehingga deteksi dini hilang.' },
    { id: 'e6', threat: 2, effects: [{ var: 'IP', to: 2450, delay: 1, dur: 3 }, { var: 'TP', to: 125, delay: 3, dur: 16 }],
      warnings: [
        { t: 9, type: 'vibration', sev: 'warn', at: 'PNL-101', text: 'Lampu di sebagian ruangan padam, sementara motor pompa dan chiller di basement berdengung keras.' },
        { t: 16, type: 'smoke', sev: 'crit', at: 'PNL-101', pos: [465, 446], text: 'Asap tipis keluar dari panel LVMDP dan bau isolasi terbakar tercium di ruang panel.' },
        { t: 24, type: 'fire', sev: 'final', at: 'PNL-101', pos: [465, 466], big: true, text: 'Busbar dan kabel yang kepanasan terbakar. Panel LVMDP terbakar dan asap menyebar ke basement.' },
      ],
      answer: { node: ['PNL-101', 'PLN-100'], param: ['E', 'T'], guide: ['partof', 'high'] },
      hint: 'Arus beban panel naik mendadak dan lampu di sebagian ruangan padam, lalu suhu busbar ikut naik. Pikirkan apa yang terjadi bila salah satu fasa pasokan hilang.',
      causes: ['Salah satu fasa pasokan PLN putus sehingga motor tiga fasa bekerja dengan dua fasa, menarik arus berlebih, dan memanaskan busbar', 'Sambungan baut busbar kendur sehingga panas terpusat di satu titik walaupun arus normal', 'Selang LPG kompor retak sehingga gas bocor ke dapur', 'Sakelar level tangki harian macet sehingga solar meluap'], causeAns: 0,
      cons: ['Motor dan busbar kepanasan hingga isolasi meleleh, lalu terjadi busur listrik dan kebakaran panel yang memadamkan listrik gedung', 'Tagihan listrik turun karena satu fasa tidak terpakai', 'Lampu padam di sebagian ruangan tanpa dampak keselamatan', 'Genset otomatis mengambil alih sehingga tidak ada dampak'], consAns: 0,
      explain: 'Arus beban naik mendadak, lampu di sebagian ruangan padam, lalu suhu busbar naik. Ini pola kehilangan satu fasa: motor tiga fasa tetap berputar dengan dua fasa tetapi menarik arus jauh lebih besar sehingga motor, kabel, dan busbar kepanasan. Dalam HAZOP, deviasinya dibaca sebagai Sebagian (Part of) pada pasokan listrik, yaitu hanya dua dari tiga fasa yang tersedia, disertai arus lebih tinggi. Relai kehilangan fasa yang membuka pemutus utama dan proteksi beban lebih motor memutus rantai ini.' },
    { id: 'e7', start: 12,
      hf: { type: 'mistake', team: 'ext', threat: 0, title: 'Selang air dipakai sebagai pengganti selang LPG karena dikira sama saja', factor: 'Selang air dipakai menggantikan selang LPG',
        roles: { tono: 'Pembantu Juru Masak (Tenant)', rudi: 'Teknisi Gedung' },
        lesson: 'Tono yakin selang air sama baiknya dengan selang LPG karena ukurannya pas dan diklem kuat. Tindakannya sesuai niat, tetapi didasari pengetahuan yang keliru, sehingga tergolong mistake. Selang khusus LPG dibuat dari bahan yang tahan terhadap propana dan butana, sedangkan selang air tidak dirancang untuk LPG sehingga bahannya cepat rusak, mengeras, lalu retak. Pencegahnya adalah suku cadang selang dan regulator LPG yang memenuhi SNI tersedia di lokasi, pengawasan pengelola gedung terhadap instalasi gas tenant, dan detektor gas dekat lantai yang menutup katup solenoid secara otomatis.',
        controls: ['Selang dan regulator LPG yang memenuhi SNI selalu tersedia sebagai suku cadang', 'Pengawasan pengelola gedung terhadap instalasi gas di area tenant', 'Detektor gas dekat lantai dengan katup solenoid penutup otomatis'] },
      chat: [
        { t: 1, who: 'lina', at: 'KC-301', text: 'Selang kompor nomor 3 retak. Tukang gas langganan baru bisa datang besok.' },
        { t: 4, who: 'tono', at: 'KC-301', mood: 'santai', text: 'Pakai selang air yang di gudang saja, Bu. Ukurannya pas, diklem juga kuat.' },
        { t: 7, who: 'lina', at: 'KC-301', text: 'Oke, yang penting kompor bisa dipakai. Pesanan makan siang banyak.' },
        { t: 10, who: 'tono', at: 'KC-301', mood: 'santai', text: 'Sudah terpasang dan kompor menyala normal.' },
        { t: 20, who: 'rudi', at: 'CR-100', mood: 'ragu', text: 'Aliran LPG ke dapur naik padahal jumlah kompor tidak bertambah.' },
        { t: 24, who: 'tono', at: 'KC-301', mood: 'panik', text: 'Bau gas menyengat di dekat kompor nomor 3! Selang yang tadi kupasang jadi kaku dan retak.' },
        { t: 28, who: 'rudi', at: 'CR-100', mood: 'panik', text: 'Tutup katup LPG utama dan jangan nyalakan apa pun! Semua keluar dari dapur!' },
      ],
      effects: [{ var: 'FL', to: 12, delay: 1, dur: 10 }, { var: 'PL', to: 21, delay: 2, dur: 10 }],
      warnings: [
        { t: 11, type: 'leak', sev: 'warn', at: 'KC-301', pos: [300, 150], text: 'Bau gas LPG tercium di dekat kompor nomor 3. Selang yang baru dipasang tampak kaku dan retak di dekat klem.' },
        { t: 17, type: 'leak', sev: 'crit', at: 'KC-301', pos: [330, 156], text: 'Bau gas sangat kuat. LPG yang lebih berat dari udara menggenang di lantai dapur.' },
        { t: 25, type: 'explosion', sev: 'final', at: 'KC-301', pos: [380, 130], big: true, text: 'Genangan LPG tersulut api kompor lain. Ledakan gas merobohkan partisi dapur dan api menjalar ke area makan.' },
      ],
      answer: { node: ['KC-301', 'REG-301'], param: ['F', 'P'], guide: ['high', 'low'] },
      hint: 'Aliran LPG naik dan tekanan setelah regulator turun tak lama setelah selang kompor diganti. Baca kembali obrolan tentang selang pengganti.',
      causes: ['Selang air dipasang sebagai pengganti selang LPG sehingga cepat rusak dan retak, lalu LPG bocor ke dapur', 'Regulator LPG rusak sehingga tekanan ke kompor terlalu tinggi', 'Endapan lemak di ducting tersulut api kompor', 'Tabung LPG hampir kosong sehingga tekanan turun'], causeAns: 0,
      cons: ['LPG menggenang di lantai dapur hingga masuk rentang mudah meledak, lalu tersulut dan meledak', 'Nyala kompor nomor 3 menjadi lebih stabil', 'Tekanan pipa tegak naik tanpa dampak', 'Suhu ducting exhaust turun'], consAns: 0,
      explain: 'Aliran LPG naik tanpa penambahan kompor lalu tekanan setelah regulator turun, polanya sama dengan kebocoran selang. Penyebabnya adalah selang air yang dipasang sebagai pengganti selang LPG sehingga bahannya cepat rusak dan retak. Detektor gas dekat lantai dengan katup solenoid otomatis dan excess flow valve tetap diperlukan karena kesalahan pemasangan dapat terjadi kapan saja.' },
    { id: 'e8', start: 12,
      hf: { type: 'lapse', team: 'mtc', threat: 1, title: 'Pompa transfer solar yang dijalankan manual lupa dimatikan karena teknisi dialihkan ke lift macet', factor: 'Pompa transfer manual lupa dimatikan',
        roles: { rudi: 'Teknisi Gedung', yanto: 'Petugas Security Ruang Kendali' },
        lesson: 'Rudi menjalankan pompa transfer secara manual karena sakelar level sedang dikalibrasi, lalu lupa mematikannya setelah dialihkan ke keadaan darurat lift macet. Lupa menyelesaikan langkah yang sudah direncanakan tergolong lapse. Gangguan yang mendesak memang wajar didahulukan, tetapi tindakan manual sementara seharusnya tidak bergantung pada ingatan satu orang. Pencegahnya adalah serah terima tugas yang jelas saat dialihkan, timer pembatas waktu pada operasi pompa manual, dan trip level tinggi-tinggi independen yang tetap aktif saat sakelar level utama dikalibrasi.',
        controls: ['Serah terima tugas yang jelas saat dialihkan ke pekerjaan lain', 'Timer pembatas waktu pada operasi pompa transfer manual', 'Trip level tinggi-tinggi independen tetap aktif saat sakelar utama dikalibrasi'] },
      chat: [
        { t: 1, who: 'rudi', at: 'TK-101', text: 'Sakelar level tangki harian sedang dikalibrasi, jadi pompa transfer kujalankan manual dulu sebelum uji genset.' },
        { t: 4, who: 'rudi', at: 'P-101', text: 'Pompa transfer sudah jalan. Mengisi tangki harian butuh sekitar sepuluh menit.' },
        { t: 7, who: 'yanto', at: 'CR-100', mood: 'panik', text: 'Pak Rudi, lift penumpang macet di lantai 2 dan ada orang terjebak di dalam!' },
        { t: 10, who: 'rudi', at: 'CR-100', text: 'Aku ke sana sekarang. Tolong hubungi teknisi lift.' },
        { t: 22, who: 'yanto', at: 'CR-100', mood: 'ragu', text: 'Level tangki harian solar di panel naik terus melewati set point pengisian.' },
        { t: 27, who: 'yanto', at: 'CR-100', mood: 'panik', text: 'Bau solar kuat dari ruang genset! Pak Rudi, pompa transfernya sudah dimatikan?' },
        { t: 31, who: 'rudi', at: 'CR-100', mood: 'panik', text: 'Astaga, aku lupa! Matikan pompa dari panel dan hentikan uji genset sekarang!' },
      ],
      effects: [{ var: 'LD', to: 100, delay: 1, dur: 13 }],
      warnings: [
        { t: 15, type: 'spill', sev: 'warn', at: 'TK-101', pos: [244, 420], text: 'Solar keluar dari pipa vent tangki harian TK-101, sementara pompa transfer terus berbunyi.' },
        { t: 21, type: 'spill', sev: 'crit', at: 'TK-101', pos: [262, 500], text: 'Solar meluap dari tangki harian dan menggenang di lantai hingga mendekati genset yang sedang diuji.' },
        { t: 27, type: 'fire', sev: 'final', at: 'GEN-101', pos: [320, 470], big: true, text: 'Solar yang meluap tersulut knalpot genset yang panas. Asap tebal masuk ke basement dan tangga darurat.' },
      ],
      answer: { node: ['TK-101', 'P-101'], param: ['L'], guide: ['high'] },
      hint: 'Level tangki harian naik terus melewati set point setelah pompa transfer dijalankan manual. Baca kembali obrolan tentang pompa transfer dan keadaan darurat yang muncul.',
      causes: ['Pompa transfer yang dijalankan manual lupa dimatikan karena teknisi dialihkan ke lift macet, sementara sakelar level sedang dikalibrasi', 'Sakelar level tangki harian macet sehingga pompa tidak berhenti otomatis', 'Tangki pendam bocor sehingga air tanah mendorong solar ke tangki harian', 'Genset memakai solar lebih sedikit dari biasanya'], causeAns: 0,
      cons: ['Solar meluap ke lantai ruang genset dan tersulut knalpot yang panas sehingga terjadi kebakaran', 'Genset dapat beroperasi lebih lama tanpa dampak', 'Tekanan LPG turun karena pasokan energi beralih', 'Suhu busbar panel naik karena genset bekerja'], consAns: 0,
      explain: 'Level tangki harian naik terus melewati set point, polanya sama dengan sakelar level yang macet. Bedanya, pompa dijalankan manual lalu terlupa karena teknisi dialihkan ke keadaan darurat lain. Trip level tinggi-tinggi yang independen, tanggul penampung, dan sprinkler ruang genset tetap diperlukan karena tindakan manual mudah terlupa.' },
  ],
  variants: [
    ['e3', 'e6', 'e5', 'e2', 'e7'],
    ['e6', 'e1', 'e5', 'e2', 'e8'],
    ['e1', 'e4', 'e8', 'e6', 'e7'],
    ['e4', 'e3', 'e5', 'e1', 'e8'],
    ['e2', 'e3', 'e7', 'e4', 'e8'],
  ],
  hotspots: [
    /* Tahap 3: pencegahan */
    { id: 'h31', stage: 3, x: 262, y: 152, label: 'Lantai dapur dekat kompor (detektor LPG dan katup solenoid)', accept: ['GSO'],
      why: 'LPG lebih berat dari udara sehingga detektor dipasang dekat lantai. Saat gas terdeteksi, katup solenoid menutup jalur LPG sebelum campuran mudah meledak terbentuk.' },
    { id: 'h32', stage: 3, x: 142, y: 256, label: 'Outlet manifold tabung LPG (excess flow valve)', accept: ['EFV'],
      why: 'Excess flow valve menutup otomatis saat aliran melonjak akibat selang atau pipa putus, sehingga isi tabung tidak terus mengalir ke titik bocor.' },
    { id: 'h33', stage: 3, x: 244, y: 428, label: 'Tangki harian TK-101 (level tinggi-tinggi)', accept: ['LSHH', 'LT'],
      why: 'Trip level tinggi-tinggi yang independen dari sakelar pengisian menghentikan pompa transfer sebelum tangki meluap. Alarm level diterima sebagai lapisan respons operator.' },
    { id: 'h34', stage: 3, x: 426, y: 472, label: 'Busbar panel LVMDP (pemantauan suhu)', accept: ['TT'],
      why: 'Sambungan kendur memanas pada arus normal sehingga relai arus lebih tidak bereaksi. Sensor suhu busbar mendeteksi titik panas sejak dini.' },
    { id: 'h35', stage: 3, x: 470, y: 420, label: 'Kabel masuk dari PLN (relai arus lebih dan gangguan tanah)', accept: ['OCR'],
      why: 'Relai arus lebih dan gangguan tanah pada sisi masuk memutus arus hubung singkat atau beban lebih sebelum kabel dan busbar terbakar.' },
    { id: 'h36', stage: 3, x: 395, y: 106, label: 'Hood dapur KC-301 (filter lemak)', accept: ['GRF'],
      why: 'Filter baffle menangkap lemak sebelum masuk ducting dan menahan lidah api dari kompor agar tidak langsung masuk ke saluran (NFPA 96).' },
    { id: 'h37', stage: 3, x: 372, y: 64, label: 'Ducting exhaust dapur (sensor suhu)', accept: ['TT'],
      why: 'Alarm suhu ducting memberi peringatan dini saat endapan lemak mulai terbakar sehingga petugas dapat mengaktifkan pemadaman lebih cepat.' },
    { id: 'h38', stage: 3, x: 510, y: 330, label: 'Lobi lantai 1', accept: [],
      why: 'Lobi tidak menyimpan bahan mudah terbakar dalam jumlah berarti dan tidak terkait dengan ancaman yang teridentifikasi. Anggaran lebih baik dipakai pada dapur, ruang genset, dan panel listrik.' },
    { id: 'h39', stage: 3, x: 700, y: 220, label: 'Area perkantoran lantai 2', accept: [],
      why: 'Area perkantoran tidak memiliki sumber ancaman proses yang teridentifikasi. Perlindungannya berupa barier mitigasi seperti detektor asap dan sprinkler pada tahap berikutnya.' },
    /* Tahap 4: mitigasi */
    { id: 'h41', stage: 4, x: 395, y: 106, label: 'Hood dapur KC-301 (pemadam wet chemical)', accept: ['WETC'],
      why: 'Sistem wet chemical memadamkan api minyak pada kompor, hood, dan pangkal ducting sekaligus memutus pasokan LPG ke kompor (NFPA 17A).' },
    { id: 'h42', stage: 4, x: 372, y: 64, label: 'Ducting exhaust dapur (shaft tahan api)', accept: ['SHAFT'],
      why: 'Ducting yang melewati plafon dan atap dibungkus shaft tahan api agar kebakaran di dalam ducting tidak merambat ke ruang lain (NFPA 96).' },
    { id: 'h43', stage: 4, x: 490, y: 150, label: 'Dapur dan area makan restoran (APAR)', accept: ['APAR'],
      why: 'APAR yang sesuai kelas kebakaran memungkinkan petugas dapur memadamkan api kecil pada tahap awal (Permenakertrans No. Per.04/MEN/1980).' },
    { id: 'h44', stage: 4, x: 584, y: 36, label: 'Puncak tangga darurat (kipas presurisasi)', accept: ['PRES'],
      why: 'Kipas presurisasi menjaga tangga darurat bebas asap sehingga penghuni dapat turun dengan aman dan petugas pemadam dapat naik.' },
    { id: 'h45', stage: 4, x: 400, y: 220, label: 'Area perkantoran lantai 2 (detektor asap atau sprinkler)', accept: ['SD', 'SPK'],
      why: 'Detektor asap memberi peringatan dini kepada penghuni (SNI 03-3985-2000). Sprinkler otomatis mengendalikan api sebelum meluas (SNI 03-3989-2000).' },
    { id: 'h46', stage: 4, x: 655, y: 232, label: 'Pipa tegak lantai 2 (kotak hidran dan selang)', accept: ['HYD'],
      why: 'Kotak hidran di setiap lantai memungkinkan regu pemadam gedung melawan api sebelum petugas pemadam kota tiba (SNI 03-1745-2000).' },
    { id: 'h47', stage: 4, x: 440, y: 316, label: 'Ruang kendali kebakaran (alarm umum dan evakuasi)', accept: ['ALARM'],
      why: 'Alarm umum, pengumuman suara, dan regu tanggap darurat yang terlatih menentukan berapa cepat ratusan penghuni dapat keluar (Kepmenaker No. Kep.186/MEN/1999).' },
    { id: 'h48', stage: 4, x: 244, y: 500, label: 'Tangki harian TK-101 (tanggul penampung)', accept: ['DIKE'],
      why: 'Tanggul menampung solar yang meluap sehingga tidak menyebar ke bawah genset dan knalpot yang panas.' },
    { id: 'h49', stage: 4, x: 348, y: 424, label: 'Ruang genset (sprinkler)', accept: ['SPK'],
      why: 'Sprinkler mengendalikan kebakaran solar di ruang genset dan mendinginkan struktur di sekitarnya.' },
    { id: 'h4a', stage: 4, x: 436, y: 424, label: 'Ruang panel LVMDP (pemadam gas bersih)', accept: ['GAS'],
      why: 'Gas bersih memadamkan api pada peralatan listrik tanpa merusak komponen dan tanpa menghantarkan listrik (NFPA 2001).' },
    { id: 'h40', stage: 4, x: 857, y: 296, label: 'Tangki air pemadam TK-201 (tanggul)', accept: [],
      why: 'Tanggul diperlukan untuk tangki bahan berbahaya atau mudah terbakar. Tangki air pemadam tidak memerlukan tanggul; anggaran lebih baik dipakai untuk tangki solar.' },
  ],
  inspect: [
    { id: 'PNL-101', itpm: 'ELEC', why: 'Inspeksi termografi inframerah dan pengencangan baut busbar secara berkala mendeteksi sambungan kendur sebelum menjadi titik panas (Permenaker No. 12 Tahun 2015).' },
    { id: 'GEN-101', itpm: 'ROT', why: 'Uji jalan berbeban dan pemantauan getaran genset memastikan daya cadangan untuk pompa kebakaran, lift kebakaran, dan presurisasi tersedia saat PLN padam.' },
    { id: 'KC-301', itpm: 'DUCT', why: 'Pembersihan filter harian dan pembersihan ducting berkala menghilangkan endapan lemak yang menjadi bahan bakar kebakaran ducting (NFPA 96).' },
  ],
  budget: { 3: 27, 4: 35 },
  bowtie: {
    top: 'Kebakaran atau ledakan di dalam gedung',
    threats: ['Kebocoran LPG di dapur', 'Luapan solar tangki harian genset', 'Busbar panel LVMDP kepanasan', 'Endapan lemak ducting tersulut'],
    cons: ['Ledakan gas di dapur restoran', 'Kebakaran ruang genset', 'Kebakaran panel dan listrik padam', 'Kebakaran ducting merambat ke atap'],
  },
};
SCENARIOS.push(SCN_GEDUNG);
