/* =====================================================================
   PSM Simulator - Data permainan
   Berisi katalog perangkat keselamatan (barier), skenario proses,
   kuis, kejadian abnormal (deviasi HAZOP), dan titik pemasangan barier.
   ===================================================================== */

const APP_INFO = {
  name: 'PSM Simulator',
  version: '1.0.0',
  tagline: 'Simulasi Keselamatan Proses: Pahami, Kenali, Lindungi',
};

const CREDITS = {
  konsep: 'M Reza Huzain, SKM, MKKK',
  organisasi: 'Nusa Safety | PT. Nusa Rendra Jayatama',
  pengembang: 'Trustie (asisten pengembangan)',
  tahun: '2026',
  referensi: [
    'Undang-Undang No. 1 Tahun 1970 tentang Keselamatan Kerja.',
    'Peraturan Pemerintah No. 50 Tahun 2012 tentang Penerapan Sistem Manajemen Keselamatan dan Kesehatan Kerja (SMK3).',
    'Keputusan Menteri Tenaga Kerja No. KEP.187/MEN/1999 tentang Pengendalian Bahan Kimia Berbahaya di Tempat Kerja.',
    'Peraturan Menteri ESDM No. 18 Tahun 2018 tentang Pemeriksaan Keselamatan Instalasi dan Peralatan pada Kegiatan Usaha Minyak dan Gas Bumi.',
    'OSHA 29 CFR 1910.119, Process Safety Management of Highly Hazardous Chemicals.',
    'CCPS (2007). Guidelines for Risk Based Process Safety. AIChE/Wiley.',
    'CCPS & Energy Institute (2018). Bow Ties in Risk Management. AIChE/Wiley.',
    'CCPS (2001). Layer of Protection Analysis: Simplified Process Risk Assessment. AIChE.',
    'IEC 61511 (2016). Functional safety: Safety instrumented systems for the process industry sector.',
    'IEC 61882 (2016). Hazard and operability studies (HAZOP studies), Application guide.',
    'ISA-5.1 (2009). Instrumentation Symbols and Identification.',
    'API RP 14C (2017). Analysis, Design, Installation, and Testing of Safety Systems for Offshore Production Facilities.',
  ],
};

/* ---------------------------------------------------------------------
   Katalog perangkat (barier). cat: 'prevent' = pencegahan (sisi kiri
   bow-tie), 'mitigate' = mitigasi (sisi kanan bow-tie). cost = satuan
   anggaran yang dipakai di Tahap 3 dan 4.
   --------------------------------------------------------------------- */
const DEVICES = {
  /* ------- Pencegahan ------- */
  PT:    { code: 'PT',   name: 'Transmitter Tekanan + Alarm (PAH/PAL)', cat: 'prevent', cost: 2, color: '#42a5f5',
           desc: 'Mengukur tekanan dan memberi alarm tinggi/rendah ke operator di ruang kendali sehingga operator dapat bertindak sebelum trip. Lapisan proteksi berbasis respons operator.' },
  LT:    { code: 'LT',   name: 'Transmitter Level + Alarm (LAH/LAL)', cat: 'prevent', cost: 2, color: '#42a5f5',
           desc: 'Mengukur level cairan dan memberi alarm tinggi/rendah. Memungkinkan operator mengoreksi sebelum level mencapai batas bahaya.' },
  TT:    { code: 'TT',   name: 'Transmitter Suhu + Alarm (TAH)', cat: 'prevent', cost: 2, color: '#42a5f5',
           desc: 'Mengukur suhu dan memberi alarm suhu tinggi. Penting pada proses eksotermik.' },
  FT:    { code: 'FT',   name: 'Transmitter Aliran + Pembatas Laju Umpan', cat: 'prevent', cost: 2, color: '#42a5f5',
           desc: 'Mengukur laju alir dan membatasi laju umpan agar tidak melebihi kapasitas pendinginan atau reaksi.' },
  PSV:   { code: 'PSV',  name: 'Pressure Safety Valve (PSV)', cat: 'prevent', cost: 3, color: '#ef5350',
           desc: 'Katup pengaman tekanan yang membuka otomatis saat tekanan melebihi set point untuk mencegah bejana pecah. Lapisan proteksi mekanis terakhir sebelum kehilangan kontainmen.' },
  RD:    { code: 'RD',   name: 'Rupture Disc (Cakram Pecah)', cat: 'prevent', cost: 2, color: '#ef5350',
           desc: 'Cakram yang pecah pada tekanan tertentu untuk melepaskan tekanan dengan sangat cepat. Cocok untuk kenaikan tekanan yang sangat cepat seperti reaksi runaway.' },
  SIS:   { code: 'SIS',  name: 'SIF Tekanan Tinggi (PSHH → SDV)', cat: 'prevent', cost: 4, color: '#ab47bc',
           desc: 'Safety Instrumented Function: sakelar tekanan tinggi-tinggi (PSHH) menutup shutdown valve (SDV) di jalur masuk secara otomatis. Lapisan proteksi independen (IPL) sesuai IEC 61511.' },
  LSHH:  { code: 'LSHH', name: 'Trip Level Tinggi-Tinggi (LSHH → tutup inlet)', cat: 'prevent', cost: 3, color: '#ab47bc',
           desc: 'Proteksi overfill: sakelar level tinggi-tinggi yang menutup katup masuk secara otomatis. Mencegah luapan tangki dan liquid carry-over.' },
  LSLL:  { code: 'LSLL', name: 'Trip Level Rendah-Rendah (LSLL → tutup outlet)', cat: 'prevent', cost: 3, color: '#ab47bc',
           desc: 'Proteksi gas blow-by: menutup katup keluar cairan bila level terlalu rendah sehingga gas bertekanan tidak menerobos ke sistem hilir bertekanan rendah.' },
  TSHH:  { code: 'TSHH', name: 'Trip Suhu Tinggi-Tinggi (TSHH → stop umpan)', cat: 'prevent', cost: 4, color: '#ab47bc',
           desc: 'SIF suhu: menghentikan umpan dan membuka pendingin darurat saat suhu reaktor melewati batas tinggi-tinggi. Mencegah reaksi runaway.' },
  FSLL:  { code: 'FSLL', name: 'Trip Aliran Pendingin Rendah (FSLL → stop umpan)', cat: 'prevent', cost: 3, color: '#ab47bc',
           desc: 'Menghentikan umpan reaktan bila aliran air pendingin hilang, karena panas reaksi tidak dapat dibuang.' },
  AGI:   { code: 'AGI',  name: 'Interlock Agitator (stop umpan bila agitator mati)', cat: 'prevent', cost: 2, color: '#ab47bc',
           desc: 'Mencegah akumulasi reaktan tak tercampur yang dapat bereaksi serentak saat agitator hidup kembali.' },
  NRV:   { code: 'NRV',  name: 'Check Valve (Non-Return Valve)', cat: 'prevent', cost: 1, color: '#66bb6a',
           desc: 'Mencegah aliran balik (reverse flow) dari sistem bertekanan tinggi ke sistem bertekanan rendah atau ke pompa yang berhenti.' },
  EFV:   { code: 'EFV',  name: 'Excess Flow Valve', cat: 'prevent', cost: 2, color: '#66bb6a',
           desc: 'Menutup otomatis bila laju alir melampaui batas, misalnya saat selang atau pipa hilir pecah.' },
  BRK:   { code: 'BRK',  name: 'Breakaway Coupling (Loading Arm)', cat: 'prevent', cost: 2, color: '#66bb6a',
           desc: 'Sambungan yang putus dan menutup sendiri bila truk bergerak saat masih tersambung, sehingga tidak terjadi pelepasan besar.' },
  GRND:  { code: 'GRND', name: 'Grounding & Bonding + Interlock', cat: 'prevent', cost: 1, color: '#66bb6a',
           desc: 'Menghilangkan muatan statis sebagai sumber nyala saat pengisian. Interlock mencegah pompa menyala bila klem grounding belum terpasang.' },
  N2:    { code: 'N2',   name: 'Nitrogen Blanketing', cat: 'prevent', cost: 2, color: '#66bb6a',
           desc: 'Mengisi ruang uap tangki dengan nitrogen agar campuran uap berada di luar rentang mudah terbakar.' },
  /* ------- Mitigasi ------- */
  GD:    { code: 'GD',   name: 'Detektor Gas (Flammable/Toxic)', cat: 'mitigate', cost: 2, color: '#ffa726',
           desc: 'Mendeteksi kebocoran gas pada tahap awal dan mengaktifkan alarm atau ESD sebelum awan gas mencapai sumber nyala.' },
  FD:    { code: 'FD',   name: 'Detektor Api/Nyala (Flame Detector)', cat: 'mitigate', cost: 2, color: '#ffa726',
           desc: 'Mendeteksi kebakaran secara cepat dan memicu sistem proteksi kebakaran aktif serta ESD.' },
  ESD:   { code: 'ESD',  name: 'Sistem Emergency Shutdown (ESD)', cat: 'mitigate', cost: 3, color: '#ef5350',
           desc: 'Tombol dan logika ESD untuk mengisolasi unit, menghentikan pompa, dan menutup SDV secara serentak saat darurat.' },
  BDV:   { code: 'BDV',  name: 'Blowdown Valve ke Flare', cat: 'mitigate', cost: 4, color: '#ef5350',
           desc: 'Melepaskan tekanan bejana ke flare dengan cepat (depressurisasi darurat) untuk mengurangi inventori dan risiko pecah saat terpapar api.' },
  DELUGE:{ code: 'DLG',  name: 'Sistem Deluge / Water Spray', cat: 'mitigate', cost: 3, color: '#29b6f6',
           desc: 'Menyemprotkan air ke permukaan bejana untuk pendinginan saat terpapar api, mencegah kegagalan bejana dan BLEVE.' },
  DIKE:  { code: 'DIKE', name: 'Tanggul (Bund/Dike) Penampung Tumpahan', cat: 'mitigate', cost: 3, color: '#8d6e63',
           desc: 'Menampung tumpahan cairan dari tangki sehingga tidak menyebar ke area lain dan luas genangan api terbatas.' },
  FOAM:  { code: 'FOAM', name: 'Sistem Busa (Foam) Tangki', cat: 'mitigate', cost: 3, color: '#29b6f6',
           desc: 'Memadamkan kebakaran cairan mudah terbakar pada permukaan tangki dengan menutup permukaan cairan.' },
  FW:    { code: 'FW',   name: 'Hidran & Monitor Air Pemadam', cat: 'mitigate', cost: 2, color: '#29b6f6',
           desc: 'Sarana pemadaman manual dan pendinginan peralatan sekitar oleh tim tanggap darurat.' },
  EIV:   { code: 'EIV',  name: 'Katup Isolasi Darurat Jarak Jauh (ROSOV)', cat: 'mitigate', cost: 3, color: '#ef5350',
           desc: 'Katup yang dapat ditutup dari jarak aman untuk menghentikan sumber kebocoran dan membatasi jumlah pelepasan.' },
  SCRUB: { code: 'SCRB', name: 'Scrubber Darurat (Vent Treatment)', cat: 'mitigate', cost: 3, color: '#66bb6a',
           desc: 'Menetralkan uap beracun yang dilepaskan melalui vent darurat sebelum mencapai atmosfer.' },
  QUENCH:{ code: 'QNC',  name: 'Sistem Quench / Injeksi Inhibitor', cat: 'mitigate', cost: 4, color: '#ab47bc',
           desc: 'Menghentikan reaksi runaway dengan menyuntikkan inhibitor atau pelarut dingin ke dalam reaktor.' },
  ALARM: { code: 'ALM',  name: 'Alarm Umum & Rencana Tanggap Darurat', cat: 'mitigate', cost: 1, color: '#ffee58',
           desc: 'Sirene, titik kumpul, dan prosedur evakuasi untuk melindungi pekerja dan masyarakat sekitar.' },
};

const PARAMS = {
  P: 'Tekanan', L: 'Level', T: 'Suhu', F: 'Aliran', C: 'Komposisi / Reaksi',
};
const GUIDEWORDS = {
  high: 'Lebih tinggi (More / High)',
  low: 'Lebih rendah (Less / Low)',
  none: 'Tidak ada (No / None)',
  reverse: 'Terbalik (Reverse)',
  other: 'Selain dari (Other than)',
};

/* =====================================================================
   SKENARIO 1: Unit Separator Produksi Migas
   ===================================================================== */
const SCN_SEPARATOR = {
  id: 'separator',
  title: 'Unit Separator Produksi Migas',
  subtitle: 'Separator tiga fasa, tangki minyak atmosferik, kompresor gas',
  level: 'Pemula',
  sector: 'Hulu Migas',
  color: '#ff8c1a',
  overview: [
    'Unit ini menerima fluida sumur (campuran gas, minyak, dan air terproduksi) dari manifold produksi dengan tekanan hulu 25 barg. Choke valve menurunkan tekanan menjadi 8 barg sebelum fluida masuk ke separator tiga fasa V-101.',
    'Di dalam V-101, gas, minyak, dan air dipisahkan berdasarkan perbedaan densitas. Tekanan bejana dijaga oleh PCV-101 di jalur keluar gas, level minyak oleh LCV-101, dan level antarmuka air oleh LCV-102.',
    'Gas dialirkan ke kompresor K-101 (sangat sensitif terhadap cairan). Minyak dialirkan ke tangki penampung atmosferik T-101 lalu dipompa P-101 ke jalur ekspor. Air terproduksi dialirkan ke unit pengolahan air yang beroperasi pada tekanan rendah (0,5 barg).',
  ],
  equipment: [
    { id: 'MAN-100', type: 'manifold', x: 40, y: 262, w: 60, h: 36, name: 'Manifold Produksi',
      desc: 'Mengumpulkan aliran dari beberapa sumur. Tekanan hulu 25 barg, suhu 55 °C. Batas unit simulasi dimulai setelah manifold.' },
    { id: 'CHK-100', type: 'valve', sub: 'manual', x: 160, y: 280, name: 'Choke Valve',
      desc: 'Katup manual yang mengatur laju alir masuk dan menurunkan tekanan dari 25 barg menjadi 8 barg.' },
    { id: 'V-101', type: 'vessel', orient: 'h', x: 290, y: 225, w: 260, h: 110, name: 'Separator Tiga Fasa V-101',
      desc: 'Bejana tekan horizontal. Tekanan operasi 8 barg, tekanan desain (MAWP) 12 barg, suhu desain 80 °C, volume 25 m³, waktu tinggal 3 menit. Memisahkan gas (atas), minyak (tengah), dan air (bawah).',
      vars: ['P1', 'L1', 'LI1', 'T1'] },
    { id: 'PCV-101', type: 'valve', sub: 'control', x: 600, y: 140, tag: 'PIC', name: 'PCV-101 (Kendali Tekanan)',
      desc: 'Katup kendali tekanan di jalur gas keluar. Loop PIC-101 menjaga tekanan V-101 pada 8 barg dengan mengatur bukaan katup. Jika katup tertutup, gas tidak punya jalan keluar.' },
    { id: 'K-101', type: 'compressor', x: 760, y: 140, name: 'Kompresor Gas K-101',
      desc: 'Mengompresi gas dari 8 barg ke 40 barg untuk penjualan. Sangat sensitif terhadap cairan terbawa (liquid carry-over) yang dapat merusak impeller.' },
    { id: 'LCV-101', type: 'valve', sub: 'control', x: 600, y: 400, tag: 'LIC', name: 'LCV-101 (Kendali Level Minyak)',
      desc: 'Katup kendali level minyak. Loop LIC-101 menjaga level minyak V-101 pada 50 %. Aliran minyak digerakkan oleh tekanan separator (8 barg) menuju tangki atmosferik.' },
    { id: 'T-101', type: 'tank', x: 700, y: 370, w: 120, h: 100, name: 'Tangki Minyak T-101',
      desc: 'Tangki penampung atmosferik (API 650), kapasitas 500 m³, tekanan desain hanya 0,05 barg. Tidak dirancang menahan tekanan gas; level dipantau operator secara manual.', vars: ['LT1'] },
    { id: 'P-101', type: 'pump', x: 860, y: 510, name: 'Pompa Ekspor P-101',
      desc: 'Pompa sentrifugal 40 m³/jam memindahkan minyak dari T-101 ke jalur ekspor bertekanan 15 barg.' },
    { id: 'LCV-102', type: 'valve', sub: 'control', x: 250, y: 450, tag: 'LIC', name: 'LCV-102 (Kendali Level Antarmuka)',
      desc: 'Katup kendali level antarmuka minyak-air. Loop LIC-102 menjaga level air pada 30 %. Jika katup terbuka saat level air habis, gas 8 barg akan menerobos ke sistem air (gas blow-by).' },
    { id: 'WT-100', type: 'sink', x: 135, y: 450, dir: 'left', name: 'Unit Pengolahan Air Terproduksi',
      desc: 'Sistem hilir bertekanan rendah: operasi 0,5 barg, tekanan desain 3,5 barg. Rentan pecah bila menerima gas blow-by dari separator.', vars: ['PW'] },
    { id: 'FL-100', type: 'flare', x: 930, y: 115, name: 'Flare FL-100',
      desc: 'Sistem flare membakar gas pelepasan darurat secara aman. Header flare tersedia dekat V-101 untuk sambungan PSV atau BDV.' },
    { id: 'CR-100', type: 'building', x: 110, y: 110, name: 'Ruang Kendali',
      desc: 'Operator memantau DCS dan merespons alarm. Lokasi tombol ESD dan pusat komunikasi darurat.' },
    { id: 'MP-100', type: 'muster', x: 120, y: 520, name: 'Titik Kumpul',
      desc: 'Area berkumpul evakuasi pekerja pada arah angin yang aman.' },
  ],
  pipes: [
    { id: 'in1', fluid: 'mix', w: 7, pts: [[100, 280], [290, 280]] },
    { id: 'gas1', fluid: 'gas', w: 6, pts: [[420, 225], [420, 140], [740, 140]] },
    { id: 'gas2', fluid: 'gas', w: 6, pts: [[780, 140], [990, 140]], arrow: true, label: 'Ke Penjualan Gas (40 barg)' },
    { id: 'oil1', fluid: 'oil', w: 6, pts: [[520, 335], [520, 400], [710, 400], [710, 380]] },
    { id: 'oil2', fluid: 'oil', w: 6, pts: [[760, 470], [760, 510], [840, 510]] },
    { id: 'oil3', fluid: 'oil', w: 6, pts: [[880, 510], [990, 510]], arrow: true, label: 'Ekspor (15 barg)' },
    { id: 'wat1', fluid: 'water', w: 6, pts: [[340, 335], [340, 450], [135, 450]], arrow: true },
    { id: 'flr', fluid: 'flare', w: 4, dashed: true, pts: [[500, 150], [500, 95], [922, 95]] },
  ],
  labels: [
    { x: 560, y: 84, text: 'Header Flare', size: 11 },
  ],
  vars: {
    P1:  { label: 'Tekanan V-101', unit: 'barg', normal: 8.0, min: 0, max: 14, lo: 6, hi: 9.5, hihi: 11, node: 'V-101', x: 300, y: 196, tau: 3, noise: 0.05, dec: 1, color: '#ef5350' },
    L1:  { label: 'Level Minyak V-101', unit: '%', normal: 50, min: 0, max: 100, lo: 30, hi: 70, hihi: 85, node: 'V-101', x: 420, y: 354, tau: 4, noise: 0.5, dec: 0, color: '#8d6e63' },
    LI1: { label: 'Level Antarmuka Air V-101', unit: '%', normal: 30, min: 0, max: 100, lo: 15, hi: 45, lolo: 8, node: 'V-101', x: 420, y: 376, tau: 4, noise: 0.5, dec: 0, color: '#29b6f6' },
    T1:  { label: 'Suhu V-101', unit: '°C', normal: 45, min: 0, max: 100, lo: 30, hi: 60, hihi: 75, node: 'V-101', x: 540, y: 196, tau: 8, noise: 0.2, dec: 1, color: '#ffa726' },
    FG:  { label: 'Aliran Gas ke K-101', unit: 'MMSCFD', normal: 5.0, min: 0, max: 10, lo: 2, hi: 8, node: 'K-101', x: 690, y: 112, tau: 2, noise: 0.05, dec: 2, color: '#ffca28' },
    FO:  { label: 'Aliran Minyak', unit: 'm³/j', normal: 40, min: 0, max: 100, lo: 15, hi: 70, node: 'LCV-101', x: 672, y: 428, tau: 2, noise: 0.5, dec: 0, color: '#a1887f' },
    LT1: { label: 'Level T-101', unit: '%', normal: 60, min: 0, max: 100, lo: 20, hi: 80, hihi: 92, node: 'T-101', x: 870, y: 440, tau: 5, noise: 0.2, dec: 0, color: '#8d6e63' },
    PW:  { label: 'Tekanan Sistem Air Hilir', unit: 'barg', normal: 0.5, min: 0, max: 6, hi: 2, hihi: 3.5, node: 'WT-100', x: 160, y: 480, tau: 2, noise: 0.02, dec: 2, color: '#26c6da' },
  },
  trendVars: ['P1', 'L1', 'LI1', 'LT1'],
  controls: [
    { id: 'qin', label: 'Bukaan choke (laju alir masuk)', unit: '%', min: 40, max: 160, def: 100, step: 5,
      effects: [{ var: 'FG', gain: 0.05 }, { var: 'FO', gain: 0.4 }, { var: 'P1', gain: 0.012 }, { var: 'L1', gain: 0.06 }] },
    { id: 'spP', label: 'Set point PIC-101 (tekanan)', unit: 'barg', min: 6, max: 10, def: 8, step: 0.5,
      effects: [{ var: 'P1', gain: 1 }, { var: 'FG', gain: -0.1 }] },
    { id: 'spL', label: 'Set point LIC-101 (level minyak)', unit: '%', min: 30, max: 70, def: 50, step: 5,
      effects: [{ var: 'L1', gain: 1 }] },
  ],
  quiz: [
    { q: 'Apa fungsi utama separator V-101?', opts: ['Menaikkan tekanan gas untuk penjualan', 'Memisahkan gas, minyak, dan air berdasarkan perbedaan densitas', 'Memanaskan fluida sumur agar mudah dipompa', 'Menyimpan minyak sebelum diekspor'], ans: 1,
      why: 'Separator tiga fasa memisahkan ketiga fasa berdasarkan densitas dan waktu tinggal. Kompresi dan penyimpanan dilakukan oleh K-101 dan T-101.' },
    { q: 'Berapa tekanan operasi normal V-101 dan berapa tekanan desainnya (MAWP)?', opts: ['8 barg operasi, 12 barg desain', '25 barg operasi, 40 barg desain', '0,5 barg operasi, 3,5 barg desain', '12 barg operasi, 8 barg desain'], ans: 0,
      why: 'Choke menurunkan tekanan dari 25 barg ke 8 barg. Selisih antara tekanan operasi dan MAWP (12 barg) adalah margin keselamatan yang harus dijaga.' },
    { q: 'Perangkat apa yang menjaga tekanan V-101 tetap 8 barg pada kondisi normal?', opts: ['LCV-101 pada jalur minyak', 'PCV-101 pada jalur keluar gas (loop PIC-101)', 'Pompa P-101', 'Choke valve secara otomatis'], ans: 1,
      why: 'Tekanan separator dikendalikan dengan mengatur laju gas keluar melalui PCV-101. Ini adalah lapisan BPCS (Basic Process Control System), bukan lapisan proteksi.' },
    { q: 'Mengapa tangki T-101 dan unit pengolahan air termasuk titik rawan pada unit ini?', opts: ['Karena keduanya berada jauh dari ruang kendali', 'Karena keduanya bertekanan desain rendah dan menerima aliran dari bejana 8 barg', 'Karena keduanya tidak memiliki pompa', 'Karena keduanya terbuat dari bahan non-logam'], ans: 1,
      why: 'Sistem hilir bertekanan rendah yang terhubung ke bejana bertekanan lebih tinggi rentan terhadap gas blow-by dan overfill, dua skenario klasik pada separator (API RP 14C).' },
    { q: 'Apa dampak cairan terbawa (liquid carry-over) ke jalur gas?', opts: ['Tidak berpengaruh karena gas dan cairan bisa dikompresi', 'Kerusakan kompresor K-101 dan potensi kebocoran gas', 'Tekanan V-101 turun drastis', 'Air terproduksi menjadi lebih bersih'], ans: 1,
      why: 'Kompresor sentrifugal tidak toleran terhadap cairan. Carry-over terjadi bila level minyak terlalu tinggi atau laju gas terlalu besar.' },
  ],
  events: [
    { id: 'e1', effects: [{ var: 'P1', to: 11.8, delay: 4, dur: 14 }, { var: 'FG', to: 0.3, delay: 2, dur: 4 }],
      answer: { node: ['V-101'], param: ['P'], guide: ['high'] },
      causes: ['PCV-101 macet tertutup (blocked outlet) sehingga gas tidak dapat keluar', 'LCV-101 macet terbuka sehingga minyak habis', 'Pompa P-101 trip', 'Suhu lingkungan turun pada malam hari'], causeAns: 0,
      cons: ['Tekanan melampaui MAWP 12 barg, bejana pecah, kebocoran gas besar, kebakaran atau ledakan', 'Level minyak turun dan tangki T-101 kosong', 'Kompresor menerima gas lebih banyak dari biasanya', 'Air terproduksi tercemar minyak'], consAns: 0,
      explain: 'Aliran gas keluar turun mendadak diikuti kenaikan tekanan V-101. Ini pola khas outlet gas terblokir (PCV gagal tertutup). Tanpa PSV atau trip tekanan tinggi, tekanan akan melampaui MAWP.' },
    { id: 'e2', effects: [{ var: 'L1', to: 96, delay: 4, dur: 16 }, { var: 'FO', to: 2, delay: 2, dur: 4 }],
      answer: { node: ['V-101'], param: ['L'], guide: ['high'] },
      causes: ['LCV-101 macet tertutup sehingga minyak tidak keluar', 'PCV-101 macet terbuka', 'Choke valve ditutup operator', 'Kompresor K-101 trip'], causeAns: 0,
      cons: ['Cairan terbawa ke jalur gas (carry-over), merusak kompresor K-101 dan berpotensi bocor', 'Tangki T-101 meluap', 'Tekanan sistem air hilir naik', 'Suhu separator naik drastis'], consAns: 0,
      explain: 'Aliran minyak keluar berhenti dan level minyak naik terus. Bila level mencapai ruang gas, cairan terbawa ke K-101. Proteksi: alarm level tinggi dan LSHH yang menutup inlet.' },
    { id: 'e3', effects: [{ var: 'LI1', to: 3, delay: 4, dur: 12 }, { var: 'PW', to: 4.2, delay: 12, dur: 8 }],
      answer: { node: ['V-101', 'LCV-102'], param: ['L'], guide: ['low'] },
      causes: ['LCV-102 macet terbuka atau transmitter level antarmuka gagal (membaca tinggi palsu)', 'LCV-101 macet tertutup', 'Choke valve dibuka terlalu besar', 'PSV terbuka'], causeAns: 0,
      cons: ['Gas 8 barg menerobos ke sistem air (gas blow-by), tekanan sistem hilir melampaui desain 3,5 barg dan pecah', 'Minyak terbawa ke jalur gas', 'Tekanan V-101 naik', 'Tangki T-101 kekurangan minyak'], consAns: 0,
      explain: 'Level antarmuka air turun hingga hampir nol, lalu tekanan sistem air hilir naik. Ini gas blow-by, skenario klasik separator. Proteksi: LSLL yang menutup LCV-102 atau SDV di jalur air.' },
    { id: 'e4', effects: [{ var: 'LT1', to: 99, delay: 3, dur: 18 }],
      answer: { node: ['T-101'], param: ['L'], guide: ['high'] },
      causes: ['Pompa ekspor P-101 trip atau jalur ekspor terblokir sementara minyak terus masuk', 'LCV-101 macet tertutup', 'PCV-101 macet tertutup', 'Air terproduksi masuk ke tangki'], causeAns: 0,
      cons: ['Tangki meluap (overfill), tumpahan minyak di area tangki, awan uap mudah terbakar (seperti insiden Buncefield 2005)', 'Kompresor rusak', 'Separator bertekanan tinggi', 'Air hilir tercemar'], consAns: 0,
      explain: 'Level T-101 naik tanpa perubahan di separator; berarti aliran keluar tangki berhenti. Tangki atmosferik tanpa proteksi overfill independen adalah penyebab beberapa bencana besar.' },
  ],
  hotspots: [
    /* Tahap 3: pencegahan */
    { id: 'h31', stage: 3, x: 480, y: 212, label: 'Nozzle puncak V-101', accept: ['PSV'],
      why: 'PSV pada bejana tekan adalah proteksi terakhir terhadap overpressure dan wajib menurut kode bejana tekan.' },
    { id: 'h32', stage: 3, x: 230, y: 280, label: 'Jalur masuk V-101 (setelah choke)', accept: ['SIS'],
      why: 'PSHH yang menutup SDV di jalur masuk menghentikan sumber tekanan sebelum PSV bekerja. Ini IPL dengan PFD yang dapat ditentukan.' },
    { id: 'h33', stage: 3, x: 360, y: 212, label: 'Nozzle instrumen tekanan V-101', accept: ['PT'],
      why: 'Alarm tekanan tinggi memberi kesempatan operator menutup choke sebelum trip. Lapisan respons operator.' },
    { id: 'h34', stage: 3, x: 562, y: 300, label: 'Nozzle level V-101 (sisi minyak)', accept: ['LT', 'LSHH'],
      why: 'Level minyak tinggi memicu carry-over. Alarm level (LT) memberi respons operator; LSHH memberi trip otomatis. Keduanya diterima di titik ini.' },
    { id: 'h35', stage: 3, x: 290, y: 320, label: 'Nozzle level antarmuka V-101 (sisi air)', accept: ['LSLL'],
      why: 'LSLL menutup katup keluar air saat antarmuka hampir habis, mencegah gas blow-by ke sistem bertekanan rendah.' },
    { id: 'h36', stage: 3, x: 822, y: 372, label: 'Puncak tangki T-101', accept: ['LSHH'],
      why: 'Proteksi overfill independen (LSHH menutup LCV-101/SDV) diwajibkan API 2350 untuk tangki atmosferik.' },
    { id: 'h37', stage: 3, x: 915, y: 510, label: 'Discharge pompa P-101', accept: ['NRV'],
      why: 'Check valve mencegah aliran balik dari jalur ekspor 15 barg ke tangki atmosferik saat pompa berhenti.' },
    { id: 'h38', stage: 3, x: 70, y: 225, label: 'Manifold produksi (hulu)', accept: [],
      why: 'Manifold berada di luar batas unit. Instrumen di sini tidak melindungi V-101 dari skenario yang teridentifikasi; anggaran lebih baik dipakai di titik lain.' },
    { id: 'h39', stage: 3, x: 700, y: 440, label: 'Dinding T-101 (suhu)', accept: [],
      why: 'Tangki atmosferik beroperasi pada suhu lingkungan. Transmitter suhu tidak menangani ancaman utama tangki, yaitu overfill.' },
    /* Tahap 4: mitigasi */
    { id: 'h41', stage: 4, x: 380, y: 120, label: 'Jalur gas keluar V-101 (ke header flare)', accept: ['BDV'],
      why: 'Blowdown ke flare menurunkan tekanan dan inventori gas saat kebakaran, mengurangi risiko pecah bejana.' },
    { id: 'h42', stage: 4, x: 250, y: 200, label: 'Area V-101 sisi masuk (deteksi)', accept: ['GD'],
      why: 'Detektor gas mendeteksi kebocoran flens dan seal lebih awal, memicu alarm dan ESD sebelum awan gas menemukan sumber nyala.' },
    { id: 'h43', stage: 4, x: 560, y: 185, label: 'Di atas V-101 (proteksi kebakaran)', accept: ['DELUGE'],
      why: 'Water spray mendinginkan dinding bejana saat terpapar api sehingga kekuatan material tidak menurun.' },
    { id: 'h44', stage: 4, x: 690, y: 485, label: 'Sekeliling T-101', accept: ['DIKE'],
      why: 'Tanggul menampung tumpahan tangki (minimal 110 % volume tangki terbesar) agar tidak menyebar.' },
    { id: 'h45', stage: 4, x: 840, y: 395, label: 'Atap T-101 (pemadaman)', accept: ['FOAM'],
      why: 'Kebakaran permukaan minyak dipadamkan dengan busa, bukan air.' },
    { id: 'h46', stage: 4, x: 680, y: 335, label: 'Area T-101 dan P-101 (deteksi api)', accept: ['FD'],
      why: 'Detektor nyala mempercepat aktivasi deluge, foam, dan ESD.' },
    { id: 'h47', stage: 4, x: 150, y: 150, label: 'Ruang kendali (tombol ESD)', accept: ['ESD'],
      why: 'ESD mengisolasi unit dan menghentikan pompa serta kompresor secara serentak dari lokasi aman.' },
    { id: 'h48', stage: 4, x: 180, y: 520, label: 'Titik kumpul dan sistem alarm umum', accept: ['ALARM'],
      why: 'Alarm umum dan rencana tanggap darurat melindungi orang, lapisan terakhir dalam model lapisan proteksi.' },
    { id: 'h49', stage: 4, x: 190, y: 420, label: 'Jalur air ke pengolahan', accept: [],
      why: 'Scrubber atau foam tidak relevan untuk air terproduksi. Ancaman gas blow-by sudah ditangani di sisi pencegahan oleh LSLL.' },
  ],
  budget: { 3: 20, 4: 23 },
  bowtie: {
    top: 'Kehilangan kontainmen hidrokarbon dari unit separator',
    threats: ['Outlet gas terblokir (PCV-101 gagal tertutup)', 'Level minyak tinggi, carry-over ke kompresor', 'Gas blow-by ke sistem air bertekanan rendah', 'Overfill tangki T-101'],
    cons: ['Kebakaran jet / ledakan awan uap', 'Kerusakan kompresor dan pelepasan gas', 'Pecahnya sistem air hilir', 'Tumpahan minyak dan kebakaran genangan'],
  },
};

/* =====================================================================
   SKENARIO 2: Reaktor Batch Eksotermik
   ===================================================================== */
const SCN_REACTOR = {
  id: 'reactor',
  title: 'Reaktor Batch Eksotermik',
  subtitle: 'Reaktor berjaket pendingin, kondensor refluks, umpan monomer',
  level: 'Menengah',
  sector: 'Industri Kimia',
  color: '#7e57c2',
  overview: [
    'Unit ini memproduksi resin melalui reaksi polimerisasi eksotermik di reaktor batch R-201 berkapasitas 10 m³. Monomer dari tangki umpan TK-201 dipompa oleh P-201 dan laju umpannya diatur FCV-201 (2 m³/jam) agar panas reaksi seimbang dengan kapasitas pendinginan.',
    'Panas reaksi dibuang melalui jaket pendingin yang dialiri air pendingin dari pompa P-203 (30 m³/jam) dan diatur TCV-201 untuk menjaga suhu reaktor 80 °C. Agitator M-201 menjaga homogenitas campuran dan perpindahan panas ke jaket.',
    'Uap pelarut dikondensasi oleh kondensor refluks E-201 dan dikembalikan ke reaktor; gas tak terkondensasi dibuang melalui vent. Produk dipompa P-202 ke tangki produk TK-202. Suhu runaway (onset) monomer sekitar 110 °C, tekanan desain reaktor 6 barg.',
  ],
  equipment: [
    { id: 'TK-201', type: 'tank', x: 50, y: 70, w: 100, h: 100, name: 'Tangki Umpan Monomer TK-201',
      desc: 'Tangki atmosferik berisi monomer mudah terbakar dan reaktif (titik nyala 10 °C). Ruang uap dapat membentuk campuran mudah terbakar.' },
    { id: 'P-201', type: 'pump', x: 160, y: 210, name: 'Pompa Umpan P-201',
      desc: 'Pompa positive displacement 0 hingga 5 m³/jam. Laju umpan diatur FCV-201.' },
    { id: 'FCV-201', type: 'valve', sub: 'control', x: 265, y: 210, tag: 'FIC', name: 'FCV-201 (Kendali Laju Umpan)',
      desc: 'Katup kendali laju umpan monomer, set point 2 m³/jam. Laju umpan menentukan laju pelepasan panas reaksi.' },
    { id: 'R-201', type: 'reactor', x: 400, y: 230, w: 160, h: 210, name: 'Reaktor Batch R-201',
      desc: 'Bejana berjaket 10 m³ dengan agitator. Suhu operasi 80 °C, tekanan operasi 1,5 barg, tekanan desain 6 barg. Suhu onset runaway sekitar 110 °C; di atas suhu ini laju reaksi dan tekanan naik secara eksponensial.',
      vars: ['T2', 'P2', 'L2'] },
    { id: 'M-201', type: 'motor', x: 505, y: 205, name: 'Agitator M-201',
      desc: 'Motor pengaduk 100 rpm. Tanpa pengadukan, perpindahan panas ke jaket turun drastis dan reaktan dapat terakumulasi.' },
    { id: 'TCV-201', type: 'valve', sub: 'control', x: 300, y: 420, tag: 'TIC', name: 'TCV-201 (Kendali Suhu)',
      desc: 'Katup kendali aliran air pendingin ke jaket. Loop TIC-201 menjaga suhu reaktor 80 °C.' },
    { id: 'P-203', type: 'pump', x: 210, y: 420, name: 'Pompa Air Pendingin P-203',
      desc: 'Pompa sentrifugal 30 m³/jam dari menara pendingin. Pendinginan hanya bergantung pada pompa ini (tanpa cadangan).' },
    { id: 'E-201', type: 'hx', x: 640, y: 120, name: 'Kondensor Refluks E-201',
      desc: 'Mengondensasi uap pelarut dan mengembalikannya ke reaktor, membantu membuang panas (sekitar 30 % beban). Didinginkan air pendingin.' },
    { id: 'VNT-201', type: 'sink', x: 835, y: 120, dir: 'right', name: 'Vent ke Atmosfer',
      desc: 'Jalur pembuangan gas tak terkondensasi. Tanpa pengolahan; pelepasan besar uap monomer akan beracun dan mudah terbakar.' },
    { id: 'P-202', type: 'pump', x: 560, y: 480, name: 'Pompa Produk P-202',
      desc: 'Memindahkan produk resin ke tangki produk setelah batch selesai.' },
    { id: 'TK-202', type: 'tank', x: 700, y: 400, w: 100, h: 100, name: 'Tangki Produk TK-202',
      desc: 'Tangki atmosferik produk resin, bahan mudah terbakar kelas II.' },
    { id: 'CW-IN', type: 'sink', x: 150, y: 420, dir: 'left', name: 'Air Pendingin dari Menara',
      desc: 'Suplai air pendingin 30 °C dari menara pendingin.' },
    { id: 'CW-OUT', type: 'sink', x: 150, y: 270, dir: 'left', name: 'Air Pendingin Kembali',
      desc: 'Air pendingin kembali ke menara dengan suhu 40 °C.' },
    { id: 'CR-200', type: 'building', x: 870, y: 300, name: 'Ruang Kendali',
      desc: 'Pusat pemantauan DCS dan tombol ESD.' },
    { id: 'MP-200', type: 'muster', x: 880, y: 520, name: 'Titik Kumpul',
      desc: 'Area berkumpul evakuasi.' },
  ],
  pipes: [
    { id: 'f1', fluid: 'chem', w: 6, pts: [[100, 170], [100, 210], [140, 210]] },
    { id: 'f2', fluid: 'chem', w: 6, pts: [[180, 210], [450, 210], [450, 230]] },
    { id: 'cw1', fluid: 'cw', w: 5, pts: [[150, 420], [190, 420]] },
    { id: 'cw2', fluid: 'cw', w: 5, pts: [[230, 420], [400, 420]] },
    { id: 'cw3', fluid: 'cw', w: 5, pts: [[400, 270], [152, 270]], arrow: true },
    { id: 'v1', fluid: 'gas', w: 5, pts: [[530, 230], [530, 120], [612, 120]] },
    { id: 'v2', fluid: 'gas', w: 5, pts: [[668, 120], [830, 120]], arrow: true },
    { id: 'rf', fluid: 'chem', w: 3, dashed: true, pts: [[640, 148], [640, 190], [545, 190], [545, 230]] },
    { id: 'pr1', fluid: 'product', w: 6, pts: [[480, 440], [480, 480], [540, 480]] },
    { id: 'pr2', fluid: 'product', w: 6, pts: [[580, 480], [720, 480], [720, 410]] },
  ],
  labels: [
    { x: 600, y: 178, text: 'Refluks', size: 10 },
    { x: 370, y: 335, text: 'Jaket', size: 10 },
  ],
  vars: {
    T2:  { label: 'Suhu Reaktor R-201', unit: '°C', normal: 80, min: 0, max: 160, lo: 65, hi: 92, hihi: 105, node: 'R-201', x: 330, y: 300, tau: 6, noise: 0.15, dec: 1, color: '#ef5350' },
    P2:  { label: 'Tekanan Reaktor R-201', unit: 'barg', normal: 1.5, min: 0, max: 8, hi: 3, hihi: 4.5, node: 'R-201', x: 640, y: 300, tau: 3, noise: 0.03, dec: 2, color: '#ab47bc' },
    L2:  { label: 'Level Reaktor R-201', unit: '%', normal: 60, min: 0, max: 100, lo: 30, hi: 80, hihi: 92, node: 'R-201', x: 480, y: 462, tau: 5, noise: 0.3, dec: 0, color: '#8d6e63' },
    FCW: { label: 'Aliran Air Pendingin', unit: 'm³/j', normal: 30, min: 0, max: 50, lo: 18, lolo: 8, node: 'P-203', x: 330, y: 472, tau: 2, noise: 0.3, dec: 0, color: '#29b6f6' },
    FA:  { label: 'Laju Umpan Monomer', unit: 'm³/j', normal: 2.0, min: 0, max: 6, hi: 3, hihi: 4, node: 'FCV-201', x: 345, y: 240, tau: 2, noise: 0.03, dec: 2, color: '#7e57c2' },
    NAG: { label: 'Putaran Agitator', unit: 'rpm', normal: 100, min: 0, max: 150, lo: 60, node: 'M-201', x: 640, y: 215, tau: 1.5, noise: 0.5, dec: 0, color: '#66bb6a' },
  },
  trendVars: ['T2', 'P2', 'FA', 'FCW'],
  controls: [
    { id: 'fa', label: 'Set point laju umpan (FIC-201)', unit: 'm³/j', min: 0.5, max: 4, def: 2, step: 0.25,
      effects: [{ var: 'FA', gain: 1 }, { var: 'T2', gain: 6 }, { var: 'P2', gain: 0.25 }] },
    { id: 'cw', label: 'Set point aliran pendingin', unit: 'm³/j', min: 10, max: 45, def: 30, step: 5,
      effects: [{ var: 'FCW', gain: 1 }, { var: 'T2', gain: -0.6 }] },
    { id: 'ag', label: 'Putaran agitator', unit: 'rpm', min: 40, max: 140, def: 100, step: 10,
      effects: [{ var: 'NAG', gain: 1 }, { var: 'T2', gain: -0.08 }] },
  ],
  quiz: [
    { q: 'Mengapa laju umpan monomer dibatasi 2 m³/jam?', opts: ['Agar pompa P-201 tidak kavitasi', 'Agar laju pelepasan panas reaksi tidak melebihi kapasitas pendinginan jaket dan kondensor', 'Agar tangki TK-201 tidak cepat kosong', 'Agar produk lebih kental'], ans: 1,
      why: 'Pada reaksi eksotermik semi-batch, laju umpan adalah pengendali utama laju pelepasan panas. Umpan berlebih berarti akumulasi reaktan dan potensi runaway.' },
    { q: 'Apa yang terjadi bila suhu reaktor melewati suhu onset sekitar 110 °C?', opts: ['Reaksi berhenti karena katalis rusak', 'Laju reaksi dan tekanan naik secara eksponensial (reaksi runaway)', 'Suhu turun sendiri karena penguapan pelarut', 'Tidak ada pengaruh selama agitator hidup'], ans: 1,
      why: 'Di atas onset, pelepasan panas melampaui pembuangan panas sehingga suhu dan tekanan naik dengan cepat; inilah mekanisme kecelakaan Seveso dan T2 Laboratories.' },
    { q: 'Perangkat mana yang termasuk sistem kendali proses dasar (BPCS), bukan lapisan proteksi?', opts: ['TCV-201 dan loop TIC-201', 'Rupture disc pada reaktor', 'Trip suhu tinggi-tinggi', 'Detektor gas di area reaktor'], ans: 0,
      why: 'Loop kendali suhu menjaga kondisi normal. Lapisan proteksi harus independen dari BPCS agar kegagalan BPCS tidak sekaligus menghilangkan proteksi (IEC 61511).' },
    { q: 'Apa peran agitator M-201 terhadap keselamatan proses?', opts: ['Hanya memperbaiki kualitas produk', 'Menjaga perpindahan panas ke jaket dan mencegah akumulasi reaktan tak tercampur', 'Mengurangi tekanan reaktor', 'Menggantikan fungsi kondensor'], ans: 1,
      why: 'Kegagalan agitator menurunkan koefisien perpindahan panas dan dapat membuat lapisan reaktan menumpuk, lalu bereaksi serentak saat pengadukan kembali.' },
    { q: 'Ke mana uap pelarut dari reaktor dialirkan pada kondisi normal?', opts: ['Langsung ke tangki produk TK-202', 'Ke kondensor refluks E-201, kondensat kembali ke reaktor, gas tak terkondensasi ke vent', 'Ke jaket pendingin', 'Ke pompa umpan P-201'], ans: 1,
      why: 'Kondensor refluks adalah bagian dari sistem pembuangan panas; kehilangan pendingin kondensor menaikkan tekanan reaktor.' },
  ],
  events: [
    { id: 'e1', effects: [{ var: 'FCW', to: 2, delay: 2, dur: 3 }, { var: 'T2', to: 128, delay: 5, dur: 16 }, { var: 'P2', to: 5.5, delay: 12, dur: 10 }],
      answer: { node: ['R-201', 'P-203'], param: ['T', 'F'], guide: ['high', 'low', 'none'] },
      causes: ['Pompa air pendingin P-203 trip sehingga panas reaksi tidak terbuang', 'Agitator berputar terlalu cepat', 'Level reaktor terlalu rendah', 'Vent tersumbat'], causeAns: 0,
      cons: ['Reaksi runaway: suhu dan tekanan naik eksponensial, bejana pecah, pelepasan uap beracun dan mudah terbakar', 'Produk terlalu encer', 'Pompa produk kavitasi', 'Tangki umpan kosong'], consAns: 0,
      explain: 'Aliran pendingin hilang lebih dulu, lalu suhu dan tekanan naik. Urutan kejadian menunjukkan penyebab awalnya kehilangan pendinginan (deviasi aliran: tidak ada). Jawaban suhu tinggi di R-201 juga diterima sebagai deviasi utama.' },
    { id: 'e2', effects: [{ var: 'FA', to: 4.5, delay: 2, dur: 4 }, { var: 'T2', to: 118, delay: 7, dur: 16 }, { var: 'P2', to: 4.2, delay: 14, dur: 10 }],
      answer: { node: ['R-201', 'FCV-201'], param: ['F', 'T'], guide: ['high'] },
      causes: ['FCV-201 terbuka berlebih (kegagalan katup atau kesalahan set point operator) sehingga umpan melampaui kapasitas pendinginan', 'Air pendingin terlalu dingin', 'Kondensor E-201 terlalu efektif', 'Agitator mati'], causeAns: 0,
      cons: ['Akumulasi monomer, pelepasan panas melebihi pendinginan, reaksi runaway dan overpressure', 'Level reaktor turun', 'Produk tidak memenuhi spesifikasi saja, tanpa dampak keselamatan', 'Pompa umpan rusak'], consAns: 0,
      explain: 'Laju umpan naik lebih dari dua kali normal diikuti kenaikan suhu. Pembatasan laju umpan (FT dengan pembatas) dan TSHH adalah proteksi yang tepat.' },
    { id: 'e3', effects: [{ var: 'P2', to: 5.8, delay: 3, dur: 14 }, { var: 'T2', to: 96, delay: 8, dur: 12 }],
      answer: { node: ['R-201', 'E-201', 'VNT-201'], param: ['P'], guide: ['high'] },
      causes: ['Jalur vent tersumbat atau kondensor E-201 kehilangan pendingin sehingga uap tidak terkondensasi', 'Umpan dihentikan', 'Agitator terlalu lambat', 'Level terlalu rendah'], causeAns: 0,
      cons: ['Tekanan melampaui desain 6 barg, bejana pecah atau flens bocor, pelepasan uap mudah terbakar', 'Suhu reaktor turun', 'Produk menjadi lebih kental', 'Pompa produk trip'], consAns: 0,
      explain: 'Tekanan naik lebih dulu tanpa perubahan umpan atau pendingin jaket; penyebab berada di sistem vent dan kondensor. Relief (PSV atau RD) wajib tersedia.' },
    { id: 'e4', effects: [{ var: 'L2', to: 97, delay: 3, dur: 16 }, { var: 'FA', to: 3, delay: 2, dur: 3 }],
      answer: { node: ['R-201'], param: ['L'], guide: ['high'] },
      causes: ['Transmitter level gagal membaca rendah palsu sehingga umpan terus masuk melampaui batas batch', 'Kondensor bocor', 'Air pendingin masuk ke reaktor', 'Pompa produk terlalu cepat'], causeAns: 0,
      cons: ['Reaktor terisi penuh, ruang uap hilang, cairan masuk ke kondensor dan vent, tumpahan monomer', 'Suhu turun drastis', 'Agitator berputar lebih cepat', 'Tekanan jaket naik'], consAns: 0,
      explain: 'Level naik melebihi batas batch. Proteksi overfill independen (LSHH menghentikan P-201) diperlukan karena BPCS level sudah gagal.' },
  ],
  hotspots: [
    { id: 'h31', stage: 3, x: 400, y: 330, label: 'Nozzle suhu R-201', accept: ['TSHH', 'TT'],
      why: 'Trip suhu tinggi-tinggi menghentikan umpan dan membuka pendingin darurat sebelum onset runaway. Alarm TT diterima sebagai lapisan operator meski lebih lemah.' },
    { id: 'h32', stage: 3, x: 470, y: 212, label: 'Nozzle puncak R-201 (relief)', accept: ['RD', 'PSV'],
      why: 'Relief diperlukan untuk overpressure. Rupture disc cocok untuk kenaikan tekanan sangat cepat pada runaway; PSV juga diterima.' },
    { id: 'h33', stage: 3, x: 350, y: 188, label: 'Jalur umpan sebelum reaktor', accept: ['FT'],
      why: 'Pembatas laju umpan mencegah pelepasan panas melebihi kapasitas pendinginan (prinsip semi-batch yang aman).' },
    { id: 'h34', stage: 3, x: 365, y: 440, label: 'Jalur air pendingin ke jaket', accept: ['FSLL'],
      why: 'Kehilangan pendingin adalah pemicu runaway tersering; trip aliran rendah menghentikan umpan secara otomatis.' },
    { id: 'h35', stage: 3, x: 560, y: 240, label: 'Motor agitator M-201', accept: ['AGI'],
      why: 'Interlock agitator menghentikan umpan bila pengaduk mati agar reaktan tidak terakumulasi.' },
    { id: 'h36', stage: 3, x: 560, y: 410, label: 'Nozzle level R-201', accept: ['LSHH', 'LT'],
      why: 'Proteksi overfill independen dari transmitter level BPCS.' },
    { id: 'h37', stage: 3, x: 150, y: 75, label: 'Ruang uap TK-201', accept: ['N2'],
      why: 'Blanketing nitrogen menjaga ruang uap tangki monomer berada di luar rentang mudah terbakar.' },
    { id: 'h38', stage: 3, x: 110, y: 240, label: 'Suction pompa P-201', accept: [],
      why: 'Titik ini tidak terkait skenario yang teridentifikasi; perangkat tambahan di sini menghabiskan anggaran tanpa menurunkan risiko utama.' },
    { id: 'h39', stage: 3, x: 650, y: 480, label: 'Discharge pompa produk P-202', accept: ['NRV'],
      why: 'Check valve mencegah aliran balik produk, perbaikan kecil namun tepat; prioritas tetap pada reaktor.' },
    /* Tahap 4 */
    { id: 'h41', stage: 4, x: 400, y: 260, label: 'Nozzle injeksi R-201', accept: ['QUENCH'],
      why: 'Quench atau inhibitor menghentikan reaksi runaway yang sudah dimulai, ketika pencegahan gagal.' },
    { id: 'h42', stage: 4, x: 750, y: 95, label: 'Jalur vent setelah E-201', accept: ['SCRUB'],
      why: 'Pelepasan darurat uap monomer harus dinetralkan sebelum ke atmosfer untuk melindungi pekerja dan masyarakat.' },
    { id: 'h43', stage: 4, x: 610, y: 350, label: 'Area reaktor (deteksi gas)', accept: ['GD'],
      why: 'Detektor gas mendeteksi kebocoran uap monomer di area reaktor.' },
    { id: 'h44', stage: 4, x: 190, y: 140, label: 'Sekeliling TK-201', accept: ['DIKE'],
      why: 'Tanggul menampung tumpahan monomer dari tangki umpan.' },
    { id: 'h45', stage: 4, x: 340, y: 470, label: 'Area bawah reaktor (deteksi api)', accept: ['FD'],
      why: 'Detektor nyala memicu deluge dan ESD bila kebocoran produk terbakar.' },
    { id: 'h46', stage: 4, x: 870, y: 345, label: 'Ruang kendali (ESD)', accept: ['ESD'],
      why: 'ESD menghentikan umpan, pompa, dan mengaktifkan quench dari jarak aman.' },
    { id: 'h47', stage: 4, x: 230, y: 180, label: 'Jalur umpan (isolasi jarak jauh)', accept: ['EIV'],
      why: 'Menghentikan suplai monomer ke area kebocoran dari jarak aman.' },
    { id: 'h48', stage: 4, x: 820, y: 520, label: 'Titik kumpul dan alarm umum', accept: ['ALARM'],
      why: 'Perlindungan orang melalui evakuasi terencana.' },
    { id: 'h49', stage: 4, x: 760, y: 380, label: 'Atap TK-202', accept: ['FOAM', 'FW'],
      why: 'Tangki produk mudah terbakar; busa atau monitor air memadamkan dan mendinginkan.' },
    { id: 'h40', stage: 4, x: 230, y: 300, label: 'Jalur air pendingin kembali', accept: [],
      why: 'Air pendingin bukan bahan berbahaya; perangkat mitigasi di sini tidak menurunkan risiko.' },
  ],
  budget: { 3: 22, 4: 24 },
  bowtie: {
    top: 'Reaksi runaway dan kehilangan kontainmen reaktor R-201',
    threats: ['Kehilangan air pendingin', 'Laju umpan berlebih', 'Vent dan kondensor terblokir', 'Overfill reaktor'],
    cons: ['Pecahnya bejana dan ledakan', 'Pelepasan uap beracun ke lingkungan', 'Kebakaran area reaktor', 'Tumpahan monomer'],
  },
};

/* =====================================================================
   SKENARIO 3: Penyimpanan dan Pengisian LPG
   ===================================================================== */
const SCN_LPG = {
  id: 'lpg',
  title: 'Penyimpanan & Pengisian LPG',
  subtitle: 'Tangki bullet bertekanan, pompa pengisian, loading bay truk',
  level: 'Lanjutan',
  sector: 'Hilir Migas / Distribusi',
  color: '#26a69a',
  overview: [
    'Terminal ini menerima LPG cair dari pipa kilang (12 barg) ke tangki bullet V-301 berkapasitas 100 m³ yang beroperasi pada 7 barg dan suhu lingkungan 30 °C. Batas pengisian maksimum tangki adalah 85 % untuk menyisakan ruang ekspansi termal.',
    'LPG dipompa P-301 (50 m³/jam) melalui loading arm ke truk tangki di loading bay. Uap yang terdesak dari truk dikembalikan ke V-301 oleh kompresor vapor return K-301 agar tidak dilepas ke udara.',
    'LPG adalah gas cair mudah terbakar yang disimpan di atas titik didihnya. Pelepasan cairan menghasilkan awan uap yang lebih berat dari udara, dan tangki yang terpapar api berisiko BLEVE (Boiling Liquid Expanding Vapour Explosion).',
  ],
  equipment: [
    { id: 'PL-300', type: 'sink', x: 135, y: 200, dir: 'left', name: 'Pipa LPG dari Kilang',
      desc: 'Suplai LPG cair 12 barg dari kilang. Pengisian tangki dilakukan secara berkala (batch).' },
    { id: 'XV-300', type: 'valve', sub: 'manual', x: 178, y: 200, name: 'Katup Isolasi Inlet',
      desc: 'Katup manual yang dibuka saat pengisian tangki dari pipa kilang.' },
    { id: 'V-301', type: 'vessel', orient: 'h', x: 220, y: 150, w: 300, h: 100, name: 'Tangki Bullet LPG V-301',
      desc: 'Bejana tekan horizontal 100 m³, tekanan operasi 7 barg (tergantung suhu), tekanan desain 17,5 barg. Batas isi maksimum 85 %. Dilengkapi level gauge dan pressure gauge lokal.',
      vars: ['P3', 'L3', 'T3'] },
    { id: 'P-301', type: 'pump', x: 450, y: 330, name: 'Pompa Pengisian P-301',
      desc: 'Pompa sentrifugal LPG 50 m³/jam. Seal mekanis adalah titik kebocoran yang umum.' },
    { id: 'XV-301', type: 'valve', sub: 'manual', x: 560, y: 330, name: 'Katup Loading Arm',
      desc: 'Katup manual pada loading arm yang dibuka operator saat truk tersambung.' },
    { id: 'TR-301', type: 'truck', x: 660, y: 310, w: 200, h: 80, name: 'Truk Tangki LPG',
      desc: 'Truk tangki 20 m³. Pengisian dihentikan pada 80 % berdasarkan pembacaan operator di meter truk. Truk harus di-grounding dan roda diganjal.', vars: ['LTR'] },
    { id: 'K-301', type: 'compressor', x: 620, y: 120, name: 'Kompresor Vapor Return K-301',
      desc: 'Mengembalikan uap LPG dari truk ke V-301 selama pengisian agar tidak dilepas ke atmosfer.' },
    { id: 'CR-300', type: 'building', x: 110, y: 420, name: 'Ruang Kendali',
      desc: 'Pusat pemantauan dan tombol ESD terminal.' },
    { id: 'MP-300', type: 'muster', x: 900, y: 520, name: 'Titik Kumpul',
      desc: 'Area berkumpul evakuasi, minimal 100 m dari tangki.' },
  ],
  pipes: [
    { id: 'in1', fluid: 'lpg', w: 6, pts: [[135, 200], [220, 200]] },
    { id: 'l1', fluid: 'lpg', w: 6, pts: [[370, 250], [370, 330], [430, 330]] },
    { id: 'l2', fluid: 'lpg', w: 6, pts: [[470, 330], [620, 330], [620, 350], [660, 350]] },
    { id: 'vr1', fluid: 'gas', w: 4, pts: [[760, 310], [760, 120], [648, 120]] },
    { id: 'vr2', fluid: 'gas', w: 4, pts: [[592, 120], [400, 120], [400, 150]], arrow: true },
  ],
  labels: [
    { x: 760, y: 430, text: 'Loading Bay', size: 12 },
    { x: 500, y: 100, text: 'Vapor return', size: 10 },
  ],
  vars: {
    P3:  { label: 'Tekanan V-301', unit: 'barg', normal: 7.0, min: 0, max: 20, lo: 4, hi: 10, hihi: 14, node: 'V-301', x: 240, y: 125, tau: 4, noise: 0.03, dec: 1, color: '#ef5350' },
    L3:  { label: 'Level V-301', unit: '%', normal: 70, min: 0, max: 100, lo: 20, hi: 85, hihi: 90, node: 'V-301', x: 440, y: 270, tau: 5, noise: 0.2, dec: 0, color: '#26a69a' },
    T3:  { label: 'Suhu V-301', unit: '°C', normal: 30, min: 0, max: 100, hi: 45, hihi: 55, node: 'V-301', x: 500, y: 125, tau: 8, noise: 0.1, dec: 1, color: '#ffa726' },
    FL:  { label: 'Aliran Pengisian', unit: 'm³/j', normal: 50, min: 0, max: 120, lo: 20, hi: 65, hihi: 80, node: 'P-301', x: 545, y: 385, tau: 1.5, noise: 0.5, dec: 0, color: '#7e57c2' },
    LTR: { label: 'Level Truk', unit: '%', normal: 55, min: 0, max: 100, hi: 80, hihi: 88, node: 'TR-301', x: 760, y: 410, tau: 3, noise: 0.2, dec: 0, color: '#8d6e63' },
    PB:  { label: 'Tekanan Loading Arm', unit: 'barg', normal: 9.0, min: 0, max: 15, lo: 5, node: 'XV-301', x: 640, y: 290, tau: 1.5, noise: 0.05, dec: 1, color: '#42a5f5' },
  },
  trendVars: ['P3', 'L3', 'FL', 'LTR'],
  controls: [
    { id: 'pump', label: 'Kecepatan pompa pengisian', unit: '%', min: 40, max: 120, def: 100, step: 5,
      effects: [{ var: 'FL', gain: 0.5 }, { var: 'PB', gain: 0.03 }] },
    { id: 'amb', label: 'Suhu lingkungan', unit: '°C', min: 20, max: 45, def: 30, step: 1,
      effects: [{ var: 'T3', gain: 1 }, { var: 'P3', gain: 0.25 }] },
    { id: 'fill', label: 'Target isi tangki V-301', unit: '%', min: 40, max: 85, def: 70, step: 5,
      effects: [{ var: 'L3', gain: 1 }] },
  ],
  quiz: [
    { q: 'Mengapa tangki LPG tidak boleh diisi melebihi 85 %?', opts: ['Agar pompa tidak bekerja terlalu berat', 'Untuk menyisakan ruang uap bagi ekspansi termal cairan; tangki penuh cairan dapat mengalami overpressure hidrostatik saat suhu naik', 'Agar level gauge mudah dibaca', 'Karena pipa kilang hanya mampu 85 %'], ans: 1,
      why: 'LPG cair memuai cukup besar terhadap suhu. Tanpa ruang uap, kenaikan suhu kecil menghasilkan tekanan sangat besar (liquid full).' },
    { q: 'Mengapa tekanan V-301 berubah mengikuti suhu lingkungan?', opts: ['Karena kompresor K-301 mengatur tekanan', 'Karena LPG disimpan sebagai cairan pada tekanan uap jenuhnya, yang bergantung pada suhu', 'Karena pompa P-301 memompa uap', 'Karena pipa kilang bertekanan 12 barg'], ans: 1,
      why: 'Tekanan tangki adalah tekanan uap jenuh campuran propana-butana pada suhu cairan. Pemanasan eksternal (api) menaikkan tekanan dengan cepat.' },
    { q: 'Apa fungsi kompresor vapor return K-301?', opts: ['Menaikkan tekanan pompa', 'Mengembalikan uap yang terdesak dari truk ke tangki agar tidak dilepas ke udara', 'Mendinginkan LPG', 'Mengosongkan tangki'], ans: 1,
      why: 'Tanpa vapor return, setiap pengisian melepaskan uap LPG mudah terbakar di loading bay.' },
    { q: 'Apa itu BLEVE dan kapan dapat terjadi pada V-301?', opts: ['Kebocoran kecil pada seal pompa', 'Ledakan bejana berisi cairan di atas titik didihnya akibat dinding bejana melemah saat terpapar api, melepaskan bola api besar', 'Tumpahan cairan yang tidak terbakar', 'Kegagalan kompresor'], ans: 1,
      why: 'BLEVE adalah skenario bencana utama fasilitas LPG (contoh: San Juanico 1984, Feyzin 1966). Pencegahannya: relief, pendinginan dinding bejana, dan isolasi cepat.' },
    { q: 'Mengapa awan uap LPG sangat berbahaya di loading bay?', opts: ['Karena uapnya beracun seperti H2S', 'Karena uap LPG lebih berat dari udara, menyebar rendah dan jauh, lalu dapat menyala pada sumber api jauh dari titik bocor', 'Karena uapnya panas', 'Karena uapnya menyebabkan korosi'], ans: 1,
      why: 'Densitas uap propana sekitar 1,5 kali udara. Sumber nyala seperti mesin truk atau listrik statis dapat memicu flash fire.' },
  ],
  events: [
    { id: 'e1', effects: [{ var: 'LTR', to: 97, delay: 3, dur: 14 }],
      answer: { node: ['TR-301'], param: ['L'], guide: ['high'] },
      causes: ['Operator tidak menghentikan pengisian pada 80 % (kesalahan manusia) atau meter level truk gagal', 'Kompresor K-301 trip', 'Suhu lingkungan naik', 'Katup XV-300 terbuka'], causeAns: 0,
      cons: ['Truk terisi penuh cairan, LPG keluar dari relief truk, awan uap di loading bay dan flash fire', 'Tekanan V-301 naik', 'Pompa kavitasi', 'Level V-301 naik'], consAns: 0,
      explain: 'Level truk naik melampaui 80 % tanpa deviasi lain. Pengisian bergantung pada pengamatan operator; proteksi overfill otomatis pada truk (LSHH menghentikan pompa) diperlukan.' },
    { id: 'e2', effects: [{ var: 'T3', to: 62, delay: 3, dur: 16 }, { var: 'P3', to: 15.5, delay: 5, dur: 16 }],
      answer: { node: ['V-301'], param: ['P', 'T'], guide: ['high'] },
      causes: ['Pemanasan eksternal: kebakaran di dekat tangki atau paparan panas yang berlebihan', 'Pompa P-301 terlalu cepat', 'Kompresor K-301 memompa terlalu banyak uap', 'Katup inlet tertutup'], causeAns: 0,
      cons: ['Tekanan uap naik melewati desain, dinding bejana melemah, BLEVE dengan bola api dan fragmen', 'Level tangki naik', 'Truk terisi lebih cepat', 'Aliran pengisian turun'], consAns: 0,
      explain: 'Suhu cairan naik lalu tekanan naik mengikuti kurva tekanan uap. Ini pola paparan panas eksternal. Mitigasi: PSV, water spray pendingin, dan isolasi jarak jauh.' },
    { id: 'e3', effects: [{ var: 'FL', to: 110, delay: 3, dur: 3 }, { var: 'PB', to: 1.5, delay: 3, dur: 3 }, { var: 'LTR', to: 50, delay: 3, dur: 10 }],
      answer: { node: ['XV-301', 'TR-301', 'P-301'], param: ['F', 'P'], guide: ['high', 'low'] },
      causes: ['Loading arm atau selang putus (misalnya truk bergerak saat masih tersambung) sehingga aliran bebas ke atmosfer', 'Truk penuh', 'Tangki V-301 kosong', 'Kompresor berhenti'], causeAns: 0,
      cons: ['Pelepasan LPG cair besar, awan uap berat menyebar, flash fire atau VCE di loading bay', 'Tekanan V-301 naik', 'Level truk naik cepat', 'Pompa berhenti sendiri'], consAns: 0,
      explain: 'Aliran melonjak sementara tekanan loading arm anjlok: tanda hilangnya tahanan hilir karena pipa atau selang putus. Excess flow valve, breakaway coupling, dan ROSOV adalah proteksinya.' },
    { id: 'e4', effects: [{ var: 'L3', to: 98, delay: 3, dur: 16 }, { var: 'P3', to: 12, delay: 14, dur: 8 }],
      answer: { node: ['V-301', 'XV-300'], param: ['L'], guide: ['high'] },
      causes: ['Pengisian dari kilang tidak dihentikan karena level gauge gagal (membaca rendah palsu)', 'Pompa P-301 trip', 'Suhu lingkungan turun', 'Kompresor K-301 memompa uap ke tangki'], causeAns: 0,
      cons: ['Tangki penuh cairan (liquid full), tekanan hidrostatik naik tajam dengan sedikit kenaikan suhu, bejana pecah atau PSV melepaskan cairan LPG', 'Truk tidak dapat diisi', 'Pompa kavitasi', 'Suhu tangki turun'], consAns: 0,
      explain: 'Level naik melampaui 85 % lalu tekanan ikut naik tanpa kenaikan suhu: tanda ruang uap hampir habis. Proteksi overfill independen (LSHH menutup inlet) sangat penting.' },
  ],
  hotspots: [
    { id: 'h31', stage: 3, x: 460, y: 138, label: 'Nozzle puncak V-301 (relief)', accept: ['PSV'],
      why: 'PSV pada tangki LPG wajib untuk overpressure akibat paparan panas; ukurannya mengikuti laju penguapan saat kebakaran (API 2510).' },
    { id: 'h32', stage: 3, x: 340, y: 138, label: 'Nozzle level V-301', accept: ['LSHH', 'LT'],
      why: 'Trip level tinggi-tinggi menutup inlet saat 85 %, independen dari level gauge. Alarm level diterima sebagai lapisan operator.' },
    { id: 'h33', stage: 3, x: 212, y: 228, label: 'Jalur inlet dari kilang', accept: ['NRV'],
      why: 'Check valve mencegah aliran balik ke pipa kilang dan membatasi inventori yang lepas bila pipa inlet pecah.' },
    { id: 'h34', stage: 3, x: 400, y: 300, label: 'Outlet cairan V-301 (sebelum pompa)', accept: ['EFV'],
      why: 'Excess flow valve menutup otomatis bila aliran melonjak akibat pipa hilir putus.' },
    { id: 'h35', stage: 3, x: 610, y: 370, label: 'Loading arm ke truk', accept: ['BRK'],
      why: 'Breakaway coupling menutup kedua sisi bila truk bergerak saat masih tersambung.' },
    { id: 'h36', stage: 3, x: 700, y: 410, label: 'Area truk (statis)', accept: ['GRND'],
      why: 'Grounding dengan interlock pompa menghilangkan sumber nyala statis dan memastikan truk tersambung dengan benar sebelum pengisian.' },
    { id: 'h37', stage: 3, x: 820, y: 300, label: 'Puncak truk tangki (overfill)', accept: ['LSHH'],
      why: 'Proteksi overfill otomatis pada truk menghentikan pompa pada 80 % tanpa bergantung pada operator.' },
    { id: 'h38', stage: 3, x: 560, y: 95, label: 'Jalur vapor return', accept: [],
      why: 'Jalur uap berdiameter kecil dan bertekanan rendah; perangkat tambahan di sini tidak menangani skenario utama.' },
    { id: 'h39', stage: 3, x: 270, y: 215, label: 'Nozzle tekanan V-301', accept: ['PT'],
      why: 'Alarm tekanan tinggi memberi peringatan dini paparan panas atau overfill ke operator.' },
    /* Tahap 4 */
    { id: 'h41', stage: 4, x: 370, y: 90, label: 'Di atas V-301 (pendinginan)', accept: ['DELUGE'],
      why: 'Water spray menjaga dinding tangki tetap dingin saat terpapar api, mitigasi utama BLEVE (NFPA 58, API 2510).' },
    { id: 'h42', stage: 4, x: 330, y: 365, label: 'Outlet V-301 (isolasi jarak jauh)', accept: ['EIV'],
      why: 'ROSOV menghentikan sumber kebocoran dari jarak aman, termasuk saat kebakaran di pompa.' },
    { id: 'h43', stage: 4, x: 520, y: 290, label: 'Area pompa P-301 (deteksi gas)', accept: ['GD'],
      why: 'Seal pompa adalah titik bocor umum; detektor gas memicu ESD sebelum awan uap membesar.' },
    { id: 'h44', stage: 4, x: 900, y: 360, label: 'Loading bay (deteksi gas)', accept: ['GD'],
      why: 'Loading bay adalah area pelepasan paling mungkin; deteksi gas di ketinggian rendah penting karena uap LPG berat.' },
    { id: 'h45', stage: 4, x: 150, y: 460, label: 'Ruang kendali (ESD)', accept: ['ESD'],
      why: 'ESD menghentikan pompa, kompresor, dan menutup ROSOV serentak.' },
    { id: 'h46', stage: 4, x: 240, y: 300, label: 'Area tangki (deteksi api)', accept: ['FD'],
      why: 'Detektor nyala mengaktifkan deluge secara otomatis dalam hitungan detik.' },
    { id: 'h47', stage: 4, x: 620, y: 440, label: 'Loading bay (pemadaman)', accept: ['FW'],
      why: 'Monitor air mendinginkan truk dan peralatan sekitar serta mengurai awan uap.' },
    { id: 'h48', stage: 4, x: 840, y: 520, label: 'Titik kumpul dan alarm umum', accept: ['ALARM'],
      why: 'Evakuasi cepat karena radius BLEVE dapat mencapai ratusan meter.' },
    { id: 'h49', stage: 4, x: 480, y: 215, label: 'Permukaan V-301 (sistem busa)', accept: [],
      why: 'Busa tidak efektif untuk LPG karena cairan mendidih pada suhu lingkungan; pendinginan air adalah pendekatan yang benar.' },
  ],
  budget: { 3: 20, 4: 22 },
  bowtie: {
    top: 'Pelepasan LPG dari sistem penyimpanan dan pengisian',
    threats: ['Overfill truk tangki', 'Paparan panas eksternal pada V-301', 'Putusnya loading arm', 'Overfill tangki V-301 (liquid full)'],
    cons: ['Flash fire di loading bay', 'BLEVE dengan bola api dan fragmen', 'Ledakan awan uap (VCE)', 'Pecahnya tangki'],
  },
};

const SCENARIOS = [SCN_SEPARATOR, SCN_REACTOR, SCN_LPG];

const STAGES = [
  { n: 1, short: 'Kondisi Normal', title: 'Tahap 1: Identifikasi Kondisi Normal', icon: 'book',
    desc: 'Pelajari setiap peralatan, jalankan simulasi, dan pahami bagaimana proses dijaga pada kondisi normal.' },
  { n: 2, short: 'Abnormalitas', title: 'Tahap 2: Identifikasi Abnormalitas', icon: 'alert',
    desc: 'Amati tren proses, kenali deviasi yang muncul, tentukan penyebab dan konsekuensinya (pendekatan HAZOP).' },
  { n: 3, short: 'Barier Pencegahan', title: 'Tahap 3: Barier Pencegahan', icon: 'shield',
    desc: 'Pasang instrumen deteksi dan proteksi untuk mencegah abnormalitas berkembang menjadi kehilangan kontainmen.' },
  { n: 4, short: 'Barier Mitigasi', title: 'Tahap 4: Barier Mitigasi', icon: 'fire',
    desc: 'Pasang perangkat untuk mencegah eskalasi insiden menjadi bencana: deteksi, isolasi, proteksi kebakaran, dan tanggap darurat.' },
];
